### ISSUE TITLE
Android content URIs considered unsafe

### ISSUE THREAD

**Issue by deckerst** [media-kit/media-kit#1002]
I've just forked `media-kit`, and running it to load media via `content` URI fails with:
```
I/flutter (15022): libmpv log: PlayerLog(prefix: stream, level: error, text: Refusing to load potentially unsafe URL from a playlist.)
I/flutter (15022): libmpv error: Refusing to load potentially unsafe URL from a playlist.
I/flutter (15022): libmpv log: PlayerLog(prefix: stream, level: error, text: Use the --load-unsafe-playlists option to load it anyway.)
I/flutter (15022): libmpv error: Use the --load-unsafe-playlists option to load it anyway.
```

Loading the same videos with the same code works fine with the currently published version of `media_kit` v1.1.11 / `media_kit_video` v1.2.5.

Here is what I've tried with the current main of `media_kit` (to no avail):
- adding `content` to the `Player` configuration `protocolWhitelist`,
- calling `await (_instance.platform as dynamic).setProperty('--load-unsafe-playlists', 'true');`

Is there a way to fix this issue via consumer side configuration, or does it require some code change on `media-kit` side?

**Comment by deckerst** [comment]
Of course, as soon as I post this I find the way -__-

Adding `fd` to the whitelisted protocols seems to work.

I would suggest however to add this protocol to the default protocol whitelist, as it is a custom protocol used by `media-kit`.

**Comment by abdelaziz-mahdy** [comment]
feel free to open a pr adding it to the list of supported protocols, it will be faster to land this way

**Comment by alexmercerind** [comment]
Maybe after #969.

**Comment by alexmercerind** [comment]
Yes. Do send a pull-request.

**Comment by deckerst** [comment]
I haven't found a solution, actually.
Whitelisting the FD protocol didn't help.
I was hoping you would know how to fix it.

**Comment by alexmercerind** [comment]
Hi! I can give you can idea... use old logic in #969 (`loadfile` instead of `loadlist`) if any of the URI starts with fd://.

Please send a pull-request, shortage of time on my end.
