### ISSUE TITLE
Player error

### ISSUE THREAD

**Issue by Clushdada** [media-kit/media-kit#1006]
flutter: RangeError (length): Invalid value: Only valid value is 0: 1
flutter: #0      List.[] (dart:core-patch/growable_array.dart)
#1      NativePlayer._handler.<anonymous closure> (package:media_kit/src/player/native/player/real.dart:1549:44)
#2      MapBase.map (dart:collection/maps.dart:82:28)
#3      NativePlayer._handler (package:media_kit/src/player/native/player/real.dart:1546:16)
#4      Initializer._callback.<anonymous closure> (package:media_kit/src/player/native/core/initializer.dart:79:45)
#5      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:31:24)
#6      Initializer._callback (package:media_kit/src/player/native/core/initializer.dart:74:26)
#7      Initializer.create.<anonymous closure> (package:media_kit/src/player/native/core/initializer.dart)
#8      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#9      _RootZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1633:26)
#10     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

**Comment by DomingoMG** [comment]
I have already experienced that error, it happens that it is taking for granted that there is an element in the list before validating that it is empty or not.
