### ISSUE TITLE
Support Wasm

### ISSUE THREAD

**Issue by hasanm08** [media-kit/media-kit#1017]
I am using your package and I want to migrate to wasm but your package is not supporting wasm

**Comment by alexmercerind** [comment]
You can help: #854

**Comment by TheComputerM** [comment]
@alexmercerind can I take over this issue, there hasn't been any update on this for some time now, also I want to try to use [videojs](https://videojs.com/) to pass http headers in all web formats and also replace the hlsjs dependency.

**Comment by alexmercerind** [comment]
@TheComputerM 

Thanks a lot. Please feel free to proceed, our web backend has a large scope of improvement.

You can join our Discord, if you need for details. We can invite you to our org eventually.

**Comment by abdelaziz-mahdy** [comment]
> @alexmercerind can I take over this issue, there hasn't been any update on this for some time now, also I want to try to use [videojs](https://videojs.com/) to pass http headers in all web formats and also replace the hlsjs dependency.

i will split the pr, to convert the controls part to work with wasm and you can work on the player it self (i got stuck this is why i stopped working on it )

**Comment by alexmercerind** [comment]
The WASM support just got merged... Video.js support may be added in future pull-requests.

Thanks!
