### ISSUE TITLE
open video on Android emulator, black screen appears

### ISSUE THREAD

**Issue by BrotherPeng** [media-kit/media-kit#1029]
vPlayer.open(Media('http://192.168.50.70:3000/video/ipa/18.mp4'));
No action, just sound

**Comment by abdelaziz-mahdy** [comment]
do you have impeller enabled? in that case you need to use the package from the github not pub

**Comment by BrotherPeng** [comment]
> do you have impeller enabled? in that case you need to use the package from the github not pub

I just used the default configuration. What properties is the impeller?

**Comment by abdelaziz-mahdy** [comment]
You can check it here 

https://docs.flutter.dev/perf/impeller?gad_source=1&gclid=CjwKCAiA3Na5BhAZEiwAzrfagIRL3S_HqZpo1P1y-O6FCmv8h5rWhZpcTVvX2LDn2S9Z4NlhufOKmRoCZ4YQAvD_BwE&gclsrc=aw.ds#android

**Comment by alexmercerind** [comment]
no matter what you do emulator will never work
