### ISSUE TITLE
ArgumentError (Invalid argument(s): Failed to load dynamic library 'libavcodec.so': dlopen failed: library "libavcodec.so" not found)

### ISSUE THREAD

**Issue by BrotherPeng** [media-kit/media-kit#1032]
An error occurs when the android app runs

  WidgetsFlutterBinding.ensureInitialized();
  MediaKit.ensureInitialized();  // Report an error here

**Comment by alexmercerind** [comment]
Learn to use your debugger.

**Comment by BrotherPeng** [comment]
> Learn to use your debugger.

For unknown reasons, I created a new project and copied the code into the new project, and it didn't give me any error, 
but the old project, even if I deleted the android directory, and then ran flutter create . It still gives me an error.

**Comment by alexmercerind** [comment]
> It still gives me an error.

It's a handled exception, configure your debugger to not set a breakpoint for handled exceptions (like God intended).

**Comment by BrotherPeng** [comment]
Yes, my bad, I turned on All Exceptions. Thank you very much.
