### ISSUE TITLE
[Linux] Video Playback Issue in Release Mode on Jetson Platform – Displays Dark and Altered Colors

### ISSUE THREAD

**Issue by thomasaab** [media-kit/media-kit#1034]
Hello,

I'm encountering an issue with video playback using the ⁠ media_kit ⁠ package on my Jetson platform. The video works perfectly when running in debug mode, but when switching to release mode, the video appears dark and with altered colors. Below, I've provided all the necessary details about my setup and the issue:

### System Configuration:
•⁠  ⁠*Device*: Jetson Orin
•⁠  ⁠*CPU Architecture*: ARMv8 (64-bit)
•⁠  ⁠*Operating System*: Ubuntu 20.04.6 LTS (64-bit)
•⁠  ⁠*GPU*: NVIDIA Tegra Orin
•⁠  ⁠*OpenGL Version*: 3.2.0 NVIDIA (Driver version: 35.5.0)
•⁠  ⁠*Flutter Version*: 3.24.4
•⁠  ⁠*media_kit Version*: [Specify the version]
•⁠  ⁠*media_kit Version*: ^1.1.11 
•⁠  ⁠*media_kit_video Version*: ^1.2.5
•⁠  ⁠*media_kit_libs_video Version*: ^1.0.5 

### Issue Description:
•⁠  ⁠*Debug Mode*: The video plays correctly without any color or display issues.
•⁠  ⁠*Release Mode*: The video appears dark and with altered colors, making it unwatchable.
•⁠  ⁠*Temporary Fix*: If I set ⁠ so="gpu" ⁠ in ⁠ VideoControllerConfiguration ⁠, the video plays correctly even in release mode, but it opens in a separate window, which is not suitable for my application.

### Steps to Reproduce:
1.⁠ ⁠Run the Flutter application using ⁠ media_kit ⁠ on the Jetson platform in debug mode – video plays as expected.
2.⁠ ⁠Switch to release mode and run the application – video appears dark and with altered colors.
3.⁠ ⁠Set ⁠ so="gpu" ⁠ in ⁠ VideoControllerConfiguration ⁠ – video works correctly, but in an external window.

### Additional Notes:
•⁠  ⁠This issue only occurs in release mode.
•⁠  ⁠I require the video to play seamlessly within the app, not in an external window.

### Request:
I would greatly appreciate any insights, guidance, or potential fixes for this issue. Is there a specific configuration or workaround that can ensure proper video playback within the app in release mode on ARM-based devices like Jetson? 

Thank you for taking the time to look into this. Your help is immensely valued, and any assistance would be greatly appreciated

**Comment by thomasaab** [comment]
Update on this issue: I discovered that the problem is related to the Image widget in Flutter. For some reason, when running in release mode on Linux, the video renders with altered colors if it shares the rendering context with the Image widget (i.e., if both are rendered at the same time). I’m not an expert in Flutter, so I don’t fully understand why this happens, but I hope this information helps in identifying the underlying problem.

**Comment by it-automatika** [comment]
@thomasaab did you find a solution? I have the same problem with videos that gets a darker color, and i also have images in the same screen.
