### ISSUE TITLE
Hardcoded libmpv versions cause issues on Linux

### ISSUE THREAD

**Issue by bbaster** [media-kit/media-kit#1047]
Good day,

When I try to run a Flet app on Linux, I get this error:
`/home/annie/.flet/bin/flet-0.22.1/flet/flet: error while loading shared libraries: libmpv.so.1: cannot open shared object file: No such file or directory`

This is because this project, which is used by Flet to render videos, hardcodes libmpv versions, as it can be seen here:
https://github.com/media-kit/media-kit/blob/436735bd8d196e2a82bb21ac4463273db1b17e89/media_kit/lib/src/player/native/core/native_library.dart#L58

libmpv.so.1 is no longer available on many Linux distributions, such as Arch Linux.

It could be solved by either removing references to specific versions on Linux, as libmpv.so is guaranteed to be always there and named the same when the (lib)mpv package is installed, or changing exception handling to only throw an error when none if the versions are present, not any of them.

Best regards,
Anastasia

**Comment by alexmercerind** [comment]
The implementation is correct.

**Comment by bbaster** [comment]
And yet libmpv.so.1 is an old version, last released in 2022, that is no longer available on modern Linux distributions like Debian 12+ and Ubuntu 22.10+:

https://pkgs.org/download/libmpv1

Multiple users have been have been experiencing the same issue:

https://github.com/flet-dev/flet/issues?q=libmpv.so.1

Why the need to reference specifically libmpv.so.1, anyway? Why not just the universal name libmpv.so?

**Comment by alexmercerind** [comment]
@bbaster 

We look for all possible libmpv shared objects names:

https://github.com/media-kit/media-kit/blob/436735bd8d196e2a82bb21ac4463273db1b17e89/media_kit/lib/src/player/native/core/native_library.dart#L56-L58

It falls back automatically if one is not found. Also, you can supply own path if you decide to distribute it some other way:

https://github.com/media-kit/media-kit/blob/436735bd8d196e2a82bb21ac4463273db1b17e89/media_kit/lib/src/player/native/core/native_library.dart#L32

I hope that makes it clear.

**Comment by alexmercerind** [comment]
To be honest, GNU/Linux setup is bit of pain at the moment. I want to compile a standalone shared library for GNU/Linux, like we do for Windows, macOS & Android & use that (instead of depending upon distribution packages)... but I don't have time.

**Comment by bbaster** [comment]
Thank you for explaining, so the issue is in how Flet is built?
