### ISSUE TITLE
MissingPluginException：VideoOutputManager.Create

### ISSUE THREAD

**Issue by Pixroc** [media-kit/media-kit#1065]
for andriod

pubspec.yaml
      media_kit: ^1.0.2
      media_kit_video: ^0.0.4
      media_kit_libs_video: ^1.0.5

code:
   controller = await VideoController.create(player.handle);

error:  
  MissingPluginException (MissingPluginException(No implementation found for method VideoOutputManager.Create on channel com.alexmercerind/media_kit_video))

**Comment by devrajraut** [comment]
I am having the Same Issue. Why is this Issue closed without resolution. Kindly Help. I'm trying it on MacOS. Have added all the 
packages required but still get the following error:

MissingPluginException(No implementation found for method VideoOutputManager.Create on channel com.alexmercerind/media_kit_video

Thanks.
