### ISSUE TITLE
[Question] position stream's events are discrete

### ISSUE THREAD

**Issue by moshOntong-IT** [media-kit/media-kit#118]
Explanation:
I have implemented a slider in my application to control the position of an audio file being played by the media player. As the media plays, the slider's value changes to reflect the current position in the audio file. However, I am encountering an issue where the slider position does not always reach the maximum value, which corresponds to the total duration of the audio file.

This behavior is inconsistent and prevents the slider from accurately representing the audio's progress. I have tried multiple audio files and the issue persists. I am seeking assistance in resolving this problem or any suggestions on what might be causing the position to not reach the maximum value of the slider.

Code:

```
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:media_kit/media_kit.dart';

// Declare necessary providers and states here

class _AudioPlayerControler extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _AudioPlayerControlerState();
}

class _AudioPlayerControlerState extends State<_AudioPlayerControler> {
  Player player = Player();
  bool seeking = false;

  List<StreamSubscription> _subscriptions = [];

  @override
  void initState() {
    super.initState();

    player.open(
      Playlist([
        Media(
          // Provide the path to the audio file here
        ),
      ]),
      play: false,
    );

    _subscriptions.addAll([
      player.streams.position.listen((event) {
        if (!seeking) {
          // Update position state here
          final duration = // Get the total duration
          double percentage =
              (event.inMilliseconds / duration.inMilliseconds) * 100;
          print(
              "Position: ${event.inMilliseconds}, Duration: ${duration.inMilliseconds}, Percentage: $percentage");
        }
      }),
      // Other subscriptions
    ]);
  }

  @override
  void dispose() {
    super.dispose();
    player.dispose();

    for (final sub in _subscriptions) {
      sub.cancel();
    }
  }

  @override
  Widget build(BuildContext context) {
    final position = // Get the position state
    final duration = // Get the duration state

    return Row(
      children: [
        IconButton(
          onPressed: () {
            // Play or pause logic
          },
          icon: // Use appropriate icon
        ),
        Expanded(
          child: Slider(
            min: 0.0,
            max: 100.0,
            value: duration.inMilliseconds > 0
                ? position.inMilliseconds.toDouble() /
                    duration.inMilliseconds.toDouble() *
                    100
                : 0.0,
            onChangeStart: (e) {
              seeking = true;
            },
            onChanged: position.inMilliseconds > 0
                ? (e) {
                    // Update position state here
                  }
                : null,
            onChangeEnd: (e) {
              seeking = false;
              player.seek(Duration(
                  milliseconds: (e / 100 * duration.inMilliseconds).toInt()));
            },
          ),
        ),
      ],
    );
  }
}

```

As you can see we have this print to observe the log 
```
      player.streams.position.listen((event) {
        if (mounted && !seeking) {
          ref.read(_positionProvider.notifier).state = event;
          final duration = ref.watch(_durationProvider);
          double percentage =
              (event.inMilliseconds / duration.inMilliseconds) * 100;
          print(
              "Position: ${event.inMilliseconds}, Duration: ${duration.inMilliseconds}, Percentage: $percentage");
        }
      }),
 ```
 
 The last output of print is
 ```
 flutter: Position: 1087, Duration: 1410, Percentage: 77.09219858156028
 ```
 
 As you can see the Position does not reach the duration which has the percentage of 77%

**Comment by alexmercerind** [comment]
WAI

**Comment by alexmercerind** [comment]
You need callbacks for every millisecond of a 1 second file... Do you know how computers work & performance?

**Comment by moshOntong-IT** [comment]
> You need callbacks for every millisecond of a 1 second file... Do you know how computers work & performance?
> 
> If you need that degree of smooth-ness, you can manually interpolate the values using [`AnimationController`](https://api.flutter.dev/flutter/animation/AnimationController-class.html) etc.
> 
> The media stream itself is decoded in chunks. These streams are provided to reflect the position updates in UI & make seek-bar etc. functional. If you are displaying an animated content of a second or two, why not use Animated WebP or GIF instead?

I think animation controller is not connected in my problem:

Watch the video attach link below:
[Issue with Duration](https://drive.google.com/file/d/1oDpChA3xcBNfACQV8rDjXtVobgfhalXZ/view?usp=sharing)


Focus on the slider aside of play buttons, as you can observe that the slider cant reach the maximum. And also I already provide the code:

**Comment by alexmercerind** [comment]
You can try to enable this:
https://mpv.io/manual/stable/#command-interface-audio-pts

**Comment by alexmercerind** [comment]
Can't really see it happen anymore. No further reports received.
