### ISSUE TITLE
[Docs] Unverified Publisher on pub.dev

### ISSUE THREAD

**Issue by piedcipher** [media-kit/media-kit#124]
Thanks for the nice package!

You could add a verified publisher on pub.dev if you wish. It would take 2 minutes. 🍺

<img src="https://user-images.githubusercontent.com/13456345/231537035-dfe26136-a31a-4d55-90d7-1a60e03d288b.png" width=350>

**Comment by alexmercerind** [comment]
Currently everything is in development. Not until matching [[RFC] Goals for 1.0.0](https://github.com/alexmercerind/media_kit/issues/114).

**Comment by alexmercerind** [comment]
It has been resolved after the latest update:

https://pub.dev/packages/media_kit

Now project is largely stable & used by number of projects. Looking forward to further improvements.
