### ISSUE TITLE
[Question] How to play video with start time?

### ISSUE THREAD

**Issue by hezhong0711** [media-kit/media-kit#228]
Is there any way to play video begin from a specific time like this command:
`mpv  --start=100 loadfile 'http://host/a.mp4' append  `

**Comment by cezres** [comment]
```dart
final Future<Duration> duration = player.streams.duration.first;
await player.open(Media(file.path), play: false);
await duration;
await player.seek(targetPosition);
await player.play();
```

**Comment by alexmercerind** [comment]
cc @ethicnology.

There is still not a dedicated solution; but above shall work.

**Comment by ethicnology** [comment]
I adapted my UX to  solve this need.
The video starts, If the user can resume, a resuming button that trigger the `player.seek` is displayed for a few seconds

**Comment by PurshuRana** [comment]
> ```dart
> final Future<Duration> duration = player.streams.duration.first;
> ```

I'm trying to open a recorded video(different Network Url) with a specific time when the user taps on the seek bar of Live Video Stream.
I tried this exactly but still video starts from the beginning.

**Comment by Prince-of-death** [comment]
this needs to be a core ability because when we do it like this the ui lags behind because first it loads position at 0 and then change it

**Comment by Prince-of-death** [comment]
@alexmercerind plz include this as a core abilty

**Comment by Prince-of-death** [comment]
> ```dart
> final Future<Duration> duration = player.streams.duration.first;
> await player.open(Media(file.path), play: false);
> await duration;
> await player.seek(targetPosition);
> await player.play();
> ```

this doest work always

**Comment by joodo** [comment]
> > ```dart
> > final Future<Duration> duration = player.streams.duration.first;
> > await player.open(Media(file.path), play: false);
> > await duration;
> > await player.seek(targetPosition);
> > await player.play();
> > ```
> 
> this doest work always

I've tried this:
```dart
await for (var buffering in player.stream.buffering) {
      if (!buffering) break;
}
player.seek(targetPosition);
```
instead of `await duration;`, it works well for me every time

**Comment by alexmercerind** [comment]
> @alexmercerind plz include this as a core abilty

We can't just publish a feature if it works for some cases. We want it to work for every case & every backend (native & web) with appropriate unit-tests.

You are free to use the solutions provided here (which hopefully work). But if the package releases something "stable" it becomes our responsibility to ensure its functioning.

**Comment by joodo** [comment]
> > @alexmercerind plz include this as a core abilty
> 
> We can't just publish a feature if it works for some cases. We want it to work for every case & every backend (native & web) with appropriate unit-tests.
> 
> You are free to use the solutions provided here (which hopefully work). But if the package releases something "stable" it becomes our responsibility to ensure its functioning.

But I think there still should be a stable way to make sure the video is "load finished", means remote video source is available and we can freely do actions like seek. Maybe `await controller.waitUntilFirstFrameRendered` should do this, but at least it does not work with seek so far.

**Comment by Prince-of-death** [comment]
> > > ```dart
> > > final Future<Duration> duration = player.streams.duration.first;
> > > await player.open(Media(file.path), play: false);
> > > await duration;
> > > await player.seek(targetPosition);
> > > await player.play();
> > > ```
> > 
> > 
> > this doest work always
> 
> I've tried this:
> 
> ```dart
> await player.stream.buffer.first;
> player.seek(targetPosition);
> ```
> 
> instead of `await duration;`, it works well for me every time

Both doesnt work right after the player is created

**Comment by Prince-of-death** [comment]
> 4\.

the problem is kind of like this

**Comment by Prince-of-death** [comment]
I recommend adding a initial time in the player.open function

**Comment by ethicnology** [comment]
> this needs to be a core ability because when we do it like this the ui lags behind because first it loads position at 0 and then change it

> @alexmercerind plz include this as a core abilty

> I recommend adding a initial time in the player.open function

@Prince-of-death Welcome to open source and free softwares where the scarce free time of developers is gifted to us

I recommend you start learning how to contribute to the codebase and implement this feature if it is so crucial for you, if not, you should work around the problem with one of the solutions offered above.

**Comment by Farg0k** [comment]
> ```dart
> final Future<Duration> duration = player.streams.duration.first;
> await player.open(Media(file.path), play: false);
> await duration;
> await player.seek(targetPosition);
> await player.play();
> ```
I don't know if it worked before, but now (media_kit: ^1.1.10, media_kit_video: ^1.2.4, media_kit_libs_video: ^1.0.4) it doesn't work.
Because player.streams.duration.first; is always zero before the stream is loaded. And it is also always zero before the stream is loaded
await player.stream.buffer.first;

For me, this solution worked
```
 await player.open(Media(file.path), play: false);
      controller.player.stream.duration.listen((event) async {
        if (event.inSeconds > 0){
          await player.seek(const Duration(seconds: targetPosition));
          await player.play();
        }
      });
```

**Comment by alexmercerind** [comment]
I did implement this in the latest PR:
- #581 

Thanks!
