### ISSUE TITLE
Is there an ability to set a poster image for video?

### ISSUE THREAD

**Issue by DenisAnkh** [media-kit/media-kit#265]
Is there an ability to set up a poster image for video and display the image before the video is not ready/started?

Something like that:

```dart
player.open(Media('https://user-images.githubusercontent.com/28951144/229373695-22f88f13-d18f-4288-9bf1-c3e078d83722.mp4', poster: '<url to poster>'));
```
or 

```dart
player.open(Media('https://user-images.githubusercontent.com/28951144/229373695-22f88f13-d18f-4288-9bf1-c3e078d83722.mp4', extras: {'poster': '<url to poster>'}));
```

**Comment by alexmercerind2** [comment]
Hi! No dedicated API yet. Maybe you can consume buffering stream & show it programmatically.

**Comment by alexmercerind** [comment]
No longer invested. It's possible to programmatically display using `Player.state` & `Player.stream` project already offers.
