### ISSUE TITLE
setAudioTrack with longer/shorter audio

### ISSUE THREAD

**Issue by kirill-21** [media-kit/media-kit#314]
Hi, i'm customly retrieving links from YouTube for video and audio and try to play them. The problem is that sometimes video duration differs from audio for 1 second. Because of this setAudioTrack feature just does not work and does not play any audio. Is there any solutions for this issue?
![image](https://github.com/media-kit/media-kit/assets/63228361/79b24f85-230a-4461-8837-854e8de4d8f9)
![image](https://github.com/media-kit/media-kit/assets/63228361/06ea0404-9c69-4748-b4bd-d03f99a8f899)

**Comment by alexmercerind** [comment]
I'll rather recommend creating two `Player`s & issuing commands to them simultaneously.

Secondly, I have no interest in setting up a sample project from scratch & retrieving video/audio samples to just reproduce the "bug".

**Comment by kirill-21** [comment]
> I'll rather recommend creating two `Player`s & issuing commands to them simultaneously.
> 
> Secondly, I have no interest in setting up a sample project from scratch & retrieving video/audio samples to just reproduce the "bug".

For some reason this issue reproduces after you first try to add direct video from youtube, then remove it and add from direct source 

With multiple players users won't be able to change sound with bottom sound button. Here is an example of the issue:

```dart
import 'package:flutter/material.dart';
import 'package:media_kit/media_kit.dart';
import 'package:media_kit_video/media_kit_video.dart';

void main() {
  MediaKit.ensureInitialized();
  runApp(MyApp());
}

// Create a [Player] to control playback.
final Player mediaKitPlayer = Player(
  configuration: const PlayerConfiguration(
    bufferSize: 128 * 1024 * 1024,
  ),
);

// Create a [VideoController] to handle video output from [Player].
final VideoController controller = VideoController(mediaKitPlayer);


class MyApp extends StatefulWidget {
  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  void initState() {
    mediaKitPlayer.open(Media('https://www.youtube.com/watch?v=Q2zfx5hQ3CE'));
   WidgetsBinding.instance.addPostFrameCallback((timeStamp) {
     mediaKitPlayer.remove(0);
     mediaKitPlayer.open(Media('https://rdce.me/videoplayback.mp4'));
     mediaKitPlayer.setAudioTrack(AudioTrack.uri('https://rdce.me/videoplayback.weba'));
   });
    super.initState();
  }

  @override
  void dispose() {
    mediaKitPlayer.dispose();
    super.dispose();
  }


  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: Center(
          child: Container(
            child: Video(
              controller: controller,
              filterQuality: FilterQuality.high,
              fit: BoxFit.fill,
              wakelock: false,
              pauseUponEnteringBackgroundMode: false,
            ),
          ),
        ),
      ),
    );
  }
}

```

**Comment by kirill-21** [comment]
Without this line of code it works fine, maybe i'm removing it in a wrong way?

```dart
  mediaKitPlayer.open(Media('https://www.youtube.com/watch?v=Q2zfx5hQ3CE'));
```

**Comment by alexmercerind** [comment]
Why are you adding direct YouTube video URL, may I ask?

**Comment by kirill-21** [comment]
> Why are you adding direct YouTube video URL, may I ask?

To start progress indicator in player while i'm parsing the direct link for audio & video tracks

**Comment by alexmercerind** [comment]
Don't. Why?

There are other better ways to indicate a "progress" rather than passing random strings to a method & causing undefined behavior.

**Comment by kirill-21** [comment]
> video

Well, by default if user has youtube-dl installed then this link will work, anyway it's strange behavior when you change media then custom audio stops working

**Comment by alexmercerind** [comment]
We unfortunately provide support for the features we have authored, tested & documented.

**Comment by alexmercerind** [comment]
> Well, by default if user has youtube-dl installed then this link will work.

I'm aware, but the latest build for Windows removes Lua support, which breaks it. The goal is to have a video/audio playback library that provides consistent behavior on all platforms (which obviously is _possible to a limit_). Please don't use any library in a way that it's not intended (otherwise you may experience "breaking changes").

I don't know what to do with this issue anymore when you are saying it works as intended after removing that YouTube URL method call. Note that it itself modifies the audio track in one way or another, it won't be wrong to expect an unintentional behavior afterwards. On GNU/Linux, where you have no control over the libmpv user has installed, it is bad to rely on such "hacks".

**Comment by alexmercerind** [comment]
> With multiple players users won't be able to change sound with bottom sound button.

If you're brave enough to experiment with hacky behaviors, you must be brave enough to write your own video controls.

**Comment by alexmercerind** [comment]
I'm going to consider this as "working-as-intended". Our Discord is a better place for discussions:

[![](https://img.shields.io/discord/1079685977523617792?color=33cd57&label=Discord&logo=discord&logoColor=discord)](https://discord.gg/h7qf2R9n57)
