### ISSUE TITLE
[Question] Complete Custom control examples?

### ISSUE THREAD

**Issue by michalss** [media-kit/media-kit#316]
Hello,

Is there any complete example with complete controls please ? I mean where i can choose from subtitles(external or embedden), choose audio tracks and so on ? I was able to found only very basic examples with play pause stop etc.. but not a way how to modify the controls or any advance control widgets as example.

BTW your player is very nice. Im very new to flutter, coming from C# world but there is many limitations in this field, but flutter offers your player with many functions and this is essential for me. Im plannig to write application similar to Kodi(currently using my own written in C#) and this could be a gold mine for me. 

Thank you regards

**Comment by sbenmeddour** [comment]
The library contains embedded controls that you can use in your app

If you want to implement an other UI, you can find inspiration in the source code: 
https://github.com/media-kit/media-kit/tree/main/media_kit_video/lib/media_kit_video_controls/src/controls

**Comment by alexmercerind** [comment]
You can build your controls the way you want or customize existing. Refer:

["Video controls" section in Guide](https://github.com/media-kit/media-kit#video-controls).
