### ISSUE TITLE
How to make the control display by default

### ISSUE THREAD

**Issue by shingohu** [media-kit/media-kit#318]
RT

**Comment by alexmercerind** [comment]
Good point. I will work on it in a few hours.

**Comment by alexmercerind** [comment]
Hi @shingohu,

1. Now buffering indicator is always visible.
2. I have added a new property called `visibleOnMount` to keep controls visible initially:

It is available for both `MaterialVideoControls` & `MaterialDesktopVideoControls`.

```dart
MaterialVideoControlsTheme(
  normal: const MaterialVideoControlsThemeData(
    visibleOnMount: true,
  ),
  fullscreen: const MaterialVideoControlsThemeData(
    visibleOnMount: true,
  ),
  child: MaterialDesktopVideoControlsTheme(
    normal: const MaterialDesktopVideoControlsThemeData(
      visibleOnMount: true,
    ),
    fullscreen: const MaterialDesktopVideoControlsThemeData(
      visibleOnMount: true,
    ),
    child: Video(
      controller: controller,
    ),
  ),
);
 ```
 
 <hr>

Refer to "Installation" section of the README for updating.

**Comment by pubpy2015** [comment]
Hi,

I am using mediakit to play live video stream from rtsp url, it works fine.
Since this is a live stream I don't need the progress bar,... and I'm setting it up like this:
`child: Video(
                      controller: _videoPlayerController,
                      controls: NoVideoControls,
                      fit: BoxFit.fill,
                    ),`
But with this setting CircularProgressIndicator will not show. Is there a setting that allows me to show it only?

**Comment by alexmercerind** [comment]
Please read the README, it has a "custom controls" section.

You can still use the existing event  streams & a `Stack` widget none the less. 🤷‍♂️

**Comment by pubpy2015** [comment]
Thanks,

I can do that by Custom Control:

controls: (state){
                        return Center(child: Visibility(
                            visible: _videoPlayer.state.buffering,
                            child: const CircularProgressIndicator()));
                      },
