### ISSUE TITLE
[Feature Request] Customize exitNativeFullscreen Orientations

### ISSUE THREAD

**Issue by shingohu** [media-kit/media-kit#320]
in my app case：
1、My app orientation  is portraitUp
2、when video enter Fullscreen and exit unable to return to portraitUp (if open the automatic rotation on android)

**Comment by alexmercerind** [comment]
Hi @shingohu,

In new update, you can pass `onEnterFullscreen` & `onExitNativeFullscreen` to `Video` to change th behavior e.g. orientation, status-bar, fullscreen etc. etc.

```dart
Video(
  controller: controller,
  onEnterFullscreen: () async {
    // TODO: Handle enter fullscreen.
  },
  onExitFullscreen: () async {
    // TODO: Handle exit fullscreen.
  },
);
```

Refer to "Installation" section of the README for updating.

<hr>

You might wanna keep our default functions to some modifications:

https://github.com/media-kit/media-kit/blob/769829c5c56c30216db646ba426c81ffb9368a39/media_kit_video/lib/src/video/video_texture.dart#L294-L343
