### ISSUE TITLE
[Bug Report] `MPV.xcframework` error on case-sensitive disk on macOS

### ISSUE THREAD

**Issue by wanjm** [media-kit/media-kit#321]
1.1.1 compile failed on case sentitive disk on macos for there are mix using MPV and Mpv and infact the dirname is Mpv.xframeworks
<img width="322" alt="image" src="https://github.com/media-kit/media-kit/assets/3118573/25fd8913-d0b6-4a07-9f10-ee63bf4d9485">

**Comment by alexmercerind** [comment]
Upgrade all dependencies, not one or two.
