### ISSUE TITLE
[Bug Report][Android] Buffering is not called in the first seek, when playing online audio

### ISSUE THREAD

**Issue by LiuFeiPublic** [media-kit/media-kit#325]
When playing online audio, seeking to the unbuffered area for the first time, player.stream.buffering is not called.
When seeking to the unbuffered area for the second time, player.stream.buffering is called normally.
https://github.com/media-kit/media-kit/assets/68208322/90ca1e5d-56d7-4529-9cdd-e070c929459f

**Comment by alexmercerind** [comment]
Hi!

Thanks for the bug-report, I'm unable to prioritize this issue at the moment due to other higher-priority issues.

**Comment by alexmercerind** [comment]
A new update has been released.

Please refer to the "Installation" section of the README.
