### ISSUE TITLE
[Question] The ability to disable gestures

### ISSUE THREAD

**Issue by Atulin** [media-kit/media-kit#326]
I'm making an application where the user can swipe through a list of images, videos, gifs, and other media. Currently, swiping through a MediaKit player can be quite janky, because of the gestures that change volume instead of letting the video be swiped away.

I could probably work around it with a transparent overlay, but it would be nice to be able to just natively disable the gestures.

**Comment by alexmercerind** [comment]
Refer to ["Video controls" section in the README](https://github.com/media-kit/media-kit#video-controls).

I have spent a huge-huge amount of time making everything customizable. Just read document carefully, you aren't forced to use the gestures. If the default video controls don't work for you, just disable them with `NoVideoControls` or write your own.

```dart
MaterialVideoControlsTheme(
  normal: const MaterialVideoControlsThemeData(
    volumeGesture: false,
    brightnessGesture: false,
    seekOnDoubleTap: false,
  ),
  fullscreen: const MaterialVideoControlsThemeData(
    volumeGesture: false,
    brightnessGesture: false,
    seekOnDoubleTap: false,
  ),
  child: Video(
    controller: controller,
  ),
);
```

<hr>

Lastly, consider improving project's documentation. The scope is very big for a single individual's "side-project time".

**Comment by Atulin** [comment]
Ah, I completely missed that somehow. Thanks!

**Comment by Atulin** [comment]
Well, I now use

```dart
MaterialVideoControlsTheme(
  normal: const MaterialVideoControlsThemeData(
    volumeGesture: false,
    brightnessGesture: false,
  ),
  fullscreen: const MaterialVideoControlsThemeData(),
  child: Video(controller: controller),
),
```

but swiping left and right still changes volume and prevents the user from swiping between pages

**Comment by alexmercerind** [comment]
I mean code can't lie:

https://github.com/media-kit/media-kit/blob/88b1a6da7de02723338333cb804d1bbde56ed66f/media_kit_video/lib/media_kit_video_controls/src/controls/material.dart#L776-L829

Do you even want video controls, just pass `NoVideoControls`. Refer to docs.

**Comment by Atulin** [comment]
I want video controls, I just don't want gestures.

And what actually happens can't lie either. So it's either a quirk on Windows or something else is wrong.

https://github.com/media-kit/media-kit/assets/11233299/f256819c-d705-4b4e-a515-8c17d6816b9c

**Comment by alexmercerind** [comment]
Hi!

By default `AdaptiveVideoControls` are used i.e. `MaterialVideoControls` on mobile & `MaterialDesktopVideoControls` on desktop.

You must set `modifyVolumeOnScroll` inside `MaterialDesktopVideoControlsThemeData`.

Once again, **please refer to docs**. 

Built-in video controls are just a "side-feature" & I assume Flutter developers should be comfortable with understanding Dart. My most work here is related to C/C++, native interop & video rendering.
