### ISSUE TITLE
#EXT-X-KEY Supported?

### ISSUE THREAD

**Issue by Arsenicss** [media-kit/media-kit#327]
Hi,
I tested a m3u8 link with #EXT-X-KEY in the demo app and it doesn't seem to work properly, it keeps loading and won't play. When I switch to another m3u8 link without #EXT-X-KEY it works fine!

The m3u8 file content is like:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-ALLOW-CACHE:YES
#EXT-X-TARGETDURATION:11
#EXT-X-KEY:METHOD=AES-128,URI="https://xxxxx.net/ott-video/vod.key"

#EXTINF:10.643967,
/live_00000000.ts
#EXTINF:9.843167,
/live_00000001.ts
#EXTINF:10.176833,
/live_00000002.ts
#EXTINF:9.509500,
/live_00000003.ts
#EXTINF:10.643967,
/live_00000004.ts
#EXTINF:10.010000,
/live_00000005.ts
#EXTINF:10.010000,
/live_00000006.ts
.....
```

**Comment by alexmercerind** [comment]
Which platform? We have done separate work for each platform.

**Comment by Arsenicss** [comment]
> Which platform? We have done separate work for each platform.

A Singaporean streaming platform [Viu.com](https://www.viu.com)
[Here's an M3U8 link ](https://d1k2us671qcoau.cloudfront.net/vodapi/viu_akm.m3u8?vid=86385679e6ccec670cd2d2397b27e244&layer=Layer2&area_id=2&lang_id=2&ts=202308052101&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kMWsydXM2NzFxY29hdS5jbG91ZGZyb250Lm5ldC92b2RhcGkvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY5MTI1ODQ2Mn19fV19&Signature=aS~mAiwHwKejrry4EFJQ~eQXz0-pp9bBY3pyn3PqkC14FrkpIRq8afg-chZMmq5s2rf~dNCbYrltGjkZTLnum4AW50KXGWtFCZW3BkG68~6PWVfbN0OvDm1ns1h-C48MX3WzJ1LmG~gMRXI-DPb83GKNqrSUb~buIotdxq~RuoKBnxSk~KfCfbXJ916RUc6tQo5j7qXUPZOS7kp0hKEqFaulPzjP-80KNDGss30K9cWTzOfoNVA1FX2erEUzbZ4RKm-kD2REAG~tVt~q3Eh16~QOTZYmkTNTFCCvaK6j4ysCLvF8~yDx-nhNxMQW-bD3OpZdCJxCgzmpPpiGn4yjCg__&Key-Pair-Id=APKAJ6Z4RF5IYK7Y3SQQ)

**Comment by joaojsrbr** [comment]
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:10
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-KEY:METHOD=AES-128,URI="https://bettdc1.ga/drm/M/ePUrDFLlON/dPXs1m7Fke/aOiwWVVx2X/EQyG7pDpSo/EQyG7pDpSo.key",IV=0x4CDF73D74D8CCEC0E479DBE40012DDA0
```

I have the same problem.

Platform: android.

**Comment by birros** [comment]
@Arsenicss, @joaojsrbr Can you try with `mpv` from cli, please.

**Comment by Arsenicss** [comment]
> @Arsenicss, @joaojsrbr Can you try with `mpv` from cli, please.

Works fine on the mpv.

**Comment by joaojsrbr** [comment]
> > @Arsenicss, @joaojsrbr Can you try with `mpv` from cli, please.
> 
> Works fine on the mpv.

```
C:\Users\joaov>mpv --version
mpv 0.35.1 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Sun Jan 29 05:42:05 2023
FFmpeg library versions:
   libavutil       57.44.100
   libavcodec      59.58.100
   libavformat     59.36.100
   libswscale      6.8.112
   libavfilter     8.55.100
   libswresample   4.9.100
FFmpeg version: N-109691-gb95b2c849


C:\Users\joaov>mpv https://betterserver.ga/pl/M/ncpt5qGkW6/8KUa2omqB3/brWyDNP5GB/qx1Me07ESq/qx1Me07ESq.m3u8 --http-header-fields="Referer: https://betteranime.net/" --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
 (+) Video --vid=1 (h264 854x480 23.976fps)
 (+) Audio --aid=1 (aac 2ch 44100Hz)
AO: [wasapi] 48000Hz stereo 2ch float
VO: [gpu] 854x480 => 854x480 yuv420p
AV: 00:00:01 / 00:23:40 (0%) A-V: -0.000 Cache: 51s/5MB
```

it works.

**Comment by birros** [comment]
@alexmercerind Adding `--enable-protocol=crypto` to `ffmpeg` build makes the following sample work.

- AES-128 content protected sample: https://cdn.theoplayer.com/video/big_buck_bunny_encrypted/stream-800/index.m3u8
- AES-128 content protected doc: https://docs.theoplayer.com/knowledge-base/02-content-protection/02-aes-128-encryption.md
- ffmpeg doc: https://ffmpeg.org/ffmpeg-protocols.html#crypto

**Comment by alexmercerind** [comment]
![](https://github.com/media-kit/media-kit/assets/28951144/6896ee98-ed62-4e2a-89b2-bf2a2bf5351e)

Can't wait to cross-compile for every platform again.

**Comment by alexmercerind** [comment]
Can someone mail me a sample at <alexmercerind@gmail.com> to confirm the fix?

**Comment by alexmercerind** [comment]
Hi! This has been fixed with the latest update, please refer to the "Installation" section in the README.

**Comment by birros** [comment]
To be consistent, I'll add `--enable-protocol=crypto` to macOS & iOS in the next few hours / days.
