### ISSUE TITLE
[Q][iOS] Why there is a black flash when jumping some video on iOS, while fine on Android.

### ISSUE THREAD

**Issue by doubleLLL3** [media-kit/media-kit#332]
Hi, there is a black flash when jumping some video (including the same video) on iOS.

![Screen Recording 2023-08-06 at 10 24 04](https://github.com/media-kit/media-kit/assets/44157339/83b10f3a-109a-4ac7-a41b-c000d795a955)

This is my player load method:

```
loadVideos(
      List<String> videoSources, Function(bool) completedListener) async {
    player ??= Player();
    controller ??= VideoController(player!);

    // switch video after video completed
    player?.stream.completed.listen(completedListener);

    final playListSources = videoSources
        .map((videoSource) => Media(
              videoSource,
            ))
        .toList();
    final playable = Playlist(playListSources, index: 0);
    await player?.open(playable);
  }
```

This is my simple switch code:
```
loadVideos(videoSources, (bool completed) async {
      if (completed) {
            player?.jump(0);  // [Q] happened a black flash between 2 videos
      }
}
```

This is the dependencies:
```
  media_kit: ^1.1.1                              # Primary package.
  media_kit_video: ^1.1.1                        # For video rendering.
  media_kit_native_event_loop: ^1.0.6            # Support for higher number of concurrent instances & better performance.
  media_kit_libs_android_video: ^1.3.0           # Android package for video native libraries.
  media_kit_libs_ios_video: ^1.0.5               # iOS package for video native libraries.
```

**Comment by birros** [comment]
I'll take care of it in a few hours.

**Comment by birros** [comment]
> Hi, there is a black flash when jumping some video (including the same video) on iOS.

I can reproduce on macOS, the code is the same as iOS. It's the "normal" behavior today.
It's caused by `textureUpdateCallback` called even when `width` or `height` is `0`: https://github.com/media-kit/media-kit/blob/111d9e868f6c57272bbce095754f1587b77bdcb2/media_kit_video/common/darwin/Classes/plugin/VideoOutput.swift#L136-L146

When I apply the following patch, the black screen disappears:
```diff
diff --git a/media_kit_video/common/darwin/Classes/plugin/VideoOutput.swift b/media_kit_video/common/darwin/Classes/plugin/VideoOutput.swift
index 9f6a6a2..a8e54f0 100644
--- a/media_kit_video/common/darwin/Classes/plugin/VideoOutput.swift
+++ b/media_kit_video/common/darwin/Classes/plugin/VideoOutput.swift
@@ -133,6 +133,10 @@ public class VideoOutput: NSObject {
       height: Double(height)
     )
 
+    if width == 0 || height == 0 {
+      return
+    }
+
     if currentWidth != width || currentHeight != height {
       currentWidth = width
       currentHeight = height
@@ -141,10 +145,6 @@ public class VideoOutput: NSObject {
       textureUpdateCallback(textureId, size)
     }
 
-    if width == 0 || height == 0 {
-      return
-    }
-
     if disposed {
       return
     }
```

@alexmercerind Should I apply this patch, or leave the current behavior (black screen)?

**Comment by birros** [comment]
@doubleLLL3 From what I understand of your code, you seem to be manually looping your playlist, there is this option to do this:

```dart
player.setPlaylistMode(PlaylistMode.loop);
```

**Comment by alexmercerind** [comment]
> Should I apply this patch, or leave the current behavior (black screen)?

I leave this to you. Does keeping/removing result in any issue? Consider this on your end.

**Comment by birros** [comment]
> Does keeping/removing result in any issue?

I don't think so. The removal of black screen should prevent the creation of new issues about that.

**Comment by alexmercerind** [comment]
Sure.

In Windows implementation, I skip texture resize entirely if video-size comes as (0, 0):

https://github.com/media-kit/media-kit/blob/9bac9ddec6db130c37ca06795cd8bc3f1873bf5c/media_kit_video/windows/video_output.cc#L242-L247

**Comment by doubleLLL3** [comment]
> @doubleLLL3 From what I understand of your code, you seem to be manually looping your playlist, there is this option to do this:↳
> 
> ```dart
> player.setPlaylistMode(PlaylistMode.loop);
> ```

Thx a lot!

Actually I also need jump to different video in sometime. So, when will the new version 1.1.2 of media_kit_video release?

Now, it throws:
```
Because app depends on media_kit_video ^1.1.2 which doesn't match any versions, version solving failed.
```

**Comment by alexmercerind** [comment]
@doubleLLL3 

We've published an update with the fix. Refer to the "Installation" section of the README.

Thanks!
