### ISSUE TITLE
Playing Videos From YouTube

### ISSUE THREAD

**Issue by MousyBusiness** [media-kit/media-kit#347]
I can't seem to play videos from Youtube, while I can play self hosted files. Is there a trick to this, is it not possible with this player, are some special headers required that you are aware of?

**Comment by alexmercerind** [comment]
I missed the part where I said it can.
Figure it out yourself... I don't want to help with shady things.

**Comment by alexmercerind** [comment]
To be clear, you should extract the actual video/audio URL with something like [youtube_explode_dart](https://pub.dev/packages/youtube_explode_dart) and then play that.

**Comment by MousyBusiness** [comment]
I wasn't aware it was a shady practice to embed YouTube videos. Given that I would assume its a common platform which I assume I'm not the only developer looking to implement, you might put a note saying that due to YouTube terms and services and its ability to play ads, this library does not support that functionality. Currently the view just infinity loads so it looks like a bug, even though based on your response, its by design.

**Comment by alexmercerind** [comment]
It never worked like that for any library. YouTube is a business with its own content-protection methods for its platform.

**Comment by Ahmadre** [comment]
> I missed the part where I said it can. Figure it out yourself... I don't want to help with shady things.

Sorry, but what is this for a response? You could explain him maybe in 2-3 words why this is not possible instead of accusing her/him to do shady things.

Github should be a safe place to talk about code and not people.

The question wasn't any dangerous question regarding security. So we would be grateful if you talk about the issue and not the person.
