### ISSUE TITLE
[Feature Request]  Supports the playback of rmvb videos

### ISSUE THREAD

**Issue by zhangruiyu** [media-kit/media-kit#348]
{"timestamp":"2023-08-09T08:37:31.738902Z","level":"error","prefix":"vd","message":"Failed to initialize a decoder for codec 'rv40'."}

I tried to use the plugin to play rmvb format video, found that can not play, how to add support for rmvb or other formats

**Comment by zhangruiyu** [comment]
![image](https://github.com/media-kit/media-kit/assets/10591822/d4e2fb14-35e1-4d72-96da-f68e4ad694d1)

**Comment by alexmercerind** [comment]
You can refer to our packages's code (each platform is different) & repositories in this organizations, to cross-compile & bundle libmpv with selected decoders.

**Comment by zhangruiyu** [comment]
Although it is very inappropriate to say, in fact, I have not been in contact with any in-depth development of audio and video, and only call good plug-ins written by others, that is, the technology is very dishes. .

**Comment by alexmercerind** [comment]
We can't include support for every codec out of the box, we want it to be small sized for most use-cases.

The project is open-source & I'm not your slave. Go ahead.

**Comment by zhangruiyu** [comment]
I will try my best. Thank you for your answer

**Comment by alexmercerind** [comment]
In the future, we plan to publish `media_kit_libs_*_video_full` packages, but no motivation at the moment.

**Comment by zhangruiyu** [comment]
Thank you very much. I will learn dart ffi and ffmeg, and also try to support rmvb by myself. Looking forward to your update in the future. May I ask if you have Alipay or wechat payment code? Because of my country, I cannot sponsor you through github. I believe that other developers in our country who use this package will also want to support your update, but there is no good channel

**Comment by alexmercerind** [comment]
You don't need to learn C/C++, FFI or FFmpeg, you just need to edit compilation configuration. In-fact, we already have full variant for Android:

https://github.com/media-kit/libmpv-android-video-build/releases/tag/v1.1.1

Just see how we the default flavor builds & make necessary changes locally.

**Comment by zhangruiyu** [comment]
Wow, thank you so much, haha, now go to study, happy

**Comment by zhangruiyu** [comment]
![image](https://github.com/media-kit/media-kit/assets/10591822/dd01721c-86fb-4697-bfb5-75b7a8f633ed)
I am trying to complete this section and ready to add the following fields in yaml. Which do you think is good, or help to come up with a name, ready to read in gradle, and then determine whether full format support
If free time allows, I will try to support ios,mac in the future

**Comment by zhangruiyu** [comment]
![image](https://github.com/media-kit/media-kit/assets/10591822/c2a4ac17-62ff-411d-800d-ede9bfbbc3f7)
![image](https://github.com/media-kit/media-kit/assets/10591822/50d11a98-c7c9-44a8-b1b3-4c0a60d083b6)
![image](https://github.com/media-kit/media-kit/assets/10591822/b42d19ac-cbea-4b5f-af50-6ec39fed52cc)

Like this I just tried to reference to full.jar

And the MD5 check should be removed, manual modification of the MD5 judgment is more troublesome thing, should be downloaded to a temporary file, through the request response code to determine whether to download the complete and then modify the corresponding name

**Comment by zhangruiyu** [comment]
I'm sorry md5 should not be modified. I reread it. Sorry
