### ISSUE TITLE
[Enhancement] Distinguishing between video and live stream

### ISSUE THREAD

**Issue by animia0** [media-kit/media-kit#352]
When playing a live stream, the player should automatically hide widgets such as the progress bar that are not applicable to live broadcasts.

Currently, I've noticed that there isn't a direct API to determine whether the current playback is a video or a live stream.

Perhaps we could add an API like this: `player.state.isLiveStream`, or are there other methods to achieve this effect?

**Comment by alexmercerind** [comment]
I have to think if there is a stable way to differentiate (because there are so many formats).

I believe it's better to handle it from your end. You must be aware if some URL is livestream or not (wherever you are fetching it from) & change the video controls accordingly.

**Comment by birros** [comment]
Like @alexmercerind I think it's up to the dev to determine whether it's a livestream or not.
I haven't found an example of `ffmpeg` being able to detect this without parsing the stream metadata for a few seconds / minutes. I doubt `mpv` will do better than `ffmpeg`.

An easy way to detect if it's a livestream is to watch if the `duration` changes over time, but that requires waiting for the buffer to load.
If this means that the user has to wait several seconds for the buffer to load just to determine whether it's a livestream or not, it's not viable…

**Comment by 23doors** [comment]
There are ways to determine that but as @alexmercerind and @birros - they are not bullet proof and as ffmpeg/mpv doesnt expose it, it shouldn't be media_kit responsibility as well.

For the brave and willing, you can download the manifest and check it. In 99% cases it will be a DASH or HLS. But there are overall 4 possibilities that I know of.

1. DASH manifest. If MPD@minimumUpdatePeriod is present - it's a live stream.
2. HLS manifest. Here you need to check master playlist and if it has video+audio streams split you need to check also media playlists. If segment streams end with EXT-X-ENDLIST - then it's not a live stream (or it's one that is already finished).
3. ISM manifest (dunno if mpv even supports ISM as it's not as popular as DASH and HLS). Check if SmoothStreamingMedia@IsLive = TRUE.
4. MPEG-TS - rarely used these days. Here media is just streamed in chunks, no way to pre-determine it other than monitoring if duration has changed.

**Comment by animia0** [comment]
Unfortunately, there doesn't seem to be a reliable way to distinguish between a live stream and a video stream during playback. 

To optimize this, I am adding an option to my application, allowing the users to manually select whether the input link is a live stream or a video stream.

**Comment by alexmercerind** [comment]
> Unfortunately, there doesn't seem to be a reliable way to distinguish between a live stream and a video stream during playback.

The most "reliable" way I can think of is to simply see if the duration is being changed after the playback has started.

I don't think any media players e.g. mpv or VLC etc. modify their UI in any way. If you work with some API or your own infrastructure, you must be well aware of the content that some URL has (& thus, show the video controls accordingly).

Thanks!

For now, I'm marking this as a non-goal; obviously, PRs are welcomed.
