### ISSUE TITLE
[Bug Report] DASH having BaseURL(s) with special characters not loading

### ISSUE THREAD

**Issue by lamarios** [media-kit/media-kit#353]
Hi, 
I'm trying to switch my invidious client app to media_kit but i'm having issues with dash.

For example, this url: https://vid.puffyan.us/api/manifest/dash/id/zrJZ3VYo3Xo

It loads indefinitely and no error in the logs. I added a listener on the error stream.

**I only tried on Android**

Here are the relevant logs i can get
```
I/flutter ( 9329): media_kit: AndroidVideoController: Emulator detected.
I/flutter ( 9329): media_kit: AndroidVideoController: Enforcing S/W rendering.
I/media_kit( 9329): com.alexmercerind.media_kit_video.VideoOutputManager.create: 132085863256032
I/media_kit( 9329): com.alexmercerind.media_kit_video.VideoOutput: id = 0
I/media_kit( 9329): com.alexmercerind.media_kit_video.VideoOutput: wid = 6442
I/flutter ( 9329): {wid: 6442, id: 0}
I/flutter ( 9329): media_kit: wakelock: _count = 1
I/flutter ( 9329): buffering true // this is my listener on buffer stream)
```

I have no issues with  [non dash stream urls](https://rr3---sn-ab5l6nrd.googlevideo.com/videoplayback?expire=1691671577&ei=uIfUZL_9O9Gp_9EPjtqg-AI&ip=2001%3A19f0%3A5%3Aeff%3A5400%3A4ff%3Afe78%3A2d55&id=o-ANQPM3RQQmdOXHQ0l7ldskp6EEXyeVtcrfG_Wuiv6ou4&itag=22&source=youtube&requiressl=yes&mh=7s&mm=31%2C26&mn=sn-ab5l6nrd%2Csn-p5qs7nsk&ms=au%2Conr&mv=m&mvi=3&pl=38&initcwndbps=2056250&spc=UWF9f3yC-jjpwoNbZB-aoEFVxj3CaMc&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=1093.032&lmt=1691574769172157&mt=1691649663&fvip=3&fexp=24007246%2C24362685&c=ANDROID&txp=4432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgIDAv4CKU4FjhDCPygqWeCkx_eIlXjAG9YZVhQpOj0ssCIQC9zE7RZHYFKTrUSdUR8Q07uWAlw4U1lZ5qXv7DhKH56w%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgS7NbL7ktLO6GGPHy-UvIfN1LMI6hXGSEu_5vaj4ypFYCIDqvY7kp8gs7UE43tNYBsA9rPJeR3jlMw7oLihAOh3bT&host=rr3---sn-ab5l6nrd.googlevideo.com) from the same api.

I'm currently using better_player and i had to make a fork because it was expecting a `.mpd `  url to figure out that it was a dash stream.  Is it the same for media_kit ?

**Comment by alexmercerind** [comment]
Thanks for the descriptive report. I'll be able to take a look in a few hours after returning from work.

We do have DASH support, this URL seems to have some problems. We'll see.

**Comment by lamarios** [comment]
no rush :)  thanks for the package, it looks really promising

**Comment by alexmercerind** [comment]
Hi! How can I play that stream? I can't seem to play the URL anywhere:

https://vid.puffyan.us/api/manifest/dash/id/zrJZ3VYo3Xo

**Comment by lamarios** [comment]
when i click this link it downloads a .mpd file.  With better_player it works, it just did not recognize the tracks by default, only after i modified it so that it doesn't specifically require a .mpd  url.

**Comment by alexmercerind** [comment]
I mean the video/audio streams inside the MPD are inaccessible.

**Comment by lamarios** [comment]
:thinking:  that's strange. It should be youtube video / audio streams. I'm not really an expert when it comes to video streams and related stuff. I just use the URL as dash stream and it works. 

Alternatively, is there a way to build a media_kit Media from my own set of tracks (audio / video / subtitles) as that could work too

I'm using invidious api, can find the data here:
https://vid.puffyan.us/api/v1/videos/zrJZ3VYo3Xo

It has `formatStreams` (with video and audio embedded) those work with media_kit, separate audio and video tracks in  `adaptiveFormats` and a `dashUrl`

**Comment by Joseph-Nathan** [comment]
is it possible to play separate audio and video track in the same time ?

**Comment by alexmercerind** [comment]
@Joseph-Nathan 
> Is it possible to play separate audio and video track at the same time?

Yes. Refer: https://github.com/media-kit/media-kit#load-external-audio-track


Our Discord is a better place for random discussion.

**Comment by alexmercerind** [comment]
I fixed this issue upstream with a patch, the fix will be ready in a few hours.

**Comment by lamarios** [comment]
Awesome. I'll check it out this week end.

**Comment by lamarios** [comment]
which of the media_kit libraries i should update ?

**Comment by alexmercerind** [comment]
@lamarios,

Apologies :) I was getting the bundles ready. Your feedback will be helpful before I make a release:

You just need to update `media_kit_libs_***` package(s):

```yaml
  media_kit_libs_windows_video:
    git:
      url: https://github.com/media-kit/media-kit.git
      ref: 3b828c734067a66395e0e3c682dd89ac8bb3f9c9
      path: libs/windows/media_kit_libs_windows_video
  media_kit_libs_android_video:
    git:
      url: https://github.com/media-kit/media-kit.git
      ref: 3b828c734067a66395e0e3c682dd89ac8bb3f9c9
      path: libs/android/media_kit_libs_android_video
```

<hr>

Refer to #355 for further details.

I also want to tell that https://vid.puffyan.us/api/manifest/dash/id/zrJZ3VYo3Xo still does not work for me (probably my region).
I tried https://onion.tube/api/manifest/dash/id/zrJZ3VYo3Xo & it works for me now (didn't work before).

I have made fixes for Windows & Android, both work well with these DASH URLs.

**Comment by alexmercerind** [comment]
Still... playing non-DASH URLs seems a safer approach to me (since you have a choice).

We already have an external audio/subtitle track API.

**Comment by alexmercerind** [comment]
Please do confirm the fix if it works.

**Comment by lamarios** [comment]
Video is working fine, though I see a couple of issues:

First, tracks are found but not identified properly:
```
I/flutter ( 6715): VIDEO
I/flutter ( 6715): VideoTrack(auto, null, null)
I/flutter ( 6715): VideoTrack(no, null, null)
I/flutter ( 6715): VideoTrack(1, null, null)
I/flutter ( 6715): VideoTrack(2, null, null)
I/flutter ( 6715): VideoTrack(3, null, null)
I/flutter ( 6715): VideoTrack(4, null, null)
I/flutter ( 6715): VideoTrack(5, null, null)
I/flutter ( 6715): VideoTrack(6, null, null)
I/flutter ( 6715): VideoTrack(7, null, null)
I/flutter ( 6715): AUDIO
I/flutter ( 6715): AudioTrack(auto, null, null)
I/flutter ( 6715): AudioTrack(no, null, null)
I/flutter ( 6715): AudioTrack(1, null, null)
I/flutter ( 6715): AudioTrack(2, null, null)
I/flutter ( 6715): AudioTrack(3, null, null)
I/flutter ( 6715): SUBS
I/flutter ( 6715): SubtitleTrack(auto, null, null, false)
I/flutter ( 6715): SubtitleTrack(no, null, null, false)
```

Second, probably related to the first one, when the connection is not good it does not switch to lower quality automatically.

**Comment by alexmercerind** [comment]
I don't think there is any information to identify besides frame-rate, bit-rate & resolution. Probably that can be exposed.

However, I don't think there's anything that can be done about "connection is not good it does not switch to lower quality automatically."

**Comment by lamarios** [comment]
Yeah exposing this data would be good so that a menu with the track options can be built.

**Comment by alexmercerind** [comment]
> Yeah exposing this data would be good so that a menu with the track options can be built.

Exposed relevant details in #358:

```
VideoTrack(auto, null, null, image: null, albumart: null, codec: null, decoder: null, w: null, h: null, channelscount: null, channels: null, samplerate: null, fps: null, bitrate: null, rotate: null, par: null, audiochannels: null)
VideoTrack(no, null, null, image: null, albumart: null, codec: null, decoder: null, w: null, h: null, channelscount: null, channels: null, samplerate: null, fps: null, bitrate: null, rotate: null, par: null, audiochannels: null)
VideoTrack(1, null, null, image: false, albumart: false, codec: h264, decoder: null, w: 1920, h: 1080, channelscount: null, channels: null, samplerate: null, fps: 60.0, bitrate: null, rotate: null, par: null, audiochannels: null)
VideoTrack(2, null, null, image: false, albumart: false, codec: h264, decoder: null, w: 1280, h: 720, channelscount: null, channels: null, samplerate: null, fps: 60.0, bitrate: null, rotate: null, par: null, audiochannels: null)
VideoTrack(3, null, null, image: false, albumart: false, codec: h264, decoder: null, w: 854, h: 480, channelscount: null, channels: null, samplerate: null, fps: 30.0, bitrate: null, rotate: null, par: null, audiochannels: null)
VideoTrack(4, null, null, image: false, albumart: false, codec: h264, decoder: null, w: 640, h: 360, channelscount: null, channels: null, samplerate: null, fps: 30.0, bitrate: null, rotate: null, par: null, audiochannels: null)
VideoTrack(5, null, null, image: false, albumart: false, codec: h264, decoder: null, w: 426, h: 240, channelscount: null, channels: null, samplerate: null, fps: 30.0, bitrate: null, rotate: null, par: null, audiochannels: null)
VideoTrack(6, null, null, image: false, albumart: false, codec: h264, decoder: null, w: 256, h: 144, channelscount: null, channels: null, samplerate: null, fps: 30.0, bitrate: null, rotate: null, par: null, audiochannels: null)
VideoTrack(7, null, null, image: false, albumart: false, codec: h264, decoder: null, w: 256, h: 144, channelscount: null, channels: null, samplerate: null, fps: 15.0, bitrate: null, rotate: null, par: null, audiochannels: null)
AudioTrack(auto, null, null, image: null, albumart: null, codec: null, decoder: null, w: null, h: null, channelscount: null, channels: null, samplerate: null, fps: null, bitrate: null, rotate: null, par: null, audiochannels: null)
AudioTrack(no, null, null, image: null, albumart: null, codec: null, decoder: null, w: null, h: null, channelscount: null, channels: null, samplerate: null, fps: null, bitrate: null, rotate: null, par: null, audiochannels: null)
AudioTrack(1, null, null, image: false, albumart: false, codec: aac, decoder: null, w: null, h: null, channelscount: 2, channels: stereo, samplerate: 44100, fps: null, bitrate: 1172, rotate: null, par: null, audiochannels: 2)
AudioTrack(2, null, null, image: false, albumart: false, codec: aac, decoder: null, w: null, h: null, channelscount: 2, channels: stereo, samplerate: 44100, fps: null, bitrate: 443, rotate: null, par: null, audiochannels: 2)
AudioTrack(3, null, null, image: false, albumart: false, codec: aac, decoder: null, w: null, h: null, channelscount: 2, channels: stereo, samplerate: 44100, fps: null, bitrate: 278, rotate: null, par: null, audiochannels: 2)
SubtitleTrack(auto, null, null, image: null, albumart: null, codec: null, decoder: null, w: null, h: null, channelscount: null, channels: null, samplerate: null, fps: null, bitrate: null, rotate: null, par: null, audiochannels: null)
SubtitleTrack(no, null, null, image: null, albumart: null, codec: null, decoder: null, w: null, h: null, channelscount: null, channels: null, samplerate: null, fps: null, bitrate: null, rotate: null, par: null, audiochannels: null)
```

**Comment by alexmercerind** [comment]
A new update has been released.

Please refer to the "Installation" section of the README.

**Comment by lamarios** [comment]
Thanks. Sorry I didn't get to test the last changes. I got caught up with something else.
