### ISSUE TITLE
[Bug Report][macOS] compilation failed: cannot find type 'mpv_node_list' in scope

### ISSUE THREAD

**Issue by isxuelinme** [media-kit/media-kit#354]
media_kit_video-1.1.3/macos/Classes/plugin/common/MPVVideoOutParams.swift:23:12: error: cannot find type 'mpv_node_list' in scope
    _ map: mpv_node_list

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.2, on macOS 13.5 22G74 darwin-arm64, locale
    zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Community Edition (version 2021.1.1)
[✓] VS Code (version 1.80.2)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 1 category.

**Comment by birros** [comment]
This error seems to indicate that the `mpv` headers are missing from the `media_kit_video` package.

Can you check their presence with the following command:
```shell
$ ls macos/Flutter/ephemeral/.symlinks/plugins/media_kit_video/macos/Headers/mpv/*
macos/Flutter/ephemeral/.symlinks/plugins/media_kit_video/macos/Headers/mpv/client.h
macos/Flutter/ephemeral/.symlinks/plugins/media_kit_video/macos/Headers/mpv/render.h
macos/Flutter/ephemeral/.symlinks/plugins/media_kit_video/macos/Headers/mpv/render_gl.h
macos/Flutter/ephemeral/.symlinks/plugins/media_kit_video/macos/Headers/mpv/stream_cb.h
```

Also, can you share with us the `media_kit_*` packages used in your `pubspec.yaml`.

**Comment by isxuelinme** [comment]
thanks for your answer
I use  brew install mpv to install mpv to my MacOs 13.5 (22G74), 
mpv -v
[cplayer] mpv 0.36.0 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects


Also found header in /opt/homebrew/include/mpv

And my env is 
export CPATH=/opt/homebrew/include
export LIBRARY_PATH=/opt/homebrew/lib

**Comment by isxuelinme** [comment]
I am just using  in pubspec.yaml

flutter_meedu_videoplayer: ^4.2.6

**Comment by isxuelinme** [comment]
<img width="910" alt="image" src="https://github.com/media-kit/media-kit/assets/13929427/0d387865-90cf-46ed-a168-2448d6485faa">

**Comment by alexmercerind** [comment]
Our CI for macOS succeeds. End of discussion.

**Comment by isxuelinme** [comment]
Still unable to compile and run, I suspect that the linked shell was not executed correctly on macOS ARM because the following location is empty: ephemeral/. symlinks/plugins/media_ Kit_ Video/macos/Headers/mpv/

**Comment by Crazy-MT** [comment]
+1
