### ISSUE TITLE
How to listen playing state changed ?

### ISSUE THREAD

**Issue by pubpy2015** [media-kit/media-kit#356]
Hi,
Currently, I'm playing an rtsp video stream and getting the play status by listening for events:

player.stream.error.listen((error) => debugPrint("error: " + error));
player.stream.buffering.listen((buffering) => debugPrint("buffering: " + buffering.toString()));
player.stream.playing.listen((playing) => debugPrint("playing: " + playing.toString()));
player.stream.log.listen((event) => debugPrint(" mpv: ${event.prefix}: ${event.level}: ${event.text}"));

with available stream, the status sequence is as follows:
playing: false => playing: true => buffering: true => buffering: false

with not available stream (disconnect):
playing: false => playing: true => buffering: true

the error event never fires and buffering still true although connection timeout.
mpv log:
mpv: ffmpeg/demuxer: error: rtsp: method DESCRIBE failed: 404 Stream Not Found
mpv: lavf: error: avformat_open_input() failed
cplayer: error: Failed to recognize file format.

Can I only listen for 1 event where the player's state is updated ?
Here is the set of player's state in VLC
enum PlayingState {
  initializing,
  initialized,
  stopped,
  paused,
  ended,
  buffering,
  playing,
  recording,
  error,
}

**Comment by alexmercerind** [comment]
The error will correctly fire for this situation in the next update.

**Comment by pubpy2015** [comment]
Thanks,

in case of source switching from one stream to another, can you discard the last frame of the previous stream (go to black screen) before connecting to the new stream?

**Comment by alexmercerind** [comment]
In most cases preserving last frame is ideal, I'll see.

**Comment by pubpy2015** [comment]
Hi, my case is:

I use media kit to display video from some network cameras (rtsp stream). When switching from one camera to another, I want to hide the image of the previous camera to show that I am connecting to another camera.

**Comment by pubpy2015** [comment]
Another question: 

By default the player decodes on GPU, but on my 1 old device, with H265 video stream, the video is not displayed. However if I set enableHardwareAcceleration=false, the video stream can display normally. In cases like this, can the media kit automatically switch back to CPU decoding when the GPU fails?

**Comment by alexmercerind** [comment]
I simply do not care.

**Comment by alexmercerind** [comment]
> Hi, my case is:
> 
> I use media kit to display video from some network cameras (rtsp stream). When switching from one camera to another, I want to hide the image of the previous camera to show that I am connecting to another camera.

Raised #418.
