### ISSUE TITLE
[Bug Report][IOS] No sound / subtitles for some formats. - Failed to initialize a decoder 

### ISSUE THREAD

**Issue by cst1412** [media-kit/media-kit#359]
Hi, i upgraded my version of media_kit from `1.0.2` to `1.1.3+1` and for some videos i do not have sound and subtitles anymore. (All mkv files). On linux this does not seem to be an issue.

The player is logging the following: 

```
flutter: PlayerLog(prefix: ad, level: error, text: Failed to initialize a decoder for codec 'dts'.)
flutter: PlayerLog(prefix: ad, level: error, text: Failed to initialize a decoder for codec 'dts'.)
flutter: PlayerLog(prefix: sub/lavc, level: fatal, text: Could not open libavcodec subtitle decoder)
flutter: PlayerLog(prefix: sub/lavc, level: fatal, text: Could not open libavcodec subtitle decoder)
flutter: PlayerLog(prefix: sub/ass, level: fatal, text: Could not open libavcodec subtitle converter)
flutter: PlayerLog(prefix: sub/ass, level: fatal, text: Could not open libavcodec subtitle converter)
flutter: PlayerLog(prefix: sub, level: error, text: Could not find subtitle decoder for format 'hdmv_pgs_subtitle'.)
flutter: PlayerLog(prefix: sub, level: error, text: Could not find subtitle decoder for format 'hdmv_pgs_subtitle'.)
```

<img width="535" alt="image" src="https://github.com/media-kit/media-kit/assets/47171405/cb4e4b1e-f269-4bf6-b89b-81f7759cfbde">

**Comment by alexmercerind** [comment]
Hello!

We decided to strip things a bit to optimize for the bundle size on Windows, Android, macOS & iOS.
For now, you can bundle the `*full*` variant instead of `*default*` one. You can find pre-compiled binaries here:

- https://github.com/media-kit/libmpv-darwin-build/releases
- https://github.com/media-kit/libmpv-android-video-build/releases

A temporary workaround can be to pin your `media_kit_libs_*` version to older one.

**Comment by andynvt** [comment]
> Hello!
> 
> We decided to strip things a bit to optimize for the bundle size on Windows, Android, macOS & iOS. For now, you can bundle the `*full*` variant instead of `*default*` one. You can find pre-compiled binaries here:
> 
> * https://github.com/media-kit/libmpv-darwin-build/releases
> * https://github.com/media-kit/libmpv-android-video-build/releases
> 
> A temporary workaround can be to pin your `media_kit_libs_*` version to older one.

can you give a detail code implementation?
