### ISSUE TITLE
help ! windows build error occured

### ISSUE THREAD

**Issue by iOSluozhiping** [media-kit/media-kit#360]
CMake Error at flutter/ephemeral/.plugin_symlinks/media_kit_libs_windows_video/windows/CMakeLists.txt:116 (message):
  ANGLE.7z integrity check failed.

**Comment by alexmercerind** [comment]
Hi!

Please do `flutter clean` & try to re-build.

We do not encounter any issues:
https://github.com/media-kit/media-kit/actions/runs/5843529203/job/15845760490
