### ISSUE TITLE
[Windows] When the window is maximized, when playing the video in full screen, there will be margins on the four edges of the video

### ISSUE THREAD

**Issue by nihai18789797273** [media-kit/media-kit#361]
When the window is maximized, when playing the video in full screen, there will be margins on the four edges of the video
![image](https://github.com/media-kit/media-kit/assets/57181627/8df912fc-9c17-4e6e-b94f-ada52db16e33)

**Comment by alexmercerind** [comment]
A bug from the window package you're using.

We filed a more neutral implementation here: https://github.com/leanflutter/window_manager/pull/367

**Comment by nihai18789797273** [comment]
This is the package I am using now
![image](https://github.com/media-kit/media-kit/assets/57181627/4475e6a4-2912-4be9-9db7-387b912a53b9)

**Comment by alexmercerind** [comment]
I linked the PR above. Or, [you can use `MaterialDesktopCustomButton`](https://github.com/media-kit/media-kit#materialvideocontrols) to call fullscreen method(s) from that package.

**Comment by nihai18789797273** [comment]
I'll give it a try Thank you very much

**Comment by alexmercerind** [comment]
[package:window_manager released a new version](https://github.com/leanflutter/window_manager/releases/tag/v0.3.6), I think it will make our fullscreen implementation compatible out-of-the-box.

Thanks!
