### ISSUE TITLE
macos build fail

### ISSUE THREAD

**Issue by twoeggs** [media-kit/media-kit#362]
media_kit: ^1.1.3                              # Primary package.
  media_kit_video: ^1.1.3                        # For video rendering.
  media_kit_native_event_loop: ^1.0.7            # Support for higher number of concurrent instances & better performance.
  media_kit_libs_macos_video: ^1.1.2             # macOS package for video native libraries.
  media_kit_libs_windows_video: ^1.0.6

flutter build macos

ld: warning: directory not found for option '-F/Users/zexu.ge/Documents/workspace/my/singing_manager/macos/Pods/../Flutter/ephemeral/.symlinks/plugins/media_kit_libs_macos_video/macos/Frameworks/.symlinks/mpv/macos'
ld: framework not found Mpv
clang: error: linker command failed with exit code 1 (use -v to see invocation)
warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Flutter Assemble' from project 'Runner')
** BUILD FAILED **

**Comment by alexmercerind** [comment]
Check this out:

https://github.com/media-kit/media-kit/actions/runs/5843529203/job/15845760531

**Comment by dev-xdyang** [comment]
this issue maybe work https://github.com/media-kit/media-kit/issues/71
