### ISSUE TITLE
[windows] Multiple RTSP streams (>=4) cause continuous increase in CPU and GPU usage, leading to black flickering

### ISSUE THREAD

**Issue by xietian0908** [media-kit/media-kit#363]
May I kindly ask for any recommended optimization methods to address this issue?

**Comment by alexmercerind** [comment]
Your hardware specifications will always matter.

On my entry-level Ryzen 3 2200U with integrated Radeon Vega 3, I can play around 15-20 HD videos simultaneously. Obviously, the increased delay & slowdown can be seen.

Even in the current state, the performance of media_kit on Windows is same as Google Chrome. For further advancements in performance on Windows, you can subscribe the following issue.
- #296

There is no timeline, entirely depends upon the support project receives.

**Comment by alexmercerind** [comment]
For further optimizations, you can limit rendering size with `width` & `height` as follows:


```dart
final VideoController player = VideoController(
  player,
  configuration: const VideoControllerConfiguration(
    // Supply your options:
    width: 640,                            // default: null
    height: 480,                           // default: null
  ),
);
```
