### ISSUE TITLE
[Feature Request] How to resume playback after app comes back from background

### ISSUE THREAD

**Issue by pubpy2015** [media-kit/media-kit#366]
Hi,

When the app is in the background, the media kit pauses (or stops?) the video. How to resume playback?

**Comment by alexmercerind** [comment]
A new update has been released.

Please refer to the "Installation" section of the README.

Following shall work:

```dart
Video(
  controller: controller,
  pauseUponEnteringBackgroundMode: true,
  resumeUponEnteringForegroundMode: true,
);
```
