### ISSUE TITLE
[Bug Report] There is a problem with pausing video playback before continuing to play during video buffering

### ISSUE THREAD

**Issue by nihai18789797273** [media-kit/media-kit#367]
During the video buffering process, click the button in the bottom left corner to pause the video playback. When continuing the video playback, Loading will always be displayed on the screen.

**Comment by alexmercerind** [comment]
Can't reproduce.

**Comment by alexmercerind** [comment]
A new update has been released.

Please refer to the "Installation" section of the README.

**Comment by nihai18789797273** [comment]
There are still issues with testing the latest package. During the loading process, the video playback was paused. After the video was successfully loaded, the loading did not disappear. However, after clicking on the play button, the loading did indeed disappear (a great job). However, after the loading was successful, the loading automatically disappeared and became a play button, which would make the experience better?

**Comment by nihai18789797273** [comment]
> 新的更新已发布。新的更新已发布。
> 
> 请参阅自述文件的“安装”部分。请参阅自述文件的“安装”部分。

There are still issues with testing the latest package. During the loading process, the video playback was paused. After the video was successfully loaded, the loading did not disappear. However, after clicking on the play button, the loading did indeed disappear (a great job). However, after the loading was successful, the loading automatically disappeared and became a play button, which would make the experience better?

**Comment by nihai18789797273** [comment]
![image](https://github.com/media-kit/media-kit/assets/57181627/2794e3d1-c684-44ba-ad87-822b349c2a3b)

**Comment by alexmercerind** [comment]
The buffering indicator will hide when you press play again (it wasn't hiding before). It is intended behaviour, I added a unit-test too:

https://github.com/media-kit/media-kit/blob/d4100553068b56c48d8ab1eaa0f19620fc01f796/media_kit/test/src/player/player_test.dart#L2392-L2462

**Comment by nihai18789797273** [comment]
> The buffering indicator will hide when you press play again (it wasn't hiding before).当您再次按下播放时，缓冲指示器将隐藏（之前没有隐藏）。
> 
> It is intended behavior, I added a unit-test too:这是预期的行为，我也添加了单元测试：
> 
> https://github.com/media-kit/media-kit/blob/d4100553068b56c48d8ab1eaa0f19620fc01f796/media_kit/test/src/player/player_test.dart#L2392-L2462

I would like to say if it is possible to automatically hide loading when buffering ends or the video can continue to play. The current effect is to click pause during the buffering process. If you do not click the play button again, loading will continue to exist.

**Comment by alexmercerind** [comment]
PR welcomed with appropriate tests.
