### ISSUE TITLE
Support for HLS video streaming

### ISSUE THREAD

**Issue by NiteshMethani** [media-kit/media-kit#369]
Hi,
Thank you so much for creating this package. It's super useful. I have couple of questions though:

1. How to extend this package to add support video streaming (eg: HLS, .m3u8, DASH, etc)? I'm new to this domain but would be happy to learn and contribute.
2. video_player package uses ExoPlayer for Android whereas AVPlayer for iOS. These I believe are native players and support HLS streaming. Does media_kit also uses these players behind the scene? If yes, then we can refer the video_player package to add support for streaming. If no, what player does media_kit uses for these platforms?

P.S.: HLS = HTTP Live Streaming

Thanks in advance!

**Comment by alexmercerind** [comment]
Already works.

**Comment by alexmercerind** [comment]
The codec support is far better in package:media_kit, plus you can enable more by compiling own binaries.

**Comment by NiteshMethani** [comment]
can you kindly provide a demo for the stream?
I tried it with the following HLS stream and it did not work on Android: https://cdn.bitmovin.com/content/assets/art-of-motion-dash-hls-progressive/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8

The debug log showed that the platform does not support the provided type.

**Comment by alexmercerind** [comment]
You should just update media_kit_libs_*** packages.

We had some regression few days ago. A new update has just been released with some other fixes.

Let us know if that works.

**Comment by NiteshMethani** [comment]
This is great. I upgraded the packages and it works well on MacOS.
I just have one more question: I'm trying to build something like a TikTok where videos will be played back to back.
Ideally there are three basic things:
1. there should not be any delay while playing the video
2. (N+1)th videos should already get fetched from the databse and added to the queue while playing Nth video.

How can I achieve this behavior? I thought streaming (instead of playing full videos) will solve the problem but there is still some delay at the start while playing .m3u8 videos.
Would appreciate your suggestions here. I am happy to read and learn more about it if you have any pointers.

**Comment by alexmercerind** [comment]
It sounds more like an implementation question rather than a bug-report or feature-request.

FORTUNATELY, I have one example to teach people:

https://github.com/media-kit/media-kit/blob/main/media_kit_test/lib/tests/09.seamless.dart

Here, pre-initialization & memoization is the key:

https://user-images.githubusercontent.com/28951144/258612232-52260678-73a4-4d66-9a46-3a93919a0421.mp4

<hr>

Please use issues only for bug-reports & feature-requests & maintain hygiene.

We have a dedicated Discord server for conversations.

**Comment by alexmercerind** [comment]
> There is still some delay at the start while playing .m3u8 videos.

That's how computers & networks work.

**Comment by NiteshMethani** [comment]
Appreciate the example. I'll reach out to the community on Discord in future.
Thank you for your patience.
