### ISSUE TITLE
[Linux] Request better instruction on how to compile the linux version

### ISSUE THREAD

**Issue by lKinderBueno** [media-kit/media-kit#370]
I am testing media-kit on linux, but I am not able to compile the linux version. 
Everytime I try to compile the project it shows this error:
`ninja: error: 'mimalloc/out/release/mimalloc.o', needed by 'plugins/media_kit_libs_linux/CMakeFiles/MIMALLOC_TARGET', missing and no known rule to make it`.

I installed the required libraries "libmpv-dev mpv" and skipped the mimalloc part because it is an optional step, but it still shows this error.

**Comment by alexmercerind** [comment]
I don't even know what kind of better instructions do you need.

I mean how hard is it to install packages by editing `pubspec.yaml`?

Check this out, GNU/Linux build succeeds:

https://github.com/media-kit/media-kit/actions/runs/5881455028/job/15949965184

**Comment by philipscott** [comment]
@alexmercerind I'm having the same issue ... and no you're right editing pubspec.yaml is super easy, but I'm new to Linux so forgive me for asking a simple question. I have now followed the instructions at https://microsoft.github.io/mimalloc/build.html to build and install mimalloc and tried both options (with the mimalloc reference in CMakeFile and without) but still get this build error. I now have a mimalloc.o but it the build still doesn't find it ... your extreme patience would be greatly appreciated

**Comment by alexmercerind** [comment]
Y'all using Flutter's snap installation?

You don't need to use or install mimalloc separately. It's completely optional (Ctrl+F in our README) & can be enabled by just adding one line.

**Comment by philipscott** [comment]
yes using snap installation.

ldd --version
ldd (Ubuntu GLIBC 2.35-0ubuntu3.1) 2.35

**Comment by alexmercerind** [comment]
Don't use it. Never.

**Comment by lKinderBueno** [comment]
> Y'all using Flutter's snap installation?
> 
> You don't need to use or install mimalloc separately. It's completely optional (Ctrl+F in our README) & can be enabled by just adding one line.

Yes, I used snapd. On Monday I'll try to install it manually. It is strange because it works flawless using githuh action

**Comment by alexmercerind** [comment]
Flutter snap is a mistake. I'll open an issue at flutter/flutter to not encourage it as the recommended way of installation.

This is not the first time people are having issues & certainly not just compile time issues.

It bundles its own dependencies, which often cause mismatch with things from the package manager. Secondly, it may not have sufficient permissions at times.

**Comment by philipscott** [comment]
Thank you @alexmercerind I have removed tech snapd version and installed flutter manually ... it compiles fine now. Appreciate your help

**Comment by RossComputerGuy** [comment]
I get the same issue on NixOS. Is there an actual fix besides "install Flutter manually"?

**Comment by alexmercerind** [comment]
@RossComputerGuy 

You'll need libmpv at the end of the day as a dependency. I'm sure NixOS has its own way of installation.

We don't control which packages get bundled inside Flutter's snap; so we can't decide. Distribution through Flatpak or Snap is another concern & documented in the README; few users have shared their experience in some other issues which you may find helpful.

**Comment by RossComputerGuy** [comment]
@alexmercerind I added libmpv and libass and I started getting this crash.
```
Launching lib/main.dart on Linux in debug mode...
Building Linux application...
Unhandled exception:
Crash when compiling:
Class 'StateError' not found in library 'dart:core'

#0      _ClassTable._getClassIndex (package:kernel/library_index.dart:194:7)
#1      _ClassTable.getConstructor (package:kernel/library_index.dart:216:12)
#2      LibraryIndex.getConstructor (package:kernel/library_index.dart:118:38)
#3      CoreTypes.stateErrorConstructor (package:kernel/core_types.dart:295:13)
#4      CoreTypes.stateErrorConstructor (package:kernel/core_types.dart)
#5      ConstantsTransformer.visitPatternVariableDeclaration (package:front_end/src/fasta/kernel/constant_evaluator.dart:1670:41)
#6      PatternVariableDeclaration.accept1 (package:kernel/src/ast/patterns.dart:2016:14)
#7      RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1920:21)
#8      ConstantsTransformer.visitBlock (package:front_end/src/fasta/kernel/constant_evaluator.dart:779:27)
#9      Block.accept1 (package:kernel/ast.dart:9176:58)
```

**Comment by alexmercerind** [comment]
Please do refer to our unit-tests; where everything works correctly & all tests pass.

I (or anyone else) hasn't encountered that.

**Comment by RossComputerGuy** [comment]
I figured out a part of the issue but discovered that the `mimalloc.o` file is not being created. It looks like only the `libmimalloc.so.*` files are being made and the `mimalloc.pc` along with the CMake files. I ran make manually and it works but this isn't going to be an optimal solution.

**Comment by alexmercerind** [comment]
Maybe we shouldn't attempt to build mimalloc by default. Also, currently it is being built through commandline; as opposed to add_subdirectory() etc. (which probably should be changed):

https://github.com/media-kit/media-kit/blob/main/libs/linux/media_kit_libs_linux/linux/CMakeLists.txt

**Comment by Pato05** [comment]
I'm facing the same issue
```
ninja: error: 'mimalloc/out/release/mimalloc.o', needed by 'plugins/media_kit_libs_linux/CMakeFiles/MIMALLOC_TARGET', missing and no known rule to make it
```

I have flutter installed manually already and debug releases work fine. I have also tried installing mimalloc, but no luck..

**Comment by alexmercerind** [comment]
@Pato05 

There are many things that can go wrong on someone's system locally.

We run unit-tests & builds on the CI for each commit:
- https://github.com/media-kit/media-kit/actions/runs/6531133257/job/17731756245

**Comment by Andreas02-dev** [comment]
> @alexmercerind I added libmpv and libass and I started getting this crash.
> ```
> Launching lib/main.dart on Linux in debug mode...
> Building Linux application...
> Unhandled exception:
> Crash when compiling:
> Class 'StateError' not found in library 'dart:core'
> 
> #0      _ClassTable._getClassIndex (package:kernel/library_index.dart:194:7)
> #1      _ClassTable.getConstructor (package:kernel/library_index.dart:216:12)
> #2      LibraryIndex.getConstructor (package:kernel/library_index.dart:118:38)
> #3      CoreTypes.stateErrorConstructor (package:kernel/core_types.dart:295:13)
> #4      CoreTypes.stateErrorConstructor (package:kernel/core_types.dart)
> #5      ConstantsTransformer.visitPatternVariableDeclaration (package:front_end/src/fasta/kernel/constant_evaluator.dart:1670:41)
> #6      PatternVariableDeclaration.accept1 (package:kernel/src/ast/patterns.dart:2016:14)
> #7      RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1920:21)
> #8      ConstantsTransformer.visitBlock (package:front_end/src/fasta/kernel/constant_evaluator.dart:779:27)
> #9      Block.accept1 (package:kernel/ast.dart:9176:58)
> ```

Hi Ross,

I just switched from Ubuntu to NixOS and am currently trying to see if I can use it to develop. I've managed to make a flake with Flutter web, Linux and Android with emulator, but I'm a bit blocked currently by not having libmpv. Do you have the time to point me in the right direction for getting libmpv in my dev environment?

Thanks in advance!
