### ISSUE TITLE
[Bug Report][GNU/Linux] Jank in UI

### ISSUE THREAD

**Issue by alexmercerind** [media-kit/media-kit#371]
While using `Player` or `VideoController` API on GNU/Linux i.e. creation, calling methods, etc. I can notice an extreme amount of jank (substantial freeze in the UI for a brief period of time). On the other hand, during normal & idle video-playback, no slowdown or jank is seen.

**Comment by ItsVeridian** [comment]
I'm on Windows and seeking and looping seems to cause a jank, even affecting other videos that aren't seeking at that moment. Not sure if it's related.

**Comment by alexmercerind** [comment]
@ItsVeridian, "jank" here is described as the freeze in Flutter UI. There is no "jank" on seek.

In the case of looping, subscribe to #150.

**Comment by vectorobject** [comment]
I want to see each frame in real-time while dragging. I've noticed that after seeking, Flutter's UI animation pauses briefly. However, when playing the video directly in mpv.exe, dragging the progress bar is very smooth.

```
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:media_kit/media_kit.dart';
import 'package:media_kit_video/media_kit_video.dart';
import 'package:media_kit_video/media_kit_video_controls/src/controls/methods/video_state.dart';

class MediaKitTest extends StatefulWidget {
  const MediaKitTest({Key? key}) : super(key: key);
  @override
  State<MediaKitTest> createState() => MediaKitTestState();
}

class MediaKitTestState extends State<MediaKitTest> {
  late final player = Player();
  late final controller = VideoController(player);

  @override
  void initState() {
    super.initState();
    player.open(Media(Uri.file(r'G:\video\demo.mp4').toString()), play: false);
  }

  @override
  void dispose() {
    player.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Material(
      color: Colors.transparent,
      child: Column(children: [
        Expanded(
            child: FittedBox(
          child: SizedBox(
            width: MediaQuery.of(context).size.width,
            height: MediaQuery.of(context).size.width * 9.0 / 16.0,
            child: Video(
              controller: controller,
              controls: (state) {
                return Material(
                    color: Colors.transparent,
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.end,
                      children: [
                        Transform.translate(
                          offset: const Offset(0.0, 16.0),
                          child: const MyMaterialDesktopSeekBar(),
                        ),
                        const Row(
                          children: [
                            MaterialDesktopPlayOrPauseButton(),
                            MaterialDesktopVolumeButton(),
                            MaterialDesktopPositionIndicator(),
                            Spacer(),
                            CircularProgressIndicator(),
                            MaterialDesktopFullscreenButton(),
                          ],
                        )
                      ],
                    ));
              },
            ),
          ),
        )),
      ]),
    );
  }
}

class MyMaterialDesktopSeekBar extends MaterialDesktopSeekBar {
  const MyMaterialDesktopSeekBar({
    Key? key,
  }) : super(key: key);

  @override
  MaterialDesktopSeekBarState createState() => MyMaterialDesktopSeekBarState();
}

class MyMaterialDesktopSeekBarState extends MaterialDesktopSeekBarState {
  double seekedSlider = 0.0;

  late Timer _timer;
  @override
  void initState() {
    _timer = Timer.periodic(const Duration(milliseconds: 100), (timeStamp) {
      if (click) {
        if (seekedSlider != slider) {
          seekedSlider = slider;
          controller(context).player.seek(duration * slider);
        }
      }
    });
    super.initState();
  }

  @override
  void dispose() {
    _timer.cancel();
    super.dispose();
  }
}

```

Flutter：

https://github.com/media-kit/media-kit/assets/49273109/5b69c0af-957f-46b3-bdcc-ae69c8760e30

mpv.exe:

https://github.com/media-kit/media-kit/assets/49273109/f4c271de-a3ed-4d90-8547-9304c8cd6972

demo.mp4:

https://github.com/media-kit/media-kit/assets/49273109/e97350dd-166f-4e39-80c8-eabaf777b48d


Reducing the interval of the _timer allows for more noticeable changes.

**Comment by alexmercerind** [comment]
@vectorobject 

First of all this is unrelated.

<hr>

There's a reason why our default seek-bar only seeks upon mouse button up event.

Currently all native methods are invoked (using dart:ffi) on the UI thread (one exception is `screenshot` method). This certainly freezes the UI for a period of time. In general situation, this is unnoticeable (when too many calls are not queued). A solution can be to move all native invocations to another `Isolate`, however that will bring additional delay & I have noticed performance degradation in an attempt while doing so.  

Secondly, as a matter of fact, video rendering is done on Flutter's rendering thread (that's how most graphics API work anyway; single-threaded). On Windows (& macOS?), we render on another thread & only copy rendered frame from that thread to destination on Flutter's rendering thread (copying is faster than rendering as far as I have seen). Essentially, video frame is rendering is sandwiched between Flutter's own UI rendering. Technically, for every video that's added to UI, time to draw each Flutter frame (UI + video(s)) will increase (which isn't noticeable for moderate number of videos, I can play 20 HD videos on my entry-level machine).

This is never going to be as efficient as mpv, primarily because:
- Additional inter-op is involved between Flutter & libmpv.
- mpv.exe is using more efficient renderer compared to package:media_kit.
  - For Windows, refer to #296.
- mpv.exe is only rendering video, while Flutter has it's own UI to draw.

This issue is specifically for GNU/Linux, because it's not possible to render to another thread. Primarily because `GdkGLArea` won't allow using that OpenGL context on another thread. In general, the amount of jank on GNU/Linux is extremely high.

On Windows, macOS & Android, Flutter UI appears smooth regardless of video playback & invocation of native methods. Obviously, this may not be the case if there are too many videos at once etc. The specifications (CPU, GPU, RAM etc.) of the computer will always be a concern & we can't defy science.

At the moment, the level of performance is very good. I don't think I can afford to research further right now.

**Comment by vectorobject** [comment]
@alexmercerind 
Thank you very much for your detailed response, and media_kit's performance has been excellent. I appreciate your efforts. However, I would like to mention some tests I recently conducted:

1. I tested another Flutter video playback library called fvp using the same method on Windows. fvp's seek appears to be very fast, and the UI is also smooth. However, fvp has many bugs, as it often seeks to the wrong frame, to the point that I had to stop using it.


2.  When I tested with media_kit, I tried removing the display of the Video and only keeping a custom SeekBar. When I drag the progress bar to seek, it still freezes the UI for a while. Below is the modified portion of the code:

```
Widget build(BuildContext context) {
    return Material(
      color: Colors.transparent,
      child: Column(children: [
        Expanded(
            child: FittedBox(
          child: SizedBox(
            width: MediaQuery.of(context).size.width,
            height: MediaQuery.of(context).size.width * 9.0 / 16.0,
            /*child:Video()...*/
          ),
        )),
        SeekBar(controller: controller)
      ]),
    );
  }
```

**Comment by alexmercerind** [comment]
@vectorobject 

I'm not interested in engaging in conversations on GitHub, especially on this thread which is for a completely different issue. Our Discord is a better place for conversations in general.

> I tested another Flutter video playback library called fvp using the same method on Windows. fvp's seek appears to be very fast, and the UI is also smooth.

I simply do not care.

package:media_kit uses dart:ffi for native interop for the most part. The advantage of this is that a large amount of code is shared on all platforms, which makes behavior the same across platforms. Secondly, the maintenance becomes easier.

I don't want to compete either. I'm not a company.


> When I tested with media_kit, I tried removing the display of the Video and only keeping a custom seek bar. 

Like I said, there's a reason why our seek-bar works differently, how it should.

**Comment by alexmercerind** [comment]
You still can move the seek call to another `Isolate` yourself.
