### ISSUE TITLE
How about exposing cli argument interface?

### ISSUE THREAD

**Issue by syehoonkim** [media-kit/media-kit#373]
Dear,
I appreciate your works here.
However, I need to pass cli arguments to mpv(such as applying low-latency profile, using lavf, ...) but it seems no such interfaces.
I made it by editing your real.dart file by myself passing arguments string to _command() in open(...) method, but I really didn't want to do.
It will be fascinating if I directly pass arguments to mpv with neat interfaces.
Please consider it.
Thank you.

**Comment by alexmercerind** [comment]
There already is a forbidden API. setProperty/observeProperty API, no support will be provided if you break something while using it though.

**Comment by alexmercerind** [comment]
Also... Not all filters & flag (most will) may work, we use minimal build to reduce bundle size.

**Comment by syehoonkim** [comment]
Thank you!!
