### ISSUE TITLE
Some m3u8 files cannot play on Chrome, work fine on Macos,Windows

### ISSUE THREAD

**Issue by twoeggs** [media-kit/media-kit#376]
platform: Chrome web
url: https://singing.tusenpo.cn/file/singing-videos/cff6cd47-b507-4e7d-b9ac-bad1598caa9d.m3u8

Error: 

dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 321:10  createErrorWithStack
dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 337:28            _throw
dart-sdk/lib/core/errors.dart 120:5                                           throwWithStackTrace
dart-sdk/lib/async/zone.dart 1386:11                                          callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 177:15           <fn>

**Comment by alexmercerind** [comment]
![image](https://github.com/media-kit/media-kit/assets/28951144/4fdb6e74-22db-4915-a97c-4c52c369e2f8)


We can't do anything about your browser, we didn't write it's code.

**Comment by alexmercerind** [comment]
[HLS.js](https://github.com/video-dev/hls.js/) seems to emulate HLS support inside web browsers.

It's not implemented for web.

**Comment by alexmercerind** [comment]
@twoeggs 

The HLS support for web will be available in next update.

- #384

Thanks!

**Comment by twoeggs** [comment]
> @twoeggs
> 
> The HLS support for web will be available in next update.
> 
> * [feat: HLS support for web #384](https://github.com/media-kit/media-kit/pull/384)
> 
> Thanks!

great !
