### ISSUE TITLE
How to display video from Uint8List?

### ISSUE THREAD

**Issue by SittiphanSittisak** [media-kit/media-kit#380]
My app records the video as Uint8List and I want to display this.

restriction:
I am using Flutter web and I can't convert Uint8List to File using `IO`.

**Comment by alexmercerind** [comment]
Only for the web?

**Comment by SittiphanSittisak** [comment]
Hi, I found a solution to display this video from Uint8List by [this](https://stackoverflow.com/a/65834130/17798537)
```
    final url = html.Url.createObjectUrlFromBlob(blob); //Uint8List can convert/revert to blob
    player.open(Media(url));
```

but it will be better if the Media can pass Uint8List instead of only the URL.

**Comment by alexmercerind** [comment]
There's a new `Media.memory` constructor in latest update. Refer to "Installation" section of the README.


> It does not work successfully for all browsers.

Try passing MIME to the `type` argument.
