### ISSUE TITLE
[Enhancement] Decryption key API

### ISSUE THREAD

**Issue by BrunoC96** [media-kit/media-kit#381]
Hi,
I'm using media_kit, and those are my dependency:
`media_kit: ^1.1.4+1`
`media_kit_video: ^1.1.5 `            
`media_kit_native_event_loop: ^1.0.7`
`media_kit_libs_android_video: ^1.3.2`
`media_kit_libs_ios_video: ^1.1.3 `
`media_kit_libs_macos_video: ^1.1.3`
`media_kit_libs_windows_video: ^1.0.7`
`media_kit_libs_linux: ^1.1.1`

i'm trying to view this DASH link,
`http://hls.redefine.pl/BCB79C03/18830/0/dash_iptv/live.mpd`,
I see in the console that he take the 1080p resolution, as in the file.
`{handle: 5986636160, id: 4890081520, rect: {height: 1080.0, left: 0.0, width: 1920.0, top: 0.0}}`
but the screen is completely gray with some flux of data scatter around.

I think I need to add to this resource a `Widevine License` but i don't know how can i add it.

**Comment by alexmercerind** [comment]
We don't have a dedicated API for it yet, but you can use the `setProperty` API probably.

```dart
final player = Player();

if (player.platform is NativePlayer) {
  await (player.platform as dynamic).setProperty(
    'demux-lavf-o',
    'decryption_key=<KEY>', /* <--- */
  );
}
await player.open(Media('XYZ'));
```

**Comment by alexmercerind** [comment]
EDIT: Fixed a typo.

**Comment by BrunoC96** [comment]
Ok, thanks for your response,

but just for clarity, I need to add only the `License Key` from the `Widevine License`or add the `URI` for getting the `Widevine License`, with relative headers, etc.

**Comment by alexmercerind** [comment]
You must fetch it then ...

**Comment by BrunoC96** [comment]
I use the `setProperty ` API, and it doesn't work. 
Are you sure about this property that they are configuring the encryption key from the CDM Module to the OEMCryptoModule?
