### ISSUE TITLE
[Question] Continuous memory usage increase with livestreams

### ISSUE THREAD

**Issue by xietian0908** [media-kit/media-kit#387]
![image](https://github.com/media-kit/media-kit/assets/64937500/639d08fc-1088-4947-91b7-e6f37668be69)
Is it normal for the memory to increase from around 1000 to around 3000 within 2 days while playing 3 RTPS standard definition streams?

**Comment by alexmercerind** [comment]
I can't really say anything, there can be a number of things.

**Comment by xietian0908** [comment]
> 我真的不能说什么，可能有很多事情。

Thank you for your response. Currently, I am planning to implement a certain interval, such as reloading the video after 6 hours. I would like to ask if there is a better way to address the continuous memory consumption of the player.

**Comment by alexmercerind** [comment]
I haven't really played a video for a prolonged duration such as 2 days... If you're able to find the cause or make any improvements z certainly let us know.

Thanks!
