### ISSUE TITLE
Old archieves have been removed.

### ISSUE THREAD

**Issue by 50ways2sayhard** [media-kit/media-kit#389]
I'm using media_kit 1.0.2 and media_kit_libs_windows_video 1.0.2 and throws this exception while building:

![img_v2_085f724c-fc34-4212-84d1-9f92ed461c9g](https://github.com/media-kit/media-kit/assets/16864600/9a5f39b0-ca4d-4f50-af74-13d00ea4b825)

After having a deep look at the exception, I found the old archieves was removed.
![img_v2_63257b88-e722-4e0f-baa7-c0d97a11e8bg](https://github.com/media-kit/media-kit/assets/16864600/1c86007a-5872-4306-8dd7-07cce29fa77e)
![img_v2_e35afb0b-0e12-4980-8bf9-56f7c598c3ag](https://github.com/media-kit/media-kit/assets/16864600/6ad74be6-64dc-49bb-8aa0-7fe00532348f)

Can you keep old archieves to make old version works well?

**Comment by alexmercerind** [comment]
Apologies for the inconveniences.

The newer versions have lesser bundle size & further improvements.

The latest version should've been picked by default. Regardless, please consider bumping your version.

Thanks!

**Comment by 50ways2sayhard** [comment]
Thank you! I've upgraded to the latest version and build success. 

Although this problem can be solved by upgrading, but it's not easy to do that, especially for team work with CICD machine. Please consider keep the old archieves.
