### ISSUE TITLE
[Question] How to use `waitUntilFirstFrameRendered`?

### ISSUE THREAD

**Issue by sofm13** [media-kit/media-kit#390]
I don't know how to use `waitUntilFirstFrameRendered`.

**Comment by alexmercerind** [comment]
How do you intend to use it? It's an API which is used to wait until first frame is rendered i.e. ready to be displayed.

It's a `Future` that gets resolved when first frame is rendered.

This example can be helpful:

https://github.com/media-kit/media-kit/blob/main/media_kit_test/lib/tests/06.paint_first_frame.dart

Download the demo from our README for further insights.
