### ISSUE TITLE
[Bug Report][Android] Hardware Acceleration breaks playing videos on old devices

### ISSUE THREAD

**Issue by clragon** [media-kit/media-kit#391]
I have a user who cannot play videos.

When I configure the Player to not use hardware acceleration, the videos work for them.
They have told me that usually hardware acceleration works on their device.

Their device information is as follows:
- Honor 9
- Android 8

I have asked them to provide me with a log from ADB:

[logcat_08-09-2023_18-00-28.txt](https://github.com/media-kit/media-kit/files/12399124/logcat_08-09-2023_18-00-28.txt)

I dont know if the hardware acceleration code in the library is not working for their device or if it would need to be dynamically disabled. 
Though I am unsure what criteria I would be using to disable it.

**Comment by alexmercerind** [comment]
The logs from `Player.stream.log` /w `PlayerConfiguration(..., logLevel: MPVLogLevel.debug)` will be more helpful.

As far as I have seen it, the software rendering fallback works correctly on my device. Still... there may be some situation.

**Comment by clragon** [comment]
I have built a special test apk and asked my user to provide me with the logs.

[video.log](https://github.com/media-kit/media-kit/files/12402666/video.log)
[video2.log](https://github.com/media-kit/media-kit/files/12402667/video2.log)

**Comment by alexmercerind** [comment]
A new version has been published, [please refer to the "Installation" section in the README](https://github.com/media-kit/media-kit#installation).

Please do notify in-case it still doesn't work.

Thanks!

**Comment by alexmercerind** [comment]
cc: @deckerst

Please consider updating the packages. Apparently S/W fallback on Android wasn't working in some cases. Apart from this, there have been some improvements to H/W initialization on Android:

- #408 

Also, AV1 H/W has been re-enabled for the capable devices. I haven't seen any Android with AV1 H/W decoder yet.

**Comment by alexmercerind** [comment]
From quick Google search, [I see that Honor 9 has Mali-G71 MP8, which doesn't support VP9 hardware decoding](https://www.cpu-monkey.com/en/igpu-arm_mali_g71_mp8).

Rest assured, best possible decoding method will be used & now software decoding fallback works in all cases.
