### ISSUE TITLE
[Feature Request] Export types used in public interfaces

### ISSUE THREAD

**Issue by clragon** [media-kit/media-kit#392]
The library has some types which are returned from public interfaces, e.g. `PlayerLog`.
However, these classes are not exported.

This leads to a problem when I wish to actually use those interfaces. For example, I cant type a `Stream<PlayerLog>` because `PlayerLog` is not public. I also cannot deconstruct the object via patterns because that requires me to specify the type. 

If the intent is to prevent these classes from being extended or implemented, dart class modifiers exist in the latest version.
If the intent is to not pollute the namespace, classes which are usually not needed can be exported in a specific import. 
Otherwise I am unsure why they would not be public.

**Comment by alexmercerind** [comment]
Sure. I didn't really expect people to reference internal types, but now that I'm seeing it, the requirement seems genuine.

**Comment by alexmercerind** [comment]
A new version has been published, [please refer to the "Installation" section in the README](https://github.com/media-kit/media-kit#installation).
