### ISSUE TITLE
[Bug Report] Subtitles not showing m3u8

### ISSUE THREAD

**Issue by kuki-kuk** [media-kit/media-kit#394]
I have a problem to show subtitles when  streaming video using m3u8 link. 
Example:
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:13
#EXT-X-MEDIA-SEQUENCE:808
#EXTINF:12.012000,
25011126_808.ts
#EXTINF:12.012000,
25011126_809.ts
#EXTINF:10.643967,
25011126_810.ts
#EXTINF:13.380033,
25011126_811.ts
#EXTINF:12.012000,
25011126_812.ts

tested on Windows and Android.

Thanks,

**Comment by femalemonkeyman** [comment]
Probably need a few more details but looks like the subtitles are external?

**Comment by alexmercerind** [comment]
Yeah, I don't think this information is sufficient, you can load external subtitles (how it's mostly done on the web):

https://github.com/media-kit/media-kit#load-external-subtitle-track

**Comment by lKinderBueno** [comment]
I have the same issue using embedded subtitles.
This is the video with embedded subtitles: [https://supertest.netsons.org/video_sub.mp4](https://supertest.netsons.org/video_sub.mp4)
This is the srt file embedded in the video [https://supertest.netsons.org/sub.srt](https://supertest.netsons.org/sub.srt)

If I try to set the subtitle from the url, they works. 
`player.setSubtitleTrack(SubtitleTrack.uri('https://supertest.netsons.org/sub.srt'));`

Instead, if I try to load the embedded subtitle, the player doesn't show any text:
`player.setSubtitleTrack(player.state.tracks.subtitle[2]);`

**Comment by lKinderBueno** [comment]
> @lKinderBueno
> 
> One more question, what platform are you on?

I tested it on Android 12 and Windows

**Comment by alexmercerind** [comment]
I've set things to cross-compile for Windows, Android & macOS. I will publish an update in few hours or tomorrow.

**Comment by alexmercerind** [comment]
FYI: This is due to a missing subtitle decoder _i.e._ issue shall not be present on GNU/Linux.

**Comment by alexmercerind** [comment]
A new version has been published, [please refer to the "Installation" section in the README](https://github.com/media-kit/media-kit#installation).

**Comment by lKinderBueno** [comment]
There are two small issues:

- By default it loads the embedded subtitle
- Once the subtitles are enabled, they can't be disabled with ```dart player.setSubtitleTrack(SubtitleTrack.no())```

```dart 
import 'package:flutter/material.dart';

import 'package:media_kit/media_kit.dart'; // Provides [Player], [Media], [Playlist] etc.
import 'package:media_kit_video/media_kit_video.dart'; // Provides [VideoController] & [Video] etc.

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  // Necessary initialization for package:media_kit.
  MediaKit.ensureInitialized();
  runApp(
    const MaterialApp(
      home: MyScreen(),
    ),
  );
}

class MyScreen extends StatefulWidget {
  const MyScreen({Key? key}) : super(key: key);
  @override
  State<MyScreen> createState() => MyScreenState();
}

class MyScreenState extends State<MyScreen> {
  // Create a [Player] to control playback.
  late final player = Player();
  // Create a [VideoController] to handle video output from [Player].
  late final controller = VideoController(player);

  @override
  void initState() {
    super.initState();
    // Play a [Media] or [Playlist].
    player.open(Media('https://supertest.netsons.org/video_sub.mp4'), play: true);
    //workaround to disable the automatic subtitle loading
    player.setSubtitleTrack(SubtitleTrack.no());
    
  }

  @override
  void dispose() {
    player.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Center(
      child: SizedBox(
        width: MediaQuery.of(context).size.width,
        height: MediaQuery.of(context).size.width * 9.0 / 16.0,
        // Use [Video] widget to display video output.
        child: Video(controller: controller),
      ),
    ),
    floatingActionButton: FloatingActionButton(
          onPressed: () {
            if(player.state.track.subtitle.id == "no")
              player.setSubtitleTrack(player.state.tracks.subtitle[2]);
            else player.setSubtitleTrack(SubtitleTrack.no());
          },
          child: Icon(
            Icons.subtitles,
          ),
        ),
    );
  }
}```

**Comment by alexmercerind** [comment]
I think I received some reply here, regardless it should work.

**Comment by lKinderBueno** [comment]
> I think I received some reply here, regardless it should work.

Yes it is working. There seems to be two minor issues:
- it loads automatically the subtitle when the player starts. I don't know if this is intentional
- if the subtitles are enabled and then they get disabled, if there is the subtitle text on screen it is stuck on the screen and is not removed

```dart
import 'package:flutter/material.dart';

import 'package:media_kit/media_kit.dart'; // Provides [Player], [Media], [Playlist] etc.
import 'package:media_kit_video/media_kit_video.dart'; // Provides [VideoController] & [Video] etc.

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  // Necessary initialization for package:media_kit.
  MediaKit.ensureInitialized();
  runApp(
    const MaterialApp(
      home: MyScreen(),
    ),
  );
}

class MyScreen extends StatefulWidget {
  const MyScreen({Key? key}) : super(key: key);
  @override
  State<MyScreen> createState() => MyScreenState();
}

class MyScreenState extends State<MyScreen> {
  // Create a [Player] to control playback.
  late final player = Player();
  // Create a [VideoController] to handle video output from [Player].
  late final controller = VideoController(player);

  @override
  void initState() {
    super.initState();
    // Play a [Media] or [Playlist].
    player.open(Media('https://supertest.netsons.org/video_sub.mp4'), play: true);
    //workaround to disable the automatic subtitle loading
    player.setSubtitleTrack(SubtitleTrack.no());
    
  }

  @override
  void dispose() {
    player.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Center(
      child: SizedBox(
        width: MediaQuery.of(context).size.width,
        height: MediaQuery.of(context).size.width * 9.0 / 16.0,
        // Use [Video] widget to display video output.
        child: Video(controller: controller),
      ),
    ),
    floatingActionButton: FloatingActionButton(
          onPressed: () {
            if(player.state.track.subtitle.id == "no")
              player.setSubtitleTrack(player.state.tracks.subtitle[2]);
            else player.setSubtitleTrack(SubtitleTrack.no());
          },
          child: Icon(
            Icons.subtitles,
          ),
        ),
    );
  }
}
```

**Comment by alexmercerind** [comment]
1. The first behavior is intentional, the default subtitle will be selected.
2. The second behavior is indeed a bug. It even occurs when you switch the `Playable` by calling `open` again.
  If previous subtitle was visible, it would be stuck. Your workaround is good, I'll resolve it once I find time.

**Comment by alexmercerind** [comment]
Regardless, movtext subtitles are now working correctly.

**Comment by alexmercerind** [comment]
@lKinderBueno latest update further resolves all your concerns.

Thanks!
