### ISSUE TITLE
Seek bug [MacOs]

### ISSUE THREAD

**Issue by ANC1024GO** [media-kit/media-kit#398]
when i “Seek” playing video then to the certine duration, for example seek from 5 minut to 1 hour position, the player loading all ts files beetwin 5 minut to 1 hour position, and not loading ts files from the 1 hour positon, that is totally unnessecory, how do i prevent that, Thank you. (Sorry for my bad English)

**Comment by alexmercerind** [comment]
Provide a sample as asked in #396.
