### ISSUE TITLE
[Bug Report] first few seconds of live FLV do not render correctly

### ISSUE THREAD

**Issue by sofm13** [media-kit/media-kit#399]
When the live source(.flv) is loaded for the first time,the video picture is distortion.
in v1.1.2 don't have this condition,update v1.1.5 happen.
https://github.com/media-kit/media-kit/assets/52565295/c7c4e04c-834b-45c7-ba6d-7901df90563f
```dart
import 'package:flutter/material.dart';
import 'package:media_kit/media_kit.dart';
import 'package:media_kit_video/media_kit_video.dart';

class testVideoPage extends StatefulWidget {
  const testVideoPage({super.key});

  @override
  State<testVideoPage> createState() => _testVideoPageState();
}

class _testVideoPageState extends State<testVideoPage> {
  late final Player player = Player();
  late final VideoController controller = VideoController(player);

  @override
  void initState() {
    super.initState();
  }

  @override
  void dispose() {
    player.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: Scaffold(
      body: Center(
        child: AspectRatio(
          aspectRatio: 16 / 9,
          child: Video(
            controller: controller,
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          // player.open(Media(
          //     "http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8"));
          player.open(Media("http://hvk.zghbsb.top/live/cx_370267.flv"));
          player.play();
        },
        tooltip: 'Increment',
        child: const Icon(Icons.start),
      ),
    ));
  }
}
```

**Comment by alexmercerind** [comment]
I can't access the URL.

**Comment by sofm13** [comment]
sorry, this is http-flv address,I uploaded the video. and after my try, I think only play http-flv video has this problem,i think maybe about waitUntilFirstFrameRendered api.

**Comment by alexmercerind** [comment]
You can try some existing media player applications e.g. VLC or mpv & see how they behave.

**Comment by sofm13** [comment]
but before I use the previous version don't have this problem,Update the latest version have this problem.
previous version:
  media_kit: ^1.1.2       
  media_kit_video: ^1.1.2                       
  media_kit_native_event_loop: ^1.0.7            
  media_kit_libs_android_video: ^1.3.0  
  media_kit_libs_ios_video: ^1.1.1

**Comment by alexmercerind** [comment]
It is (likely) because I incorrectly rendered first frame on Android:

- #339 

Now it is "correct".

**Comment by alexmercerind** [comment]
You can restore old behavior by passing `vo: 'gpu'` & `'hwdec: 'auto'` in `VideoControllerConfiguration` (see README).

https://github.com/media-kit/media-kit#display-the-video

NOTE: I haven't tested, but it should work like before, on my end I cannot make any changes since this is the default preferred behavior & most users actually seem satisfied with the change.

**Comment by sofm13** [comment]
think you,This works fine

**Comment by alexmercerind** [comment]
@sofm13 make sure to do it only for Android! On other platforms, `vo` & `hwdec` are best kept `null`.

I've added "re-evaluate-in-future" tag to see if we find any time or further requests in future.
