### ISSUE TITLE
costume control bar hotkeys not working

### ISSUE THREAD

**Issue by ANC1024GO** [media-kit/media-kit#401]
after i costume player control bar, cannot using hotkeys to control playing video, like pressing left arrow to backward video dose not working anymore.

Video(
    controller: controller,
    controls: (state) {
         return SizedBox.shrink();
    },
 );

**Comment by alexmercerind** [comment]
The shortcut keys are part of `MaterialDesktopVideoControls`. If you decide to create your own control & disable default ones, you must also create other things on your own too, including shortcuts.

Don't worry it's barely 5 lines of code, you can read our implementation.
