### ISSUE TITLE
native_library.dart not found debug build failed in android and ios but working fine in web 

### ISSUE THREAD

**Issue by 25thammar** [media-kit/media-kit#415]
### by the way very cool package I am very thankful for the sponsers and you who made this such a wonderful package! 

added in pub spec yaml 
  media_kit: ^1.1.5
  media_kit_video: ^1.0.2
  media_kit_libs_video: ^1.0.1

../../../../.pub-cache/hosted/pub.dev/media_kit_video-1.0.2/lib/src/video_controller/native_video_controller/real.dart:17:8: Error: Error when reading '../../../../.pub-cache/hosted/pub.dev/media_kit-1.1.5/lib/src/player/libmpv/core/native_library.dart': No such file or directory
import 'package:media_kit/src/player/libmpv/core/native_library.dart';
       ^
../../../../.pub-cache/hosted/pub.dev/media_kit_video-1.0.2/lib/src/video_controller/android_video_controller/real.dart:23:8: Error: Error when reading '../../../../

 flutter doctor -v
[!] Flutter (Channel stable, 3.7.1, on macOS 13.2 22D49 darwin-arm64, locale en-PK)
    • Flutter version 3.7.1 on channel stable at /Users/macbook/Desktop/development/flutter
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.19.2/libexec/bin/dart, which is not inside your current Flutter SDK checkout at
      /Users/macbook/Desktop/development/flutter. Consider adding /Users/macbook/Desktop/development/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7048ed95a5 (7 months ago), 2023-02-01 09:07:31 -0800
    • Engine revision 800594f1f4
    • Dart version 2.19.1
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/macbook/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_361-b09)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.

**Comment by alexmercerind** [comment]
Hi @25thammar,

All the package(s) are interlinked, you have to update all packages, not just one:

```yaml
dependencies:
  media_kit: ^1.1.7                              # Primary package.
  media_kit_video: ^1.1.8                        # For video rendering.
  media_kit_libs_video: ^1.0.1                   # Native video dependencies.
```

I hope this will resolve your issue. Our [builds from CI are also succeeding](https://github.com/media-kit/media-kit/actions/runs/5987493098/job/16241691353).

**Comment by alexmercerind** [comment]
Do close the issue if it's solved.

**Comment by alexmercerind** [comment]
Lastly, you can just try dependency_overrides if you have conflicts. But, that's it.

**Comment by 25thammar** [comment]
Hi @alexmercerind
Thank you for your quick response I have updated the packages to the latest in pub.yaml 
The problem was latest packages were not installed and I had an older version of Flutter 3.7 and Dart < 3.0.1 
I used FVM and was able to build on Android
