### ISSUE TITLE
[Question][Windows] Build Failed

### ISSUE THREAD

**Issue by stefan321** [media-kit/media-kit#416]
This problem has troubled me for a long time, there is no way I can only find the source code.

I checked the resource file and client.h should be in the mpv directory

windows\flutter\ephemeral\.plugin_symlinks\media_kit_native_event_loop\src\media_kit_native_event_loop.h
#if defined(_WIN32)
#include <client.h> # I don't know. Why is it written like that
#elif defined(ANDROID) || defined(__ANDROID__)
#include "include/client.h"
#elif defined(__linux__)
#include <mpv/client.h>
#elif defined(__APPLE__)
#include <mpv/client.h>
#endif

**Comment by alexmercerind** [comment]
The best I can guide is to do a "flutter clean".

You can see our latest CI build, where Windows compiles successfully:

https://github.com/media-kit/media-kit/actions/runs/5987141398/job/16241023640

Blatantly saying something is not working doesn't seem like the best idea to me. Furthermore, you can download the demo application from the README for testing purposes.

Thanks!

**Comment by alexmercerind** [comment]
> I checked the resource file and client.h should be in the mpv directory.

The build process will download the required headers & shared libraries etc.

**Comment by guchengxi1994** [comment]
@stefan321 
![image](https://github.com/media-kit/media-kit/assets/33513462/6cbccbad-9dbf-4c84-b3b5-732e78de1321)
add these 2 dependencies to your pubspec.yaml should work
