### ISSUE TITLE
Capture screenshot without playing video

### ISSUE THREAD

**Issue by Airyzz** [media-kit/media-kit#419]
Hi, I noticed that this package has screenshot function, I was wondering if there is any possibility to capture a screenshot from a video without necessarily playing the video? 

The use case is to generate a thumbnail image for a given video file. In my project I cannot generate thumbnails on back end because we use end to end encryption, so need to do it client side.

Thanks!

**Comment by alexmercerind** [comment]
As far as I understand, only attaching `VideoController` to `Player` will allow you to capture screenshots.

**Comment by alexmercerind** [comment]
Regardless, I only target video & audio playback at the moment.
