### ISSUE TITLE
Path Error When Using 'Add to iOS App' (Flutter Module)

### ISSUE THREAD

**Issue by weitsai** [media-kit/media-kit#421]
Similar issue to GitHub issue #159

Here is the minimal reproducible project for the error: 
- [Flutter Module](https://github.com/weitsai/flutter_module_use_media_kit/tree/main/flutter_module)
- [iOS Project](https://github.com/weitsai/flutter_module_use_media_kit/tree/main/ios_fullscreen)

The error message for running the iOS project is as follows:
```log
Analyzing dependencies
make: Nothing to be done for `all'.
media_kit: ERROR: No pubspec.lock was found: ENV["PWD"] = "/Users/weitsai/Downloads/samples-main/add_to_app/fullscreen/ios_fullscreen"
[!] Failed to load 'media_kit_video' podspec: 
[!] Invalid `media_kit_video.podspec` file: media_kit: ERROR: No pubspec.lock was found: ENV["PWD"] = "/Users/weitsai/Downloads/samples-main/add_to_app/fullscreen/ios_fullscreen".

 #  from /Users/weitsai/Downloads/samples-main/add_to_app/fullscreen/flutter_module/.ios/.symlinks/plugins/media_kit_video/ios/media_kit_video.podspec:13
 #  -------------------------------------------
 #    # Initialize `MediaKitUtils`
 >    mku = MediaKitUtils.new(MediaKitUtils::Platform::IOS)
 #  
 #  -------------------------------------------
```

**Comment by alexmercerind** [comment]
The linked issue was different.

**Comment by weitsai** [comment]
Yes, he is currently actively exploring Flutter architecture.

I'm considering how to make it possible for him to support the Flutter Module structure.

**Comment by weitsai** [comment]
> I don't think this is supported at the moment (at least on iOS) because the build script looks for the Flutter project's structure.

Yes, he is currently actively exploring Flutter architecture.

I'm considering how to make it possible for him to support the Flutter Module structure.

**Comment by birros** [comment]
@weitsai If `media_kit_video.podspec` has trouble finding the `pubspec.lock` in your project, you can manually set the path to the folder containing it using the `PWD_FALLBACK` environment variable:

https://github.com/media-kit/media-kit/blob/592420ee7bd4e35f1083e410d3719563896abcfd/media_kit_video/common/darwin/Podspec/media_kit_utils.rb#L21-L31

`pubspec.lock` is used to determine which `media_kit_libs_**` are used.

**Comment by alexmercerind** [comment]
Should we close it then?

I don't think we can do anything about project specific structures. I didn't work on macOS or iOS implementation.

**Comment by weitsai** [comment]
> Should we close it then?
> 
> I don't think we can do anything about project specific structures. I didn't work on macOS or iOS implementation.

I believe this is an area that can be improved, which would benefit iOS and Mac developers effectively. 
Since we've just started experimenting, if we succeed, we will submit a pull request.

**Comment by alexmercerind** [comment]
> If we succeed, we will submit a pull request.

Sure.

**Comment by nikunjramiweave** [comment]
Is there any update regarding supporting Flutter as a module?

**Comment by vhly** [comment]
> [@weitsai](https://github.com/weitsai) If `media_kit_video.podspec` has trouble finding the `pubspec.lock` in your project, you can manually set the path to the folder containing it using the `PWD_FALLBACK` environment variable:
> 
> [media-kit/media_kit_video/common/darwin/Podspec/media_kit_utils.rb](https://github.com/media-kit/media-kit/blob/592420ee7bd4e35f1083e410d3719563896abcfd/media_kit_video/common/darwin/Podspec/media_kit_utils.rb#L21-L31)
> 
> Lines 21 to 31 in [592420e](/media-kit/media-kit/commit/592420ee7bd4e35f1083e410d3719563896abcfd)
> 
>  # Find the nearest path to `pubspec.lock` using `PWD` env var set by 
>  # `cocoapods` 
>  current_dir       = ENV['PWD'] || '/' 
>  pubspec_lock_path = MediaKitUtils::find_nearest_pubspec_lock(current_dir) 
>   
>  # If not found try again using `PWD_FALLBACK` env var manually set, 
>  # `PWD_FALLBACK` must point to app folder or any child folder 
>  if pubspec_lock_path == '' 
>    current_dir       = ENV['PWD_FALLBACK'] || '/' 
>    pubspec_lock_path = MediaKitUtils::find_nearest_pubspec_lock(current_dir) 
>  end 
> `pubspec.lock` is used to determine which `media_kit_libs_**` are used.

The PWD_FALLBACK env use set absolute path for Flutter module, do not use relative path
