### ISSUE TITLE
[Question] Set Proxy for the Video Content

### ISSUE THREAD

**Issue by BrunoC96** [media-kit/media-kit#423]
Hi,

I'm using `media_kit`, and I was trying to reproduce to a geocoding content, and for doing that I need to set up a proxy in my app at the top level, but because I need to set it as dynamically as possible to access the content, I want to know if it is possible to set up the internal HTTP request with a proxy.

There are some settings, or some configuration, that I can add for doing that?

**Comment by BrunoC96** [comment]
Thanks for response,

if I have `authentication` for the `proxy`, so I need to add `username` and `password`, how can I add these fields?

**Comment by birros** [comment]
> if I have authentication for the proxy, so I need to add username and password, how can I add these fields?

I don't know if mpv supports [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), but it is common to set credentials in the url:
```
http://username:password@example.com/
```

**Comment by BrunoC96** [comment]
Hi,
I try to use this format `http://username:password@example.com/` and it's working just fine, the only problem that I encounter is that the stream is blocking intermittently.

Seems like that the player doesn't cache new ts frame and only when consume the last frame download another one.
I think it's because the  `'http-proxy'` parameter only set the proxy for the first time that it tries to download the frame, but the parameter isn't pass for the consecutive request, and it's put back when finish to consume the last frame.

**Comment by birros** [comment]
> Seems like that the player doesn't cache new ts frame and only when consume the last frame download another one.
I think it's because the `'http-proxy'` parameter only set the proxy for the first time that it tries to download the frame, but the parameter isn't pass for the consecutive request, and it's put back when finish to consume the last frame.

I presume you are using **HLS**. Perhaps you need to adjust one or more of the cache settings.
Otherwise, there may be a problem on the mpv side when `http-proxy` and **HLS** are used together. In this case, I invite you to visit the [mpv tracker](https://github.com/mpv-player/mpv/issues).

> I also have this in the log:
> flutter: media_kit: wakelock: _count = 0

Don't worry, it's a debug message that will probably disappear in future versions now that wakelock is stable.

**Comment by BrunoC96** [comment]
Thanks for response,
yes, I'm using HLS stream with proxy.

So there are some setting that need to be adjusted if I add `http-proxy` setting with HLS streams.
I try to find which setting need to be used, and I post it here, so who have the same problem could refer to this.

**Comment by BrunoC96** [comment]
I try different settings, but anything's seems to be working.
So I install from scratch the last version of `mpv` on macOS (I test media-kit also on macOS, and also in other platforms), these are the version of `mpv`:
mpv 0.36.0-UNKNOWN Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Aug 31 2023 12:04:30
[cplayer] FFmpeg version: 6.0
[cplayer] FFmpeg library versions:
[cplayer]    libavutil       58.2.100
[cplayer]    libavcodec      60.3.100
[cplayer]    libavformat     60.3.100
[cplayer]    libswscale      7.1.100
[cplayer]    libavfilter     9.3.100
[cplayer]    libswresample   4.10.100

I add only the steam resource and the `http-proxy` as in the `setParameter` of `media-kit` and work just fine, so the problem is not `mpv` itself, but i t could be how media-kit handle this, or maybe the mpv version of media-kit is not the latest.

Any idea how to solve?

**Comment by BrunoC96** [comment]
Hi,
I have more insight and some more questions.
The player reproduce only the first frame in the playlist, no matter what.
I try to reset the config of the `mpv` player and add manually the parameter for the cache.

dynamic platform = player.platform as dynamic;
await platform.setProperty('no-config', '');
await platform.setProperty('http-proxy', 'http://username:password@example.com/');
await platform.setProperty('cache', 'yes');
await platform.setProperty('demuxer-readahead-secs', '30');
await platform.setProperty('cache-secs', '30');
await platform.setProperty('cache-pause-initial', 'yes');

but the player still loads the first 4-second frame.

There is a way to properly see the debug log of the player, and also have to see the config of this after I reset it?
(I try with `setParameter` but seems not be working)

Which version of `mpv` is based `media-kit`?

Which code of media-kit is responsible to the cache of the player?

**Comment by birros** [comment]
> There is a way to properly see the debug log of the player

```dart
final Player player = Player();
player.stream.error.listen((error) => debugPrint(error));

// or

final Player player = Player(
  configuration: const PlayerConfiguration(
    logLevel: MPVLogLevel.info,
  ),
);
player.stream.log.listen((log) => debugPrint(log.toString()));
```

> and also have to see the config of this after I reset it?

```dart
final platform = player.platform as NativePlayer;
platform.setProperty('property', 'value');
platform.observeProperty('property', (value) async => debugPrint(value));
```

> Which version of `mpv` is based `media-kit`?

https://github.com/media-kit/libmpv-darwin-build/blob/488bf6965d45320e28bedf82e1e34947b4492052/downloads.lock#L29-L30

> Which code of media-kit is responsible to the cache of the player?

`mpv` itself.

**Comment by BrunoC96** [comment]
From the log file, I see this:
`PlayerLog(prefix: lavf, level: error, text: avformat_open_input() failed)`

But I think this doesn't matter too much, because I have the same log message, in the `zsh` when I lunch `mpv` directly, and there, it's working just fine.

The other problem I see is this:
`PlayerLog(prefix: ffmpeg, level: error, text: Seek failed (to 2693140, size 2943140))`

It's showing for each frame I reproduce.
But I don't understand the error where is coming from.

Also in Android I have the same problems above, and I see also this other log:
`D/HostConnection(13272): createUnique: call`
`D/HostConnection(13272): HostConnection::get() New Host Connection established 0xb40000790ca5cbd0, tid 13580`

So my question is, Can I see also the `ffmpeg` log for more clue? If so, how?
And do you have any clue where is coming from the Seek failed error log?

**Comment by birros** [comment]
> Can I see also the `ffmpeg` log for more clue?

You already have access to the `ffmpeg` logs:
> `PlayerLog(prefix: ffmpeg, level: error, text: Seek failed (to 2693140, size 2943140))`

`prefix: ffmpeg` means that it comes from `ffmpeg`, but `mpv` manages these logs, so only those sent by `mpv` are available.

You can try adjusting `MPVLogLevel` to get more logs.

---

> And do you have any clue where is coming from the Seek failed error log?

No clue, sorry :(

**Comment by BrunoC96** [comment]
Digging more deeply, I found this.

In my flutter app, I have:

`flutter: PlayerLog(prefix: lavf, level: v, text: Found 'hls' at score=100 size=2048.)`
`flutter: PlayerLog(prefix: lavf, level: error, text: avformat_open_input() failed)`

Otherwise, in my `mpv` console, I see this:

`[lavf] Found 'hls' at score=100 size=2048.`
`[ffmpeg/demuxer] hls: Skip ('#EXT-X-VERSION:3')`
`[ffmpeg/demuxer] hls: Skip ('#EXT-X-ALLOW-CACHE:NO')`

Probably the `avformat_open_input()` fail and doesn't skip the HLS `EXT-X-ALLOW-CACHE:NO`
and so the flutter app doesn't cache other frames.

Also, I was trying to have clean settings for the app with the `setProperty` to `no-config` like this:
`await platform.setProperty('no-config', '');`

But I get this:
```
[ERROR:flutter/shell/common/shell.cc(1004)] The 'com.alexmercerind/media_kit_video' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.
See https://docs.flutter.dev/platform-integration/platform-channels#channels-and-platform-threading for more information.
```

Any clue how to solve `avformat_open_input()` failing and how to set `no-config` for the app??

**Comment by BrunoC96** [comment]
I solve the issue by adding this:
`await platform.setProperty('demuxer-lavf-o', 'allowed_extensions=[ts,key]');`

The problem was that `AVOPTION allowed_extensions=ALL` failed to be set at the start of the player, and the file is not to be read as `hls` but as the other format `M..TS` (I don't remember), and can't read it successfully, and give `avformat_open_input() failed`.

So, setting up by yourself the option `[ts, key]` on `demuxer-lavf-o allowed_extensions` overwrite the option set ALL that fail, and it just works.

The problem seems to be showing only when `http-proxy` is set.

**Comment by alexmercerind** [comment]
The FFmpeg & mpv API is huge. Most importantly, it is not part of this project.

If you wish to consume it, you are liable & responsible for any unexpected behavior. It's like forking this project & writing your own code & blaming us. We can't provide support for it.

It's a freedom that you can consume internal APIs very easily thanks to project's architecture & design.

If you want to see it implemented as a feature, PRs welcomed. We don't have time or interest, we are not a company.

Thanks!

**Comment by cer-cer** [comment]
> I solve the issue by adding this: `await platform.setProperty('demuxer-lavf-o', 'allowed_extensions=[ts,key]');`
> 
> The problem was that `AVOPTION allowed_extensions=ALL` failed to be set at the start of the player, and the file is not to be read as `hls` but as the other format `M..TS` (I don't remember), and can't read it successfully, and give `avformat_open_input() failed`.
> 
> So, setting up by yourself the option `[ts, key]` on `demuxer-lavf-o allowed_extensions` overwrite the option set ALL that fail, and it just works.
> 
> The problem seems to be showing only when `http-proxy` is set.

Solved my problem, thanks.
