### ISSUE TITLE
Support for selecting audio and video tracks in media_kit

### ISSUE THREAD

**Issue by usman615** [media-kit/media-kit#424]
@zezo357 
brother I'm getting these problems in media_kit customization in the following code.

1. I want to set 'desktopVideoControlsThemeData' for both mobile or desktop instead of 'AdaptiveVideoControls'.
2. when I exit fullscreen then goback the screen is back to home screen instead of previous screen.
3. when the video starts it is too laggy.
4. when video starts the colors of video destroy for 2 sec. (screenshots below).
5. how can I customize Ui for Live Streams like hide progress bar and put live Svg instead of durations (10:22/01:13:23)

**Code**

```
class VideoPlayer extends StatefulWidget {
  final String videoUrl;
  final dynamic isLiveStream;
  const VideoPlayer({
    Key? key,
    required this.videoUrl,
    required this.isLiveStream,
  }) : super(key: key);

  @override
  _VideoPlayerState createState() => _VideoPlayerState();
}

class _VideoPlayerState extends State<VideoPlayer> {
  
  late final player = Player();
  late final controller = VideoController(player);

  @override
  void initState() {
    super.initState();
    player.open(Media(widget.videoUrl));
  }

  @override
  void dispose() {
    player.dispose();
    super.dispose();
  }

   @override
  Widget build(BuildContext context) {
    MaterialDesktopVideoControlsThemeData desktopVideoControlsThemeData =
        desktopControls();
    return SafeArea(
      child: AspectRatio(
        aspectRatio: 16 / 9,
        child: MaterialDesktopVideoControlsTheme(
          normal: desktopVideoControlsThemeData,
          fullscreen: desktopVideoControlsThemeData,
          child:Video(
              controller: controller,
            ),
        ),
      ),
    );
  }

  MaterialDesktopVideoControlsThemeData desktopControls() {
    return MaterialDesktopVideoControlsThemeData(
     bottomButtonBar: [
      MaterialDesktopSkipPreviousButton(),
      MaterialDesktopPlayOrPauseButton(),
      MaterialDesktopSkipNextButton(),
      MaterialDesktopVolumeButton(),
      MaterialDesktopPositionIndicator(),
      Spacer(),
      MaterialDesktopFullscreenButton(),
    ]);
  }
}
```

![WhatsApp Image 2023-08-28 at 11 06 57 PM](https://github.com/media-kit/media-kit/assets/69667190/dd1c1043-291a-4e95-8939-b8a5678c4b9f)
![WhatsApp Image 2023-08-28 at 11 05 51 PM](https://github.com/media-kit/media-kit/assets/69667190/fc697d65-da0a-40b9-9384-f8b191f8f75f)

**Comment by zezo357** [comment]
1. add  `controls: MaterialDesktopVideoControls`

```
Video(
              controller: controller,
              controls: MaterialDesktopVideoControls,
            ),
```

2. i dont get the problem 

3 & 4, please provide the url so test it and figure out the problem 

5 you can do it like this 
```
    return MaterialDesktopVideoControlsThemeData(bottomButtonBar: [
      if (widget.isLiveStream) ...[],
      if (!widget.isLiveStream) ...[],
      MaterialDesktopSkipPreviousButton(),
      MaterialDesktopPlayOrPauseButton(),
      MaterialDesktopSkipNextButton(),
      MaterialDesktopVolumeButton(),
      MaterialDesktopPositionIndicator(),
      Spacer(),
      MaterialDesktopFullscreenButton(),
    ]);
```

full code
```

class VideoPlayer extends StatefulWidget {
  final String videoUrl;
  final dynamic isLiveStream;
  const VideoPlayer({
    Key? key,
    required this.videoUrl,
    required this.isLiveStream,
  }) : super(key: key);

  @override
  _VideoPlayerState createState() => _VideoPlayerState();
}

class _VideoPlayerState extends State<VideoPlayer> {
  late final player = Player();
  late final controller = VideoController(player);

  @override
  void initState() {
    super.initState();
    player.open(Media(widget.videoUrl));
  }

  @override
  void dispose() {
    player.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    MaterialDesktopVideoControlsThemeData desktopVideoControlsThemeData =
        desktopControls();
    return SafeArea(
      child: AspectRatio(
        aspectRatio: 16 / 9,
        child: MaterialDesktopVideoControlsTheme(
          normal: desktopVideoControlsThemeData,
          fullscreen: desktopVideoControlsThemeData,
          child: Video(
            controller: controller,
            controls: MaterialDesktopVideoControls,
          ),
        ),
      ),
    );
  }

  MaterialDesktopVideoControlsThemeData desktopControls() {
    return MaterialDesktopVideoControlsThemeData(bottomButtonBar: [
      if (widget.isLiveStream) ...[],
      if (!widget.isLiveStream) ...[],
      MaterialDesktopSkipPreviousButton(),
      MaterialDesktopPlayOrPauseButton(),
      MaterialDesktopSkipNextButton(),
      MaterialDesktopVolumeButton(),
      MaterialDesktopPositionIndicator(),
      Spacer(),
      MaterialDesktopFullscreenButton(),
    ]);
  }
}

```

**Comment by usman615** [comment]
For 3 & 4, 
i think there is no problem with video url because this problem happens on avery video url so mean that there is problem with video player or my device oppo A9 2020 (if the video url will works fine when you test) 

Video url: http://xtv.ooo:8080/live/sYcp4cRDr8Pz/dpw3PLGtVFkR/25990.m3u8

**Comment by zezo357** [comment]
This url doesn't work for me, even tested with MX player on my mobile its just doesn't open

**Comment by usman615** [comment]
Yes problem with video url, thanks for pointing out 😊

**Comment by zezo357** [comment]
If all issues are solved, I guess we should close the issue,

Also for further help I suggest using discord server in the top of the readme to keep GitHub issues for bugs/improvements.

**Comment by usman615** [comment]
@zezo357 
Sorry to comment here again.


**Brother please help me to implement Audio and Video tracks selection**
bro if video format is hls .m3u8 show all available video quality and audio tracks in showQualities modalSheet and for formats .mp4 and .mkv show default quality and all available audio tracks in showAudios void function,  bro i have many VODs in .mp4 or .mkv format which have multiple audio tracks please help to implement this whenever you free to help 💖

### My Code

```
class _VideoPlayerState extends State<VideoPlayer> {
  late final player = Player();
  late final controller = VideoController(player);

  @override
  void initState() {
    super.initState();
    player.open(Media(widget.videoUrl));
  }

  @override
  void dispose() {
    player.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    MaterialDesktopVideoControlsThemeData desktopVideoControlsThemeData =
        desktopControls();
    return SafeArea(
      child: AspectRatio(
        aspectRatio: 16 / 9,
        child: MaterialDesktopVideoControlsTheme(
          normal: desktopVideoControlsThemeData,
          fullscreen: desktopVideoControlsThemeData,
          child: Video(
            controller: controller,
            subtitleViewConfiguration:
                SubtitleViewConfiguration(visible: false),
            controls: MaterialDesktopVideoControls,
          ),
        ),
      ),
    );
  }

  void _showAudios() {
    showModalBottomSheet<void>(
      backgroundColor: Colors.transparent,
      context: context,
      builder: (context) {
        return SafeArea(
          top: false,
          child: SingleChildScrollView(
            physics: const BouncingScrollPhysics(),
            child: Container(
              padding: const EdgeInsets.symmetric(horizontal: 4, vertical: 8),
              decoration: BoxDecoration(
                color: MyColorTheme.surface,
                borderRadius: const BorderRadius.only(
                    topLeft: Radius.circular(24.0),
                    topRight: Radius.circular(24.0)),
              ),
              child: Column(
                children: [
                  Center(child: Text('Audios')),
                ],
              ),
            ),
          ),
        );
      },
    );
  }

  void _showQualities() {
    showModalBottomSheet<void>(
      backgroundColor: Colors.transparent,
      context: context,
      builder: (context) {
        return SafeArea(
          top: false,
          child: SingleChildScrollView(
            physics: const BouncingScrollPhysics(),
            child: Container(
              padding: const EdgeInsets.symmetric(horizontal: 4, vertical: 8),
              decoration: BoxDecoration(
                color: MyColorTheme.surface,
                borderRadius: const BorderRadius.only(
                    topLeft: Radius.circular(24.0),
                    topRight: Radius.circular(24.0)),
              ),
              child: Column(
                children: [
                  Center(child: Text('qualities')),
                ],
              ),
            ),
          ),
        );
      },
    );
  }

  MaterialDesktopVideoControlsThemeData desktopControls() {
    return MaterialDesktopVideoControlsThemeData(
            displaySeekBar: false,
            bottomButtonBarMargin: EdgeInsets.symmetric(horizontal: 5.0),
            buttonBarHeight: 50.0,
            buttonBarButtonSize: 25.0,
            topButtonBar: [
                Spacer(),
                GestureDetector(
                  onTap: _showAudios,
                  child:
                      Icon(Icons.audiotrack_rounded, color: Colors.white),
                ),
                SizedBox(width: 12),
                GestureDetector(
                  onTap: _showQualities,
                  child:
                      Icon(Icons.video_settings_rounded, color: Colors.white),
                ),
              ],
            bottomButtonBar: [
                Padding(
                  padding: const EdgeInsets.fromLTRB(10, 15, 17, 15),
                  child: Image.asset(
                    'assets/images/live.png',
                    filterQuality: FilterQuality.medium,
                  ),
                ),
                MaterialDesktopSkipPreviousButton(),
                MaterialDesktopPlayOrPauseButton(),
                MaterialDesktopSkipNextButton(),
                MaterialDesktopVolumeButton(),
                Spacer(),
                MaterialDesktopFullscreenButton(),
              ]);
  }
}
```

**Comment by zezo357** [comment]
> @zezo357 
> Sorry to comment here again.
> 
> 
> **Brother please help me to implement Audio and Video tracks selection**
> bro if video format is hls .m3u8 show all available video quality and audio tracks in showQualities modalSheet and for formats .mp4 and .mkv show default quality and all available audio tracks in showAudios void function,  bro i have many VODs in .mp4 or .mkv format which have multiple audio tracks please help to implement this whenever you free to help 💖
> 
> ### My Code
> 
> ```
> class _VideoPlayerState extends State<VideoPlayer> {
>   late final player = Player();
>   late final controller = VideoController(player);
> 
>   @override
>   void initState() {
>     super.initState();
>     player.open(Media(widget.videoUrl));
>   }
> 
>   @override
>   void dispose() {
>     player.dispose();
>     super.dispose();
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     MaterialDesktopVideoControlsThemeData desktopVideoControlsThemeData =
>         desktopControls();
>     return SafeArea(
>       child: AspectRatio(
>         aspectRatio: 16 / 9,
>         child: MaterialDesktopVideoControlsTheme(
>           normal: desktopVideoControlsThemeData,
>           fullscreen: desktopVideoControlsThemeData,
>           child: Video(
>             controller: controller,
>             subtitleViewConfiguration:
>                 SubtitleViewConfiguration(visible: false),
>             controls: MaterialDesktopVideoControls,
>           ),
>         ),
>       ),
>     );
>   }
> 
>   void _showAudios() {
>     showModalBottomSheet<void>(
>       backgroundColor: Colors.transparent,
>       context: context,
>       builder: (context) {
>         return SafeArea(
>           top: false,
>           child: SingleChildScrollView(
>             physics: const BouncingScrollPhysics(),
>             child: Container(
>               padding: const EdgeInsets.symmetric(horizontal: 4, vertical: 8),
>               decoration: BoxDecoration(
>                 color: MyColorTheme.surface,
>                 borderRadius: const BorderRadius.only(
>                     topLeft: Radius.circular(24.0),
>                     topRight: Radius.circular(24.0)),
>               ),
>               child: Column(
>                 children: [
>                   Center(child: Text('Audios')),
>                 ],
>               ),
>             ),
>           ),
>         );
>       },
>     );
>   }
> 
>   void _showQualities() {
>     showModalBottomSheet<void>(
>       backgroundColor: Colors.transparent,
>       context: context,
>       builder: (context) {
>         return SafeArea(
>           top: false,
>           child: SingleChildScrollView(
>             physics: const BouncingScrollPhysics(),
>             child: Container(
>               padding: const EdgeInsets.symmetric(horizontal: 4, vertical: 8),
>               decoration: BoxDecoration(
>                 color: MyColorTheme.surface,
>                 borderRadius: const BorderRadius.only(
>                     topLeft: Radius.circular(24.0),
>                     topRight: Radius.circular(24.0)),
>               ),
>               child: Column(
>                 children: [
>                   Center(child: Text('qualities')),
>                 ],
>               ),
>             ),
>           ),
>         );
>       },
>     );
>   }
> 
>   MaterialDesktopVideoControlsThemeData desktopControls() {
>     return MaterialDesktopVideoControlsThemeData(
>             displaySeekBar: false,
>             bottomButtonBarMargin: EdgeInsets.symmetric(horizontal: 5.0),
>             buttonBarHeight: 50.0,
>             buttonBarButtonSize: 25.0,
>             topButtonBar: [
>                 Spacer(),
>                 GestureDetector(
>                   onTap: _showAudios,
>                   child:
>                       Icon(Icons.audiotrack_rounded, color: Colors.white),
>                 ),
>                 SizedBox(width: 12),
>                 GestureDetector(
>                   onTap: _showQualities,
>                   child:
>                       Icon(Icons.video_settings_rounded, color: Colors.white),
>                 ),
>               ],
>             bottomButtonBar: [
>                 Padding(
>                   padding: const EdgeInsets.fromLTRB(10, 15, 17, 15),
>                   child: Image.asset(
>                     'assets/images/live.png',
>                     filterQuality: FilterQuality.medium,
>                   ),
>                 ),
>                 MaterialDesktopSkipPreviousButton(),
>                 MaterialDesktopPlayOrPauseButton(),
>                 MaterialDesktopSkipNextButton(),
>                 MaterialDesktopVolumeButton(),
>                 Spacer(),
>                 MaterialDesktopFullscreenButton(),
>               ]);
>   }
> }
> ```

For m3u8 I get it, but mp4 and mkv I don't know how to do it

**Comment by usman615** [comment]
is media_kit support audio tracks for .mp4 or .mkv formats

**Comment by zezo357** [comment]
I am not sure actually, I don't know


But if mpv supports it then yes

Also did you use that in video_player?

**Comment by usman615** [comment]
I didn't get it what to use in video_player

**Comment by zezo357** [comment]
> I didn't get it what to use in video_player
> 

If you play any video track you can play any audio track for it that's what I understand


So it doesn't matter what the format, as you long there is an audio file for it 


For m3u8 I know how to extract audio and video from it so I know it's possible, mp4 and mkv I didn't try it before 


For video_player I mean any functionality done in it, can be done in media_kit

**Comment by zezo357** [comment]
Also I don't understand all of the functionalities yet, I did work a bit with the controls this what I can help with for now 



For functionality please ask on discord there alot of people who can help you better there

**Comment by usman615** [comment]
oh, that's what you mean, I'm struggling for last 4 to 5 weeks in search of best video player package that have all the stuf that i need. So that's why I didn't try video_player package before using meedu player I used better_player but then it gives me error because of outdated, I think media_kit have support for selecting audio tracks for .mp4 or .mkv formats. I will search furthermore but the time is too short because I have to deploy my app to play store before 3 Sep.

**Comment by zezo357** [comment]
Did it work with meedu_player if it did it should work here, 


And in meedu_player I didn't have a way to set audio tracks btw!? Why it's needed now?

**Comment by usman615** [comment]
No, not in meedu player or not in better player support for .mp4 or .mkv audio tracks but I see this other format audio selecting support in flutter_vlc_player package, I also searched its source code but don't get it how to apply in media_kit.

**Comment by zezo357** [comment]
Sadly I don't know too😢

**Comment by usman615** [comment]
of flutter_vlc_player or media_kit ?

**Comment by zezo357** [comment]
Media_kit

**Comment by usman615** [comment]
ok brother I will try it

**Comment by 23doors** [comment]
media_kit works just fine with mp4 and mkv containers. All audio, video and subtitle tracks are parsed.
You can find a basic track selector here which you can use as a base:
https://github.com/media-kit/media-kit/blob/main/media_kit_test/lib/common/widgets.dart#L10

Track selection is simply not exposed in default controls.

**Comment by usman615** [comment]
ok bro let me try it

**Comment by usman615** [comment]
Alhamdulillah,

Successfully implemented video and audio tracks.

Thanks, brothers @zezo357 @23doors 
Thanks to media_kit 💝


Now only a few things left:

How can I implement a set video aspect ratio feature ( fit, stretch, fit height, fit width, etc.) in a video player?

**Comment by zezo357** [comment]
The video widget can take the fit argument, you will need to set state whenever your user changes it 


That's from my little understanding, if anyone can help please do.

**Comment by usman615** [comment]
Ok bro

**Comment by alexmercerind** [comment]
All features that you'll need are available. The codec support is already very good, you don't need to worry.

- ["Select video, audio or subtitle track" section in README](https://github.com/media-kit/media-kit#select-video-audio-or-subtitle-track)
- `MaterialCustomButton` or `MaterialDesktopCustomButton` may be used for any custom action.

**Comment by usman615** [comment]
Ok thanks bro 🙌
