### ISSUE TITLE
[Question] how do i add videos qualities and change theme  by the controller ?

### ISSUE THREAD

**Issue by Joseph-Nathan** [media-kit/media-kit#426]
how do i add videos qualities and change theme  by the controller ?

**Comment by alexmercerind** [comment]
We provide `MaterialCustomButton` & `MaterialDesktopCustomButton`.

You can use them to add custom action & trigger whichever action you want.

Contributions are welcomed for more higher order pre-built widgets.

**Comment by alexmercerind** [comment]
You can talk to other people in the community on our Discord.

**Comment by ksanchez9306** [comment]
> Discord

Can you provide the discord link if possible ? thanks
