### ISSUE TITLE
[Android] Failure to initialize in emulator / Windows Subsystem for Android

### ISSUE THREAD

**Issue by deckerst** [media-kit/media-kit#427]
It seems media_kit fails to initialize video surfaces/codecs when used in an emulator.

Also, I've submitted my app to the Amazon App Store to target, among others, Windows 11 devices (via [WSA](https://learn.microsoft.com/en-us/windows/android/wsa/)). They had accepted previous versions of Aves that used a different video engine, but this time the app got rejected because video playback fails on WSA with media_kit. I don't have Windows so I can't test this myself, but Amazon testers were kind enough to provide logs.

Here are filtered [logs for the emulator case](https://github.com/media-kit/media-kit/files/12469569/aves.v1.9.3.-.emulator.issue.log), and the more thorough [logs for the WSA case](https://github.com/media-kit/media-kit/files/12469568/aves.v1.9.2.-.amazon.windows.issue.log).

Package versions:
```
media_kit: "1.1.7"
media_kit_libs_android_video: "1.3.3"
media_kit_native_event_loop: "1.0.7"
media_kit_video: "1.1.8"
```

**Comment by alexmercerind** [comment]
We already fallback to S/W rendering in emulators, that's the best we will do here.

**Comment by deckerst** [comment]
Falling back to SW rendering is fine. But what I'm reporting is that it fails.

**Comment by deckerst** [comment]
My bad, I got mistaken, it does not fail all the time. I got some videos to work on an Android 13 emulator. I thought all videos were failing but I guess only some codecs were badly handled.
Want me to close this issue?

**Comment by alexmercerind** [comment]
Hi!

Apologies, not very active these days. In most cases (with last update), S/W fallback works very well on Android.

On emulators, I simply use following to enforce S/W rendering:

https://github.com/media-kit/media-kit/blob/8fd22cc5b11035ac22fd2a0f930056a18fc69095/media_kit_video/android/src/main/java/com/alexmercerind/media_kit_video/Utils.java#L12-L37

I believe it's good that way. I think WSA is not being handled by above.
