### ISSUE TITLE
[Question] How to display video from Uint8List on android and ios ?

### ISSUE THREAD

**Issue by Kevin301099** [media-kit/media-kit#428]

**Comment by blackcz2015** [comment]
#380
Using the `Media.memory` constructor

**Comment by Kevin301099** [comment]
i want to stream video data in byte chunks from server.

can you give example  ?

**Comment by birros** [comment]
> i want to stream video data in byte chunks from server.

What you describe sounds like the [HLS](https://en.wikipedia.org/wiki/HTTP_Live_Streaming) or [Dash](https://en.wikipedia.org/wiki/Dynamic_Adaptive_Streaming_over_HTTP) protocols. HLS is supported by `media-kit`, I recommend you to use this protocol.

As mentioned by @blackcz2015, there's also `Media.memory`, but I doubt it supports chunked videos.
