### ISSUE TITLE
[Question] Pause and resume video depending on window focus state

### ISSUE THREAD

**Issue by temzints** [media-kit/media-kit#430]
Hello, I'm currently pausing and playing the video with [window_manager](https://pub.dev/packages/window_manager) onWindowEvent.onWindowBlur. Could this be achieved without additional dependencies? I would like to stop the videos to prevent performance issues when they are minimized or inattentive.

**Comment by birros** [comment]
```dart
Video(
  pauseUponEnteringBackgroundMode: true,
  resumeUponEnteringForegroundMode: true,
);
```

**Comment by temzints** [comment]
@birros This doesn't seem to work on windows desktop app. It still uses cpu and gpu even when I opened fullscreen game.

**Comment by alexmercerind** [comment]
I'm not going to introduce additional logic to separately handle Windows.

Ask Flutter to make API behave same on Windows.
