### ISSUE TITLE
[Bug Report][GNU/Linux] When switching between two video pages, there will be a screenshot cover similar to the previous video

### ISSUE THREAD

**Issue by junmingchen123** [media-kit/media-kit#433]
![image](https://github.com/media-kit/media-kit/assets/135569486/f9cd44be-0eeb-42c5-8bdc-f0f8781e9404)

```dart
class _VideoPlayerState extends State {
    @Override
    void initState() {
        super.initState();
        widget.player.open(Media(widget.videoUrl));
     }

   @Override
   Widget build(BuildContext context) {
        return Video(
             controller: widget.controller,
             controls: NoVideoControls,
        );
}
```

**Comment by alexmercerind** [comment]
Few important questions:

- Platform?
- Code?

**Comment by bdlukaa** [comment]
I am also experiencing this issue. When I pop a page and dispose the player on the widget's `dispose` method, the app bugs and crashes.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

// Make sure to add following packages to pubspec.yaml:
// * media_kit
// * media_kit_video
// * media_kit_libs_video
import 'package:media_kit/media_kit.dart'; // Provides [Player], [Media], [Playlist] etc.
import 'package:media_kit_video/media_kit_video.dart'; // Provides [VideoController] & [Video] etc.

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  // Necessary initialization for package:media_kit.
  MediaKit.ensureInitialized();
  runApp(
    const TestApp(),
  );
}

class TestApp extends StatelessWidget {
  const TestApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Builder(builder: (context) {
        return Scaffold(
          body: Align(
            alignment: Alignment.topLeft,
            child: TextButton(
              child: const Text('Open other screen'),
              onPressed: () {
                Navigator.of(context).push(
                  MaterialPageRoute(builder: (c) => const MyScreen()),
                );
              },
            ),
          ),
        );
      }),
    );
  }
}

class MyScreen extends StatefulWidget {
  const MyScreen({Key? key}) : super(key: key);
  @override
  State<MyScreen> createState() => MyScreenState();
}

class MyScreenState extends State<MyScreen> {
  // Create a [Player] to control playback.
  late final player = Player();
  // Create a [VideoController] to handle video output from [Player].
  late final controller = VideoController(player);

  @override
  void initState() {
    super.initState();
    // Play a [Media] or [Playlist].
    player.open(
      Media(
        'https://user-images.githubusercontent.com/28951144/229373695-22f88f13-d18f-4288-9bf1-c3e078d83722.mp4',
      ),
    );
  }

  @override
  void dispose() {
    player.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Test')),
      body: Center(
        child: SizedBox(
          width: MediaQuery.of(context).size.width,
          height: MediaQuery.of(context).size.width * 9.0 / 16.0,
          // Use [Video] widget to display video output.
          child: Video(controller: controller),
        ),
      ),
    );
  }
}
```

</details>

[Video showcasing the issue](https://github.com/media-kit/media-kit/assets/45696119/8f435189-df44-4388-bf5d-2a53eaff17cd)

---

A workaround this issue is to call `player.pause()` before disposing the player. Of course this is not the best solution - and may be annoying to add it to all the screens one may have - but it works.

```dart
class MyScreenState extends State<MyScreen> {
  // Create a [Player] to control playback.
  late final player = Player();
  // Create a [VideoController] to handle video output from [Player].
  late final controller = VideoController(player);

  @override
  void initState() {
    super.initState();
    // Play a [Media] or [Playlist].
    player.open(
      Media(
        'https://user-images.githubusercontent.com/28951144/229373695-22f88f13-d18f-4288-9bf1-c3e078d83722.mp4',
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        leading: BackButton(
          onPressed: () async {
            await player.pause();
            await Future.delayed(const Duration(milliseconds: 100));
            if (mounted) {
              Navigator.of(context).maybePop();
            }
          },
        ),
        title: const Text('Test'),
      ),
      body: Center(
        child: SizedBox(
          width: MediaQuery.of(context).size.width,
          height: MediaQuery.of(context).size.width * 9.0 / 16.0,
          // Use [Video] widget to display video output.
          child: Video(controller: controller),
        ),
      ),
    );
  }
}
```

**Comment by femalemonkeyman** [comment]
> I am also experiencing this issue. When I pop a page and dispose the player on the widget's `dispose` method, the app bugs and crashes.
> 
> Code sample
>  Screencast.from.11-12-2023.18.31.37.webm 
> A workaround this issue is to call `player.pause()` before disposing the player. Of course this is not the best solution - and may be annoying to add it to all the screens one may have - but it works.
> 
> ```dart
> class MyScreenState extends State<MyScreen> {
>   // Create a [Player] to control playback.
>   late final player = Player();
>   // Create a [VideoController] to handle video output from [Player].
>   late final controller = VideoController(player);
> 
>   @override
>   void initState() {
>     super.initState();
>     // Play a [Media] or [Playlist].
>     player.open(
>       Media(
>         'https://user-images.githubusercontent.com/28951144/229373695-22f88f13-d18f-4288-9bf1-c3e078d83722.mp4',
>       ),
>     );
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         leading: BackButton(
>           onPressed: () async {
>             await player.pause();
>             await Future.delayed(const Duration(milliseconds: 100));
>             if (mounted) {
>               Navigator.of(context).maybePop();
>             }
>           },
>         ),
>         title: const Text('Test'),
>       ),
>       body: Center(
>         child: SizedBox(
>           width: MediaQuery.of(context).size.width,
>           height: MediaQuery.of(context).size.width * 9.0 / 16.0,
>           // Use [Video] widget to display video output.
>           child: Video(controller: controller),
>         ),
>       ),
>     );
>   }
> }
> ```
Yours looks like the page transition issue. 
Try adding 
```dart
pageTransitionsTheme: const PageTransitionsTheme(
          builders: {
            TargetPlatform.linux: OpenUpwardsPageTransitionsBuilder(),
          },
        ),```
To your apps theme

**Comment by bdlukaa** [comment]
Thank you! That fixes the problem - but I still think this is an issue since it doesn't happen on the other platforms.

**Comment by alexmercerind** [comment]
@bdlukaa,

The issue you commented here is completely unrelated to this issue. That relates to #64 & #167. A bug in Flutter.

**Comment by bdlukaa** [comment]
I apologize!
