### ISSUE TITLE
Can't Watch Video on Windows 7

### ISSUE THREAD

**Issue by mohammadinfo** [media-kit/media-kit#435]
Hello dear friends,

I have been using this package, and it works perfectly fine on Windows 8, 10, and 11. However, on Windows 7, it only displays a black screen while the video's audio plays in the background. I don't have a video picture, and I'm not sure what to do to resolve this issue. If anyone has any insights, please guide me.

Thank you.

![image](https://github.com/media-kit/media-kit/assets/62583428/1c44fc4a-9ace-44e6-9d49-67febdb7d048)

**Comment by alexmercerind** [comment]
It's not an issue with Windows 7, 8, 8.1, 10 or 11. It's related to Direct X feature level.

It's a bug in Flutter in-fact. I don't have time to explain again:

- #249

**Comment by alexmercerind** [comment]
Even if it is resolved, only software rendering will work (Flutter is also falling back to S/W).
