### ISSUE TITLE
[Bug Report] DTS not working

### ISSUE THREAD

**Issue by ijuniorfu** [media-kit/media-kit#437]
dts audio is not surpported

**Comment by alexmercerind** [comment]
Not interested in adding more codecs.

**Comment by ijuniorfu** [comment]
dts audio is very common, looking forward to adding，There is no need for a codec anymore.

**Comment by ijuniorfu** [comment]
[https://github.com/media-kit/libmpv-darwin-build/blob/main/scripts/ffmpeg/meson.build#L138](url)

provided but not supported

**Comment by birros** [comment]
`--enable-decoder=dca` is required on macOS.
@alexmercerind maybe it's also required on other platforms?

**Comment by alexmercerind** [comment]
> [Provided but not supported.](https://github.com/media-kit/libmpv-darwin-build/blob/main/scripts/ffmpeg/meson.build#L138)

This sounds like a mistake on my end.

Other than this, I'm not really convinced to add more decoders/demuxers to the default selection. It is sufficient for most applications (or even multimedia applications). I took [Audio/Video in Chrom(ium|e)](https://www.chromium.org/audio-video/) as a base & added additional decoders/demuxers/protocols.

I will add the same for Windows & Android.

In even better case (probably enterprise grade projects), one should make their own finer selection of features & focus on optimization. On the other hand, if one is building a media-player, possibly it's better to use a max-ed out version of FFmpeg/mpv (probably with GPL code as well).

**Comment by ijuniorfu** [comment]
I tested with  media_kit_libs_ios_video v0.5.8 , dts still not working

**Comment by birros** [comment]
> I tested with media_kit_libs_ios_video v0.5.8 , dts still not working

I'll check it, I didn't take the time to check on iOS, only on macOS, maybe the decoder is different on this platform... (Apple...)

**Comment by alexmercerind** [comment]
Have you tried other platforms?

**Comment by birros** [comment]
> I tested with media_kit_libs_ios_video v0.5.8 , dts still not working

DTS works fine on iOS.

I used a sample from here: https://filesamples.com/formats/dts

```shell
$ ffmpeg -i sample1.dts
ffmpeg version 6.0 Copyright (c) 2000-2023 the FFmpeg developers
Input #0, dts, from 'sample1.dts':
  Duration: 00:02:02.10, start: 0.000000, bitrate: 1411 kb/s
  Stream #0:0: Audio: dts (DTS), 44100 Hz, stereo, fltp, 1411 kb/s
```

**Comment by ijuniorfu** [comment]
sorry about that, i took wrong SHA256SUM, DTS works fine on iOS.

**Comment by alexmercerind** [comment]
Apologies for the delay. Getting DTS resolved on Windows & Android.

**Comment by alexmercerind** [comment]
A new update has been released. Please refer to the ["Installation" section of the README](https://github.com/media-kit/media-kit#installation).

Thanks!
