### ISSUE TITLE
[Bug Report] Continuous video stops every 5-10 seconds w/ HTTP live streams 

### ISSUE THREAD

**Issue by reteset** [media-kit/media-kit#440]
Hi , First of all thank you for the great work you did.
i have been using it since the beginning, 
I am developing a multi platform app  and used media_kit as the player 
The player is playing HTTP live streams

With the previous version update (1.1.6) a problem has arisen where player stops periodically on every 5-10 secons
and sometimes it continues after a delay or it stops completely
As you can see logs below 
```

I/flutter (13000): PAUSED 
I/flutter (13000): media_kit: wakelock: _count = 2
I/flutter (13000): BUFFERING  = true
D/something(13000): PlayerBase::stop() from IPlayer
D/AudioTrack(13000): stop(50): called with 1109760 frames delivered
I/flutter (13000): BUFFERING = false
```

- playerMediaKit.stream.playing. is set to `false` 
- playerMediaKit.stream.buffering is set to `true`
- then PlayerBase::stop() comes
- playerMediaKit.stream.buffering is set to `false`

Then stream continues to play in most times but it stops completely sometimes

**I tried it on :**

- MacOS With M1
- IOS
- Android
- Android TV
- Windows

It happens on all devices but more often on Android devices

There is no problem with static movie files even on same server that live stream comes from
And there is no internet speed or connection issue , Tests were made with high spec devices

**Comment by alexmercerind** [comment]
Hi!

You may see our recent commits (I believe there aren't many) before the latest release. I believe it will be easier for you to find out the cause because you're the one experiencing it. I'm welcomed to pull-requests & public contributions. I can just guess that one of these is probably causing trouble:

https://github.com/media-kit/media-kit/blob/eff00e3b096e4e47d28a754061db1a2d66a0215c/media_kit/lib/src/player/native/player/real.dart#L2351-L2356

Thanks!

**Comment by alexmercerind** [comment]
I'm unable to proceed with any fix as I couldn't reproduce. We'll appreciate pull-request from your end.

Thanks!

It shouldn't be hard to pin down a faulty commit.

**Comment by nguyenxuankiet262** [comment]
I got the same issue.
One video has infinity buffering
One video buffers at the 4th second in the 6s video. It only occurs everytime i play the video in the first time.
