### ISSUE TITLE
[Bug Report][Android] Video sound is inconsistent

### ISSUE THREAD

**Issue by guozhigq** [media-kit/media-kit#445]
I am developing a third-party app, and users report that the video sound in the app is inconsistent with the official app.

I asked the user to install the **v1.1.7**  「media_kit_test_android-arm64-v8a.apk」 installation package in the release, through  
[https://user-images.githubusercontent.com/28951144/229373695-22f88f13-d18f-4288-9bf1-c3e078d83722.mp4](https://user-images.githubusercontent.com/28951144/229373695-22f88f13-d18f-4288-9bf1-c3e078d83722.mp4) Video and sound comparison, also found inconsistent

The models are 
Pixel 5   android 13
Pixel 6  Pro  android 13

My English is not very good, so I used Google Translate, sorry.

Thank you for making such an excellent plugin。🤝

**Comment by alexmercerind** [comment]
Inconsistent in what way may I ask?

**Comment by guozhigq** [comment]
Sorry, I didn't explain it clearly. 
Inconsistent volume levels,  Using media_kit, the volume level is 20% lower than normal

**Comment by alexmercerind** [comment]
Hi!

I'm not really sure if it's possible to resolve it, it doesn't seem like a necessity. I'm not really able to feel the difference on the other hand. Currently, we use --ao=opensles, you can try to use --ao=audiotrack & let us know how that feels. This can be done through our `setProperty` API.

However, it is possible to support volume boost (support for volume higher than 100.0).

**Comment by alexmercerind** [comment]
As stated above, you can try to use --ao=audiotrack.
