### ISSUE TITLE
[Enhancement] Keep seekbar visible when seeking

### ISSUE THREAD

**Issue by ashilkn** [media-kit/media-kit#450]
The seekBar disappears after `controlsHoverDuration` is over when seeking a video. Couldn't find a way to keep it visible.

**Comment by ijuniorfu** [comment]
how can i get my seekbar's dragging position?

**Comment by ashilkn** [comment]
> ijuniorfu

`videoController.player.state.position`
`videoController.player.stream.position`

**Comment by alexmercerind** [comment]
Resolved in https://github.com/alexmercerind/media-kit/commit/8fa1bc1f4f13d005c17358903a416865c697ba0a.

Thanks!

<hr>

It's been a practice to keep issues opened until next stable release.

As a side-note, contributions to built-in video-controls are extremely welcomed. Without any doubt, I spent a lot of time on these video-controls to make them look & feel good. However, this is not my primary interest in this project, I rather work on native implementation etc. which I believe demand my higher attention.

**Comment by alexmercerind** [comment]
> How can i get my seekbar's dragging position?

Though existing video-controls are customizable to good extent, you may consider writing your own video-controls from scratch if you have some very specific requirements. Our "Guide" in the README will help you through. Alternatively, you may consider sending pull-requests to add more features/options to existing.

**Comment by ashilkn** [comment]
> Resolved in [alexmercerind@8fa1bc1](https://github.com/alexmercerind/media-kit/commit/8fa1bc1f4f13d005c17358903a416865c697ba0a).
> 
> Thanks!
> 
> It's been a practice to keep issues opened until next stable release.
> 
> As a side-note, contributions to built-in video-controls are extremely welcomed. Without any doubt, I spent a lot of time on these video-controls to make them look & feel good. However, this is not my primary interest in this project, I rather work on native implementation etc. which I believe demand my higher attention.

Thank you @alexmercerind!

**Comment by ijuniorfu** [comment]
> 
Thanks!

**Comment by alexmercerind** [comment]
A new update has been released. Please refer to the ["Installation" section of the README](https://github.com/media-kit/media-kit#installation).

Thanks!
