### ISSUE TITLE
[Bug Report] `subtitleViewConfiguration` does not work in fullscreen

### ISSUE THREAD

**Issue by mhkarami** [media-kit/media-kit#460]
[windows platform]
`subtitleViewConfiguration ` does not work in full-screen mode.
```
...
          child: Video(
            controller: _controller,
            subtitleViewConfiguration: const SubtitleViewConfiguration(style: TextStyle(fontSize: 10)),
...
```
subtitle configuration changes in normal mode but does not change in fullscreen mode. even i can not hide that with  `visible: false`

**Comment by alexmercerind** [comment]
It's actually a bug. This feature was added in later versions & I forgot to pass it here (probably few other too):

https://github.com/media-kit/media-kit/blob/12600d4da12f67615b412ff89766ad0b21d4d34b/media_kit_video/lib/media_kit_video_controls/src/controls/methods/fullscreen.dart#L41-L53

You can send us a PR if you wish to.

**Comment by alexmercerind** [comment]
@mhkarami 

A new update has been released. Please refer to the ["Installation" section of the README](https://github.com/media-kit/media-kit#installation). It should work correctly now.

Thanks!

**Comment by alexmercerind** [comment]
The update has been really delayed. Apologies.
