### ISSUE TITLE
[Bug Report][Windows] Exiting process causes crash

### ISSUE THREAD

**Issue by wanjm** [media-kit/media-kit#461]
media_kit cause crash in windows when closed
![image](https://github.com/media-kit/media-kit/assets/3118573/1afb2f29-7668-4f38-88f0-c093400c14ac)

**Comment by wanjm** [comment]
why does it sleep 5 seconds  in line 127, which cause the program exit slow;

**Comment by wanjm** [comment]
does it has anything to do with https://github.com/aaassseee/screen_brightness/issues/23, I  "flutter pub upgrade " today which will use the latest brightness for windows;

**Comment by alexmercerind** [comment]
Hi @wanjm,

https://github.com/aaassseee/screen_brightness/issues/23 was partially related. I did attempt to resolve this in https://github.com/media-kit/media-kit/pull/452/commits/0c5e56ae52a63436e4603da99b1beb93a89ef223:

- #452

Your feedback or confirmation is extremely welcomed.

**Comment by alexmercerind** [comment]
> Why does it sleep 5 seconds in line 127, which cause the program exit slow.

It's (probably futile) attempt to save from an "mutex destroyed while busy error" on Windows by adding some delay. I don't know, `std::mutex` from MSVC seems to behave a bit odd at times. It's clear that mutex isn't acquired while it's being freed, same implementation never results in any problem on other platforms.

**Comment by wanjm** [comment]
when will the next release be published, I am blocked by this issue; 
thanks;

**Comment by alexmercerind** [comment]
@wanjm 

A new update has been released. Please refer to the ["Installation" section of the README](https://github.com/media-kit/media-kit#installation).

Thanks!

<hr>

Apologies. This update has been really delayed, a number of fixes & improvements were made.

**Comment by wanjm** [comment]
thanks
