### ISSUE TITLE
Cannot open videos in android emulator

### ISSUE THREAD

**Issue by EMUNES** [media-kit/media-kit#462]
I can not open video files in the android emulator (PIXEL 5 API 34). I'm pretty sure there is no problem about the video files as media kit can display the length of the videos accurately. But it just can not display video content.

Here are the logs and error messages related to media_kit when this problem occurs :

```
I/media_kit(30861): com.alexmercerind.media_kit_video.VideoOutputManager.create: 139262421291520
I/media_kit(30861): flutterJNIAPIAvailable = true
I/media_kit(30861): com.alexmercerind.media_kit_video.VideoOutput: id = 0
I/flutter (30861): {id: 0}
I/flutter (30861): media_kit: AndroidVideoController: Emulator detected.
I/flutter (30861): media_kit: AndroidVideoController: Enforcing S/W rendering.
I/flutter (30861): media_kit: wakelock: _count = 1
I/media_kit(30861): com.alexmercerind.media_kit_video.VideoOutputManager.createSurface: 139262421291520
I/flutter (30861): {wid: 12430}
I/media_kit(30861): com.alexmercerind.media_kit_video.VideoOutputManager.setSurfaceTextureSize: 139262421291520 960 540
E/EGL_emulation(30861): tid 31018: eglCreateContext(1738): error 0x3004 (EGL_BAD_ATTRIBUTE)
E/EGL_emulation(30861): tid 31019: eglCreateContext(1738): error 0x3004 (EGL_BAD_ATTRIBUTE)
D/EGL_emulation(30861): app_time_stats: avg=67.31ms min=13.22ms max=293.23ms count=15
I/flutter (30861): media_kit: wakelock: _count = 0
```

My code is following the example. The main difference is that I used video player in a `Dialog` widget

```
# Initialize in a stateful widget.
  late final Player videoPlayer = Player();
  late final VideoController videoController = VideoController(videoPlayer);

  @override
  void dispose() {
    videoPlayer.dispose();
    super.dispose();
  }

...

# The callback to invoke the video plaer.
    setState(() {
      _videos.add(videoRecord);
      videoPlayer.open(Media(videoRecord.filePath));
    });

...

# Display video.
ConstrainedBox(
    // To be responsive on different platforms. The constraint has to be set in different values.
    constraints: const BoxConstraints(
        maxHeight: 600, maxWidth: 600),
    child: Video(
      controller: videoController,
      width: 320,
      height: 180,
      // fit: BoxFit.contain,
    )))

```

**Comment by alexmercerind** [comment]
The graphics (OpenGL (ES)) in emulators is pretty terrible. For now, I'm just going to blame it on any of the emulator image, emulator configuration or host device. We enforce software rendering in emulators (as you can see in the logs) to circumvent any issues, but it seems it still doesn't work in some cases.

In my own experience, (speaking of the official images in Android Studio): Android 5.0 just refuses to display any video, while we have users who are able to play videos just fine on real Android 5.x devices. Same for Android 6.0. Modern images with newer Android versions never gave me any trouble however.

**Comment by alexmercerind** [comment]
I unfortunately cannot actively work or look for solutions to this as it's merely a development time concern.

That for some minor cases.

**Comment by EMUNES** [comment]
Thanks for your reply. I will try to debug on a real android device when video playing is needed.

**Comment by pubpy2015** [comment]
if using emulator, you can using API 28:
![ảnh](https://github.com/media-kit/media-kit/assets/59004953/cc29ec34-3f3f-4a70-a6e2-6c984729a86e)
