### ISSUE TITLE
Debian package missing dependencies

### ISSUE THREAD

**Issue by twilight1794** [media-kit/media-kit#463]
Hi. In order to work, Spotube needs `libmpv2` package as a dependency, however it is not listed in the Debian package. I used Debian Bookworm unstable.

**Comment by twilight1794** [comment]
Sorry, I did a mistake

**Comment by alexmercerind** [comment]
No worries.

This issue tracker is meant for developers who wish to report any issues or request any features in package:media_kit. Support to the users of any applications which use package:media_kit is not provided here. You should reach out the developer(s) of the  individual project(s).

Thanks!
