### ISSUE TITLE
[Bug Report][iOS] "seamless.dart" code-sample causes problem

### ISSUE THREAD

**Issue by vanvixi** [media-kit/media-kit#464]
I'm using the example you provided.
After play, video is broken and can't continue.
This problem occurs even in profile mode.

**Log:**
```
VideoOutput: enableHardwareAcceleration: true
flutter: VideoOutput.Resize
flutter: {handle: 5164696000, rect: {height: 0.0, left: 0.0, top: 0.0, width: 0.0}, id: 12}
flutter: NativeVideoController: Texture ID: 12
flutter: media_kit: wakelock: _count = 1
VideoOutput: enableHardwareAcceleration: true
flutter: VideoOutput.Resize
flutter: {handle: 5166792144, id: 13, rect: {left: 0.0, height: 0.0, top: 0.0, width: 0.0}}
flutter: NativeVideoController: Texture ID: 13
TextureGL: resize: 854.0x480.0
flutter: VideoOutput.Resize
flutter: {rect: {top: 0.0, width: 854.0, left: 0.0, height: 480.0}, id: 12, handle: 5164696000}
TextureGL: resize: 1280.0x720.0
flutter: VideoOutput.Resize
flutter: {handle: 5166792144, rect: {top: 0.0, height: 720.0, left: 0.0, width: 1280.0}, id: 13}
flutter: players: (0, 1)
flutter: controllers: (0, 1)
flutter: media_kit: wakelock: _count = 2
flutter: media_kit: wakelock: _count = 1
VideoOutput: enableHardwareAcceleration: true
flutter: VideoOutput.Resize
flutter: {id: 14, rect: {left: 0.0, height: 0.0, top: 0.0, width: 0.0}, handle: 5300739584}
flutter: NativeVideoController: Texture ID: 14
TextureGL: resize: 1280.0x720.0
flutter: VideoOutput.Resize
flutter: {handle: 5300739584, id: 14, rect: {height: 720.0, left: 0.0, width: 1280.0, top: 0.0}}
flutter: players: (1, 2)
flutter: controllers: (1, 2)
flutter: media_kit: wakelock: _count = 2
flutter: media_kit: wakelock: _count = 1
VideoOutput: enableHardwareAcceleration: true
flutter: VideoOutput.Resize
flutter: {rect: {left: 0.0, top: 0.0, width: 0.0, height: 0.0}, handle: 5288609088, id: 15}
flutter: NativeVideoController: Texture ID: 15
MediaKitEventLoopHandler::Register: std::thread exit: 5164696000
MediaKitEventLoopHandler::Dispose: 5164696000
flutter: players: (2, 3)
flutter: controllers: (2, 3)
flutter: media_kit: wakelock: _count = 2
TextureGL: resize: 1280.0x720.0
flutter: VideoOutput.Resize
flutter: {handle: 5288609088, rect: {width: 1280.0, left: 0.0, top: 0.0, height: 720.0}, id: 15}
flutter: media_kit: wakelock: _count = 1
VideoOutput: enableHardwareAcceleration: true
flutter: VideoOutput.Resize
flutter: {rect: {left: 0.0, top: 0.0, width: 0.0, height: 0.0}, handle: 5288039136, id: 16}
flutter: NativeVideoController: Texture ID: 16
MediaKitEventLoopHandler::Register: std::thread exit: 5166792144
MediaKitEventLoopHandler::Dispose: 5166792144
flutter: players: (2, 3)
flutter: controllers: (2, 3)
flutter: media_kit: wakelock: _count = 2
flutter: media_kit: wakelock: _count = 1
TextureGL: resize: 1280.0x720.0
flutter: VideoOutput.Resize
flutter: {id: 16, rect: {left: 0.0, top: 0.0, width: 1280.0, height: 720.0}, handle: 5288039136}
VideoOutput: enableHardwareAcceleration: true
flutter: VideoOutput.Resize
flutter: {id: 17, rect: {top: 0.0, left: 0.0, width: 0.0, height: 0.0}, handle: 5288275808}
flutter: NativeVideoController: Texture ID: 17
MediaKitEventLoopHandler::Register: std::thread exit: 5288039136
MediaKitEventLoopHandler::Dispose: 5288039136
TextureGL: resize: 1280.0x720.0
flutter: VideoOutput.Resize
flutter: {handle: 5288275808, id: 17, rect: {left: 0.0, top: 0.0, width: 1280.0, height: 720.0}}
flutter: media_kit: wakelock: _count = 0
```

**Video**

https://github.com/media-kit/media-kit/assets/75975945/d21bf69d-5c86-44b8-98e7-5221010f3ea7

**Comment by alexmercerind** [comment]
What makes you think "video is broken"? You can possibly improve logic & solve issues in the code sample.

**Comment by alexmercerind** [comment]
Misleading issue title; edited.

**Comment by vanvixi** [comment]
> What makes you think "video is broken"? You can possibly improve logic & solve issues in the code sample.

I also implemented it myself, but still have the same problem as in the video.
For me Android still works fine, the problem is only with IOS.

**Comment by birros** [comment]
I confirm, the tests concerned:
- `04.tabs_test.dart`
- `09.seamless.dart`

The issue does not concern hardware rendering, as it happens with `HW` and `SW` rendering.

I'll check which commit introduced this bug.

**Comment by birros** [comment]
Ok, I found the bug:
https://github.com/media-kit/media-kit/blob/12600d4da12f67615b412ff89766ad0b21d4d34b/media_kit/lib/src/player/native/player/real.dart#L728

Error created by:
https://github.com/media-kit/media-kit/blob/12600d4da12f67615b412ff89766ad0b21d4d34b/media_kit_test/lib/tests/09.seamless.dart#L91

I tried to use `NativePlayer.disposed`:
```dart
if (!player.platform.disposed) {
  player.seek(Duration.zero);
}
```

But that's impossible, because in the meantime `disposed` can be set to `false`, probably caused by `lock`.

I suggest replacing all `throw AssertionError('[Player] has been disposed')` with `return`.

---

Off-topic: I've noticed weird behavior if an external audio track (Spotify...) is already playing when running tests with `player.setVolume(0.0)`, I suggest replacing with `player.setAudioTrack(AudioTrack.no())`.

**Comment by birros** [comment]
I'm an idiot…
No need to remove the `throw AssertionError('[Player] has been disposed')`, reordering the instructions in `onPageChanged` is enough: https://github.com/media-kit/media-kit/pull/467/commits/34aa1eced6551421c42e0caf8b5d85b64c97eceb.

**Comment by vanvixi** [comment]
@birros 
I merged your code. 
I checked it, the error will still appear anytime and without rules.

**Comment by alexmercerind** [comment]
You're free to raise a PR with further optimizations. It's not a "problem" which can't be solved by re-writing code one way or another. I can't reproduce on may Windows, GNU/Linux or Android.

**Comment by birros** [comment]
> I checked it, the error will still appear anytime and without rules.

I can't reproduce.
