### ISSUE TITLE
Trusting Production Ready & LTS

### ISSUE THREAD

**Issue by jtkeyva** [media-kit/media-kit#466]
This package is amazing and seems like a no-brainer to use. I do have my concernts though using it in production:

-  It's fairly new
- unverified uploader
- 18 contributers
- github community standards are on the weak side

It is nice that it is sponsored by Stream and I've had good response on bugs/issues.

What's the consensus? Is this fully battle tested production ready? Can we have confidence this isn't going to go the way of Better_Player?

Thank you

**Comment by MehmetKaranlik** [comment]
We are experimenting with this package on scrollable feed like twitter. It's some times freezes whole app, but its cross-platform support is exceptional. Much better than raw video_player. Which is using exo-player for android. It is non stop crashes when there is certain amount of controller.

**Comment by bdlukaa** [comment]
We use this package on [Bluecherry](https://github.com/bluecherrydvr/unity) to display RTSP streams. It is very good, support is awesome and very easy to use. Better than `dart_vlc` for desktop and `video_player` for mobile, performance and memory management rocks.

**Comment by jtkeyva** [comment]
> We are experimenting with this package on scrollable feed like twitter. It's some times freezes whole app, but its cross-platform support is exceptional. Much better than raw video_player. Which is using exo-player for android. It is non stop crashes when there is certain amount of controller.

Hi @MehmetKaranlik I am in the same situation. Care to share your solution?

**Comment by MehmetKaranlik** [comment]
@jtkeyva Well, we couldn't find a solution yet for freeze issue we are experimenting on.

**Comment by alexmercerind** [comment]
@MehmetKaranlik 

I'll add a code sample for social media like feeds.

We do have Instagram Reels like sample in our demo application (refer to README); which works very smoothly.

From performance metrics (Android), I've mostly seen libmpv outperform ExoPlayer, as it's native (you can enable further performance increase but that can take a toll on stability across devices). The support for far more codecs, formats & protocols is applicable to all platforms; where performance is also good.

For crash: Dispose resources correctly. If you don't, eventually RAM will run out & crash will happen. You can see our demo application playing 8 videos concurrently (& can be restarted countless times without any issues; rest depends upon hardware; desktop can handle more concurrent instances compared to mobile).

For freeze: Dispose resources correctly. You haven't specified the platform. I can replicate the freeze issue on GNU/Linux. It highly depends on the platform; both Flutter & media_kit may receive improvements in this regard.

If there's a clear crash reproduction (besides "I carelessly created too many videos which made memory usage exceed") that you can provide, please file issue.

<hr>

@jtkeyva 

Improvements are due in every regard. Next version will always be better than the previous.

package:media_kit also has a large number of unit-tests to ensure stability & less breakage.

This is an open-source project; contributions are welcomed (implementation, tests, docs, code samples). This is not a product of some company. I (as an individual) have limited time & motivation towards something; it has to be either: 1. enjoyable or/and 2. rewarding for me.

I'm trying my best to ensure the quality (a number of projects depend). Still... project is under MIT license & comes with no warranty. So, you and/or your organisation have to take the obligation for the quality of any software product you release in the market, without blaming it on some open-source code available publicly.

Many production applications already use package:media_kit, few are really good. There's a pinned issue which mentions some I could find: #449.

<hr>

Try using the demo application for seeing the level of performance that is achievable presently before commenting vaguely. ¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯

The main idea behind that demo application is that, it can allow developers to evaluate the project's current state before committing their resources into development.

**Comment by MehmetKaranlik** [comment]
> @MehmetKaranlik
> 
> I'll add a code sample for social media like feeds.
> 
> We do have Instagram Reels like sample in our demo application (refer to README); which works very smoothly.
> 
> From performance metrics (Android), I've mostly seen libmpv outperform ExoPlayer, as it's native (you can enable further performance increase but that can take a toll on stability across devices). The support for far more codecs, formats & protocols is applicable to all platforms; where performance is also good.
> 
> For crash: Dispose resources correctly. If you don't, eventually RAM will run out & crash will happen. You can see our demo application playing 8 videos concurrently (& can be restarted countless times without any issues; rest depends upon hardware; desktop can handle more concurrent instances compared to mobile).
> 
> For freeze: Dispose resources correctly. You haven't specified the platform. I can replicate the freeze issue on GNU/Linux. It highly depends on the platform; both Flutter & media_kit may receive improvements in this regard.
> 
> If there's a clear crash reproduction (besides "I carelessly created too many videos which made memory usage exceed") that you can provide, please file issue.
> 
> @jtkeyva
> 
> Improvements are due in every regard. Next version will always be better than the previous.
> 
> package:media_kit also has a large number of unit-tests to ensure stability & less breakage.
> 
> This is an open-source project; contributions are welcomed (implementation, tests, docs, code samples). This is not a product of some company. I (as an individual) have limited time & motivation towards something; it has to be either: 1. enjoyable and/or 2. rewarding for me.
> 
> I'm trying my best to ensure the quality (a number of projects depend). Still... project is under MIT license & comes with no warranty. So, you and/or your organisation have to take the obligation for the quality of any software product you release in the market, without blaming it on some open-source code available publicly.
> 
> Many production applications already use package:media_kit, few are really good. There's a pinned issue which mentions some I could find: #449.
> 
> Try using the demo application for seeing the level of performance that is achievable presently before commenting vaguely. ¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯
> 
> The main idea behind that demo application is that, it can allow developers to evaluate the project's current state before committing their resources into development.

Well i profiled, it does not seem memory issue though. Anyways if i can spot exactly what is wrong, i would file a report. Thanks for your efforts.

**Comment by srix55** [comment]
This issue can be closed @alexmercerind

**Comment by jtkeyva** [comment]
> @MehmetKaranlik
> 
> I'll add a code sample for social media like feeds.
> 
> We do have Instagram Reels like sample in our demo application (refer to README); which works very smoothly.
> 
> From performance metrics (Android), I've mostly seen libmpv outperform ExoPlayer, as it's native (you can enable further performance increase but that can take a toll on stability across devices). The support for far more codecs, formats & protocols is applicable to all platforms; where performance is also good.
> 
> For crash: Dispose resources correctly. If you don't, eventually RAM will run out & crash will happen. You can see our demo application playing 8 videos concurrently (& can be restarted countless times without any issues; rest depends upon hardware; desktop can handle more concurrent instances compared to mobile).
> 
> For freeze: Dispose resources correctly. You haven't specified the platform. I can replicate the freeze issue on GNU/Linux. It highly depends on the platform; both Flutter & media_kit may receive improvements in this regard.
> 
> If there's a clear crash reproduction (besides "I carelessly created too many videos which made memory usage exceed") that you can provide, please file issue.
> 
> @jtkeyva
> 
> Improvements are due in every regard. Next version will always be better than the previous.
> 
> package:media_kit also has a large number of unit-tests to ensure stability & less breakage.
> 
> This is an open-source project; contributions are welcomed (implementation, tests, docs, code samples). This is not a product of some company. I (as an individual) have limited time & motivation towards something; it has to be either: 1. enjoyable and/or 2. rewarding for me.
> 
> I'm trying my best to ensure the quality (a number of projects depend). Still... project is under MIT license & comes with no warranty. So, you and/or your organisation have to take the obligation for the quality of any software product you release in the market, without blaming it on some open-source code available publicly.
> 
> Many production applications already use package:media_kit, few are really good. There's a pinned issue which mentions some I could find: #449.
> 
> Try using the demo application for seeing the level of performance that is achievable presently before commenting vaguely. ¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯
> 
> The main idea behind that demo application is that, it can allow developers to evaluate the project's current state before committing their resources into development.

Thank you for your hard work and contribution. I hope you continue to get satisfaction and appreciation for your creation! I wanna use, just need that smoooooth scrubbing ;)

**Comment by MehmetKaranlik** [comment]
@jtkeyva I have managed to use media kit with feed like structure in my project with solid architecture. My crash problem was due to unsupported codec. That somehow managed to slip out of my ffmpeg conversion on backend. I convert every video uploaded to my system to MP4/H264, it works so smooth. With proper player life and cancellable operation api for  fast user scrolls that solved my problem. If you still need help i can share demo code. @alexmercerind Thanks for this package.

**Comment by jtkeyva** [comment]
@MehmetKaranlik great to hear. Thank you for the info. Sure, I'd love to see how you did it. And I'm certain the community would appreciate it too if you don't mind sharing. This is a very requested use case and not a lot of battle tested proven code is out there to show how it's done.
