### ISSUE TITLE
[Bug Report][GNU/Linux] Popping from a route makes `Player` freeze randomly

### ISSUE THREAD

**Issue by junmingchen123** [media-kit/media-kit#476]
```dart
import 'package:flutter/material.dart';
import 'package:media_kit/media_kit.dart';
import 'package:media_kit_video/media_kit_video.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  MediaKit.ensureInitialized();
  runApp(
    const MaterialApp(
      home: MyPage(),
    ),
  );
}

class PlayerSingleton {
  static final PlayerSingleton _instance = PlayerSingleton._internal();
  factory PlayerSingleton() => _instance;
  PlayerSingleton._internal() {
    player = Player();
    videoController = VideoController(player);
  }

  late final Player player;
  late final VideoController videoController;
}

class MyPage extends StatefulWidget {
  const MyPage({Key? key}) : super(key: key);

  @override
  State<MyPage> createState() => _MyPageState();
}

class _MyPageState extends State<MyPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            Navigator.of(context).push(
              MaterialPageRoute(
                builder: (context) => Scaffold(
                  appBar: AppBar(
                    title: const Text('Video'),
                  ),
                  body: const VideoPlayer(
                    'https://user-images.githubusercontent.com/28951144/229373709-603a7a89-2105-4e1b-a5a5-a6c3567c9a59.mp4',
                  ),
                ),
              ),
            );
          },
          child: const Text('Go'),
        ),
      ),
    );
  }
}

class VideoPlayer extends StatefulWidget {
  final String resource;
  const VideoPlayer(this.resource, {super.key});

  @override
  State<VideoPlayer> createState() => _VideoPlayerState();
}

class _VideoPlayerState extends State<VideoPlayer> {
  @override
  void initState() {
    super.initState();
    PlayerSingleton().player.open(Media(widget.resource));
  }

  @override
  void dispose() {
    PlayerSingleton().player.stop();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Video(
      controller: PlayerSingleton().videoController,
      controls: NoVideoControls,
    );
  }
}

```

```
flutter: media_kit: wakelock: _count = 0
flutter: media_kit: wakelock: _count = 1
flutter: media_kit: wakelock: _count = 2
flutter: media_kit: wakelock: _count = 1
flutter: media_kit: wakelock: _count = 0
flutter: media_kit: wakelock: _count = 1
flutter: media_kit: wakelock: _count = 2
flutter: media_kit: wakelock: _count = 1
flutter: media_kit: wakelock: _count = 0`
```

Hello, I have made the Player a singleton. In initState, when openMedia is disposed, it stops. When I pop back from the next page, the player gets stuck and there is no video playing. May I know how to solve this problem? Thank you

**Comment by alexmercerind** [comment]
Hi @junmingchen123,

It's a bug in default route transition on Flutter, when it is used in GNU/Linux.

https://github.com/media-kit/media-kit/issues/167#issuecomment-1528676658

- #64 
- #167 

<hr>

The recommended workaround for now is to replace the default route transition (at least for GNU/Linux):

https://github.com/media-kit/media-kit/blob/ac336385a689d963ae0d19c0901917cf5991d6de/media_kit_test/lib/main.dart#L43-L51

**Comment by alexmercerind** [comment]
Feel free to let us know if that works well.

Thanks!

**Comment by junmingchen123** [comment]
Thanks for your help, but bad news, I added this and it had no effect

**Comment by alexmercerind** [comment]
You can try using our demo application (download links in README & source code inside media_kit_test directory).

**Comment by junmingchen123** [comment]
Thank you, I have used it, but if I create and dispose frequently, my program will sometimes hang.

**Comment by junmingchen123** [comment]
So I tried making it a singleton

**Comment by junmingchen123** [comment]
This bug, if I dispose without player.stop, no problem, but the video does not close, it will keep playing, because I can hear it, the page returns, and a new video should be played, but it gets stuck. When I swipe left to switch pages , and it can be played normally. I want to know if there is something wrong with what I wrote. Sorry to trouble you.

**Comment by alexmercerind** [comment]
I'll try to reproduce. I haven't really had any trouble in the past. Your code does seem correct.

**Comment by junmingchen123** [comment]
Thank you for causing trouble to you. I wish you a happy life.

**Comment by alexmercerind** [comment]
@junmingchen123,

[Like I said in my comment above](https://github.com/media-kit/media-kit/issues/476#issuecomment-1716886479), it's related to `ZoomPageTransition`.

I could reproduce freeze on GNU/Linux, but replacing with `OpenUpwardsPageTransitionsBuilder` fixed it.

I updated your code sample above:

```dart
import 'package:flutter/material.dart';
import 'package:media_kit/media_kit.dart';
import 'package:media_kit_video/media_kit_video.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  MediaKit.ensureInitialized();
  runApp(
    MaterialApp(
      theme: ThemeData(
        pageTransitionsTheme: const PageTransitionsTheme(
          builders: {
            TargetPlatform.windows: OpenUpwardsPageTransitionsBuilder(),
            TargetPlatform.linux: OpenUpwardsPageTransitionsBuilder(),
            TargetPlatform.macOS: OpenUpwardsPageTransitionsBuilder(),
            TargetPlatform.iOS: OpenUpwardsPageTransitionsBuilder(),
            TargetPlatform.android: OpenUpwardsPageTransitionsBuilder(),
          },
        ),
      ),
      darkTheme: ThemeData(
        pageTransitionsTheme: const PageTransitionsTheme(
          builders: {
            TargetPlatform.windows: OpenUpwardsPageTransitionsBuilder(),
            TargetPlatform.linux: OpenUpwardsPageTransitionsBuilder(),
            TargetPlatform.macOS: OpenUpwardsPageTransitionsBuilder(),
            TargetPlatform.iOS: OpenUpwardsPageTransitionsBuilder(),
            TargetPlatform.android: OpenUpwardsPageTransitionsBuilder(),
          },
        ),
      ),
      home: const MyPage(),
    ),
  );
}

class PlayerSingleton {
  static final PlayerSingleton _instance = PlayerSingleton._internal();
  factory PlayerSingleton() => _instance;
  PlayerSingleton._internal() {
    player = Player();
    videoController = VideoController(player);
  }

  late final Player player;
  late final VideoController videoController;
}

class MyPage extends StatefulWidget {
  const MyPage({Key? key}) : super(key: key);

  @override
  State<MyPage> createState() => _MyPageState();
}

class _MyPageState extends State<MyPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            Navigator.of(context).push(
              MaterialPageRoute(
                builder: (context) => Scaffold(
                  appBar: AppBar(
                    title: const Text('Video'),
                  ),
                  body: const VideoPlayer(
                    'https://user-images.githubusercontent.com/28951144/229373709-603a7a89-2105-4e1b-a5a5-a6c3567c9a59.mp4',
                  ),
                ),
              ),
            );
          },
          child: const Text('Go'),
        ),
      ),
    );
  }
}

class VideoPlayer extends StatefulWidget {
  final String resource;
  const VideoPlayer(this.resource, {super.key});

  @override
  State<VideoPlayer> createState() => _VideoPlayerState();
}

class _VideoPlayerState extends State<VideoPlayer> {
  @override
  void initState() {
    super.initState();
    PlayerSingleton().player.open(Media(widget.resource));
  }

  @override
  void dispose() {
    PlayerSingleton().player.stop();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Video(
      controller: PlayerSingleton().videoController,
      controls: NoVideoControls,
    );
  }
}
```

**Comment by alexmercerind** [comment]
On other platforms, it works fine in all cases.

The issue is better reported at flutter/flutter with adequete code sample showing `Texture` + `ZoomPageTransition`.

**Comment by junmingchen123** [comment]
OK , thank you,Let me try

**Comment by junmingchen123** [comment]
Thank you again for taking the time to deal with this problem, but it still doesn't work for me. Is there something wrong with what I wrote? In order to prevent the video from freezing, I also monitored

`class PlayerSingleton {
  static final PlayerSingleton _instance = PlayerSingleton._internal();
  factory PlayerSingleton() => _instance;
  PlayerSingleton._internal() {
    player = Player();
    videoController = VideoController(player);
  }

  late final Player player;
  late final VideoController videoController;
}

class CustomCarousel extends StatefulWidget {
  final List<ScreenSaver> screenSavers;

  const CustomCarousel({super.key, required this.screenSavers});

  @override
  // ignore: library_private_types_in_public_api
  _CustomCarouselState createState() => _CustomCarouselState();
}

class _CustomCarouselState extends State<CustomCarousel> {
  final CarouselController _controller = CarouselController();
  int _currentIndex = 0;
  bool _isShowingQrCode = false;

  // check frozen
  Duration _lastProgress = Duration.zero;
  int _frozenCount = 0;
  Timer? _frozenTimer;

  bool _isInForeground = true;
  @override
  void initState() {
    super.initState();
    addListenToPlayer();
    _startTimer();
    _isInForeground = true;
  }

  @override
  void dispose() {
    _temporaryTime?.cancel();
    _resetFrozenStateTime?.cancel();
    _stopTimer();
    _isInForeground = false;
    PlayerSingleton().player.stop();
    super.dispose();
  }

  void addListenToPlayer() {
    // check video is completed
    PlayerSingleton().player.stream.completed.listen((completed) {
      if (completed) {
        if (_isShowingQrCode) {
          PlayerSingleton().player.seek(Duration.zero);
          PlayerSingleton().player.play();
        } else {
          jumpToNextPage();
          // when videoEnd -> reset _frozenCount and _lastProgress
          _frozenCount = 0;
          _lastProgress = Duration.zero;
          _videoIsFrozen = true;
        }
      }
    });

    // check video is frozen when video is play
    PlayerSingleton().player.stream.position.listen((Duration duration) {
      Duration current = duration;
      if (current == _lastProgress) {
        _frozenTimer = Timer.periodic(const Duration(seconds: 2), (timer) {
          _frozenCount++;
          if (_frozenCount > 10) {
            _handleVideoEnd();
          }
        });
      } else {
        _frozenCount = 0;
        _lastProgress = duration;
        _frozenTimer?.cancel();
        _videoIsFrozen = false;
      }
    });
  }

  Timer? _timer;
  void _startTimer() {
    _stopTimer();
    // if only one screenSaver don't start timer (No rotation)
    if (widget.screenSavers.length < 2) return;

    // if type is video don't start timer (don't use timer)
    if (widget.screenSavers[_currentIndex].mediaType ==
        ScreenSaverMediaType.SCREEN_SAVER_MEDIA_TYPE_VIDEO) return;

    // if showing qrCode don't nextPage
    _timer = Timer.periodic(
        Duration(
            seconds: widget.screenSavers[_currentIndex].duration.toInt() == 0
                ? 5
                : widget.screenSavers[_currentIndex].duration.toInt()), (_) {
      if (!_isShowingQrCode) {
        jumpToNextPage();
      }
    });
  }

  Timer? _temporaryTime;
  Timer? _resetFrozenStateTime;
  bool _videoIsFrozen = true;
  void jumpToNextPage() {
    if (!_isInForeground) return;

    _resetFrozenStateTime?.cancel();
    _temporaryTime?.cancel();
    _controller.nextPage(
        duration: const Duration(milliseconds: 300), curve: Curves.easeInOut);

    // Restore the stuck state every 1 second in case the video gets stuck
    _resetFrozenStateTime = Timer.periodic(const Duration(seconds: 1), (timer) {
      _videoIsFrozen = true;
    });

    // Check every 20 seconds to prevent it from getting stuck
    _temporaryTime = Timer.periodic(const Duration(seconds: 20), (timer) {
      if (_videoIsFrozen) {
        _controller.nextPage(
            duration: const Duration(milliseconds: 300),
            curve: Curves.easeInOut);
        // cancel Time
        _temporaryTime?.cancel();
        _resetFrozenStateTime?.cancel();
        _videoIsFrozen = true;
      }
    });
  }

  void _stopTimer() {
    _timer?.cancel();
  }

  void _handleVideoEnd() {
    // if showing qrCode don't jump
    if (_isShowingQrCode) return;
    jumpToNextPage();
  }

  void openQrCode({required ScreenSaver screenSaver}) {
    // update _isShowingQrCode
    setState(() {
      _isShowingQrCode = true;
    });
    // report click cta for cubit
    context.read<ScreenSaverCubit>().reportScreenSaverEvent(
        screenSaverUuid: screenSaver.uuid,
        eventType: ScreenSaverEventType.SCREEN_SAVER_EVENT_TYPE_CLICK_CTA);
    // stop timer
    _stopTimer();
    // show qrCode
    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      backgroundColor: Colors.transparent,
      builder: (BuildContext context) {
        return QrCodeAlertWidget(
            data: screenSaver.cta,
            context: context,
            onClose: () {
              Navigator.pop(context);
              setState(() {
                _isShowingQrCode = false;
              });
              _startTimer();
              if (PlayerSingleton().player.state.completed) {
                _handleVideoEnd();
              }
            });
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return CarouselSlider(
      items: widget.screenSavers.map((screenSaver) {
        return InkWell(
          onTap: screenSaver.cta == ''
              ? () {}
              : () => openQrCode(screenSaver: screenSaver),
          child: screenSaver.mediaType ==
                  ScreenSaverMediaType.SCREEN_SAVER_MEDIA_TYPE_VIDEO
              ? CustomStack(
                  widget: VideoPlayer(
                    videoUrl: photoBaseUrl(screenSaver.url),
                  ),
                  screenSavers: widget.screenSavers)
              : CachedNetworkImage(
                  imageUrl: photoBaseUrl(screenSaver.url),
                  fit: BoxFit.cover,
                  width: 1.sw,
                  height: 1.sh,
                  imageBuilder: (context, imageProvider) {
                    return CustomStack(
                      screenSavers: widget.screenSavers,
                      widget: Container(
                        decoration: BoxDecoration(
                          image: DecorationImage(
                            image: imageProvider,
                            fit: BoxFit.cover,
                          ),
                        ),
                      ),
                    );
                  },
                  placeholder: (context, url) {
                    return CustomStack(
                      widget: const RotationLoadingImagePage(),
                      screenSavers: widget.screenSavers,
                      lineColor: Colors.transparent,
                      topBarBackgroundColor:
                          const Color(0xFF000000).withOpacity(0.1),
                      topBarForegroundColor:
                          const Color(0xFF263741).withOpacity(0.5),
                      touchToStartColor: const Color(0xFF9398A2),
                      circleCurrentColor: const Color(0xFF69BA00),
                      circleOldColor: const Color(0xFF69BA00).withOpacity(0.3),
                    );
                  },
                  errorWidget: (context, url, error) {
                    return CustomStack(
                      widget: const ContentFailedPage(),
                      screenSavers: widget.screenSavers,
                      lineColor: Colors.transparent,
                      topBarBackgroundColor:
                          const Color(0xFF000000).withOpacity(0.1),
                      topBarForegroundColor:
                          const Color(0xFF263741).withOpacity(0.5),
                      touchToStartColor: const Color(0xFF9398A2),
                      circleCurrentColor: const Color(0xFF69BA00),
                      circleOldColor: const Color(0xFF69BA00).withOpacity(0.3),
                    );
                  }),
        );
      }).toList(),
      carouselController: _controller,
      options: CarouselOptions(
        viewportFraction: 1,
        height: double.infinity,
        autoPlay: false,
        onPageChanged: (index, reason) {
          setState(() {
            _currentIndex = index;
          });
          context.read<ScreenSaverCubit>().updateCarousel(index);
          _startTimer();
          widget.screenSavers[index].mediaType ==
                  ScreenSaverMediaType.SCREEN_SAVER_MEDIA_TYPE_IMAGE
              ? PlayerSingleton().player.stop()
              : PlayerSingleton().player.play();
        },
      ),
    );
  }
}

class VideoPlayer extends StatefulWidget {
  final String videoUrl;
  const VideoPlayer({super.key, required this.videoUrl});

  @override
  State<VideoPlayer> createState() => _VideoPlayerState();
}

class _VideoPlayerState extends State<VideoPlayer> {
  @override
  void initState() {
    super.initState();
    PlayerSingleton().player.open(Media(widget.videoUrl));
  }

  @override
  Widget build(BuildContext context) {
    return Video(
      controller: PlayerSingleton().videoController,
      controls: NoVideoControls,
    );
  }
}
`

**Comment by junmingchen123** [comment]
Hello author, the problem still exists, the method is invalid. Where did I write it? Is there a problem? Could you please help me take a look? Thank you
