### ISSUE TITLE
[Bug Report][GNU/Linux]  Replacing with OpenUpwardsPageTransitionsBuilder cannot fixed my question

### ISSUE THREAD

**Issue by junmingchen123** [media-kit/media-kit#477]
Hello author, I used this, but after you mentioned it, it did not solve my problem. It's my code. Is there any problem? Can you help me take a look? Thank you

`
import 'package:flutter/material.dart';
import 'package:media_kit/media_kit.dart';
import 'package:media_kit_video/media_kit_video.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  MediaKit.ensureInitialized();
  runApp(
    MaterialApp(
      theme: ThemeData(
        pageTransitionsTheme: const PageTransitionsTheme(
          builders: {
            TargetPlatform.windows: OpenUpwardsPageTransitionsBuilder(),
            TargetPlatform.linux: OpenUpwardsPageTransitionsBuilder(),
            TargetPlatform.macOS: OpenUpwardsPageTransitionsBuilder(),
            TargetPlatform.iOS: OpenUpwardsPageTransitionsBuilder(),
            TargetPlatform.android: OpenUpwardsPageTransitionsBuilder(),
          },
        ),
      ),
      darkTheme: ThemeData(
        pageTransitionsTheme: const PageTransitionsTheme(
          builders: {
            TargetPlatform.windows: OpenUpwardsPageTransitionsBuilder(),
            TargetPlatform.linux: OpenUpwardsPageTransitionsBuilder(),
            TargetPlatform.macOS: OpenUpwardsPageTransitionsBuilder(),
            TargetPlatform.iOS: OpenUpwardsPageTransitionsBuilder(),
            TargetPlatform.android: OpenUpwardsPageTransitionsBuilder(),
          },
        ),
      ),
      home: const MyPage(),
    ),
  );
}

class PlayerSingleton {
  static final PlayerSingleton _instance = PlayerSingleton._internal();
  factory PlayerSingleton() => _instance;
  PlayerSingleton._internal() {
    player = Player();
    videoController = VideoController(player);
  }

  late final Player player;
  late final VideoController videoController;
}

class MyPage extends StatefulWidget {
  const MyPage({Key? key}) : super(key: key);

  @override
  State<MyPage> createState() => _MyPageState();
}

class _MyPageState extends State<MyPage> {
  @override
  void dispose() {
    // don't work
    print('dispose-----------------------------');
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    // don't work
    PlayerSingleton().player.play();
    return Scaffold(
      body: Stack(
        children: [
          const VideoPlayer(
            'https://user-images.githubusercontent.com/28951144/229373709-603a7a89-2105-4e1b-a5a5-a6c3567c9a59.mp4',
          ),
          Positioned(
            bottom: 20,
            child: SizedBox(
              width: MediaQuery.of(context).size.width,
              child: Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  ElevatedButton(
                      onPressed: () {
                        // can't stop player, so i stop it like my project stop in dispose
                        PlayerSingleton().player.stop();
                        Navigator.push(
                            context,
                            MaterialPageRoute(
                                builder: (context) => Scaffold(
                                      body: Center(
                                        child: ElevatedButton(
                                          onPressed: () {
                                            Navigator.pop(context);
                                          },
                                          child: const Text('Back'),
                                        ),
                                      ),
                                    )));
                      },
                      child: const Text('Stop')),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class VideoPlayer extends StatefulWidget {
  final String resource;
  const VideoPlayer(this.resource, {super.key});

  @override
  State<VideoPlayer> createState() => _VideoPlayerState();
}

class _VideoPlayerState extends State<VideoPlayer> {
  @override
  void initState() {
    super.initState();
    PlayerSingleton().player.open(Media(widget.resource));
  }

  @override
  void dispose() {
    // don't work
    print('dispose--++++++++--');
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Video(
      controller: PlayerSingleton().videoController,
      controls: NoVideoControls,
    );
  }
}

`

**Comment by alexmercerind** [comment]
I'll unfortunately need a minimal reproducible sample to work.

The code that you shared on other thread worked correctly for me.

**Comment by junmingchen123** [comment]
Thank you again for your review. I will provide it, please

**Comment by junmingchen123** [comment]
Hello author, I have modified the code. My problem is that you can now take a look. The video is playing on the homepage. After the homepage enters the background, I play player. stop(), but when I return to the homepage, the init method does not work, and the build method does not work. The video is stuck and cannot be played. What should I do? Thank you

`
import 'package:flutter/material.dart';
import 'package:media_kit/media_kit.dart';
import 'package:media_kit_video/media_kit_video.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  MediaKit.ensureInitialized();
  runApp(
    MaterialApp(
      theme: ThemeData(
        pageTransitionsTheme: const PageTransitionsTheme(
          builders: {
            TargetPlatform.windows: OpenUpwardsPageTransitionsBuilder(),
            TargetPlatform.linux: OpenUpwardsPageTransitionsBuilder(),
            TargetPlatform.macOS: OpenUpwardsPageTransitionsBuilder(),
            TargetPlatform.iOS: OpenUpwardsPageTransitionsBuilder(),
            TargetPlatform.android: OpenUpwardsPageTransitionsBuilder(),
          },
        ),
      ),
      darkTheme: ThemeData(
        pageTransitionsTheme: const PageTransitionsTheme(
          builders: {
            TargetPlatform.windows: OpenUpwardsPageTransitionsBuilder(),
            TargetPlatform.linux: OpenUpwardsPageTransitionsBuilder(),
            TargetPlatform.macOS: OpenUpwardsPageTransitionsBuilder(),
            TargetPlatform.iOS: OpenUpwardsPageTransitionsBuilder(),
            TargetPlatform.android: OpenUpwardsPageTransitionsBuilder(),
          },
        ),
      ),
      home: const MyPage(),
    ),
  );
}

class PlayerSingleton {
  static final PlayerSingleton _instance = PlayerSingleton._internal();
  factory PlayerSingleton() => _instance;
  PlayerSingleton._internal() {
    player = Player();
    videoController = VideoController(player);
  }

  late final Player player;
  late final VideoController videoController;
}

class MyPage extends StatefulWidget {
  const MyPage({Key? key}) : super(key: key);

  @override
  State<MyPage> createState() => _MyPageState();
}

class _MyPageState extends State<MyPage> {
  @override
  void dispose() {
    // don't work
    print('dispose-----------------------------');
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    // don't work
    PlayerSingleton().player.play();
    return Scaffold(
      body: Stack(
        children: [
          const VideoPlayer(
            'https://user-images.githubusercontent.com/28951144/229373709-603a7a89-2105-4e1b-a5a5-a6c3567c9a59.mp4',
          ),
          Positioned(
            bottom: 20,
            child: SizedBox(
              width: MediaQuery.of(context).size.width,
              child: Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  ElevatedButton(
                      onPressed: () {
                        // can't stop player, so i stop it like my project stop in dispose
                        PlayerSingleton().player.stop();
                        Navigator.push(
                            context,
                            MaterialPageRoute(
                                builder: (context) => Scaffold(
                                      body: Center(
                                        child: ElevatedButton(
                                          onPressed: () {
                                            Navigator.pop(context);
                                          },
                                          child: const Text('Back'),
                                        ),
                                      ),
                                    )));
                      },
                      child: const Text('Stop')),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class VideoPlayer extends StatefulWidget {
  final String resource;
  const VideoPlayer(this.resource, {super.key});

  @override
  State<VideoPlayer> createState() => _VideoPlayerState();
}

class _VideoPlayerState extends State<VideoPlayer> {
  @override
  void initState() {
    super.initState();
    PlayerSingleton().player.open(Media(widget.resource));
  }

  @override
  void dispose() {
    // don't work
    print('dispose--++++++++--');
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Video(
      controller: PlayerSingleton().videoController,
      controls: NoVideoControls,
    );
  }
}

`

**Comment by alexmercerind** [comment]
> But when I return to the homepage, the init method does not work, and the build method does not work.

That's how Flutter works.

I can't reproduce, no freeze of any kind can be reproduced.
