### ISSUE TITLE
video_controller_set_size is not  available on Android 

### ISSUE THREAD

**Issue by IrfanHangingPanda** [media-kit/media-kit#479]
Getting Error -  Unsupported operation: [AndroidVideoController.setSize] is not available on Android

Can you please tell me what to do for ANDROID for video_controller_set_size support??
But in IOS Working fine

**Comment by alexmercerind** [comment]
Hi!

As the error states, `VideoController.setSize` API is unavailable for Android:

https://github.com/media-kit/media-kit/blob/8926ede69cb11aca45e9ea2b26428202e82ea5de/media_kit_video/lib/src/video_controller/android_video_controller/real.dart#L338-L346

If you're familiar with it's use-case, you can alternatively try out `VideoControllerConfiguration.scale` on Android:

https://github.com/media-kit/media-kit/blob/8926ede69cb11aca45e9ea2b26428202e82ea5de/media_kit_video/lib/src/video_controller/platform_video_controller.dart#L98-L102

To reduce the render size, pass a value less than 1.0. As a result, small improvement in performance may be seen. Although: Performance is already very significant & mostly dependent on hardware itself.

Thanks!

**Comment by alexmercerind** [comment]
The `scale` does not work on other platforms at the moment, due to lack of time & other higher priority issues.
