### ISSUE TITLE
 [android] java.io.FileNotFoundException: No content provider

### ISSUE THREAD

**Issue by mhkarami** [media-kit/media-kit#482]
[Android Platform]
I try to open video files when the user selects the `'openwith'` button in Android device file manager and then select my app to play the video.
I tried some libraries to get the file uri . all of them gave me the same uri like `"content://com.mi.android.globalfileexplorer.myprovider/external_files/Download/file_name.mp4"` when i try open media file with :     
```
final playable = Media(uri);
await player.open(playable);
```
it trows exception: 
```
W/System.err(16859): java.io.FileNotFoundException: No content provider: content://com.mi.android.globalfileexplorer.myprovider/external_files/Download/file_name.mp4
W/System.err(16859): 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1994)
W/System.err(16859): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1823)
W/System.err(16859): 	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1656)
W/System.err(16859): 	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1603)
W/System.err(16859): 	at com.alexmercerind.mediakitandroidhelper.MediaKitAndroidHelper.openFileDescriptorJava(MediaKitAndroidHelper.java:43)
```
i tried libraries to convert the uri to file path
```
uri_content
uri_to_file
```
or other ways to get file of that :
`File.fromUri(uri)`
but all of them trows exception.
is there any way to play that uri ?

**Comment by alexmercerind** [comment]
That's a content URI, you don't have permissions to it (or haven't requested them). You must learn about Android development e.g. permissions, scoped storage, storage access framework etc. It's entirely separate topic of discussion.

Off-Topic:

- I implemented [opening of file(s) (`content://`) through intents on Android in Harmonoid.](https://github.com/harmonoid/harmonoid/blob/6732720e6736d1ca3f5fab331d627c0dba760a48/android/app/src/main/kotlin/com/alexmercerind/harmonoid/MainActivity.kt#L128-L207)
- [package:file_picker](https://pub.dev/packages/file_picker) also locally caches file first. It's not possible to use `content://` directly in Flutter.

As a cross-platform project, better is to work with more "universal" approaches.

**Comment by alexmercerind** [comment]
The content:// URI however, do work as intended, as long as you have permission:

- https://github.com/media-kit/media-kit/issues/252

Probably declare & prompt new Android 13 permissions:

https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions
