### ISSUE TITLE
Unhandled Exception: Exception: Cannot find libmpv-2.dll in your system %PATH%.

### ISSUE THREAD

**Issue by oniangel12933** [media-kit/media-kit#484]
full error console:
`[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Cannot find libmpv-2.dll in your system %PATH%. One way to deal with this is to ship libmpv-2.dll with your compiled executable or script in the same directory.
#0      NativeLibrary.ensureInitialized (package:media_kit/src/player/native/core/native_library.dart:78:9)
#1      nativeEnsureInitialized (package:media_kit/src/player/native/player/real.dart:47:17)
#2      MediaKit.ensureInitialized (package:media_kit/src/media_kit.dart:24:9)
#3      main (package:megatv/main.dart:38:12)
<asynchronous suspension>`

Here is my flutter info:

[√] Flutter (Channel stable, 3.13.3, on Microsoft Windows [Version 10.0.19044.3086], locale en-US)
    • Flutter version 3.13.3 on channel stable at D:\sdk\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2524052335 (11 days ago), 2023-09-06 14:32:31 -0700
    • Engine revision b8d35810e9
    • Dart version 3.1.1
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\OniAn\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = C:\Users\OniAn\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2019 16.11.30)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.34031.81
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.82.2)
    • VS Code at C:\Users\OniAn\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.72.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.3086]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 116.0.5845.142
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 116.0.1938.76

[√] Network resources
    • All expected network resources are available.

**Comment by Sikander-Sikki** [comment]
same issue!! any solution found?

**Comment by alexmercerind** [comment]
Have you installed as mentioned in the README?

**Comment by alexmercerind** [comment]
You can try our example application.

**Comment by alexmercerind** [comment]
A first step can be to try if the provided demo application works.
