### ISSUE TITLE
[Bug Report][Web] player.stream.audioDevices not working on web

### ISSUE THREAD

**Issue by IvoB1987** [media-kit/media-kit#485]
When listening to player.stream.audioDevices on web it never gets an event. Is changing listening to and changing audio devices not possible on web or is this a bug?

**Comment by alexmercerind** [comment]
It's not implemented for web. I'm not familiar with any web API which allows this.

**Comment by alexmercerind** [comment]
The web backend has number of limitations compared to native platforms.

This is due to browser environment & have been mentioned in "Notes" section of the README.
