### ISSUE TITLE
media_kit: x86 JAR verification failed.

### ISSUE THREAD

**Issue by lee-stars** [media-kit/media-kit#488]
# dependencies 
 media_kit: ^1.1.7
  media_kit_video: ^1.1.8
  media_kit_libs_video: ^1.0.1

# Error Info
```
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\10370\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\media_kit_libs_android_video-1.3.3\android\build.gradle' line: 111

* What went wrong:
A problem occurred evaluating project ':media_kit_libs_android_video'.
> media_kit: x86 JAR verification failed.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Exception: Gradle task assembleDebug failed with exit code 1
```

**Comment by alexmercerind** [comment]
Hi!

Perform a flutter clean & try again. You may refer to our CI run to confirm that everything is working fine.

Thanks!

**Comment by lee-stars** [comment]
Hello, thank you for your reply. I tried again according to your method, but the problem has not been solved

> Hi!
> 
> Perform a flutter clean & try again. You may refer to our CI run to confirm that everything is working fine.
> 
> Thanks!

**Comment by lee-stars** [comment]
> Hi!
> 
> Perform a flutter clean & try again. You may refer to our CI run to confirm that everything is working fine.
> 
> Thanks!

Sorry to bother you, I have found the problem, which is caused by my local network environment. After shutting down the network proxy, I tried many times and finally succeeded

**Comment by alexmercerind** [comment]
Glad to hear. Your machine must be able to access GitHub in order to fetch dependencies.

**Comment by EchoSerendipity** [comment]
`A problem occurred evaluating project ':media_kit_libs_android_video'.
> media_kit: arm64-v8a JAR verification failed.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Exception: Gradle task assembleDebug failed with exit code 1`

Same thing happens
