### ISSUE TITLE
[Question] IOS fatal error: 'mpv/client.h' file not found

### ISSUE THREAD

**Issue by yuhaya** [media-kit/media-kit#497]
Could not build the precompiled application for the device.
```
Lexical or Preprocessor Issue (Xcode): 'mpv/client.h' file not found
/Users/rustyu/.pub-cache/hosted/pub.dev/media_kit_native_event_loop-1.0.7/src/media_kit_native_event_loop.h:15:9
```

**Comment by alexmercerind** [comment]
Build & unit-tests for all platforms succeed:

https://github.com/media-kit/media-kit/actions/runs/6316539195/job/17151392460

Check your internet connection.

**Comment by dev-xdyang** [comment]
this issue maybe work: https://github.com/media-kit/media-kit/issues/71
