### ISSUE TITLE
How to add headers to SubtitleTrack.uri

### ISSUE THREAD

**Issue by Noobware1** [media-kit/media-kit#499]
how can i add headers to the SubtitleTrack.uri constructor because i need to pass in a cookie headers for the request.

**Comment by alexmercerind** [comment]
Hi @Noobware1,

You should manually fetch subtitles using [`package:http`](https://pub.dev/packages/http) & use them through `SubtitleTrack.data`.

Passing HTTP headers through `SubtitleTrack.uri` is unsupported (& will probably never work on web).

Thanks!
