### ISSUE TITLE
Error while loading libmpv.so.1 on Fedora Linux

### ISSUE THREAD

**Issue by Airyzz** [media-kit/media-kit#507]
Apps which depend on media-kit are unable to open on Fedora Linux
Maybe I installed libmpv incorrectly?

```
[user@fedora]$ ldconfig -p | grep libmpv
	libmpv.so.2 (libc6,x86-64) => /lib64/libmpv.so.2
[user@fedora]$ ./media_kit_test 
./media_kit_test: error while loading shared libraries: libmpv.so.1: cannot open shared object file: No such file or directory
```

**Comment by birros** [comment]
Can you check the links in your binary:

```shell
$ ldd ./media_kit_test
```

The binary seems to be linked to `libmpv.so.1` and not `libmpv.so.2`.

**Comment by Airyzz** [comment]
Yea its definitely linked to `libmpv.so.1`

 I saw [here](https://github.com/media-kit/media-kit/blob/ed353ad0ecbdd3882a994e813499da283c4fac35/media_kit/lib/src/player/native/core/native_library.dart#L55) it looks like it should be trying to find `libmpv.so.2` as well, but i guess since the app doesnt launch it never gets to this point?

Im not super familiar with the linking process unfortunately, so maybe im mistaken, but is it possible to not have this reference to `libmpv.so.1` baked in, so that even if libmpv isnt installed at all the flutter app still works, albeit without any video functionality?

I was just testing the 'Demo' files from [here](https://pub.dev/packages/media_kit)

Its strange that different distros are using differently named files, is there anything that can be done flutter side to work around this? It would be a shame to have to build multiple different linux versions just for this

**Comment by Airyzz** [comment]
I did find that if I just create a link like so: `sudo ln /lib64/libmpv.so.2 /lib64/libmpv.so.1` the app was able to open, but was not able to play the example videos: `flutter: Failed to initialize a decoder for codec 'h264'.` but this may be a seperate issue?

**Comment by alexmercerind** [comment]
> I saw [here](https://github.com/media-kit/media-kit/blob/ed353ad0ecbdd3882a994e813499da283c4fac35/media_kit/lib/src/player/native/core/native_library.dart#L55) it looks like it should be trying to find libmpv.so.2 as well, but i guess since the app doesnt launch it never gets to this point?

That only concerns the dart:ffi interop. media_kit_video plugin "natively" links to the shared library:

https://github.com/media-kit/media-kit/blob/ed353ad0ecbdd3882a994e813499da283c4fac35/media_kit_video/linux/CMakeLists.txt#L56


> Is it possible to not have this reference to libmpv.so.1 baked in, so that even if libmpv isnt installed at all the flutter app still works, albeit without any video functionality?

Yes. If you don't add media_kit_video.

> It's strange that different distros are using differently named files, is there anything that can be done flutter side to work around this? It would be a shame to have to build multiple different linux versions just for this.

It's not related to Flutter. That's just how executables work. The change in naming is done by mpv to handle breaking changes in their API.

**Comment by alexmercerind** [comment]
Sounds like a distribution problem to me.

> I did find that if I just create a link like so: `sudo ln /lib64/libmpv.so.2 /lib64/libmpv.so.1` the app was able to open, but was not able to play the example videos: `flutter: Failed to initialize a decoder for codec 'h264'.` but this may be a seperate issue?

It's not an issue in media_kit, probably your installation. If mpv can open the same file, media_kit will too. That's just how GNU/Linux works, shared libraries actually being "shared" between packages.

**Comment by birros** [comment]
> It would be a shame to have to build multiple different linux versions just for this

It's the principle of Linux distributons, you have to compile the binary according to its libs and conventions.

If you don't want to bother with this, I suggest you to try [Flatpak](https://flatpak.org/), the equivalent of Docker for graphic applications.
You embed libs and binaries linked together in your "container", eliminating the linking problem.

The `media-kit` demo is compiled on an Ubuntu CI, which can cause this kind of linking problem.

**Comment by Airyzz** [comment]
Thank you, this is useful information! Yes I was planning on setting up flatpak. So if i am understanding correctly, if I want to be able to run it not inside a container, I will need to build the app on Fedora itself so it picks up the correct library?

**Comment by birros** [comment]
> So if i am understanding correctly, if I want to be able to run it not inside a flatpak container, I will need to build the app on Fedora itself so it picks up the correct library?

Yep, by building it on the targeted distribution, linking will be done at build time and will be valid at runtime.

**Comment by Airyzz** [comment]
Thank you all!
