### ISSUE TITLE
Frame stream

### ISSUE THREAD

**Issue by FranMaric** [media-kit/media-kit#509]
I have a use case where I need to overlay some widgets over the video. That overlay changes on every frame so I need a way to get the information when a new frame is shown in the video player to change the overlay.

Player class has a stream property that can give me the current position and duration, which could be used to calculate the current frame but proved unreliable (sometimes I would get negative values). 

It would be nice to have a Stream<int> frameStream on Player.stream where the integer indicates the current frame index.

Would this be possible to implement? If not can you suggest a solution to how to do it in my own code?

Thank you in advance for any help!

**Comment by birros** [comment]
I'm not a Flutter expert, but what you're asking seems tricky. Even if we expose this type of stream, there will always be a delay of a few milliseconds between the emission and reception of the event.

You should be aware that it is possible to display a transparent, semi-opaque or blurred overlay over a `Video` widget.

Also, multiple `Video` widgets can be created from a single `VideoController`.

Finally, if none of these possibilities suit you, it may be possible to override Flutter's `Texture` widget… maybe…

**Comment by alexmercerind** [comment]
No. There's no plan for this. This package is for playing video & audio; that's all for now.

Even notifying Dart about every frame draw will be very expensive, there's a reason that's done in native code entirely.


> Would this be possible to implement? If not can you suggest a solution to how to do it in my own code?

You are free to play around with the [`NativePlayer.observeProperty` API](https://github.com/media-kit/media-kit/pull/350). I fear even if you implement this, it won't be reliable, like @birros said there'll always be some delay or race etc.

<hr>

One more thing I'd like to clarify along the way: Please don't hope there'll ever be a "frame stream" where you can access raw pixel data of current video frame (say as `Uint8List`), that's not how video is rendered internally. It's entirely done on the GPU & uses relevant structures. Secondly, even if we encode it into pixel-buffer for sending/accessing it in Dart, performance will be killed.

**Comment by alexmercerind** [comment]
IIRC, web has some API that allows to capture <video> frame & draw over <canvas>... but it takes very-high CPU time.

**Comment by FranMaric** [comment]
Thank you for your answers! Could it be possible to write a shader that would have the information which frame is currently shown?

**Comment by johannphilippe** [comment]
One feature that would be interesting though would be some kind of audio stream or callback - (a way to access audio buffer when a new bloc is about to be sent to outputs) - allowing to process audio samples without loosing video/audio sync.
Would that be something that could be imagined ?
