### ISSUE TITLE
HTTP headers are not supported on web. Documentation?

### ISSUE THREAD

**Issue by gokhanmeteerturk** [media-kit/media-kit#510]
Switched from another video player library to this one because the documentation stated that it supports HTTP headers.

Now I'm getting "HTTP headers are not supported on web".

Apparently, media-kit does not actually support cross-platform custom headers:

https://github.com/media-kit/media-kit/blob/ed353ad0ecbdd3882a994e813499da283c4fac35/media_kit/lib/src/models/media/media_web.dart#L81

Would be nice to have this feature on the web, and until then, would be great to have a notice about this on README.

**Comment by alexmercerind** [comment]
> It would be nice to have this feature on the web.

We didn't implement the web browser you use. Besides this, there are other concerns as well e.g. CORS.

On native platforms, we have more freedom & thus more features.

The documentation mentions following:

![](https://github.com/media-kit/media-kit/assets/28951144/c7daa06d-f866-46f5-b7ba-099500a90c18)
