### ISSUE TITLE
Widevine, FairPlay and Clearkey DRM implementation

### ISSUE THREAD

**Issue by GitGud31** [media-kit/media-kit#511]
Hi, I was wondering how/if we can configure **DRM** to play encrypted videos using this package ? 

EDIT: question clarification.

**Comment by alexmercerind** [comment]
Hi!

We use a stripped variant of mpv/FFmpeg to power media playback on native platforms

I think there's one option that we can expose:

https://github.com/mpv-player/mpv/issues/8286#issuecomment-729846059

You are free to try out, we can't proceed without any sample. Regardless, closing as duplicate:

- #381

**Comment by alexmercerind** [comment]
At the moment, core-features & cross-platform is focus.
