### ISSUE TITLE
Load limited buffer size

### ISSUE THREAD

**Issue by Kevin301099** [media-kit/media-kit#515]
when i play video full video load and store in ram. so ram will increasing rapidly. i want to load limited buffer of video at a time. so only chunks video store in memory and ram usage will decrease.

**Comment by Kevin301099** [comment]
this kind of option available on better_player
<img width="1029" alt="Screenshot 2023-10-05 at 4 05 51 PM" src="https://github.com/media-kit/media-kit/assets/49025655/1389767d-3733-4b56-9c1c-442d2d5a7de6">

**Comment by alexmercerind** [comment]
There's a `NativePlayer.setProperty` API (search other issues) that you can use to set backend (e.g. libmpv, web) specific properties entirely within Dart.

**Comment by alexmercerind** [comment]
I forgot to update the comment; it's 128 MB by default, you can try reducing back to 32 MB.
