### ISSUE TITLE
[Bug Report] video_player_media_kit: ^1.0.0+1 Unsupported operation: Infinity or NaN toInt

### ISSUE THREAD

**Issue by Fantuan-cell** [media-kit/media-kit#517]
Device:
Android 8.0

**dependencies:**
```
  video_player_media_kit: ^1.0.0+1
  media_kit_libs_android_video: any 
  media_kit_libs_ios_video: any   
```
myCode
```
  @override
  void onInit() {
    // setHorizontal();
    VideoPlayerMediaKit.ensureInitialized(
      android: true,
      iOS: true,
    );
    controller = VideoPlayerController.networkUrl(
      Uri.parse(""),
      httpHeaders: {
        "User-Agent":
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36",
      },
    );}

```
![image](https://github.com/media-kit/media-kit/assets/53990888/ee66af02-b3b4-46ba-bd79-d2b9aa3c21a6)

_LinearProgressIndicatorState#08ee6(ticker inactive)):
Unsupported operation: Infinity or NaN toInt

 I use video_player,When I finish initializing ,   An error occurred in the VideoProgressIndicator
![image](https://github.com/media-kit/media-kit/assets/53990888/c6899d88-a07d-4de3-aa17-33e1f4baeefe)
![image](https://github.com/media-kit/media-kit/assets/53990888/55fe1630-6131-4227-9523-313102125399)

**Comment by alexmercerind** [comment]
Hi @Fantuan-cell,

[video_player:media_kit: ^1.0.0](https://pub.dev/packages/video_player_media_kit) has been published. It should resolve your issue.

Thanks!
