### ISSUE TITLE
How to active subtitle tracks in media kit?

### ISSUE THREAD

**Issue by mohsenjim** [media-kit/media-kit#518]
Hi! Thanks for media kit! very powerful and perfect plugin for flutter.

I can't active some subtitles and audio that attached to mkv video. media kit test codes just play video track. 
I need soon as soon 😊 

Thank You ❤️

**Comment by alexmercerind** [comment]
Hi @mohsenjim,

You can refer to following sections in the README:
- https://github.com/media-kit/media-kit#select-video-audio-or-subtitle-track
- https://github.com/media-kit/media-kit#load-external-subtitle-track
- https://github.com/media-kit/media-kit#load-external-audio-track

You can also use [`TrackSelector` widget](https://github.com/media-kit/media-kit/blob/8554f23f688f67b3f2b23d47579847ac107e63d3/media_kit_test/lib/common/widgets.dart#L10-L155) as a reference.

Thanks!

**Comment by mohsenjim** [comment]
I tried to use it but 
Which is page of media kit tool usable it?
source_native.dart?
or
page of play videos?

Can you write example in media kit test?

**Comment by alexmercerind** [comment]
https://github.com/media-kit/media-kit/blob/8554f23f688f67b3f2b23d47579847ac107e63d3/media_kit_test/lib/common/widgets.dart#L10-L155

**Comment by mohsenjim** [comment]
I put these codes in widget.dart?

`List<VideoTrack> videos = player.state.tracks.video;
List<AudioTrack> audios = player.state.tracks.audio;
List<SubtitleTrack> subtitles = player.state.tracks.subtitle;

// Get notified as [Stream]:
player.stream.tracks.listen((event) {
  List<VideoTrack> videos = event.video;
  List<AudioTrack> audios = event.audio;
  List<SubtitleTrack> subtitles = event.subtitle;
});`

**Comment by mohsenjim** [comment]
Thank you 😊
✅ for use this class just it in scaffold:  TracksSelector(player: player),
