### ISSUE TITLE
[Question] media_kit Can support playing part of a specified interval for a media file

### ISSUE THREAD

**Issue by Titans1001** [media-kit/media-kit#523]
media_kit Specifies whether to support playing part of a specified interval of a media file？
For example, if the total length of a media file is 120 seconds, you can play it for only 30 to 100 seconds。

**Comment by alexmercerind** [comment]
The current API can allow you to programmatically achieve this; there's no built-in feature for this.

**Comment by alexmercerind** [comment]
Implemented:
- #581
