### ISSUE TITLE
How to prevent the video control bar from automatically hiding? 

### ISSUE THREAD

**Issue by jihchao** [media-kit/media-kit#529]
How to prevent the video control bar from automatically hiding? I want to manually control it to hide, Because I customized a button, clicking it will display the Overlay layer. If the control bar is automatically hidden at this time, it will cause my Overlay layer to be destroyed.

**Comment by alexmercerind** [comment]
Just build your custom controls if you need higher level of modification.

It makes no sense to permanently show controls on top of the video.
