### ISSUE TITLE
[Bug Report][Android] HLS may cause video/audio de-sync or unexpected jump

### ISSUE THREAD

**Issue by Noobware1** [media-kit/media-kit#530]
media_kit: ^1.1.8+2                              
media_kit_video: ^1.2.1                         
media_kit_libs_video: ^1.0.3

I tried playing a video from a uri in my app and example app provided and notice when the video is played the video duration is automatically skipped to 5 to 10 seconds ahead but the audio doesn't, causing them to be not in sync this unusual gap is not intended the video should start from 0 duration and i have tested it on mx video player and vlc it's plays just fine

Here is a this uri I was trying to play https://eno.tendoloads.com/_v6/925c615330f0330f013d807573b7ea54e706d2962cad28521163ad2702a56a72b2f3dad103b9f54d9131b30ad60341e4853351048eb05138134ddc4a4a1f65a36ac70736150e6781187bb877efc03978a4c5b19f0d296a5da0048da8da5d8a2f1aeb9632f8a538e1004b5a9f9bb56139371b0540410eb2112cfcfd3f69ebb3cf/master.m3u8

**Comment by alexmercerind** [comment]
Android?

**Comment by Noobware1** [comment]
Yes

**Comment by alexmercerind** [comment]
Hi @Noobware1,

There's a workaround for HLS streams on Android, that you can use:

```dart
late final Player player = Player();
late final VideoController controller = VideoController(
  player,
  configuration: const VideoControllerConfiguration(
    // NOTE:
    androidAttachSurfaceAfterVideoParameters: false,
  ),
);
```

Set `androidAttachSurfaceAfterVideoParameters` to `false`. Let me know if this works; for me it does.

Thanks!
