### ISSUE TITLE
[Web] Asset not working

### ISSUE THREAD

**Issue by moinkhan780** [media-kit/media-kit#531]
In web asset is working fine in debug mode but in release mode its not working.

**Comment by dasaintgray** [comment]
Even Windows Desktop App, in debug mode it's working but it production  or release mode nothing display

**Comment by alexmercerind** [comment]
> Even Windows Desktop App, in debug mode it's working but it production or release mode nothing display

ADD THE ASSET TO YOUR PUBSPEC.YAML.

**Comment by alexmercerind** [comment]
The web is a known issue & under progress.

**Comment by moinkhan780** [comment]
Any how this is working for me in production and debug BOTH. I set the "play" to "true" then after i call pause . so it will work like this. i don't know its is a good way or not.

`import 'package:flutter/material.dart';
import 'package:media_kit/media_kit.dart';
import 'package:media_kit_video/media_kit_video.dart';

class VideoPlayWidget extends StatefulWidget {
  final String videoUrl;
  const VideoPlayWidget({Key? key, required this.videoUrl}) : super(key: key);

  @override
  State<VideoPlayWidget> createState() => _VideoPlayWidgetState();
}

class _VideoPlayWidgetState extends State<VideoPlayWidget> {
  bool isLoading = false;
  // Create a [Player] to control playback.
  late final player = Player();
  // Create a [VideoController] to handle video output from [Player].
  late final controller = VideoController(player);

  @override
  void initState() {
    super.initState();
    player.open(Media(widget.videoUrl), play: true);
    player.pause();
  }

  @override
  void dispose() {
    super.dispose();
    player.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return ClipRRect(
      borderRadius: BorderRadius.circular(10),
      child: Container(
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(10),
          border: Border.all(width: 6, color: const Color(0xff00645e)),
        ),
        child: AspectRatio(
          aspectRatio: 16 / 9,
          child: Video(controller: controller),
        ),
      ),
    );
  }
}
`

**Comment by alexmercerind** [comment]
It should work both ways... Just make sure that you use asset like `asset:///asset/videos/bee.mp4` & add it in pubspec.yaml.

**Comment by alexmercerind** [comment]
> I set the "play" to "true" then after i call pause . so it will work like this.

Doesn't matter. This "hack" shouldn't be required & I don't think changes anything at all.

**Comment by moinkhan780** [comment]
> It should work both ways... Just make sure that you use asset like `asset:///asset/videos/bee.mp4` & add it in pubspec.yaml.

I tried already this as you mention but no luck. it continuously loading in iphone safari browser

**Comment by alexmercerind** [comment]
> I tried already this as you mention but no luck. it continuously loading in iphone safari browser

That's how web-browsers work. You can't play a video before there's a user by the user in the page:

https://developer.chrome.com/blog/autoplay

I'll add a `muted` attribute to `PlayerConfiguration` to allow this, because muted videos can auto-play.

**Comment by moinkhan780** [comment]
> > I tried already this as you mention but no luck. it continuously loading in iphone safari browser
> 
> That's how web-browsers work. You can't play a video before there's a user by the user in the page:
> 
> https://developer.chrome.com/blog/autoplay
> 
> I'll add a `muted` attribute to `PlayerConfiguration` to allow this, because muted videos can auto-play.

Thank you very much I will look into this. Btw the package is very great 🥇

**Comment by alexmercerind** [comment]
Like I said in earlier comment, I can confirm that assets are not working on web in release mode. Give me a while to resolve.

**Comment by alexmercerind** [comment]
Hi! 

A new version has been released, please refer to the ["Installation" section in the README](https://github.com/media-kit/media-kit/blob/main/README.md#installation).

**Comment by alexmercerind** [comment]
Now, assets work correctly on web in release mode. Also: A new parameter `PlayerConfiguration.muted` has been added.

Thanks!
