### ISSUE TITLE
Null check operator used on a null value. Error thrown while dispatching a pointer event. Causing Crashes

### ISSUE THREAD

**Issue by usman615** [media-kit/media-kit#532]
**MaterialSeekBarState.onPointerMove**

Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError
Null check operator used on a null value. Error thrown while dispatching a pointer event.

error on this line: package:media_kit_video/media_kit_video_controls/src/controls/material.dart:1180

getting crashes on oppo mobile

![image](https://github.com/media-kit/media-kit/assets/69667190/65b60033-53c3-410e-b57a-5ea7dcfeb6b6)

**Comment by alexmercerind** [comment]
It's not a crash.

**Comment by usman615** [comment]
Brother but I'm getting crash when skip the duration through seekbar

**Comment by alexmercerind** [comment]
From [Wikipedia](https://en.wikipedia.org/wiki/Crash_(computing)): "A crash, or system crash, occurs when a computer program such as a [software application](https://en.wikipedia.org/wiki/Software_application) or an [operating system](https://en.wikipedia.org/wiki/Operating_system) stops functioning properly and [exits](https://en.wikipedia.org/wiki/Exit_(system_call))."

**Comment by usman615** [comment]
Ok thanks, Hitesh brother

**Comment by alexmercerind** [comment]
It still is a situation that should likely be handled. Keeping open so that it stays on top of my head.

**Comment by alexmercerind** [comment]
Hi! 

A new version has been released, please refer to the ["Installation" section in the README](https://github.com/media-kit/media-kit/blob/main/README.md#installation).
