### ISSUE TITLE
Please provide a way to set a custom color for CircularProgressIndicator

### ISSUE THREAD

**Issue by PawlikMichal25** [media-kit/media-kit#535]
Currently the library is always using `Color(0xFFFFFFFF)` which isn't universally suitable.

**Comment by alexmercerind** [comment]
Hi @PawlikMichal25,

You may provide a custom builder for the buffering indicator (to replace the default `CircularProgressIndicator` one):

https://github.com/media-kit/media-kit/blob/b4a851650602c9b55a6bfb5412b28655f34b65aa/media_kit_video/lib/media_kit_video_controls/src/controls/material.dart#L142-L143

Please refer:

- https://github.com/media-kit/media-kit#use--modify-video-controls

Thanks!

**Comment by SP4RKiOP** [comment]
can we add % progress indicator? (8hrs until using and implementing this package in my flutter app). I have customized the player theme and it would be great if this is possible.

**Comment by abdelaziz-mahdy** [comment]
you pass your custom progress indicator and get the percentage using the changes in this pr https://github.com/media-kit/media-kit/pull/789, you will need to use the code from github

**Comment by SP4RKiOP** [comment]
Appreciate the fast response!!. Thanks I’ll try and let you know

**Comment by SP4RKiOP** [comment]
i have added those lines to the package in my project.
how do i call it here in MaterialVideoControlsTheme :
![image](https://github.com/user-attachments/assets/e675e591-6924-4ef9-85a0-a50be45c9055)

**Comment by abdelaziz-mahdy** [comment]
Glad you got it 😊

**Comment by SP4RKiOP** [comment]
Last question. Since i have edited the package files itself. will it survive IDE restart or anything? and what happens when package gets updated or i run flutter pub get. maybe dumb questions but it's just 5 days i am into flutter.

**Comment by abdelaziz-mahdy** [comment]
> Last question. Since i have edited the package files itself. will it survive IDE restart or anything? and what happens when package gets updated or i run flutter pub get. maybe dumb questions but it's just 5 days i am into flutter. 
> 

You edited the package itself? You can get the GitHub changes using pubspec

**Comment by abdelaziz-mahdy** [comment]
@SP4RKiOP https://github.com/media-kit/media-kit/issues/947#issuecomment-2381380594
This is for reference

**Comment by SP4RKiOP** [comment]
@abdelaziz-mahdy Thanks for pointing this. got to learn new today. Done changing pubspec, tested working fine.

Leaving the uses here if anyone struggles:
![image](https://github.com/user-attachments/assets/165e1d22-00dd-4761-bf12-0e16f0a56ca9)

**Comment by abdelaziz-mahdy** [comment]
> @abdelaziz-mahdy Thanks for pointing this. got to learn new today. Done changing pubspec, tested working fine.
> 
> Leaving the uses here if anyone struggles: ![image](https://private-user-images.githubusercontent.com/68564589/380941837-165e1d22-00dd-4761-bf12-0e16f0a56ca9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxNjY5ODksIm5iZiI6MTczMDE2NjY4OSwicGF0aCI6Ii82ODU2NDU4OS8zODA5NDE4MzctMTY1ZTFkMjItMDBkZC00NzYxLWJmMTItMGUxNmYwYTU2Y2E5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDAxNTEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyMjIyZDA2NThmMTUyMDZhZmRjZTlkNzEzZjM0ZGM0OTRkNmJhZGZhYmFlYmJlNGVjMGY4MjVmMmEwMjE2YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VCEVKzCWi3StqQrhVRNq0gZWVMnqRCF7Wj0xtANwdaY)

instead of a screen shot you can share the code that will be more beneficial to other people, and glad i could help <3
