### ISSUE TITLE
How can I pass init params to mpv player?

### ISSUE THREAD

**Issue by 0Franky** [media-kit/media-kit#539]
Hi to @media-kit group all,
first of all thank you for your contribution!

I'm porting an application, and I should use the mpv player to play an udp stream.

In particular, this is the command I run to start the player on my machine:
```
mpv --no-cache --untimed --no-demuxer-thread --vd-lavc-threads=1 udp://127.0.0.1:12345?overrun_nonfatal=1
```

However I would like to pass these mpv initialization parameters directly from your library to be able to import the player into the app.

Can you help me?

**Comment by alexmercerind** [comment]
https://github.com/media-kit/media-kit/issues/14#issuecomment-1373205132

**Comment by 0Franky** [comment]
@alexmercerind 
I'm sorry to continue this issue but I'm still having problems. 


Here a recap:

First of all the aim of the application is to receive an udp stream and play it.

To this I need to pass specific parameters to mpv and I do this as follow (in initState func):
```
if (player.platform is NativePlayer) {
  (player.platform as dynamic).setProperty("rtsp-transport", "udp");
  (player.platform as dynamic).setProperty("profile", "low-latency");
  (player.platform as dynamic).setProperty("cache", "no");
  (player.platform as dynamic).setProperty("cache-on-disk", "no");
  (player.platform as dynamic).setProperty("demuxer-thread", "no");
  (player.platform as dynamic).setProperty("vd-lavc-threads", "1");
  (player.platform as dynamic).setProperty("untimed", "");
}
```

The stream video is generated as follows:
```
.\ffmpeg.exe -init_hw_device cuda:0 -hwaccel cuda -hwaccel_device cuda -f gdigrab -framerate 60 -video_size 1920x1080 -i desktop -c:v hevc_nvenc -qp:v 20 -c:a copy -g 10 -delay 0 -preset fast -tune ull -profile:v main10 -level:v 4.1 -b:v 4000k -rc-lookahead 0 -maxrate 2000k -bufsize 512k -maxrate 2000K -bufsize 512k -f mpegts udp://192.168.178.47:12345
```

This simply cast the screen (on windows using cuda acceleration for low latency) and send the stream to the cast.


The problem is that sooner or later the delay increases to several seconds, as well as starting to show gray/green screens.

My assumptions are:
1. despite passing the parameters to disable the cache (zero size), it still saves the data and fetches it from there when the loading is slower
2. the integration system with flutter introduces a lot of lag (optimization problem)


The thing I found right away is that by running the following command from the command line (linux - other pc) the lag is always very low and does not suffer from any of the above problems:
```
mpv --rtsp-transport=udp --profile=low-latency --cache=no --cache-on-disk=no --demuxer-thread=no --vd-lavc-threads=1 --untimed udp://127.0.0.1:12345?overrun_nonfatal=1
```


Note:
The parameters seem to be correctly passed to mpv, you can see this by adding this line:
```
(player.platform as dynamic).setProperty("vf", "tblend=c0_mode=difference,eq=contrast=2");
```

Is there anyone who can give me support?
