### ISSUE TITLE
[Bug Report] Application hangs at DBusServiceUnknownException when playing video on Linux

### ISSUE THREAD

**Issue by crxssed7** [media-kit/media-kit#540]
Hi, I'm trying to play a video using this package, but whenever I play a video the application hangs and throws a DBusServiceUnknownException. I'm building the project as a Linux application. Note that the application does not quit, instead it freezes and the audio still plays. I might be doing something stupid as I'm a Flutter newbie, but maybe someone can provide me some insight. Here is my player code, I've tried it with both an asset file and a url:

```dart
import 'package:flutter/material.dart';
import 'package:media_kit/media_kit.dart';
import 'package:media_kit_video/media_kit_video.dart';

class TempView extends StatefulWidget {
  const TempView({super.key});

  @override
  State<TempView> createState() => _TempViewState();
}

class _TempViewState extends State<TempView> {
  late final player = Player();
  late final controller = VideoController(player);

  @override
  void initState() {
    super.initState();
    player.open(Media('asset:///asset/test.mp4'));
  }

  @override
  void dispose() {
    player.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Video(controller: controller)
    );
  }
}
```

I've tried to follow the simple example shown in the readme, any help would be appreciated.
Thanks.

**Comment by alexmercerind** [comment]
Does mpv work?

**Comment by alexmercerind** [comment]
Sorry. We're really unable to reproduce the issue. No other reports such reports exist for GNU/Linux.
