### ISSUE TITLE
Web Issues;  Error: Type 'VideoControlsBuilder' not found.     VideoControlsBuilder? controls,

### ISSUE THREAD

**Issue by azulmouad** [media-kit/media-kit#543]
../../../.pub-cache/hosted/pub.dev/media_kit_video-1.2.3/lib/src/video/video_web.dart:202:5: Error: Type 'VideoControlsBuilder' not found.
    VideoControlsBuilder? controls,
    ^^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/media_kit_video-1.2.3/lib/src/video/video_texture.dart:125:46: Error: A value of type 'Widget Function(VideoState/*1*/)' can't be assigned to a variable of type 'Widget Function(VideoState/*2*/)?'.
 - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('../../../Developer/flutter/packages/flutter/lib/src/widgets/framework.dart').
 - 'VideoState/*1*/' is from 'package:media_kit_video/src/video/video_web.dart' ('../../../.pub-cache/hosted/pub.dev/media_kit_video-1.2.3/lib/src/video/video_web.dart').
 - 'VideoState/*2*/' is from 'package:media_kit_video/src/video/video_texture.dart' ('../../../.pub-cache/hosted/pub.dev/media_kit_video-1.2.3/lib/src/video/video_texture.dart').
    this.controls = media_kit_video_controls.AdaptiveVideoControls,
                                             ^
../../../.pub-cache/hosted/pub.dev/media_kit_video-1.2.3/lib/src/video/video_web.dart:202:5: Error: 'VideoControlsBuilder' isn't a type.
    VideoControlsBuilder? controls,
    ^^^^^^^^^^^^^^^^^^^^

Failed to compile application.

**Comment by azulmouad** [comment]
Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.83.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • iPhone 15 Pro Max (mobile) • EE80707B-FF41-45AF-9ABB-8CD1F07DEF28 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • macOS 14.0 23A344 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 112.0.5615.137
    ! Error: Browsing on the local area network for iPhone 13 pro max. Ensure
      the device is unlocked and attached with a cable or associated with the
      same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code
      -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by alexmercerind** [comment]
Hi @azulmouad,

Thanks for the report. Seems I broke something; give me few minutes.

**Comment by alexmercerind** [comment]
Hi @azulmouad,

Please update: https://github.com/media-kit/media-kit#installation

**Comment by azulmouad** [comment]
it works, thanks
