### ISSUE TITLE
When playing live streams, the memory will keep increasing.

### ISSUE THREAD

**Issue by SQSora** [media-kit/media-kit#549]
![332ae1988c58ee613dea1e3f850950ec](https://github.com/media-kit/media-kit/assets/87071734/8bf489fe-3c78-43c7-a636-a05613aeb05b)
![6551ec6f3ceeebfb0c79b40a31d90993](https://github.com/media-kit/media-kit/assets/87071734/e938f6ec-7484-4998-981f-e45c4ce98602)

Maybe this is related to the video content cached by the progress bar? How should I release memory regularly or close the cache?

**Comment by SQSora** [comment]
Thank you for your reply, I just started using FLutter and my description is not very accurate. When watching the live stream, it will keep loading data into the cache, causing the memory to keep increasing. I found that I can assign this.buffering of class PlayerStream to false to close the cache. But I didn’t find a way to modify it externally.

` 
https://github.com/media-kit/media-kit/blob/main/media_kit/lib/src/models/player_stream.dart
const PlayerStream(
  //omit
  this.buffering = false,
  //omit
  );
}`

**Comment by alexmercerind** [comment]
`Player.stream.buffering` & `Player.stream.buffering` are only for listening i.e. showing progress indicator etc.

**Comment by alexmercerind** [comment]
Try this:

```dart
final player = Player();
if (player.platform is NativePlayer) {
  await (player.platform as dynamic).setProperty('cache', 'no');
}
```

**Comment by SQSora** [comment]
I tried to add this code in the following three places, but the memory still keeps growing (it cannot load the previous content when dragging the progress bar).

```
class MyScreenState extends State<MyScreen> {
  dynamic tmp =
      'https://127.0.0.1/';
  late final player = Player();
  late final controller = VideoController(player);

  @override
  void initState() {
    super.initState();
    void testFun() async {
      if (player.platform is NativePlayer) {
        await (player.platform as dynamic).setProperty('cache', 'no');
        print('run code');
      }
    }

    // testFun();
    player.open(Media(tmp));
    testFun();
  }

  @override
  Widget build(BuildContext context) {
    // void testFun() async {
    //   if (player.platform is NativePlayer) {
    //     await (player.platform as dynamic).setProperty('cache', 'no');
    //     print('run code');
    //   }
    // }

    // testFun();
    return Column(children: [
      SizedBox(height: 300, child: Video(controller: controller)),
      TextButton(
          onPressed: () => player.dispose(), child: const Text('dispose'))
    ]);
  }

  @override
  void dispose() {
    super.dispose();
  }
}
```

**Comment by alexmercerind** [comment]
Does following work? You have it at the right place; before open.

await (player.platform as dynamic).setProperty('cache', 'yes');
await (player.platform as dynamic).setProperty('cache-on-disk', 'yes');

**Comment by SQSora** [comment]
I tried using this code. I have two Windows devices running in Proflie mode, one memory stays at 360M, but the other one is as follows.
![image](https://github.com/media-kit/media-kit/assets/87071734/6f5744a5-500f-4105-bc20-687bc0bfae81)

**Comment by DovgopolsSerj** [comment]
This is an error in the documentation.
For the bufferSize configuration property of the player, it is written:
Default: 32 MB or 32 * 1024 * 1024 bytes.
But these are not megabytes, but gigabytes.
I use:
final _player = Player(
  configuration: const PlayerConfiguration(
    bufferSize: 5 * 1024,
  ),
);
The player additionally uses 5 megabytes of memory and stops growing.

**Comment by alexmercerind** [comment]
@DovgopolsSerj,

Thanks for your comment, would you like to share us a pull-request with the fix in default configuration & documentation?

**Comment by DovgopolsSerj** [comment]
@alexmercerind 
Thanks but I don't speak English well, so I don't want to publish a machine translation.

**Comment by zezo357** [comment]
from mpv 
```
--demuxer-max-bytes=<bytesize>
This controls how much the demuxer is allowed to buffer ahead. The demuxer will normally try to read ahead as much as necessary, or as much is requested with --demuxer-readahead-secs. The option can be used to restrict the maximum readahead. This limits excessive readahead in case of broken files or desynced playback. The demuxer will stop reading additional packets as soon as one of the limits is reached. (The limits still can be slightly overstepped due to technical reasons.)

Set these limits higher if you get a packet queue overflow warning, and you think normal playback would be possible with a larger packet queue.

See --list-options for defaults and value range. <bytesize> options accept suffixes such as KiB and MiB.
```

we can use <bytesize> options accept suffixes such as KiB and MiB?

**Comment by yhsj0919** [comment]
When I playing a live stream, I call player.open() multiple times, which causes the memory to continue to increase

**Comment by ToneyWang** [comment]
I have the same issues. playing RTSP video streams and the memory increased to 1GiB within 3 hours. How do I set the parameters? thanks.
@alexmercerind @abdelaziz-mahdy 
I am using the latest version of currently main branche

**Comment by DovgopolsSerj** [comment]
> I have the same issues. playing RTSP video streams and the memory increased to 1GiB within 3 hours. How do I set the parameters? thanks. @alexmercerind @abdelaziz-mahdy I am using the latest version of currently main branche

As a result, I moved to the fvp package.
Since the author of this package appears in this repository, I think that media_kit is preparing to switch to its backend

**Comment by abdelaziz-mahdy** [comment]
> > I have the same issues. playing RTSP video streams and the memory increased to 1GiB within 3 hours. How do I set the parameters? thanks. @alexmercerind @abdelaziz-mahdy I am using the latest version of currently main branche
> 
> As a result, I moved to the [fvp](https://pub.dev/packages/fvp) package. Since the author of this package appears in this repository, I think that media_kit is preparing to switch to its backend

i personally switched to fvp due to the faster seek and since i was using media_kit controls i created a package for the ui only https://pub.dev/packages/universal_video_controls which is a clone from media_kit controls but adjusted to work with any player  (currently video_player and fvp(since same interface ) ) but any other interface can be added and adjusted to work

**Comment by DovgopolsSerj** [comment]
> I have the same issues. playing RTSP video streams and the memory increased to 1GiB within 3 hours. How do I set the parameters? thanks.

The solution was found. 
When the stream starts playing, you can reset the buffer storage:
```
NativePlayer nPlayer = player.platform as NativePlayer;
nPlayer.setProperty("demuxer-max-back-bytes", "0");
```
This will completely disable the ability to rewind the stream. Or you can specify the required number in bytes how much to store (5Mb):
`nPlayer.setProperty("demuxer-max-back-bytes", "5242880");`

You can listen to player events and dynamically change this value when switching between streams/files.
