### ISSUE TITLE
Raspberry Pi 4 - blu screen playing instead of video

### ISSUE THREAD

**Issue by kekko7072** [media-kit/media-kit#552]
@alexmercerind I successfully tested the **media_kit_test** app on my Linux Ubuntu desktop, now i'm testing it on Raspberry Pi 4 with RaspbianOS Desktop 64 bit and i'm getting blue screen and the error: 
`Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory`

![IMG_4575 copia](https://github.com/media-kit/media-kit/assets/32552589/9aa268c4-97da-4277-9b8d-20af8cc6f210)

**Comment by kekko7072** [comment]
sorry my mistake.

**Comment by YehudaKremer** [comment]
Thank Gosh I was about to cancel my holiday to the Maldives 😥

**Comment by alexmercerind** [comment]
Does S/W toggle work?

**Comment by kekko7072** [comment]
@alexmercerind  Sorry this week i will be out of office, so i will check it next monday. Thank you so much for quick response and all your support on every subject!

**Comment by kekko7072** [comment]
Ok it works using S/W acceleration.

**Comment by zezo357** [comment]
`enableHardwareAcceleration ` set it as false

**Comment by nidhin579** [comment]
Tried that, but it still throws issue `Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory
`
If enableHardwareAcceleration is true, the screen will be blue and if it is false, the screen will be black.

**Comment by alexmercerind** [comment]
Try to get [mpv](https://mpv.io/manual/stable) working first on your hardware.

**Comment by Andrekarma** [comment]
I can replicate the error too on the Rpi4
With enableHardwareAcceleration set to true, all videos are blu
With enableHardwareAcceleration set to false, only some videos works but the performances are very bad, almost all videos stutters 
For the videos that doesnt work the error is the same of @nidhin579 : Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory

If i open the videos using mpv from terminal, all the videos works and runs smoothly 
Is there something i can try to make it work?

**Comment by kunjaarogyatech** [comment]
I was able to solve by changing hwdec. 

```
late final controller = VideoController(
    player,
    configuration: const VideoControllerConfiguration(
      hwdec: 'vaapi',
    ),
  );

```
