### ISSUE TITLE
Play TCP or UDP Stream Error

### ISSUE THREAD

**Issue by jiangchunyu** [media-kit/media-kit#553]
I want to play the video stream in tcp:// or udp:// format, but the playback fails and the error message Failed to recognize file format is prompted.

```
late Player player = Player(configuration:PlayerConfiguration(logLevel: MPVLogLevel.trace));
 late final VideoController controller = VideoController(   player,   configuration: VideoControllerConfiguration(enableHardwareAcceleration:false), ); 
player.open(Media("tcp://192.168.1.104:8000"));

```

**Comment by jiangchunyu** [comment]
The following is the log information
```
media_kit: VideoOutput: Create Texture: 1800998056480
[ERROR:flutter/shell/common/shell.cc(1004)] The 'com.alexmercerind/media_kit_video' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.
See https://docs.flutter.dev/platform-integration/platform-channels#channels-and-platform-threading for more information.
flutter: VideoOutput.Resize
flutter: {handle: 1800890088272, id: 1800998056480, rect: {height: 0, left: 0, top: 0, width: 0}}
flutter: NativeVideoController: Texture ID: 1800998056480
flutter: media_kit: wakelock: _count = 1
flutter: Failed to recognize file format.

```

**Comment by alexmercerind** [comment]
Which platform? Every platform has separate implementation.

**Comment by alexmercerind** [comment]
We do have TCP protocol enabled:

https://github.com/media-kit/libmpv-win32-video-cmake/blob/af821697a4d779bd6a09f9a5cf2fb6418d7ca2fd/packages/ffmpeg.cmake#L288

**Comment by jiangchunyu** [comment]
I have tested on both Windows and Mac. Currently, it cannot be played. I am using SinglePlayerSingleVideoScreen in media_kit_test for testing, but the playback prompt fails.

**Comment by jiangchunyu** [comment]
I use the ffplay command to play the video and it can be played successfully.
```
ffplay.exe -i tcp://192.168.1.104:8000 -fflags nobuffer -sync ext -probesize 32 -analyzeduration 0 -vf setpts=0 -flags low_delay

```

**Comment by alexmercerind** [comment]
It must be noted that media_kit does not have all parsers, decoders or protocols enabled by default. This has been done to reduce the bundle size by a great margin. You can provide us details which one specifically you wish to be enabled.

Furthermore, you can find the relevant repositories under this GitHub organization to cross-compile.

Thanks!

**Comment by alexmercerind** [comment]
We have full variants for some platforms; but not published as Flutter packages.
