### ISSUE TITLE
Is there any way to adjust the video placement in full screen mode?

### ISSUE THREAD

**Issue by azeek** [media-kit/media-kit#557]
Is there any way to adjust the video placement in full screen mode?

For example, I want to show the file listbox on the right side and not cover the player screen. 

There is no way to achieve this in fullscreen mode because it only shows the player. 

It would be inconvenient if the user had to turn off fullscreen mode to see the file list box.

**Comment by alexmercerind** [comment]
Build your custom UI.

**Comment by alexmercerind** [comment]
Refer code samples:

https://github.com/media-kit/media-kit/tree/main/media_kit_test/lib/tests
