### ISSUE TITLE
Shuffle not working on Android?

### ISSUE THREAD

**Issue by topse** [media-kit/media-kit#559]
Hi,
I am doing

```
await player.setShuffle(true);
    await player.open(play: false, list)
```
... and later of course `player.play()`...

But the songs in the list won't get shuffled at playback... Am I doing something wrong or is there a problem in media kit 1.1.10 / media_kit_libs_audio 1.0.4?

Best Regards,
Tobias

**Comment by alexmercerind** [comment]
The `setShuffle` works after `open`. If you call `open` again; it gets reset.

**Comment by topse** [comment]
I swear I also tried that...

Thank you very much and sorry for bothering!

Best Regards,
Tobias

PS: Really GREAT work with this lib!!!!

**Comment by alexmercerind** [comment]
Does it work right now?

The idea is that you open a `Playlist` first, then use `setShuffle` to enable/disable shuffle in that bunch of `Media`s.

**Comment by topse** [comment]
You know... sometimes when you have a problem, it disappears when talk to someone...

Yeah -- after trying _open_ before _setShuffle_ **now** (after this talk) it works :-)

Best Regards,
Tobias
