### ISSUE TITLE
[Question] Audio "stuttering" on Android when app goes to background or device to standby

### ISSUE THREAD

**Issue by topse** [media-kit/media-kit#560]
Hi sorry, me again.

I am using media_kit for an audio player, but when the screen of my phone goes black after some time (which is normal expected behaviour), the audio begins to stutter. The stuttering immediatly stops when the display is reactivated.

I don't find the problem -- maybe anyone has experience with such a behaviour?

Thanks again and Best Regards,
Tobias

**Comment by topse** [comment]
OK -- I accidently found that this problem only seem to exist in Release build of the application (`flutter build apk` and then install it). When just press "F5" in Visual Studio Code, the problem does not exist. I would appreciate any idea :-/

**Comment by topse** [comment]
Sorry another finding...

When I rename delete  `build\media_kit_libs_android_audio\outputs\aar\media_kit_libs_android_audio-release.aar` and rename the debug (media_kit_libs_android_audio-debug.aar) to `-release`, then the stuttering goes away.

**Comment by alexmercerind** [comment]
I have seen this problem with package:just_audio aswell (where I'm yet to migrate to package:media_kit).

It happens rarely, when application is in background with display off; turning on display removes choppiness. Not always.

**Comment by alexmercerind** [comment]
The issue seems to be in Android:

https://www.reddit.com/r/Android/comments/kdw434/experiencing_frequent_audio_stuttering_with/

**Comment by topse** [comment]
I don't think so... on my phone I have at least 4 more audio player apps running without a problem... so no -- not a general android problem.

**Comment by topse** [comment]
So it is... with the named package a wrapper can be created and media_kit then runs in a background process... now it works. But it was not really funny to implement...

Thanks and Best Regards,
Tobias

**Comment by alexmercerind** [comment]
Yeah... that does require some code to hook around. I'll do something when I have bit of time on my hands.
