### ISSUE TITLE
Sorry, neither hdmv_pgs_subtitle nor trueHD are supported?

### ISSUE THREAD

**Issue by user1121114685** [media-kit/media-kit#561]
I found a post
https://github.com/media-kit/media-kit/issues/359
But I have no way of understanding what should be done to support these two formats!

I found that the iso file cannot be played. I used Windows and Android for testing. Tested in debug mode and release mode respectively!
I'm hoping to get a little hint, I've looked a lot of places but I'm getting nowhere!

**Comment by alexmercerind** [comment]
You can replace the libmpv with more decoders/demuxers/parsers/protocols.

**Comment by andynvt** [comment]
> You can replace the libmpv with more decoders/demuxers/parsers/protocols.

can you give a guide on this?
