### ISSUE TITLE
[Question]support other subtitle types? (smi... ass....)

### ISSUE THREAD

**Issue by azeek** [media-kit/media-kit#563]
MPV player seems to support SAMI (SMI) or ASS subtitles well. 

When I tried to play those subtitles in the media_kit library, I got the following error message and the subtitles are not displayed. 

flutter: Can not open external file
 

Does the media_kit library parse with different logic than libmpv's subtitle system?

**Comment by alexmercerind** [comment]
FYI: The bundle size of media_kit is about 1/3 of full-fledge mpv.

No point in enabling support for these rare formats by default. You can replace libmpv-2.dll with your own one.

Read: https://github.com/media-kit/media-kit/issues/561#issuecomment-1787783637

**Comment by alexmercerind** [comment]
You can enable libass for better subtitle rendering using `PlayerConfiguration`.

**Comment by andynvt** [comment]
> You can enable libass for better subtitle rendering using `PlayerConfiguration`.

this still cannot read this subtitle codec "hdmv_pgs_subtitle"

**Comment by hongfeiyucode** [comment]
> 仅供参考：media_kit 的捆绑包大小约为完整 mpv 的 1/3。
> 
> 默认启用对这些罕见格式的支持毫无意义。你可以用自己的 libmpv-2.dll 替换它。
> 
> 阅读：[#561（评论）](https://github.com/media-kit/media-kit/issues/561#issuecomment-1787783637)

HDmvSub (hdmv_pgs_stitle) subtitles are not uncommon, and many official videos use this type of subtitle. We hope to add support for it
