### ISSUE TITLE
Add support for .ass/.ssa subtitles

### ISSUE THREAD

**Issue by wiedymi** [media-kit/media-kit#564]
Hi! It will be great to support rendering for .ass/.ssa subtitles which are commonly used. Could you add it in upcoming versions?

**Comment by 23doors** [comment]
Fairly sure that ass subs work already just fine. libass is included, just enable it.

**Comment by wiedymi** [comment]
@23doors could you provide an example how to do that?

**Comment by wiedymi** [comment]
Also what about fonts? The .ass subtitles support using different fonts, they may not be included on your device, so I would like to have a method to provide a list with links to .ttf fonts files.

**Comment by wiedymi** [comment]
Also what about web implemetation for libass, do you support it?

**Comment by 23doors** [comment]
What platform are you using? On desktops and mobile - .ass should work out of the box. Just add `PlayerConfiguration(libass:true)` to `Player()`. On web it is limited by what browser supports and none of them supports .ass subtitles.

.ass subtitles I used had embedded fonts and it was working fine. I didnt use external .ass subs, only those defined as tracks within mkv. And they work just fine.

**Comment by wiedymi** [comment]
There's libass-wasm to support rendering for .ass subtitle on the web, it will be great to have it implementation here.

**Comment by 23doors** [comment]
Feel free to submit a PR ;)

**Comment by wiedymi** [comment]
> Feel free to submit a PR ;)

I would love to, I am not sure that I am capable to do it on good quality level. But if no one do that, I will try.

**Comment by alexmercerind** [comment]
> > Feel free to submit a PR ;)
> 
> I would love to, I am not sure that I am capable to do it on good quality level. But if no one do that, I will try.

Feel free.
