### ISSUE TITLE
Error while Loading  videos on particular systems

### ISSUE THREAD

**Issue by mobileteamdct** [media-kit/media-kit#566]
While loading the  videos on media_kit package(Linux - ubuntu) on particular system it showing driver issue, In the first video loading this error coming but video is playing but after that if we load it is stucked in 1 second. [Note : System : Lenova - ThinkCentre-neo-50t-Gen-3 , Graphics ; Mesa Intel® Graphics (ADL-S GT1) , Proceesser : 12th Gen Intel® Core™ i5-12400 × 12 ]

libva info: VA-API version 1.7.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_7
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
libva info: va_openDriver() returns 1
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_6
libva error: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed
libva info: va_openDriver() returns -1

How to solve this issue.

**Comment by iamJana** [comment]
While creating the player instance, In VideoPlayerConfiguration set the hwdec='auto-safe'

**Comment by alexmercerind** [comment]
The workaround specified in comment above should work. Nothing that we can do.
