### ISSUE TITLE
I am trying to install media_kit but I get the following error: media_kit: arm64-v8a JAR verification failed.

### ISSUE THREAD

**Issue by indacurdev** [media-kit/media-kit#568]
* Where:
Build file 'C:\Users\pc\AppData\Local\Pub\Cache\hosted\pub.dev\media_kit_libs_android_video-1.3.6\android\build.gradle' line: 102

* What went wrong:
A problem occurred evaluating project ':media_kit_libs_android_video'.
media_kit: arm64-v8a JAR verification failed.

I have the latest version of Flutter installed.

**Comment by indacurdev** [comment]
Build file 'C:\Users\pc\AppData\Local\Pub\Cache\hosted\pub.dev\media_kit_libs_android_video-1.3.6\android\build.gradle' line: 102

* What went wrong:
A problem occurred evaluating project ':media_kit_libs_android_video'.
> media_kit: arm64-v8a JAR verification failed.

**Comment by alexmercerind** [comment]
Just see our unit-tests & builds which succeed on our CI.

I won't come to your office or home to fix your internet.

**Comment by dghub-founder** [comment]
Same error.
How to fix ?
