### ISSUE TITLE
equalizer not work with FLAC format

### ISSUE THREAD

**Issue by DemeoStep** [media-kit/media-kit#570]
I'm trying to implement equalizer with

```dart
Future<void> eq() async {
    if (!isEqualized) {
      if (_player.platform is NativePlayer) {
        await (_player.platform as NativePlayer).setProperty(
          'af',
          'equalizer=f=5000:g=20',
        );
      }
    } else {
      if (_player.platform is NativePlayer) {
        await (_player.platform as dynamic).setProperty(
          'af',
          '',
        );
      }
    }
    isEqualized = !isEqualized;
  }
``` 
With MP3 file it works as expected, but playing FLAC file throws error

```dart
flutter: PlayerLog(prefix: ffmpeg, level: error, text: 'aresample' filter not present, cannot convert formats.)
flutter: PlayerLog(prefix: lavfi, level: fatal, text: failed to configure the filter graph)
flutter: PlayerLog(prefix: af, level: error, text: Disabling filter equalizer.00 because it has failed.)
```

**Comment by alexmercerind** [comment]
Support is only provided for media_kit API. There's no dedicated equalizer API yet.

**Comment by DemeoStep** [comment]
(_player.platform is NativePlayer) tells you nothing?

**Comment by alexmercerind** [comment]
Everything you wrote in that block is similar to forking the package & adding your own code.

Reach out to FFmpeg or mpv developers if you need any support/information in relation to that. I only provide support for methods and classes provided by media_kit.

**Comment by DemeoStep** [comment]
You provide your own libmpv  - you don't know?
https://github.com/media-kit/libmpv-darwin-build/tree/main

**Comment by alexmercerind** [comment]
Yes, I don't know. It's a software built by a large number of contributors & dependencies.

I also reference to documentation for implementing features.

I did enable equalizer filter in FFmpeg, which shall work. Since media_kit doesn't have an equalizer feature yet, I haven't analyzed the challenges or requirements. Contributions welcomed...

**Comment by DemeoStep** [comment]
Maybe you can enable 'aresample' filter too?
