### ISSUE TITLE
HLS playback issues

### ISSUE THREAD

**Issue by sudhanshugairola** [media-kit/media-kit#571]
Test on: Windows

while playing HLS or m3u8 content something weird issue i face like infinite loading while changing audio or video tracks. second while seeking from one position to other by dragging same infinite loading issue was appeared.

only issue with HLS.
1. high initial loading time.
2. so much buffering.
3. Infinite loading while track changing or seeking.

check url: https://devstreaming-cdn.apple.com/videos/streaming/examples/adv_dv_atmos/main.m3u8

**Comment by alexmercerind** [comment]
Can you even play that in Google Chrome?

**Comment by sudhanshugairola** [comment]
> Can you even play that in Google Chrome (Android)?

No not in browser, it's Windows desktop and same on linux.

**Comment by alexmercerind** [comment]
I mean a URL won't play if it's not even accessible (or it's segments).

**Comment by sudhanshugairola** [comment]
Android Chrome is not capable to Play HLS.

**Comment by sudhanshugairola** [comment]
I tested mkv and mp4 that working smoothly without any issue. I see a serious bug of HLS in all platforms Android, iOS, windows, Linux.

**Comment by alexmercerind** [comment]
> Android Chrome is not capable to Play HLS.


Read: https://www.chromium.org/audio-video/

**Comment by sudhanshugairola** [comment]
I'm here talking about windows desktop application.

**Comment by alexmercerind** [comment]
Even VLC can't play your URL. It's a problem with your source not the library or application. We many many users playing HLS on all platforms successfully.

**Comment by sudhanshugairola** [comment]
I know vlc and MX player are not maded for HLS streaming. They can just play mkv and mp4 well. Try once on Exoplayer.

**Comment by alexmercerind** [comment]
No.

**Comment by sudhanshugairola** [comment]
If that plugin based on VLC so I don't think that's can able to Play HLS streaming properly.

**Comment by sudhanshugairola** [comment]
Recently I noticed if any Dash or HLS content contain multiple resolution, multiple audio and subtitles then that issue I face.

**Comment by zezo357** [comment]
Hi Alex,

I've tested the URL on our examples:

- **Web**: Works as expected.
- **macOS**: Does not work. It loads indefinitely and doesn't appear to be using any network resources.

Additionally, I think implementing a feature to copy logs directly from the examples would be beneficial. It would allow users to easily share logs for troubleshooting.

**Comment by sudhanshugairola** [comment]
same issue https://github.com/media-kit/media-kit/issues/524

**Comment by birros** [comment]
> Even VLC can't play your URL. It's a problem with your source not the library or application. We many many users playing HLS on all platforms successfully.

I agree with @alexmercerind, Apple's HLS sample is problematic natively (VLC, mpv, IINA...).

> That Apple Dev HLS because apple develop HLS streaming, so I don't think that source url issue.

@sudhanshugairola Just because Apple has billions of dollars and makes systems with a very smooth interface doesn't mean they're the most competent in terms of standards development and implementation ^^

The following sample works perfectly, confirming that it's a source issue : https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8

I'm closing this issue because it concerns `mpv` and not `media-kit`, but if anyone finds options to solve this, feel free to share them with us.

**Comment by basemkhirat** [comment]
I am also have a high initial loading time in android with hls url.

When I test the same URL with BetterPlayer, it works fine.

This my log:

```
I/media_kit( 1749): com.alexmercerind.media_kit_video.VideoOutputManager.create: 489849310288
I/media_kit( 1749): flutterJNIAPIAvailable = true
I/media_kit( 1749): com.alexmercerind.media_kit_video.VideoOutput: id = 7
I/media_kit( 1749): com.alexmercerind.media_kit_video.VideoOutputManager.createSurface: 489849310288
I/MediaCodec( 1749): name: OMX.qcom.video.decoder.avc
I/OMXClient( 1749): IOmx service obtained
I/MediaCodec( 1749): configure format is :{csd-1=java.nio.DirectByteBuffer[pos=0 lim=9 cap=9], mime=video/avc, width=1920, csd-0=java.nio.DirectByteBuffer[pos=0 lim=33 cap=33], height=1080}
I/ExtendedACodec( 1749): setupVideoDecoder()
I/ExtendedACodec( 1749): Decoder will be in frame by frame mode
I/MediaCodec( 1749): start
E/ACodec  ( 1749): [OMX.qcom.video.decoder.avc] Failed to get port format to send format change
I/media_kit( 1749): com.alexmercerind.media_kit_video.VideoOutputManager.setSurfaceTextureSize: 489849310288 1920 1080
D/        ( 1749): PlayerBase::PlayerBase()
D/        ( 1749): TrackPlayerBase::TrackPlayerBase()
```

**Comment by sudhanshugairola** [comment]
Yeah same with all

**Comment by sudhanshugairola** [comment]
> I am also have a high initial loading time in android with hls url.
> 
> When I test the same URL with BetterPlayer, it works fine.
> 
> This my log:
> 
> ```
> I/media_kit( 1749): com.alexmercerind.media_kit_video.VideoOutputManager.create: 489849310288
> I/media_kit( 1749): flutterJNIAPIAvailable = true
> I/media_kit( 1749): com.alexmercerind.media_kit_video.VideoOutput: id = 7
> I/media_kit( 1749): com.alexmercerind.media_kit_video.VideoOutputManager.createSurface: 489849310288
> I/MediaCodec( 1749): name: OMX.qcom.video.decoder.avc
> I/OMXClient( 1749): IOmx service obtained
> I/MediaCodec( 1749): configure format is :{csd-1=java.nio.DirectByteBuffer[pos=0 lim=9 cap=9], mime=video/avc, width=1920, csd-0=java.nio.DirectByteBuffer[pos=0 lim=33 cap=33], height=1080}
> I/ExtendedACodec( 1749): setupVideoDecoder()
> I/ExtendedACodec( 1749): Decoder will be in frame by frame mode
> I/MediaCodec( 1749): start
> E/ACodec  ( 1749): [OMX.qcom.video.decoder.avc] Failed to get port format to send format change
> I/media_kit( 1749): com.alexmercerind.media_kit_video.VideoOutputManager.setSurfaceTextureSize: 489849310288 1920 1080
> D/        ( 1749): PlayerBase::PlayerBase()
> D/        ( 1749): TrackPlayerBase::TrackPlayerBase()
> ```

Really things will show when you have hls or dash content with multiple tracks like audios, subtitles, resolution then forget you can change the tracks or play video smoothly like Betterplayer or videoplayer.

**Comment by sudhanshugairola** [comment]
> > Even VLC can't play your URL. It's a problem with your source not the library or application. We many many users playing HLS on all platforms successfully.
> 
> I agree with @alexmercerind, Apple's HLS sample is problematic natively (VLC, mpv, IINA...).
> 
> > That Apple Dev HLS because apple develop HLS streaming, so I don't think that source url issue.
> 
> @sudhanshugairola Just because Apple has billions of dollars and makes systems with a very smooth interface doesn't mean they're the most competent in terms of standards development and implementation ^^
> 
> The following sample works perfectly, confirming that it's a source issue : https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8
> 
> I'm closing this issue because it concerns `mpv` and not `media-kit`, but if anyone finds options to solve this, feel free to share them with us.

You need to find it root cause other no benefit of this plugin.

**Comment by paulinofonsecas** [comment]
There is any solution for that problem?
