### ISSUE TITLE
[Enhancement][Android] HDR configuration

### ISSUE THREAD

**Issue by sudhanshugairola** [media-kit/media-kit#573]
Due to absence of native view colour fading is appearing. HDR work bit better because of absence of native view brightness and sharpness is missing. All things can make better if player use platform or native view for HDR and Dolby vision video.

**Comment by sudhanshugairola** [comment]
![Uploading Screenshot_2023-11-06-09-43-16-340_com.alexmercerind.media_kit_test.jpg…]()

**Comment by sudhanshugairola** [comment]
![Screenshot_2023-11-06-09-43-16-340_com alexmercerind media_kit_test](https://github.com/media-kit/media-kit/assets/42227576/162b20cc-04b6-402c-8e67-b997f7e3783e)

**Comment by user1121114685** [comment]
`  /// Default: Platform specific.
  /// * Windows, GNU/Linux, macOS & iOS: `libmpv`
  /// * Android: `gpu``
  
  Neither supports gpu_next, so Dolby Vision video cannot be played.

**Comment by sudhanshugairola** [comment]
What are you talking, you are out of point, I'm talking about native view.

**Comment by alexmercerind** [comment]
Do you mind providing a sample of your video file?

**Comment by alexmercerind** [comment]
> What are you talking, you are out of point, I'm talking about native view.

It's not related to native view either. There's no native HDR support in mpv or anything based on FFmpeg.

However, results can be made pretty close (or at-least acceptable) using correct configuration.

**Comment by sudhanshugairola** [comment]
No completed because of flutter view using the place of platformview.

**Comment by alexmercerind** [comment]
Like I said, that's only one side of the puzzle.

**Comment by sudhanshugairola** [comment]
Kindly test same thing on native Android.

**Comment by alexmercerind** [comment]
> Kindly test same thing on native Android.

Kindly test same thing without ExoPlayer.

**Comment by alexmercerind** [comment]
If it works well on mpv-android (there are many options to optimize the rendering), it can in media_kit.

Does not depend upon platform view or texture view.

https://play.google.com/store/apps/details?id=is.xyz.mpv&hl=en&gl=US

**Comment by 23doors** [comment]
One thing I can add. You're using DolbyVision video. Not sure if DV support has finally landed in mpv but it seems that DV tonemapping in mpv afaik is only supported with gpu_next vo like @user1121114685 already said. MPV has no hdr passthrough at all even in mpv-android project, it always does tone-mapping but most likely still only for HDR10, not DV. Platform view wouldn't change a thing here unless a non-mpv backend is used.

**Comment by sudhanshugairola** [comment]
I can understand that

**Comment by alexmercerind** [comment]
Even tone mapping can do some good in the time being. This is currently off, possibly relates:

https://github.com/media-kit/media-kit/blob/e01d5344135922289d38a709639a686d92d1a531/media_kit/lib/src/player/native/player/real.dart#L2375

There's existing ExoPlayer backend issue: #410 for future.

**Comment by 23doors** [comment]
Tonemapping works without hdr-compute-peak. No need to change that. hdr-compute-peak only helps with per frame hdr accuracy. MPV simply doesnt work with DV unless vo=gpu_next is used (although this may be outdated, last time I checked they waited for DV patch to be merged in ffmpeg but it was some time ago). HDR10 works fine even with hdr-compute-peak off or not

**Comment by 23doors** [comment]
Some DV files use profile that has HDR10 fallback. These will work just fine. But DV without HDR10 fallback will then show this pink/green tint

**Comment by alexmercerind** [comment]
Good to know.

**Comment by deckerst** [comment]
@alexmercerind @23doors is it possible with the current version of media_kit to use `vo=gpu_next`?

**Comment by alexmercerind** [comment]
@deckerst 

For Android specifically, it is very much possible since we use `--wid` embedding. The implementation is very much same as mpv-android & there's ongoing progress: https://github.com/mpv-android/mpv-android/pull/596

On other platforms, I don't think gpu-next is available in the GL render API yet. Related: #296.
