### ISSUE TITLE
Application stuck in window 

### ISSUE THREAD

**Issue by waulite-786** [media-kit/media-kit#575]
[ERROR:flutter/shell/common/shell.cc(1004)] The 'com.alexmercerind/media_kit_video' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.

**Comment by alexmercerind** [comment]
Provide minimal sample code to reproduce.

**Comment by waulite-786** [comment]
thank for reply but I resolved the issue,  the issue was my side




Regards,
Abdul Majid Khan
Senior Software Developer
Mob: 8369691917
Waulite Technologies Pvt. Ltd.
F-11, Shanti Nagar Industrial estate, Vakola, Santacruz East, Mumbai,
Maharashtra 400055

**Comment by waulite-786** [comment]
sorry I thought it resolved but now it stuck after 6 hr ,any cache issue is
there




Regards,
Abdul Majid Khan
Senior Software Developer
Mob: 8369691917
Waulite Technologies Pvt. Ltd.
F-11, Shanti Nagar Industrial estate, Vakola, Santacruz East, Mumbai,
Maharashtra 400055

**Comment by alexmercerind** [comment]
Feel free to share fixes.

**Comment by waulite-786** [comment]
player.open(Media(widget.path))
await playerSingleOne.open(Media(widget.path))
when i added await after that it stuck 4 to 6 hr




Regards,
Abdul Majid Khan
Senior Software Developer
Mob: 8369691917
Waulite Technologies Pvt. Ltd.
F-11, Shanti Nagar Industrial estate, Vakola, Santacruz East, Mumbai,
Maharashtra 400055

**Comment by waulite-786** [comment]
import 'dart:async';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:media_kit/media_kit.dart';
import 'package:media_kit_video/media_kit_video.dart';
import 'package:wauly_template/controller/slide_content_controller.dart';
import 'package:wauly_template/utils/app_log.dart';

class PlayerSinglePageOne extends StatefulWidget {
  final String path;
  final String? thumbnail;
  const PlayerSinglePageOne(
      {super.key, required this.path, required this.thumbnail});
  @override
  State<PlayerSinglePageOne> createState() => PlayerSinglePageOneState();
}

class PlayerSinglePageOneState extends State<PlayerSinglePageOne> {


  // Create a [Player] to control playback.
  late final playerSingleOne = Player();
  // Create a [VideoController] to handle video output from [Player].
  late final controllerOne = VideoController(playerSingleOne);

  StreamController<double?> streamControllerOne = StreamController<double
?>();
  Stream<double?> get stream => streamControllerOne.stream;
  var videoStart = true;

  @override
  void initState() {
    super.initState();
    onInit();
  }

  void onInit() async {
    try {
      if (playerSingleOne.platform is NativePlayer) {
         Print.log(
                tag: "majid",
                message: "Majid100 Step 10 : native.............. ");
        await (playerSingleOne.platform as dynamic).setProperty('cache',
'no');
        await (playerSingleOne.platform as dynamic).setProperty(
'cache-on-disk', 'no');
      }
      await playerSingleOne.open(Media(widget.path));

      playerSingleOne.stream.completed.listen(
        (bool complete) {
          if (complete) {
            streamControllerOne.close();

            Print.log(
                tag: "majid",
                message: "Majid100 Step 10 : playerSingleOne is completed "
);
            Get.find<SlideContentController>()
                .getMessageFromPage(1, "video completed");
          } else {
            // Paused.
          }
        },
      );
      playerSingleOne.stream.position.listen((Duration position) {
        double value = position.inMilliseconds.toDouble();
        if (value != 0.0) {
          if (videoStart) {
            videoStart = false;
            addValue(value);
          }
        }
      });
    } catch (e) {
      Print.log(
          tag: "majid",
          message: "Majid100 Step excetion PlayerSinglePageOne :$e");
    }
  }

  void addValue(double? value) {
    streamControllerOne.add(value);
  }

  @override
  void dispose() async {
    super.dispose();
    await playerSingleOne.dispose();
    Print.log(
        tag: "majid",
        message: "Majid100 video view destroy :PlayerSinglePageOne");
  }

  @override
  Widget build(BuildContext context) {
    // AppConstant.createLog(
    //   AppConstant.getContent,
    //   "PlayerSinglePageOne build() called ${AppConstant.getLogTime()}",
    // );
    // Print.log(
    //     tag: "tag",
    //     message: 'Majid100 Step 7 : PlayerSinglePageOne build() called
');
    return Center(
      child: SizedBox(
        width: MediaQuery.of(context).size.width,
        height: MediaQuery.of(context).size.height,
        // Use [Video] widget to display video output.
        child: StreamBuilder(
          stream: controllerOne.player.stream.playing,
          builder: (context, playing) => playing.data == true
              ? StreamBuilder(
                  stream: streamControllerOne.stream,
                  builder: (context, position) {
                    double? value = position.data;
                    Print.log(tag: 'video value 1', message: "$value");
                    if (value != null && value != 0.0) {
                      return Video(
                        controller: controllerOne,
                        fit: BoxFit.fill,
                        controls: NoVideoControls,
                      );
                    } else {
                      return SizedBox(
                        child:
                            widget.thumbnail != null && widget.thumbnail !=
''
                                ? SizedBox(
                                    width: double.infinity,
                                    height: double.infinity,
                                    child: Image.file(
                                      File(widget.thumbnail!),
                                      fit: BoxFit.fill,
                                    ),
                                  )
                                : const SizedBox(),
                      );
                    }
                  })
              : SizedBox(
                  child: widget.thumbnail != null && widget.thumbnail != ''
                      ? SizedBox(
                          width: double.infinity,
                          height: double.infinity,
                          child: Image.file(
                            File(widget.thumbnail!),
                            fit: BoxFit.fill,
                          ),
                        )
                      : const SizedBox(),
                ),
        ),
      ),
    );
  }
}




Regards,
Abdul Majid Khan
Senior Software Developer
Mob: 8369691917
Waulite Technologies Pvt. Ltd.
F-11, Shanti Nagar Industrial estate, Vakola, Santacruz East, Mumbai,
Maharashtra 400055

**Comment by waulite-786** [comment]
I am replacing page one after other it working but after some time video
player not destory




Regards,
Abdul Majid Khan
Senior Software Developer
Mob: 8369691917
Waulite Technologies Pvt. Ltd.
F-11, Shanti Nagar Industrial estate, Vakola, Santacruz East, Mumbai,
Maharashtra 400055

**Comment by waulite-786** [comment]
I am replacing page one after other it working but after some time video
player not destroy then screen stuck when next page load becoz old not
destroy




Regards,
Abdul Majid Khan
Senior Software Developer
Mob: 8369691917
Waulite Technologies Pvt. Ltd.
F-11, Shanti Nagar Industrial estate, Vakola, Santacruz East, Mumbai,
Maharashtra 400055
