### ISSUE TITLE
[iOS] crash: partial apply for closure #1 in VideoOutput.updateCallback()

### ISSUE THREAD

**Issue by JulienDev** [media-kit/media-kit#576]
Hello,
I'm using the latest version of MediaKit video (1.1.4) and I noticed that a lot of iOS users are experiencing a crash (1 756 crashes for 837 users). Looking at Crashlytics report it seems to happen only when the app is in background but I can't verify that because I'm not able to reproduce it on my iPhone. Let me know if you need more information :)

> Crashed: Thread
> 0  Flutter                        0x1c238 (Manquant UUID 4c4c441f55553144a1682f45551c1451)
> 1  Flutter                        0x2a7bc (Manquant UUID 4c4c441f55553144a1682f45551c1451)
> 2  media_kit_video                0x1243c partial apply for closure #1 in VideoOutput.updateCallback() + 129 (VideoOutput.swift:129)
> 3  media_kit_video                0x1241c partial apply for thunk for @escaping @callee_guaranteed () -> () + 20 (<compiler-generated>:20)
> 4  media_kit_video                0x13c58 Worker.loop() + 69 (Worker.swift:69)
> 5  media_kit_video                0x13d50 thunk for @escaping @callee_guaranteed @Sendable () -> () + 28 (<compiler-generated>:28)
> 6  Foundation                     0x64bdc <redacted> + 792
> 7  libsystem_pthread.dylib        0x3338 _pthread_start + 116
> 8  libsystem_pthread.dylib        0x1938 thread_start + 8

**Comment by birros** [comment]
It's difficult to use this log. Since it occurs when the application is running in the background and concerns a method that uses mpv rendering, I think the crash is caused by mpv using the GPU, which is forbidden by Apple when the application is running in the background.

Are you using these settings?
```dart
Video(
  …
  pauseUponEnteringBackgroundMode: true,
  resumeUponEnteringForegroundMode: true,
)
```

**Comment by JulienDev** [comment]
Hummm, no I'm not using these settings, I'll give it a try.
Also I don't know if it can be related but the "Background fetch" capability was checked for my app. I'll publish a new version and let you know if it resolves the issue :)

**Comment by alexmercerind** [comment]
We can probably skip render loop if application is not in foreground...

Same on Windows maybe e.g. on minimize.
