### ISSUE TITLE
Player not working on Web, Black screen

### ISSUE THREAD

**Issue by azulmouad** [media-kit/media-kit#578]
the only issues i get is: `The platformViewRegistry getter is deprecated and will be removed in a future release. Please import it from `dart:ui_web` instead.`

Flutter Doctor : `Flutter (Channel stable, 3.13.9, on macOS 14.0 23A344 darwin-x64, locale en-MA)`

**Comment by alexmercerind** [comment]
Listen to `player.stream.error` for possible errors or check your web browser's development console.

The line you provided is warning not an error.

**Comment by azulmouad** [comment]
I'm listening to `player.stream.error`
i got this errors:
Error Stream: Failed to load because no supported source was found.
Error Stream: Failed to load because no supported source was found.
Error: 


dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 327:10  createErrorWithStack
dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 337:28            _throw
dart-sdk/lib/core/errors.dart 120:5                                           throwWithStackTrace
dart-sdk/lib/async/zone.dart 1386:11                                          callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:15           <fn>

**Comment by alexmercerind** [comment]
The error is pretty clear.

**Comment by alexmercerind** [comment]
If your web browser can't play that URL; certainly nothing can make it work.

**Comment by azulmouad** [comment]
> If your web browser can't play that URL; certainly nothing can make it work.

The URLs I've been using were functioning well until the latest update. However, now, they only display a black screen on the player page without any apparent issues. What could be the cause?

**Comment by alexmercerind** [comment]
Can you please share a sample? Does URL work if you open it in a new tab?

**Comment by azulmouad** [comment]
i'm using m3u url's, i can't share it here

**Comment by alexmercerind** [comment]
There hasn't been any change related to that. Our unit-test for HLS on web still passes.

**Comment by azulmouad** [comment]
Weird, anyway thanks for your support and timing .

**Comment by azulmouad** [comment]
Error Stream: Failed to load because no supported source was found.
Error: MEDIA_ELEMENT_ERROR: Format error


dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 327:10  createErrorWithStack
dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 337:28            _throw
dart-sdk/lib/core/errors.dart 120:5                                           throwWithStackTrace
dart-sdk/lib/async/zone.dart 1386:11                                          callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7            <fn>

**Comment by OmarZakiAli** [comment]
I have same issue , link works on android and ios but not web

**Comment by OmarZakiAli** [comment]
@azulmouad found any solution yet

**Comment by azulmouad** [comment]
add in the end of the url video .m3u8

**Comment by azulmouad** [comment]
> @azulmouad found any solution yet

add in the end of the url video .m3u8
