### ISSUE TITLE
cant run in windows 

### ISSUE THREAD

**Issue by 944095635** [media-kit/media-kit#582]
media_kit: ^1.1.10                   #
media_kit_video: ^1.2.4              #
media_kit_libs_video: ^1.0.4         #

camke network error?

Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Launching lib\main.dart on Windows in debug mode...

mpv-dev-x86_64-20230924-git-652a1dd.7z

**Comment by alexmercerind** [comment]
Please just refer to our passing unit-tests & builds in our CI.
