### ISSUE TITLE
[Warning][Windows] `flutter::MethodChannel::InvokeMethod` background thread usage 

### ISSUE THREAD

**Issue by waulite-786** [media-kit/media-kit#590]
[ERROR:flutter/shell/common/shell.cc(1004)] The 'com.alexmercerind/media_kit_video' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.

**Comment by basemkhirat** [comment]
I have this issue also in ios

**Comment by alexmercerind** [comment]
This is merely a warning.

**Comment by alexmercerind** [comment]
> I have this issue also in iOS.

Resolved in #596 for macOS & iOS.
