### ISSUE TITLE
[Bug Report][Windows] media_kit_native_event_loop eventually falls into deadlock

### ISSUE THREAD

**Issue by waulite-786** [media-kit/media-kit#591]
Tested in flutter window 
My requirement is play video and image continuously when i play 
only image my application runs 24 hr without any issue but when
play video by using media-kit after 2 0r 3hr application stuck

I am thing any cache where you store, why  after 2 or 3 hr  application stuck
i used this line of code also but problem not solved
**await (playerSingleOne.platform as dynamic).setProperty('cache', 'no');
await (playerSingleOne.platform as dynamic).setProperty('cache-on-disk', 'no');**

import 'dart:async';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:media_kit/media_kit.dart';
import 'package:media_kit_video/media_kit_video.dart';
import 'package:wauly_template/controller/slide_content_controller.dart';
import 'package:wauly_template/utils/app_log.dart';

class PlayerSinglePageOne extends StatefulWidget {
  final String path;
  final String? thumbnail;
  const PlayerSinglePageOne(
      {super.key, required this.path, required this.thumbnail});
  @override
  State<PlayerSinglePageOne> createState() => PlayerSinglePageOneState();
}

class PlayerSinglePageOneState extends State<PlayerSinglePageOne> {

  // Create a [Player] to control playback.
  late final playerSingleOne = Player();
  // Create a [VideoController] to handle video output from [Player].
  late final controllerOne = VideoController(playerSingleOne);

  StreamController<double?> streamControllerOne = StreamController<double?>();
  Stream<double?> get stream => streamControllerOne.stream;
  var videoStart = true;

  @override
  void initState() {
    super.initState();
    onInit();
  }

  void onInit() async {
    try {
      if (playerSingleOne.platform is NativePlayer) {
         Print.log(
                tag: "majid",
                message: "Majid100 Step 10 : native.............. ");
        await (playerSingleOne.platform as dynamic).setProperty('cache', 'no');
        await (playerSingleOne.platform as dynamic).setProperty('cache-on-disk', 'no');
      }
      await playerSingleOne.open(Media(widget.path));
      
      playerSingleOne.stream.completed.listen(
        (bool complete) {
          if (complete) {
            streamControllerOne.close();

            Print.log(
                tag: "majid",
                message: "Majid100 Step 10 : playerSingleOne is completed ");
            Get.find<SlideContentController>()
                .getMessageFromPage(1, "video completed");
          } else {
            // Paused.
          }
        },
      );
      playerSingleOne.stream.position.listen((Duration position) {
        double value = position.inMilliseconds.toDouble();
        if (value != 0.0) {
          if (videoStart) {
            videoStart = false;
            addValue(value);
          }
        }
      });
    } catch (e) {
      Print.log(
          tag: "majid",
          message: "Majid100 Step excetion PlayerSinglePageOne :$e");
    }
  }

  void addValue(double? value) {
    streamControllerOne.add(value);
  }

  @override
  void dispose() async {
    super.dispose();
    await playerSingleOne.dispose();
    Print.log(
        tag: "majid",
        message: "Majid100 video view destroy :PlayerSinglePageOne");
  }

  @override
  Widget build(BuildContext context) {
    // AppConstant.createLog(
    //   AppConstant.getContent,
    //   "PlayerSinglePageOne build() called ${AppConstant.getLogTime()}",
    // );
    // Print.log(
    //     tag: "tag",
    //     message: 'Majid100 Step 7 : PlayerSinglePageOne build() called ');
    return Center(
      child: SizedBox(
        width: MediaQuery.of(context).size.width,
        height: MediaQuery.of(context).size.height,
        // Use [Video] widget to display video output.
        child: StreamBuilder(
          stream: controllerOne.player.stream.playing,
          builder: (context, playing) => playing.data == true
              ? StreamBuilder(
                  stream: streamControllerOne.stream,
                  builder: (context, position) {
                    double? value = position.data;
                    Print.log(tag: 'video value 1', message: "$value");
                    if (value != null && value != 0.0) {
                      return Video(
                        controller: controllerOne,
                        fit: BoxFit.fill,
                        controls: NoVideoControls,
                      );
                    } else {
                      return SizedBox(
                        child:
                            widget.thumbnail != null && widget.thumbnail != ''
                                ? SizedBox(
                                    width: double.infinity,
                                    height: double.infinity,
                                    child: Image.file(
                                      File(widget.thumbnail!),
                                      fit: BoxFit.fill,
                                    ),
                                  )
                                : const SizedBox(),
                      );
                    }
                  })
              : SizedBox(
                  child: widget.thumbnail != null && widget.thumbnail != ''
                      ? SizedBox(
                          width: double.infinity,
                          height: double.infinity,
                          child: Image.file(
                            File(widget.thumbnail!),
                            fit: BoxFit.fill,
                          ),
                        )
                      : const SizedBox(),
                ),
        ),
      ),
    );
  }
}

**Comment by alexmercerind** [comment]
If you're on Windows, can you remove media_kit_native_event_loop & try to run?

**Comment by waulite-786** [comment]
I used only these

  media_kit: ^1.1.8                              # Primary package.
  media_kit_video: ^1.1.9                        # For video rendering.
  media_kit_libs_video: ^1.0.2                   # Native video dependencies




Regards,
Abdul Majid Khan
Senior Software Developer
Mob: 8369691917
Waulite Technologies Pvt. Ltd.
F-11, Shanti Nagar Industrial estate, Vakola, Santacruz East, Mumbai,
Maharashtra 400055

**Comment by waulite-786** [comment]
Thanks for support
While create exe file I remove  *media_kit_native_event_loop.dll*  file now
i tested 14 hr works perfectly

Please fixed in later version because every time deleted this file while
creating build it is difficult

Again I would like to tell you  "Thanks from the depth of my heart."


Regards,
Abdul Majid Khan
Senior Software Developer
Mob: 8369691917
Waulite Technologies Pvt. Ltd.
F-11, Shanti Nagar Industrial estate, Vakola, Santacruz East, Mumbai,
Maharashtra 400055

**Comment by zezo357** [comment]
As a workaround for now, can you remove:
```yaml
media_kit_libs_video: ^1.0.2                   # Native video dependencies
```

And add the following dependencies:
```yaml
media_kit_libs_android_video: ^1.3.6
media_kit_libs_ios_video: ^1.1.4
media_kit_libs_macos_video: ^1.1.4
media_kit_libs_windows_video: ^1.0.9
media_kit_libs_linux: ^1.1.3
```

**Comment by waulite-786** [comment]
thanks




Regards,
Abdul Majid Khan
Senior Software Developer
Mob: 8369691917
Waulite Technologies Pvt. Ltd.
F-11, Shanti Nagar Industrial estate, Vakola, Santacruz East, Mumbai,
Maharashtra 400055

**Comment by alexmercerind** [comment]
I mean I'm not sure. Do let me know if it works... std::mutex on Windows is very unreliable I don't know why.

**Comment by waulite-786** [comment]
yes now it working fine i tested 24 hr  continuously  runs




Regards,
Abdul Majid Khan
Senior Software Developer
Mob: 8369691917
Waulite Technologies Pvt. Ltd.
F-11, Shanti Nagar Industrial estate, Vakola, Santacruz East, Mumbai,
Maharashtra 400055

**Comment by waulite-786** [comment]
https://drive.google.com/file/d/1ELbJa4T4doj5Rh0UIFWFgtsUQneoOxop/view?usp=drive_link




Regards,
Abdul Majid Khan
Senior Software Developer
Mob: 8369691917
Waulite Technologies Pvt. Ltd.
F-11, Shanti Nagar Industrial estate, Vakola, Santacruz East, Mumbai,
Maharashtra 400055

**Comment by alexmercerind** [comment]
Build against main branch... media_kit_native_event_loop is deprecated.
