### ISSUE TITLE
Issue using multiple players in a list.

### ISSUE THREAD

**Issue by scottynoshotty** [media-kit/media-kit#592]
I am loading up videos as part of a PageView. I have noticed strange behavior on iOS. When the list initially the first video can be played without issue. Scroll to the next page and try to play the next video and there is a lag in the beginning of the next video. This is reproducable throughout the list. At any point in the list when there is only one active Player instance the video plays without issue. When there is more than one player (say you scroll from one page with a video to the next page which also hosts a video) there will always be some lag in starting the next video.

What is the prescribed way to implement multiple players in a list/page view? Should they be sharing a player instance?

**Comment by alexmercerind** [comment]
I think I understand what this is.

If you go through our example application (download link in README), you'll find two samples:

- https://github.com/media-kit/media-kit/blob/main/media_kit_test/lib/tests/04.tabs_test.dart
- https://github.com/media-kit/media-kit/blob/main/media_kit_test/lib/tests/09.seamless.dart

I think you're implementing a situation similar to 1.

You should optimize your code so that it initializes `Player` etc. efficiently. It is something that we can (probably) optimize in our own implementation e.g. using isolates, but I can't confirm to what extent.

**Comment by scottynoshotty** [comment]
Thanks for the feedback! I will look into it.

Just to clarify the issue a bit, I have PageView items that I am scrolling through. The items can be either a video or a image. I am using a builder so that items are built on demand. The video items do not autoplay (although I will set it that way once I have this issue sorted out). 

Scenario 1:
Only one video list item is currently built (this means one player is initialized). You click play and the video plays back with no issue.

Scenario 2:
Two video list items are built (two player instances are initialized). Click play on a video list item and the playback begins immediately, pauses for a half second and then plays the rest of the video without issue.

This is 100% reproducible.

**Comment by scottynoshotty** [comment]
I added some additional logs to my code and found that when I switch pages I attach the next video player and detach (dispose) the previous one. So when I click play on the next video it still has the issue of immediately playing, pausing for a half second then continuing play even when there is no other attached video player.

**Comment by scottynoshotty** [comment]
Update: I changed my underlying player to Flutter's bog standard video_player and it works well now. Bit of a bummer because I like this package and it's API. If you want to investigate further I can provide more details.

**Comment by alexmercerind** [comment]
From what I can tell... The dispose method is freezing UI for substantial amount of time & thus the delay.

**Comment by alexmercerind** [comment]
Even that seems alright once I try release mode.

**Comment by scottynoshotty** [comment]
That would be my guess too Alex, it looked like something was happening in dispose
