### ISSUE TITLE
Seeking Assistance for Default Full Screen Mode in Video Playback

### ISSUE THREAD

**Issue by user1121114685** [media-kit/media-kit#593]
Hello Author,

Thank you very much for your hard work. I have gained a lot of knowledge from using the framework. Now, I have a small problem that I still can't solve after consulting a lot of materials. But it might be a small problem for you, so I take the liberty to disturb you. I want to ask a question, how to enter full screen mode by default after opening the video, instead of entering from the normal mode by clicking the full screen button!

Thank you, I look forward to your reply!

**Comment by zezo357** [comment]
check https://github.com/zezo357/media_kit/blob/examples/media_kit_test/lib/tests/15.full_screen_player.dart

**Comment by user1121114685** [comment]
Hello @zezo357  Thank you for your help, it means a lot to me. I learned a lot and gained a deeper understanding of the project, which is a great project. It is an honor for the project and for flutter to have people like you and @alexmercerind  who maintain it. I will recommend media-kit to more people, it is the best project I have ever used, without a doubt.


`late final GlobalKey<VideoState> key = GlobalKey<VideoState>();`    
`Video(key: key,`    
`key.currentState?.enterFullscreen();`


These are the three most critical points of this issue.
