### ISSUE TITLE
BUG: `af` filter breaks in Android

### ISSUE THREAD

**Issue by Velosofy** [media-kit/media-kit#600]
I'm testing with my mpv `af` filter, it works in Linux build, but not Android.
Possibility of [this](https://github.com/media-kit/media-kit/issues/373#issuecomment-1683373120) ?

```dart
late final player = Player();
late final controller = VideoController(player);
NativePlayer get nativePlayer => player.platform as NativePlayer;

@override
void initState() {
  super.initState();
  player.open(
    Media('http://10.17.7.245:8000/test.mp4'),
  );

  nativePlayer.setProperty('af', 'lavfi=graph=%22%pan=stereo|FL=c0|FR=c0');

  nativePlayer.observeProperty('af', (value) async {
    print('The value of af property is $value');
  });
}
```

`lavfi=graph=%22%pan=stereo|FL=c0|FR=c0` is for playing only the L track on both LR channel/output.

The filter works as expected in my Linux machine, but in Android, it simply doesn't have audio.

**Comment by alexmercerind** [comment]
The libmpv that media_kit uses on GNU/Linux is yours (package manager).

On normal platforms, we provide own binaries (to make application standalone) which comply with LGPL & have far less bundle size. As a result, a large number of decoders, demuxers, parsers, filters etc. are missing.

<hr>

We only provide support for API that package:media_kit offers. If you use features from mpv & FFmpeg directly, you are on your own. The `NativePlayer` API is not exposed directly & notes these warnings for a reason:

https://github.com/media-kit/media-kit/blob/3c7d705cc906cdf139a9c8352c71bf017ff3d366/media_kit/lib/src/player/native/player/real.dart#L1386
https://github.com/media-kit/media-kit/blob/3c7d705cc906cdf139a9c8352c71bf017ff3d366/media_kit/lib/src/player/native/player/real.dart#L1411
https://github.com/media-kit/media-kit/blob/3c7d705cc906cdf139a9c8352c71bf017ff3d366/media_kit/lib/src/player/native/player/real.dart#L1447
https://github.com/media-kit/media-kit/blob/3c7d705cc906cdf139a9c8352c71bf017ff3d366/media_kit/lib/src/player/native/player/real.dart#L1473

**Comment by alexmercerind** [comment]
We have full-binaries with all features enabled for Android, but no Flutter packages (lack of time & developers).

See repositories in this organization.

**Comment by Velosofy** [comment]
Ah gotcha, thanks, will definitely look into it.
