### ISSUE TITLE
video_player_media_kit， When I play a very large video, the playback is very laggy, even if I set the buffer to be very large.

### ISSUE THREAD

**Issue by longgong** [media-kit/media-kit#605]
like this  url, https://betacs.101.com/v0.1/static/preproduction_ndr_38a_49f75d/ppt_parsing/test/result/0d936754-6df4-4098-a552-0f0720b41ff9/preproduction_ndr_38a_49f75d_6040eb88-c574-49fd-b5c7-c4cb7e51504d/slide3_1_VZaVcw5S-phAc-4eH8-XFaP-ztD43Q49wWrP.mp4

**Comment by birros** [comment]
I can reproduce with `mpv` and `vlc`, so it's not specific to `media-kit`.
It's a network/server issue, the bandwidth is too slow for this video resolution.
`mpv`, `vlc` and `media-kit` cannot miraculously display 1080p video when the bandwidth is only a few kb/s ^^

Sorry

**Comment by alexmercerind** [comment]
I agree with @ birros.

**Comment by longgong** [comment]
My bandwidth is tens of Mb. Is there any way to make the buffer large enough before playing?
