### ISSUE TITLE
[Bug Report][Android]Failed to run the problem, program won't open

### ISSUE THREAD

**Issue by junmingchen123** [media-kit/media-kit#609]
`
Launching lib/main.dart on sdk gphone x86 in debug mode...
Running Gradle task 'assembleDebug'...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app-debug.apk...
Debug service listening on ws://127.0.0.1:40495/Ma4ePj2FP20=/ws
Syncing files to device sdk gphone x86...
D/permissions_handler(16600): No permissions found in manifest for: []32
D/permissions_handler(16600): No permissions found in manifest for: []32
D/permissions_handler(16600): No permissions found in manifest for: []33
D/permissions_handler(16600): No permissions found in manifest for: []33
I/media_kit(16600): package:media_kit_libs_android_video detached.
`
Hi admin, I can run it fine in both Linux and Android phone emulators. But when I run in Nexus 5X API 30(Android 11.0) or Nexus 7(2012) API30(Android 11.0), the program can't get up, similar to flashback effect, above is the log, please help me to see.
`  media_kit: ^1.1.10+1                           # Primary package.
  media_kit_video: ^1.2.4                        # For video rendering.
  media_kit_libs_video: ^1.0.4                   # Native video dependencies.
  media_kit_libs_android_video: ^1.3.6           # Android video dependencies.
`
Sorry to trouble you, thank you

**Comment by alexmercerind** [comment]
I think you should declare permission your ApplicationManifest.xml if you're requesting them...

I don't see anything related to package:media_kit in your logs.

**Comment by junmingchen123** [comment]
`I/media_kit(16600): package:media_kit_libs_android_video detached.`
This ,when app run in  Nexus 5X API 30(Android 11.0) or Nexus 7(2012) API30(Android 11.0),closed.
in AndroidMnifest.xml 
`
    <uses-permission android:name="android.permission.INTERNET" />
    
    <uses-permission android:name="android.permission.READ_MEDIA_AUDIO" />
    <uses-permission android:name="android.permission.READ_MEDIA_VIDEO" />
    
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" />
`
in main.dart
`checkPermissions() async {
  final DeviceInfoPlugin deviceInfoPlugin = DeviceInfoPlugin();

  if (Platform.isAndroid) {
    AndroidDeviceInfo androidInfo = await deviceInfoPlugin.androidInfo;
    int androidVersion = androidInfo.version.sdkInt;

    if (androidVersion >= 13) {
      if (await Permission.videos.isDenied ||
          await Permission.videos.isPermanentlyDenied) {
        final state = await Permission.videos.request();
        if (!state.isGranted) {
          await SystemNavigator.pop();
        }
      }

      if (await Permission.audio.isDenied ||
          await Permission.audio.isPermanentlyDenied) {
        final state = await Permission.audio.request();
        if (!state.isGranted) {
          await SystemNavigator.pop();
        }
      }
    } else {
      if (await Permission.storage.isDenied ||
          await Permission.storage.isPermanentlyDenied) {
        final state = await Permission.storage.request();
        if (!state.isGranted) {
          await SystemNavigator.pop();
        }
      }
    }
  }
}
`
and I used it before runApp
`WidgetsFlutterBinding.ensureInitialized();
  await checkPermissions();`
