### ISSUE TITLE
Can the --stream-buffer-size parameter setting be supported?

### ISSUE THREAD

**Issue by longgong** [media-kit/media-kit#612]
For online large file streaming, buffer data loading is very slow. I want to set it larger.It is best to support allowing us to customize setting parameters.

**Comment by zezo357** [comment]
you can update it on all platfroms except for web 


```dart
if (player.platform is NativePlayer) {
  NativePlayer playerNative = player.platform as NativePlayer;
  playerNative.setProperty("stream-buffer-size", "<bytesize>");
}
```

Replace `<bytesize>` with the desired buffer size, such as (default: 128KB), `512KB`, or `1MiB`.

**Comment by longgong** [comment]
thank you，effective.

**Comment by longgong** [comment]
if (player.platform is NativePlayer) {
  NativePlayer playerNative = player.platform as NativePlayer;
  playerNative.setProperty("stream-buffer-size", "<bytesize>");
}     This setting will cause the web to fail to compile.

**Comment by alexmercerind** [comment]
Use `as dynamic`.

**Comment by zezo357** [comment]
> if (player.platform is NativePlayer) {
>   NativePlayer playerNative = player.platform as NativePlayer;
>   playerNative.setProperty("stream-buffer-size", "<bytesize>");
> }     This setting will cause the web to fail to compile.

I believe this is because of the Nativeplayer import, you will have to use conditional imports to make this import only work on platforms other than web
