### ISSUE TITLE
Playlist Transitions

### ISSUE THREAD

**Issue by Andrekarma** [media-kit/media-kit#617]
Hi,

there is a way to add a transition beetween videos of a playlist?

Thanks

**Comment by alexmercerind** [comment]
Not possible. Use your Flutter & Widget skills to do transitions, animations & UI etc.

**Comment by fabioselau077** [comment]
> Not possible. Use your Flutter & Widget skills to do transitions, animations & UI etc.

You won't need to listen when a video in the playlist is finished, right? How do you do this?
