### ISSUE TITLE
The captured image screenshot appears as a blank image.in a Windows desktop environment.

### ISSUE THREAD

**Issue by kyungjoongo77777** [media-kit/media-kit#622]
When you capture a screenshot in a Windows environment and save it to the local dir,

 the captured image is displayed as a blank image.

Is there a way to fix a bug like this?

I'm not sure what the problem is.

(For reference, the video card is amd rx580.)

The code is as shown below.
-----------------------------------------------------------------------------------------------------------
saveImageFrame() async {

    final Uint8List? screenshotUintList = await player.screenshot(format: 'image/png');

    String dir = Directory.current.path;
    print(dir);
    final filepath = "${getRandomString(15)}.png";
    var fullFilePath = dir + "/" + filepath;
    File imgFile = File(dir + "/" + filepath);
    imgFile.writeAsBytes(screenshotUintList as List<int>);

    
  }

**Comment by isaacy13** [comment]
https://github.com/media-kit/media-kit/issues/802#issuecomment-2209433976

> +1 on this
> My current workaround is to just use player.screenshot() or player.screenshot(format: 'image/jpeg') and save it into a .png file

**Comment by alexmercerind** [comment]
Attaching `VideoController` is necessary.
