### ISSUE TITLE
[Linux] Call 'setlocale(LC_NUMERIC, "C") Segmentation fault

### ISSUE THREAD

**Issue by khomin** [media-kit/media-kit#625]
The player works fine - until i open gstreamer libraries (i need video calls in my app)
Just the player or just my gstreamer code works fine

But together i get:
`Non-C locale detected. This is not supported.`
`Call 'setlocale(LC_NUMERIC, "C");' in your code.`
`Segmentation fault`

I check i call ensureInitialized every time before using the player
`VideoPlayerMediaKit.ensureInitialized(
      linux: true,
 );`

Please help
How to combine gstreamer and media_kit in single app?

Update:
I see that the Segmentation fault doesn't happen if i call:
`fflush(stdout);`
`setlocale(LC_NUMERIC, "C");`

After i closed gstreamer
But still don't know how to use both gstreamer and media_kit at the same time

Update:
Actually they work both after `setlocale(LC_NUMERIC, "C");` back
after gst_init()
But this can be a serious issue for others part of an app
When the player sets LC_NUMERIC it affects the whole app environment!

**Comment by alexmercerind** [comment]
The libmpv API requires LC_NUMERIC. There's no way around it.

**Comment by alexmercerind** [comment]
I wouldn't use two separate libraries GStreamer & libmpv anyway if you're building some reliable software... go with one.
