### ISSUE TITLE
<LINUX ARM64> Cannot find libmpv at the usual places.

### ISSUE THREAD

**Issue by JGNS** [media-kit/media-kit#638]
Hello. When I execute a program in Linux, the error is as follows:
Unhandled Exception: Exception: Cannot find libmpv at the user places Depending on your distribution, you can install the libmpv package to make shared library available globally On Debian or Ubuntu based systems, you can install it with: aptinstall libmpv dev# 0 NativeLibrary. ensueInitialized (package: media_kit/src/player/native/core/native library. art: 78)
Dec 13 16:50:59 ZTL demo_ Nolibs [25652]: # 1 nativeEnsureInitiated (package: media_kit/src/player/native/player/real. date: 47)
Dec 13 16:50:59 ZTL demo_ Nolibs [25652]: # 2 MediaKit. ensueInitialized (package: media_kit/src/media_kit. date: 30)
Dec 13 16:50:59 ZTL demo_ Nolibs [25652]: # 3 main (package: demo_dolibs/main. art: 18)
Main. art: 18: MediaKit. ensueInitialized ()
I am certain that I have done the following:
1. Add dependencies(  media_kit: ^1.1.10
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4)
2. MediaKit. ensueInitialized () before runApp
3. sudo aptinstall libmpv dev mpv
4. i can find so (libmpv. so, libmpv. so. 1, libmpv. so. 1.107.0) under /usr/lib/arch64 Linux gnu/
5. The versions of libmpv-dev mpv are all 0.32.0-1ubuntu1
I don't know why my program reports an error and can't find libmpv.

My Linux device is an embedded device with Ubuntu 20.04 installed. It has an arm64 architecture.

thanks

**Comment by JGNS** [comment]
it does not support ARM architecture？

**Comment by femalemonkeyman** [comment]
Unfortunately with shared libraries things can come out a bit more complicated sometimes. Ill give it a shot and see if i can build the test on my raspberry pi if i get a minute

**Comment by JGNS** [comment]
> Unfortunately with shared libraries things can come out a bit more complicated sometimes. Ill give it a shot and see if i can build the test on my raspberry pi if i get a minute

Thank you for your reply. If you want to try on an embedded device, you may not be able to directly run the Flutter project (based on my experience). I am using elinux, which can help me launch the Flutter app in embedded Linux.

**Comment by fabioselau077** [comment]
resolved? same issue here in ubuntu... :/

**Comment by JGNS** [comment]
> resolved? same issue here in ubuntu... :/

not yet, if you resolved it, Please record it here.

**Comment by hauserx** [comment]
Possibly this code in media-kit could be extended to collect actual error messages, not sure if those would be useful but maybe those will give additional context: https://github.com/media-kit/media-kit/blob/63c6ebe8366db7ecfbd13ab9ce76b11dd86dae48/media_kit/lib/src/player/native/core/native_library.dart#L75

From what I see you could try to run ensureInitialized with absolute path to your libmpv library, although not sure it will actually help as seems it's already in pretty generic location but maybe worth a try.

**Comment by JGNS** [comment]
> Possibly this code in media-kit could be extended to collect actual error messages, not sure if those would be useful but maybe those will give additional context:
> 
> https://github.com/media-kit/media-kit/blob/63c6ebe8366db7ecfbd13ab9ce76b11dd86dae48/media_kit/lib/src/player/native/core/native_library.dart#L75
> 
> From what I see you could try to run ensureInitialized with absolute path to your libmpv library, although not sure it will actually help as seems it's already in pretty generic location but maybe worth a try.

You are so awesome. I have made new progress based on your clues, as follows:
I used MediaKit.ensureInitialized(libmpv: '/usr/lib/aarch64-linux-gnu/libmpv.so') for initialization. ''/usr/lib/aarch64-linux-gnu/libmpv.so'' is the location of libmpv in my embedded device.
Doing this solves the problem of not being able to find libmpv.
But new problems arise:
①There is a warning: media_kit: WARNING: package:media_kit_native_event_loop not found. I am not sure what it will affect.
②An error: MissingPluginException(No implementation found for method VideoOutputManager.Create on channel com.alexmercerind/media_kit_video)
Jan 04 15:14:50 ztl demo_nolibs[46018]: flutter: #0 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308)
Jan 04 15:14:50 ztl demo_nolibs[46018]: flutter: <asynchronous suspension>
Jan 04 15:14:50 ztl demo_nolibs[46018]: flutter: #1 NativeVideoController.create (package:media_kit_video/src/video_controller/native_video_controller/real.dart:128)
Jan 04 15:14:50 ztl demo_nolibs[46018]: flutter: <asynchronous suspension>
Jan 04 15:14:50 ztl demo_nolibs[46018]: flutter: #2 new VideoController.<anonymous closure> (package:media_kit_video/src/video_controller/video_controller.dart:83)
Jan 04 15:14:50 ztl demo_nolibs[46018]: flutter: <asynchronous suspension>
Jan 04 15:14:50 ztl demo_nolibs[46018]: flutter:
Jan 04 15:14:50 ztl demo_nolibs[46018]: [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method VideoOutputManager.Create on channel com.alexmercerind/media_kit_video)
Jan 04 15:14:50 ztl demo_nolibs[46018]: flutter: media_kit: wakelock: _count = 1
There is currently no way to solve it. I am a novice in Linux and embedded systems.

**Comment by mvasilchuk** [comment]
You are trying to build media-kit for ELinux, but it is only implemented for Linux. So none of the platform plugins are actually built.

 The difference between Linux and ELinux is that ELinux doesn't include GTK which is required by media-kit, so even if add elinux platform to all media-kit libraries and copy the content of **/linux to **/elinux you won't be able to build the library. The only way to make media-kit work in ELinux is to add ELinux as a supported program and rewrite all native code to not to use GTK.

**Comment by JGNS** [comment]
> You are trying to build media-kit for ELinux, but it is only implemented for Linux. So none of the platform plugins are actually built.
> 
> The difference between Linux and ELinux is that ELinux doesn't include GTK which is required by media-kit, so even if add elinux platform to all media-kit libraries and copy the content of **/linux to **/elinux you won't be able to build the library. The only way to make media-kit work in ELinux is to add ELinux as a supported platform and rewrite all native code to not to use GTK.

Thank you for your guidance. Now I am instructing that media-kit does not support embedded devices for the time being. It seems to be an unsolvable problem and it is beyond my ability.

**Comment by barribarrier** [comment]
GTK is too heavy for embedded devices. With hello world flutter example app, I get consistent 60 fps on elinux, ~20 fps on regular flutter linux (GTK) build. So you can imagine it will only be worse when playing videos.
There was an interest in exploring custom embedders by the owner in https://github.com/media-kit/media-kit/pull/388#issuecomment-1694416869
But it looks like nothing came of it yet.

**Comment by 4kz** [comment]
this is  needed for arm64 devices such as the macbook air

**Comment by sobuur0** [comment]
> You are trying to build media-kit for ELinux, but it is only implemented for Linux. So none of the platform plugins are actually built.
> 
> The difference between Linux and ELinux is that ELinux doesn't include GTK which is required by media-kit, so even if add elinux platform to all media-kit libraries and copy the content of **/linux to **/elinux you won't be able to build the library. The only way to make media-kit work in ELinux is to add ELinux as a supported platform and rewrite all native code to not to use GTK.

hi @mvasilchuk what if my embedded linux box supports gtk is there a way to bypass this?
or this isn't solvable currently?
