### ISSUE TITLE
A problem occurred evaluating project ':media_kit_libs_android_video'.

### ISSUE THREAD

**Issue by dghub-founder** [media-kit/media-kit#642]
FAILURE: Build failed with an exception.

* Where:
Build file '/home/dghub/.pub-cache/hosted/pub.dev/media_kit_libs_android_video-1.3.6/android/build.gradle' line: 74

* What went wrong:
A problem occurred evaluating project ':media_kit_libs_android_video'.
> Connection timed out

**Comment by dghub-founder** [comment]
> media_kit: arm64-v8a JAR verification failed.

**Comment by mdddj** [comment]
<img width="947" alt="image" src="https://github.com/media-kit/media-kit/assets/29020213/374d0d45-70a2-411f-871a-2d81b5c30eab">

the same problem

```dart
  media_kit: ^1.1.10+1
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4
```

I have tried Flutter Clean

**Comment by dghub-founder** [comment]
Now working
I forgot flutter pub get

**Comment by KBoss174** [comment]
![image](https://github.com/media-kit/media-kit/assets/30442394/8fda8ba3-8d13-463f-a701-6c90c09f95a7)
the same problem, someone know how to solve it

**Comment by dghub-founder** [comment]
> ![image](https://private-user-images.githubusercontent.com/30442394/292473458-8fda8ba3-8d13-463f-a701-6c90c09f95a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0NzQ0OTcsIm5iZiI6MTcwMzQ3NDE5NywicGF0aCI6Ii8zMDQ0MjM5NC8yOTI0NzM0NTgtOGZkYThiYTMtOGQxMy00NjNmLWE3MDEtNmM5MGMwOWY5NWE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDAzMTYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiNjAwNmNmZTFkYWJlYmZjOTRiMjc5MTM1YzVjNDlhNTgwNzcxOGQ2YmI1YjY2MGRhYjU0MDk3NTIwNTExMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fjHFXhnAlrLjF2Ituw_gaaHQr8XgVTTzGEbQhT1iTcg) the same problem, someone know how to solve it

**Comment by lucasjinreal** [comment]
hosted/pub.flutter-io.cn/media_kit_libs_android_video-1.3.6/android/build.gradle' line: 111

* What went wrong:
A problem occurred evaluating project ':media_kit_libs_android_video'.
> media_kit: x86 JAR verification failed.

Why close? @dghub-founder  Can u post your solution pelase?
