### ISSUE TITLE
No sound on iPhone (web)

### ISSUE THREAD

**Issue by Joao-Pimenta** [media-kit/media-kit#643]
HI. So I opened up the web demo under https://media-kit.github.io/media-kit/#/ in my iPhone, and realized that there's no sound in any of the videos.

This came after I realized the same in my web app, and started looking for a solution, without much success. 

I tried muting the video before it played, but that did not work. Any help?

**Comment by 23doors** [comment]
Tried on me device, both Safari and Chrome work fine.

**Comment by Joao-Pimenta** [comment]
Any idea of why my own implementation is not working? The demo under https://media-kit.github.io/media-kit/#/ I now see was a problem of bad testing, but my current implementation still fails.

My implementation is quite simple:

`import 'package:flutter/material.dart';
import 'package:media_kit/media_kit.dart';
import 'package:media_kit_video/media_kit_video.dart';

class VideoPlayerWidget extends StatefulWidget {
  final String videoUrl;

  const VideoPlayerWidget({required this.videoUrl});

  @override
  _VideoPlayerWidgetState createState() => _VideoPlayerWidgetState();
}

class _VideoPlayerWidgetState extends State<VideoPlayerWidget> {
  late final Player player;
  late final VideoController videoController;
  bool isMuted = true;

  @override
  void initState() {
    super.initState();

    player = Player();
    videoController = VideoController(player);

    // Play the provided video URL.
    player.open(Media(widget.videoUrl)).then((value) => {
          // player.pause(),
          // player.setVolume(0.0),
        });
  }

  @override
  Widget build(BuildContext context) {
    return AspectRatio(
        aspectRatio: 16.0 / 9.0,
        child: Video(
          controller: videoController,
        ));
  }

  @override
  void dispose() {
    player.dispose();
    super.dispose();
  }
}
`

I also do (on main.dart):
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  MediaKit.ensureInitialized();
  setPathUrlStrategy(); 
  (...)


My pubspec.yaml:
  media_kit: ^1.1.10+1
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4


And flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 3.18.0-0.1.pre, on macOS 14.1.1 23B81 darwin-arm64, locale en-PT)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.85.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

**Comment by alexmercerind** [comment]
https://developer.chrome.com/blog/autoplay

**Comment by Joao-Pimenta** [comment]
> https://developer.chrome.com/blog/autoplay

I was aware of that, that's why I tested my starting the video paused, and requiring the human input to start it. But that made no difference

**Comment by alexmercerind** [comment]
Use PlayerConfiguration.muted... "paused" isn't "muted". In most cases, you'll want user to interact first.

**Comment by Joao-Pimenta** [comment]
> Use PlayerConfiguration.muted... "paused" isn't "muted". In most cases, you'll want user to interact first.

I tried an implementation based on that suggestion, but now I don't have sound anywhere, even when I visit the web app via the computer or android.
`
import 'package:flutter/material.dart';
import 'package:media_kit/media_kit.dart';
import 'package:media_kit_video/media_kit_video.dart';

class VideoPlayerWidget extends StatefulWidget {
  final String videoUrl;

  const VideoPlayerWidget({required this.videoUrl});

  @override
  _VideoPlayerWidgetState createState() => _VideoPlayerWidgetState();
}

class _VideoPlayerWidgetState extends State<VideoPlayerWidget> {
  late final Player player;
  late final VideoController videoController;
  bool isMuted = true;

  @override
  void initState() {
    super.initState();
    player = Player(configuration: PlayerConfiguration(muted: isMuted));
    videoController = VideoController(player);
    player.open(Media(widget.videoUrl));
  }

  @override
  Widget build(BuildContext context) {
    return Center(
        child: Stack(alignment: Alignment.center, children: [
      Center(
        child: AspectRatio(
            aspectRatio: 16.0 / 9.0,
            child: Video(
              controller: videoController,
            )),
      ),
      IconButton(
        icon:
            Icon(isMuted ? Icons.volume_up_rounded : Icons.volume_mute_rounded),
        onPressed: () {
          setState(() {
            player.setVolume(isMuted ? 100.0 : 0.0);
            isMuted = !isMuted;
          });
        },
      ),
    ]));
  }

  @override
  void dispose() {
    player.dispose();
    super.dispose();
  }
}`

**Comment by Joao-Pimenta** [comment]
I'm testing multiple variations of the same idea: muting/setting the volume to 0; and then adding some type of controls to add it back, and nothing is working. Specifically, I notice that the buttons don't seem to even react/render properly.
I now switched to controls: MaterialDesktopVideoControls, and I have the same issue. The mute/unmute button appears, but clicking it does nothing.

My code:
```
import 'package:flutter/material.dart';
import 'package:media_kit/media_kit.dart';
import 'package:media_kit_video/media_kit_video.dart';

class VideoPlayerWidget extends StatefulWidget {
  final String videoUrl;

  const VideoPlayerWidget({required this.videoUrl});

  @override
  _VideoPlayerWidgetState createState() => _VideoPlayerWidgetState();
}

class _VideoPlayerWidgetState extends State<VideoPlayerWidget> {
  late final Player player =
      Player(); //configuration: PlayerConfiguration(muted: isMuted)
  late final VideoController videoController = VideoController(player);
  bool isMuted = true;

  @override
  void initState() {
    super.initState();

    videoController.player.open(Media(widget.videoUrl)).then((value) => {
          player.setVolume(0.0),
        });
  }

  @override
  Widget build(BuildContext context) {
    return Center(
      child: AspectRatio(
        aspectRatio: 16.0 / 9.0,
        child: Video(
          controller: videoController,
          controls: MaterialDesktopVideoControls,
        ),
      ),
    );
  }

  @override
  void dispose() {
    player.dispose();
    super.dispose();
  }
}
```

**Comment by Joao-Pimenta** [comment]
> Tried on me device, both Safari and Chrome work fine.
> Use PlayerConfiguration.muted... "paused" isn't "muted". In most cases, you'll want user to interact first.

Could you guys take a look at my lastest code? I really need some help in this

**Comment by alexmercerind** [comment]
Sorry this is a bug-tracker.

Unfortunately, we do not provide support. We're just bunch of individuals (with limited time & resources) working on this project as a hobby. You'll be able to figure it out on your own, sufficient APIs are available.
