### ISSUE TITLE
delete media_kit.jar when verification failed

### ISSUE THREAD

**Issue by Passer-by** [media-kit/media-kit#645]
I found that when the download fails, there is also a default-arm64-v8a.jar file, but the size of this file is 0 kb. According to the judgment in [build.gradle](https://github.com/media-kit/media-kit/blob/main/libs/android/media_kit_libs_android_video/android/build.gradle#L101-L112) it is considered as having a file and will undergo an MD5 verification.

**Comment by Passer-by** [comment]
Perhaps it can be directly deleted after the verification fails. After all, this is just a cache file.

**Comment by josh4500** [comment]
This is an annoying issue and still can't get past this

**Comment by khomin** [comment]
Still not working

```
Build file 'user/.pub-cache/hosted/pub.dev/media_kit_libs_android_video-1.3.6/android/build.gradle' line: 102

* What went wrong:
A problem occurred evaluating project ':media_kit_libs_android_video'.
> media_kit: arm64-v8a JAR verification failed.
```

**Comment by zezo357** [comment]
https://github.com/media-kit/media-kit/pull/656 this pr fixes it, but sadly its not merged yet
