### ISSUE TITLE
build failed in macos

### ISSUE THREAD

**Issue by dht-hedaihua** [media-kit/media-kit#646]
the error :
`
[   +1 ms] ** BUILD FAILED **
[   +2 ms] The following build commands failed:
[        ]   CompileC
$project_root/build/macos/Build/Intermediates.noindex/Pods.build/Debug/media_kit_native_event_loop.build/Obje
cts-normal/x86_64/media_kit_native_event_loop.o
/Users/hedaihua/.pub-cache/hosted/pub.flutter-io.cn/media_kit_native_event_loop-1.0.8/macos/Classes/media_kit_native_event_loop.cc normal x86_64 c++
com.apple.compilers.llvm.clang.1_0.compiler (in target 'media_kit_native_event_loop' from project 'Pods')
[        ] (1 failure)
[  +59 ms] Building macOS application... (completed in 9.5s)
[   +2 ms] Exception: Build process failed
[   +1 ms] "flutter run" took 18,789ms.`

**Comment by femalemonkeyman** [comment]
Adding the -v to the end of the compilation commands allow a more verbose message with better error messages

**Comment by alexmercerind** [comment]
Build against main branch... media_kit_native_event_loop is deprecated.
