### ISSUE TITLE
lagging

### ISSUE THREAD

**Issue by dghub-founder** [media-kit/media-kit#651]
I using aws s3 link
So lag 
how to fix
I tested other player is fine

https://github.com/media-kit/media-kit/assets/112307287/d92babc3-1701-425c-b431-ecf3c3ad6f23

**Comment by zezo357** [comment]
> I using aws s3 link So lag how to fix I tested other player is fine
> 
>  video_2023-12-20_13-55-53.mp4

are you sure its not an internet problem? looks like it from my side, please check same link with other players and let us know,

**Comment by dghub-founder** [comment]
Now working 
Changed buffer size 32MB to 5MB
