### ISSUE TITLE
What's wrong with you

### ISSUE THREAD

**Issue by azmatjan520** [media-kit/media-kit#652]
xxxx\flutter.bat --no-color build apkFlutter assets will be downloaded from https://storage.flutter-io.cn/. Make sure you trust this source!Running Gradle task 'assembleRelease'...                        FAILURE: Build failed with an exception.* Where:Build file 'xxxx/ pub.flutter-io.cn\media_kit_libs_android_video-1.3.6\android\build.gradle' line: 102* What went wrong:A problem occurred evaluating project ':media_kit_libs_android_video'.> media_kit: arm64-v8a JAR verification failed.* Try:> Run with --stacktrace option to get the stack trace.> Run with --info or --debug option to get more log output.> Run with --scan to get full insights.* Get more help at https://help.gradle.orgbuild/ FAILED in 2sRunning Gradle task 'assembleRelease'...                         2,796msGradle task assembleRelease failed with exit code 1Process finished with exit code 1
!
 [Screenshot_2023-12-21-20-34-31-08_708f76cdf2c7449ff16a8486e0e036f6](https://github.com/media-kit/media-kit/assets/98287786/61c47d18-d0ce-49c0-9e66-e6fc57b3f91b)

**Comment by Passer-by** [comment]
1. Check your internet connection.
2. Perform the operation like [this issue](https://github.com/media-kit/media-kit/issues/642#issuecomment-1863984037)
3. Please use the internet responsibly.

**Comment by user1121114685** [comment]
第一次见发帖骂人的。

**Comment by mdddj** [comment]
有可能是翻译错了

**Comment by EchoSerendipity** [comment]
> 有可能是翻译错了

也遇到这个问题了，求解？是国内网络原因吗？

**Comment by Passer-by** [comment]
> > 有可能是翻译错了
> 
> 也遇到这个问题了，求解？是国内网络原因吗？

是的，国内网络的问题，先主动删除掉 build/media_kit_libs_android_video 目录，（或者直接调用flutter clean)
然后再加载特殊的网络环境，重新运行一下

**Comment by Passer-by** [comment]
实在不行，就根据错误里面的链接，自己去下载那个包，然后放到build/media_kit_libs_android_video目录下

**Comment by mdddj** [comment]
> > 有可能是翻译错了
> 
> 也遇到这个问题了，求解？是国内网络原因吗？

挂全局试试,多试几次

**Comment by EchoSerendipity** [comment]
> > > 有可能是翻译错了
> > 
> > 
> > 也遇到这个问题了，求解？是国内网络原因吗？
> 
> 是的，网络的问题，先主动删除掉 build/media_kit_libs_android_video 目录，（或者直接调用flutter clean) 然后再加上特殊的网络环境，重新运行一下

特殊的网络环境解决了，一把心酸泪啊

**Comment by zezo357** [comment]
> xxxx\flutter.bat --no-color build apkFlutter assets will be downloaded from https://storage.flutter-io.cn/. Make sure you trust this source!Running Gradle task 'assembleRelease'... FAILURE: Build failed with an exception.* Where:Build file 'xxxx/ pub.flutter-io.cn\media_kit_libs_android_video-1.3.6\android\build.gradle' line: 102* What went wrong:A problem occurred evaluating project ':media_kit_libs_android_video'.> media_kit: arm64-v8a JAR verification failed.* Try:> Run with --stacktrace option to get the stack trace.> Run with --info or --debug option to get more log output.> Run with --scan to get full insights.* Get more help at https://help.gradle.orgbuild/ FAILED in 2sRunning Gradle task 'assembleRelease'... 2,796msGradle task assembleRelease failed with exit code 1Process finished with exit code 1 ! [Screenshot_2023-12-21-20-34-31-08_708f76cdf2c7449ff16a8486e0e036f6](https://github.com/media-kit/media-kit/assets/98287786/61c47d18-d0ce-49c0-9e66-e6fc57b3f91b)

i think the guys in comments has the problem fixed can you try it and close issue if its fixed for you

**Comment by aike1202** [comment]
有解决的吗

**Comment by abdelaziz-mahdy** [comment]
> Is there a solution?

use a vpn, which does not block the network
