### ISSUE TITLE
Optimizing Fullscreen Performance: Addressing GPU Strain and Frame Pipeline Concerns

### ISSUE THREAD

**Issue by user1121114685** [media-kit/media-kit#654]
HI,

I hope this message finds you well. I wanted to bring to your attention a potential issue that might be affecting performance. It seems that in fullscreen mode, there is excessive refreshing occurring even when the MaterialPositionIndicator is not visible. This is putting a strain on GPU performance and could potentially lead to errors on mobile devices, such as the GPU reporting "pipelineFull: too many frames in pipeline."

Your attention to this matter is greatly appreciated.

Best regards

**Comment by user1121114685** [comment]
@alexmercerind @zezo357 Could you please assess whether this issue is worth fixing?

**Comment by zezo357** [comment]
Can you provide these details 

an example code or if it happens on the example apps


please include the versions used of the package


On which platforms it happens
