### ISSUE TITLE
Is  it possible to manipulate each frame before rendering?

### ISSUE THREAD

**Issue by dbsxdbsx** [media-kit/media-kit#657]
For example, I would like to do some frame/image processing before rendering it. Is this technically possible using this package?

**Comment by zezo357** [comment]
i think there no option to do so, you can take screen shot of the frame and then render it with your processing 


or do the overlay on top of the video player it self, 


if you explain your use case more, maybe other solutions come to mind

**Comment by dbsxdbsx** [comment]
> i think there no option to do so, you can take screen shot of the frame and then render it with your processing
> 
> or do the overlay on top of the video player it self,
> 
> if you explain your use case more, maybe other solutions come to mind

I want to apply a super video resolution algorithm to the video frame.

**Comment by zezo357** [comment]
> > i think there no option to do so, you can take screen shot of the frame and then render it with your processing
> > 
> > or do the overlay on top of the video player it self,
> > 
> > if you explain your use case more, maybe other solutions come to mind
> 
> I want to apply a super video resolution algorithm to the video frame.

From my current knowledge I don't think that's possible using mpv, or any player actually, since it requires mapping the frames to your code and then rendering it, which most probably is not fast enough to handle video playback fps

**Comment by dbsxdbsx** [comment]
Thanks~
