### ISSUE TITLE
Couldn't able to stream http streaming

### ISSUE THREAD

**Issue by balasubrahmanyams** [media-kit/media-kit#659]
I'm using python flask to stream live camera, but when i tried to stream a video over http in flutter using media_kit packages it is showing the following error  

ERROR:flutter/shell/common/shell.cc(1004)] The 'com.alexmercerind/media_kit_video' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.

**Comment by zezo357** [comment]
> I'm using python flask to stream live camera, but when i tried to stream a video over http in flutter using media_kit packages it is showing the following error
> 
> ERROR:flutter/shell/common/shell.cc(1004)] The 'com.alexmercerind/media_kit_video' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.

this is a warning, check https://github.com/media-kit/media-kit/issues/590
