### ISSUE TITLE
problem in Ubuntu

### ISSUE THREAD

**Issue by fabioselau077** [media-kit/media-kit#662]
Hello, has error in try build in Ubuntu
```
Launching lib/main_dev.dart on Linux in debug mode...
CMake Error at flutter/ephemeral/.plugin_symlinks/media_kit_video/linux/CMakeLists.txt:16 (add_library):
  Target "media_kit_video_plugin" links to target "PkgConfig::mpv" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
```

In my research they talk about adding find_package(PkgConfig REQUIRED) in CMakeLists.txt but checking the commit of this file this line was added weeks ago, unfortunately it goes out of my scope and I can't help :/

If anyone knows how to solve it I would be grateful.

In history of commit have [chore: remove find packages logic](https://github.com/media-kit/media-kit/commit/87599e08f1e09111862455e9edabbbad1c4e22f0), have relation? (Looking more closely, I believe it is the logic of the internal packages, it has no relation to Linux.)

Another thing, for Linux do I need to install any extra packages? Execute some other command?

**Comment by avsnormandie** [comment]
Hello,

Install libmpv
System shared libraries from distribution specific user-installed packages are used by-default. This is how GNU/Linux works. You can install these as follows:

Ubuntu/Debian
sudo apt install libmpv-dev mpv

see https://pub.dev/packages/media_kit#gnulinux

**Comment by molihuan** [comment]
> Hello,
> 
> Install libmpv System shared libraries from distribution specific user-installed packages are used by-default. This is how GNU/Linux works. You can install these as follows:
> 
> Ubuntu/Debian sudo apt install libmpv-dev mpv
> 
> see https://pub.dev/packages/media_kit#gnulinux

thanks
