### ISSUE TITLE
How to use SOCKS/HTTP proxy for the player's http requests

### ISSUE THREAD

**Issue by OmidNejadabbasi** [media-kit/media-kit#664]
Hi I want the player to stream the http media files through a socks or http proxy. Currently I am using `flutter_socks_proxy` and I have added this code to my main function before using media-kit: 
`SocksProxy.initProxy(proxy: 'SOCKS5 192.168.31.xxx:7891');
`

But this does not seem to work. (the player does not use it)

**Comment by MiaoMint** [comment]
You can try this, but only http proxy

https://mpv.io/manual/stable/#options-http-proxy
``` dart
 if (player.platform is NativePlayer) {
      await (player.platform as dynamic).setProperty('http-proxy', 'xxx');
 }
```

**Comment by cer-cer** [comment]
After set the proxy as your said, the m3u8 can't play...

> You can try this, but only http proxy
> 
> https://mpv.io/manual/stable/#options-http-proxy
> 
>  if (player.platform is NativePlayer) {
>       await (player.platform as dynamic).setProperty('http-proxy', 'xxx');
>  }
