### ISSUE TITLE
I want to keep video continues from its current playback position when changing the quality .

### ISSUE THREAD

**Issue by juwel-sheikh** [media-kit/media-kit#674]
I want to keep video continues from its current playback position when changing the quality but media kit has no player.setDataSource(...).
Now I needed to declare duration for loading and sometimes if load takes less time then video start from first position. How I can acheive without fixed duration?

**Comment by 23doors** [comment]
That's pretty vague. When source has multiple video qualities (like a dash or hls), just add a track selector. If url is different, save start position, load new url, set start position.
