### ISSUE TITLE
Problem with some online video (bufferin related maybe)

### ISSUE THREAD

**Issue by SpaceXM** [media-kit/media-kit#679]
I'm having some problems with playing some videos from an online source (unfortunately I can't insert the file into the post). On android and windows some video files do not play correctly, the total duration is loaded but nothing is played by the player. In addition, other video files are played correctly. On the other hand, if you download the video file, it plays without any problem, only online play is not working, also on the same file!.
Is strange but if i set the buffer size to a very high value in some case (not always) the player can start the reproduction

What could be the problem? Is there a way to fix it?

Here is the logcat (this is a firestick but also my Galaxy S23 have the same problem)

`I/media_kit(27678): com.alexmercerind.media_kit_video.VideoOutputManager.create: 3069869808
I/media_kit(27678): flutterJNIAPIAvailable = true
I/media_kit(27678): com.alexmercerind.media_kit_video.VideoOutput: id = 0
I/flutter (27678): {id: 0}
I/flutter (27678): media_kit: wakelock: _count = 1
I/media_kit(27678): com.alexmercerind.media_kit_video.VideoOutputManager.createSurface: 3069869808
I/flutter (27678): {wid: 11474}
W/VideoCapabilities(27678): Unrecognized profile 4 for video/av01
I/chatty  (27678): uid=10230(com.example.tv) Thread-6 identical 9 lines
W/VideoCapabilities(27678): Unrecognized profile 4 for video/av01
W/VideoCapabilities(27678): Unrecognized profile 4 for video/av01
I/chatty  (27678): uid=10230(com.example.tv) Thread-6 identical 9 lines
W/VideoCapabilities(27678): Unrecognized profile 4 for video/av01
W/VideoCapabilities(27678): Unsupported mime video/dolby-vision
I/chatty  (27678): uid=10230(com.example.tv) Thread-6 identical 8 lines
W/VideoCapabilities(27678): Unsupported mime video/dolby-vision
W/VideoCapabilities(27678): Unrecognized profile/level 1/32 for video/mp4v-es
W/VideoCapabilities(27678): Unrecognized profile/level 32768/2 for video/mp4v-es
W/VideoCapabilities(27678): Unrecognized profile/level 32768/64 for video/mp4v-es
I/OMXClient(27678): IOmx service obtained
I/MediaCodecLogger(27678): [ASAP] HW.omx.video.avc P2 + 132829572
W/OMXUtils(27678): do not know color format 0x7f000001 = 2130706433
I/MediaCodecLogger(27678): [ASAP] HW.omx.video.avc P2 - 132829579
I/MediaCodecLogger(27678): [ASAP] HW.omx.video.avc P3 + 132829587
I/MediaCodecLogger(27678): [ASAP] HW.omx.video.avc P3 - 132829694
I/MediaCodecLogger(27678): [ASAP] HW.omx.video.avc Got First Input Frame 132829697 pts:0
I/MediaCodecLogger(27678): updateFormatChanged width = 1920 height = 1080
I/MediaCodecLogger(27678): updatePTSTime [HW.omx.video.avc] First PTS after Flush or reset = 0
I/MediaCodecLogger(27678): [ASAP] HW.omx.video.avc Got First Frame Ready 132830078(381)
I/libOpenSLES(27678): Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2)
I/libOpenSLES(27678): AUDIOINFO: format:0x5 sample_rate:48000 channels:2 content_type:0 stream_type:0x3 selectedDeviceId:0
I/media_kit(27678): com.alexmercerind.media_kit_video.VideoOutputManager.setSurfaceTextureSize: 3069869808 1920 1080
I/MediaCodecLogger(27678): Flushing: 27678.HW.omx.video.avc.framerate = 23.952 fps
I/MediaCodecLogger(27678): 27678.HW.omx.video.avc.ASAP-P2Ms = 7
I/MediaCodecLogger(27678): 27678.HW.omx.video.avc.ASAP-P3Ms = 107
I/MediaCodecLogger(27678): 27678.HW.omx.video.avc.FirstFrameReadyMs = 381
I/OMXClient(27678): IOmx service obtained
I/MediaCodecLogger(27678): [ASAP] HW.omx.video.avc P2 + 132830920
W/OMXUtils(27678): do not know color format 0x7f000001 = 2130706433
I/MediaCodecLogger(27678): [ASAP] HW.omx.video.avc P2 - 132830929
I/MediaCodecLogger(27678): [ASAP] HW.omx.video.avc P3 + 132830930
I/MediaCodecLogger(27678): [ASAP] HW.omx.video.avc P3 - 132830956
I/MediaCodecLogger(27678): [ASAP] HW.omx.video.avc Got First Input Frame 132830960 pts:0
E/libc    (27678): Access denied finding property "vendor.product.pvr.debug_level"
E/IMGSRV  (27678): :4890: IsTextureConsistent: IMGEGLImage is not consistent
E/IMGSRV  (27678): :4890: IsTextureConsistent: IMGEGLImage is not consistent
E/IMGSRV  (27678): :4890: IsTextureConsistent: IMGEGLImage is not consistent
I/media_kit(27678): VideoOutput.WaitUntilFirstFrameRenderedNotify = 3069869808
I/flutter (27678): VideoOutput.WaitUntilFirstFrameRenderedNotify
I/flutter (27678): {handle: 3069869808}
I/flutter (27678): 3069869808
I/flutter (27678): media_kit: wakelock: _count = 0
I/flutter (27678): dispodsed
I/MediaCodecLogger(27678): 27678.HW.omx.video.avc.ASAP-P2Ms = 9
I/MediaCodecLogger(27678): 27678.HW.omx.video.avc.ASAP-P3Ms = 26
I/MediaCodecLogger(27678): 27678.HW.omx.video.avc.FirstFrameReadyMs = -132830960`

This is the media info from VLC

![Screenshot 2024-01-17 093650](https://github.com/media-kit/media-kit/assets/12715144/b747f827-c817-46a4-8ef8-1d698857fbf1)

**Comment by 23doors** [comment]
Check MPV (library media kit uses for playback on all platforms except for web) on relevant platforms first as this seems like issue on their side. Without some reproducible example, no one can do much to help.
