### ISSUE TITLE
Can't  build apps on Asahi Linux

### ISSUE THREAD

**Issue by hobleyd** [media-kit/media-kit#682]
All,

I am wanting to move from MacOS to Asahi Linux (m2 silicon, arm64) and have one problem with media_kit when I try and build my app on Asahi Linux:

```
CMake Error at flutter/ephemeral/.plugin_symlinks/media_kit_video/linux/CMakeLists.txt:16 (add_library):
  Target "media_kit_video_plugin" links to target "PkgConfig::mpv" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
```

I have tried both Fedora and Ubuntu spins of Asahi Linux and have ensured that (on Ubuntu for these names) libmpv-dev and mpv are both installed:

```
$ sudo apt install libmpv-dev mpv
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libmpv-dev is already the newest version (0.36.0-1ubuntu1).
mpv is already the newest version (0.36.0-1ubuntu1).
$
$ locate mpv.pc
/usr/lib/aarch64-linux-gnu/pkgconfig/mpv.pc
```

Can anyone please point me in the right direction.

**Comment by ahmedNY** [comment]
getting the same error on Fedora
```Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.8, on Nobara Linux 39 (KDE Plasma) 6.7.0-204.fsync.fc39.x86_64, locale
    en_US.utf8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.85.1)
[✓] Connected device (1 available)
[✓] Network resources```

**Comment by alexmercerind** [comment]
You must be familiar with your GNU/Linux distribution's package management. I haven't used every GNU/Linux flavor on planet.

In future, we might consider providing standalone static builds for GNU/Linux too like other platforms, however lack of time & interest.

**Comment by hobleyd** [comment]
Given I tested Ubuntu and the only difference being the architecture, I was hoping for a pointer of where to look next. It isn't like Ubuntu is an out-there option and I am happy to investigate; but I'm not sure where to start!
