### ISSUE TITLE
Play/Pause with Single Tap on Web

### ISSUE THREAD

**Issue by sapphire008** [media-kit/media-kit#683]
Hi, I am trying out the web examples provided on https://pub.dev/packages/media_kit (i.e. [Visit](https://media-kit.github.io/media-kit/)). On desktop browsers (Safari and Chrome), single tap does not seem to pause / play the video. However, I also tried it on my phone browser (iOS; Safari and Chrome) and the single tap function seems to work. I did not write any code in this case, as I am simply visiting the link provided on pub.dev. Is this behavior expected? If this is indeed expected, are there settings that can enable single-tap to play/pause in the Player or VideoController class?

**Comment by oddgai** [comment]
I am also concerned about the same issue. Does anyone know the details?

**Comment by abdelaziz-mahdy** [comment]
check last version on pub
