### ISSUE TITLE
RTSP speed and playlist

### ISSUE THREAD

**Issue by diegocatalao** [media-kit/media-kit#685]
Hello, Folks.

Thank you for maintaining this project. I have some questions about the playback of RTSP streams.

The first one is about the standard described in the [RTSP RFC](https://datatracker.ietf.org/doc/html/rfc2326#section-12.35) for fast video playback. I would like to know if the RTSP playback when the speed is, for example, 5.00 is sent to the RTSP server as specified in the RFC description.

The second one is about running more than one videos in the RTSP playlist. I have had no success running two URLs for the stream like this example:

```dart
await controller.player.open(Playlist([Media(liveURI1.toString()), Media(liveURI2.toString())]));
```

Would it be possible?

Thank you for maintaining the project and for your help.

**Comment by diegocatalao** [comment]
Someone here?

**Comment by zezo357** [comment]
for the speed i dont know 

but to play two live streams you will need to create two players each with its widget and it will work yes (hopefully)
