### ISSUE TITLE
Build process failed

### ISSUE THREAD

**Issue by ChiranjibGanguly** [media-kit/media-kit#693]
**Adding those file in pubspec.yaml  and trying to run in linux**

 **media_kit: ^1.1.10                             # Primary package.
  media_kit_video: ^1.2.4                        # For video rendering.
  media_kit_libs_video: ^1.0.4**

Getting this error

```
mediakitdemo/linux/flutter/ephemeral/.plugin_symlinks/media_kit_video/linux/video_output.cc:103:12: error: variable 'hardware_acceleration_supported' set but not used [-Werror,-Wunused-but-set-variable]
Exception: Build process failed
```

**System Config**

> Distributor ID:	Ubuntu
> Description:	Ubuntu 22.10
> Release:	22.10
> Codename:	kinetic 

**Linux toolchain - develop for Linux desktop**
    • Ubuntu clang version 15.0.7
    • cmake version 3.24.2
    • ninja version 1.11.0
    • pkg-config version 0.29.2

**Comment by almaz-uno** [comment]
I fixed this issue on Debian 12 with:

```
apt install libmpv-dev
```
