### ISSUE TITLE
Playing videos in a scrollable list

### ISSUE THREAD

**Issue by scottynoshotty** [media-kit/media-kit#694]
I am displaying videos as part of a page view (one video per page). What is the way to display multiple videos in a list? I have tried initiating a new player in each list item and disposing it in onDispose. The issue with this is when you scroll to the next video the previous one is disposed which kills the next video a few seconds in. I have tried reusing the same Player for the entire list. This works well but when you scroll to the next item the previous video displays for a split second before the next one loads.

**Comment by scottynoshotty** [comment]
One additional point: It appears that calling dispose() on a Player affects other current Player objects as well. As an example:

I have list items that create a Player in their initState and dispose of the player on their dispose.
When scrolling from one list item to another the next list item starts playing and then when the previous list item calls dispose on it's Player object it stops playback of the current list item.

This is strange and unexpected behavior. I would expect calling dispose on a Player to only affect the object it is called on and not any other currently constructed Players.

**Comment by Farg0k** [comment]
And if you create one player and then add videos to it through player.open?

**Comment by scottynoshotty** [comment]
Hey Farg0k,

That doesn't really work.  As you scroll from one video to the next the previous video should live on.

I think the biggest issue I have found is that dispose is very expensive and blocks the UI thread for some time making scrolling through a list of videos very janky.

**Comment by scottynoshotty** [comment]
Update:

I spent some time playing with it and I don't think dispose() is blocking the UI thread but rather calling dispose() on a previous Player instance pauses the currently playing Player. I am displaying players in a PageView and when the user scrolls to the next page I create the next Player. The next video starts playing for a second or two and then is paused when the previous player is disposed. I can press play as soon as the video is paused and it continues playing without issue. To make it more concrete here is the class representing the video widget.


```
class _PostVideoState extends State<PostVideo> {
  late final Player _player = Player();
  late final VideoController _videoController = VideoController(_player);
  late Future<void> _initializeVideoPlayerFuture;

  @override
  void initState() {
    super.initState();
    _initializeVideoPlayerFuture = initVideo();
  }

  Future<void> initVideo() async {
    String resource = "some url";
    await _player.open(Media(resource));
  }

  @override
  void dispose() async {
   // The issue happens with or without the call to pause()
    await _player.pause();
    await _player.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
        future: _initializeVideoPlayerFuture,
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.done) {
            return Container(
              width: double.infinity,
              child: GestureDetector(
                onTap: widget.postVideoController.playOrPause,
                child: AspectRatio(
                  aspectRatio: widget.post.blobs[1].aspectRatio,
                  child: Video(
                    controller: _videoController,
                  ),
                ),
              ),
            );
          } else {
            return Container(
              width: double.infinity,
              child: AspectRatio(
                aspectRatio: widget.post.blobs[1].aspectRatio,
                child: Container(
                  color: Theme.of(context).colorScheme.background,
                ),
              ),
            );
          }
        });
  }
}
```

**Comment by scottynoshotty** [comment]
The issue is different on Android as well. On Android is does not pause the video but rather around 1 second in to playing the next video there is a slight pause when the previous video calls dispose() and then the video plays without issue. It looks like in that case dispose is pausing the UI thread slightly which causes the glitch in the video

**Comment by gaganyadav80** [comment]
Hi @scottynoshotty, I am also facing the same issue. Were you able to find any workaround?

**Comment by gaganyadav80** [comment]
@alexmercerind  

I’ve think the line that appears to be causing the issue is this one:
https://github.com/media-kit/media-kit/blob/main/media_kit/lib/src/player/native/player/real.dart#L98

Calling `stop()` inside `NativePlayer.dispose()` causes other `NativePlayer` instances to pause without their `playing` state being updated. Right after the `stop()` call inside `dispose()` completes, the currently active player’s gets paused unexpectedly.

**Workaround:** after disposing the old player, trigger a pause/play cycle on the current player to resync its state:

```dart
await oldPlayer.dispose();

Future.delayed(Duration.zero, () async {
  await currentPlayer.pause();
  await currentPlayer.play();
});
```
