### ISSUE TITLE
App closes when player.open() runs. (Win11)

### ISSUE THREAD

**Issue by vindolin** [media-kit/media-kit#703]
I created a new app and added the example app from the README.md, added the dependencies to pubspec.yaml.

It builds on Win11 but when player.open(...) is called, the app closes without an error.

![image](https://github.com/media-kit/media-kit/assets/834347/0284d4fc-3cf2-476c-88b6-f952a2da8c85)

Interestingly when I clone the github repo and run the app, all examples run perfectly.

The same app also runs fine in Android/Web.

**Comment by zezo357** [comment]
can you share the logs ?
for example create the player with these settings to show all logs, it will help find the issue
```
    player =
        Player(configuration: PlayerConfiguration(logLevel: MPVLogLevel.debug));
    player.stream.log.listen((event) {
      print("log $event");
    });
```

**Comment by vindolin** [comment]
> can you share the logs ? for example create the player with these settings to show all logs, it will help find the issue
> 
> ```
>     player =
>         Player(configuration: PlayerConfiguration(logLevel: MPVLogLevel.debug));
>     player.stream.log.listen((event) {
>       print("log $event");
>     });
> ```

![image](https://github.com/media-kit/media-kit/assets/834347/010a6307-8dba-4d4a-b173-723f12cbf405)

**Comment by alexmercerind** [comment]
Can you try to make these changes locally?

https://github.com/media-kit/media-kit/pull/619/files

**Comment by vindolin** [comment]
That worked, the video plays now.

**Comment by zezo357** [comment]
closing since it got fixed on github, will need to release it on pub.dev
