### ISSUE TITLE
Exception: Cannot find libmpv.so. Please ensure it's presence in the APK.

### ISSUE THREAD

**Issue by codeswot** [media-kit/media-kit#704]
As per the Documentation, I added   MediaKit.ensureInitialized(); in my main function so  

``` 
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  MediaKit.ensureInitialized();
}
```
  but I get the following error whenever I try to start the app
  ` media_kit: ERROR: MediaKit.ensureInitialized
I/flutter ( 6527): This indicates that one or more required dependencies could not be located.
I/flutter ( 6527): 
I/flutter ( 6527): Refer to the "Installation" section of the README for further details:
I/flutter ( 6527): GitHub: https://github.com/media-kit/media-kit#installation
I/flutter ( 6527): pub. dev : https://pub.dev/packages/media_kit#installation
I/flutter ( 6527): 
I/flutter ( 6527): TIP: Copy-paste required packages from the above link to your pubspec. yaml.
I/flutter ( 6527): 
I/flutter ( 6527): If you recently added the packages, make sure to re-run the project ("hot-restart" & "hot-reload" is not sufficient for native plugins).
I/flutter ( 6527): --------------------------------------------------------------------------------
E/flutter ( 6527): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Cannot find libmpv.so. Please ensure it's presence in the APK.
E/flutter ( 6527): #0      NativeLibrary.ensureInitialized (package:media_kit/src/player/native/core/native_library.dart:78:9)`
and I believe the error is mostly related to this log here`Unhandled Exception: Exception: Cannot find libmpv.so. Please ensure it's presence in the APK.`
because when I initialize the Mediakit like so. `MediaKit.ensureInitialized(libmpv: '');` all the error go away`

I was running the app on an Android TV Emulator running Android S with the arm64 architecture

these are my package combinations in pubspec.yaml

```
media_kit: ^1.1.10                         
media_kit_video: ^1.2.4                       
media_kit_libs_video: ^1.0.4
```
Note I am using a Macbook Pro with M1Pro chip, if that is important

**Comment by zezo357** [comment]
does that only happen on android tv? 

does android emulator work? if yes then maybe its an android version problem? in the docs its 
Android 5.0 or above. , but i dont know what is android s version is.

**Comment by codeswot** [comment]
I haven’t tested it on a mobile android emulator. But also note the android
tv emulator is running on androids 12

**Comment by zezo357** [comment]
so its not a version issue, but can you test on the emulator and let us know? or even a real device.

**Comment by codeswot** [comment]
> so its not a version issue, but can you test on the emulator and let us know? or even a real device.

I just ran it on a physical device (Pixel 4XL using android 13)
I indeed got the same error

**Comment by codeswot** [comment]
> > so its not a version issue, but can you test on the emulator and let us know? or even a real device.
> 
> I just ran it on a physical device (Pixel 4XL using android 13) I indeed got the same error

if I may add. this seems to only affect android devices, it runs fine on iOS simulator

**Comment by zezo357** [comment]
Very weird, if the package is added and it works on iOS it should work on Android,  since the package adds the files for both, 


Maybe a flutter clean and rerun may help? I don't know the problem and just stating normal trouble shooting stuff now 😂

**Comment by codeswot** [comment]
I did a `flutter clean`, but at first it did not solve the issue, I then deleted the Android folder and did a `flutter create  .`
this solved it. 
Thank you for your help

**Comment by zezo357** [comment]
> I did a `flutter clean`, but at first it did not solve the issue, I then deleted the Android folder and did a `flutter create  .`
> this solved it. 
> Thank you for your help

Mmmm ok, glad it got solved.

Thank you for letting me know

**Comment by windmillcode0** [comment]
i have the same issue however i cant do this i have quite bit configuration in my android app

**Comment by Judimax** [comment]
for me downgrading to java 17 and doing nothing else did the trick this should be the case I want to develop with Java 21
