### ISSUE TITLE
Android impller support 

### ISSUE THREAD

**Issue by abdelaziz-mahdy** [media-kit/media-kit#707]
based on my testing running android with --enable-impeller will result in a black video playing, don't know if its an issue with flutter it self or not, but i saw an issue explaining that support for platform views are not stable yet on impeller, tested on flutter 3.19.0, keeping this for the record

**Comment by Predidit** [comment]
Enable Impeller support in release mode also leads to black video playing. 

The application is running in vulcan mode, and media_kit hardware accelerated is enable.

**Comment by tiltmaster** [comment]
so what ur telling me is that this issue is going to remain as such because it doesnt support impeller?

**Comment by abdelaziz-mahdy** [comment]
Even video_player doesn't support it yet

**Comment by tiltmaster** [comment]
man, so i really picked the wrong framework to work with for the last 4 years, it feels as if Flutter and dart is just isnt built for any real-world application besides making a simple firebase notes application or something that simple, beyond that it feels you need an entire team to fix what isnt even supported.

**Comment by abdelaziz-mahdy** [comment]
If you are comparing flutter to native, yes native has more features since you got access to everything that the platform provides, flutter compared to other cross platform frameworks 
Flutter is much better from my point of view,


Impeller is not fully supported yet on Android it's only in preview, so I don't understand the problem

**Comment by tiltmaster** [comment]
> If you are comparing flutter to native, yes native has more features since you got access to everything that the platform provides, flutter compared to other cross platform frameworks Flutter is much better from my point of view,
> 
> Impeller is not fully supported yet on Android it's only in preview, so I don't understand the problem

brother, this framework barely supports playing videos. please.

**Comment by 23doors** [comment]
Feel free to use a different one. This isn't a place for venting your unfounded frustration.

**Comment by abdelaziz-mahdy** [comment]
> > If you are comparing flutter to native, yes native has more features since you got access to everything that the platform provides, flutter compared to other cross platform frameworks Flutter is much better from my point of view,
> > 
> > Impeller is not fully supported yet on Android it's only in preview, so I don't understand the problem
> 
> brother, this framework barely supports playing videos. please.

Let's think about checking other cross platform frameworks and you will find out that none is perfect but each try to handle it in its own way 


Flutter tries to support all platforms for the main features and rendering engine and open source community helps improve that by contributing,

This package for example is open source and anyone can contribute to it 

For example: Npm packages are the same it's made by the community, it's just they are a lot more mature than flutter, due to how new flutter is, 

anyway each one of us picks what fits their use cases the most, if flutter is not enough and you can't improve it, check the other framework for what suits you the most

**Comment by cts-cts** [comment]
same issue!

**Comment by abdelaziz-mahdy** [comment]
The migration was not done in the package, and the issue is being investigated, check open pr,


When it's merged the fix will be available

**Comment by Predidit** [comment]
Android impller is enabled by default after flutter/flutter#54156. I think this will land on stable channel soon.

Can we expect media_kit package support for android impller？

**Comment by abdelaziz-mahdy** [comment]
I don't think there is a problem doing so, but video player package still doesn't support it yet

**Comment by Predidit** [comment]
video_player already support that. It works very well.

**Comment by Predidit** [comment]
https://docs.flutter.dev/release/breaking-changes/android-surface-plugins

Seems that Impller won't break older API any more in the next stable release.

Maybe migrating to SurfaceProducer is not an emergency.

**Comment by abdelaziz-mahdy** [comment]
It's a necessity, if you close the screen and return it won't display anything due to the surface being destroyed and it won't benefit from the impeller

**Comment by abdelaziz-mahdy** [comment]
@Predidit actually the impeller fix landed on video_player will try to do it https://pub.dev/packages/video_player_android/changelog

**Comment by abdelaziz-mahdy** [comment]
@Predidit @tiltmaster can you guys test this pr https://github.com/media-kit/media-kit/pull/824 and let me know if there is any problem?

**Comment by Predidit** [comment]
Thanks for your effots, it works very well now.

**Comment by abdelaziz-mahdy** [comment]
> Thanks for your effots, it works very well now.

Thank you for testing it out, just one more to check before releasing it 


There was a problem with surface destroying on closing the app screen it should work now but I need to test it before releasing

**Comment by Predidit** [comment]
I test it on Android14 (API 34) with https://github.com/media-kit/media-kit/actions/runs/10550943409/artifacts/1852459477

Surface will be destroyed after the screen is closed but will be recreated when the screen is opened. I can see a flicker when the screen is opened.

But I think it's totally acceptable, and overall it works pretty well

**Comment by abdelaziz-mahdy** [comment]
Wow thank you for testing it will go through with the release, first thing in the morning tomorrow I think, note this will only work on latest version

**Comment by tiltmaster** [comment]
> @Predidit @tiltmaster can you guys test this pr #824 and let me know if there is any problem?

Unfortunately, since media-kit isnt supporting HLS, i dont think i would be able to do so, but i believe you have fixed it so, hopefully there is plans to support HLS.

**Comment by Predidit** [comment]
@tiltmaster 

media_kit is well compatible with HLS video in any mainstream standard format. Maybe you are playing HLS with disguised file header. Producers of video streams often abuse public free image hosting services in this way.

AVPlayer/ExoPlayer(offical video player in iOS/android) can play those non-standard video streaming. But more versatile players, like VLC/MPV can't play them.

media_kit is based on MPV. So it can't play those non-standard video streaming

**Comment by tiltmaster** [comment]
> @tiltmaster
> 
> media_kit is well compatible with HLS video in any mainstream standard format. Maybe you are playing HLS with disguised file header. Producers of video streams often abuse public free image hosting services in this way.
> 
> AVPlayer/ExoPlayer(offical video player in iOS/android) can play those non-standard video streaming. But more versatile players, like VLC/MPV can't play them.
> 
> media_kit is based on MPV. So it can't play those non-standard video streaming

Hey, I was told and even tested it, I am even using BunnyCDN, and it kept giving me errors from what i remember related to incorrect format.

**Comment by Predidit** [comment]
@tiltmaster 

The following response assumes that the file headers of your video stream are disguised.

If your video stream's file headers are disguised, and you cannot correctly play the stream using mpv on Windows, then media_kit will also be unable to do so. The hosting location does not affect the format of the video stream itself or whether it is disguised. This kind of disguise is applied to the TS segments. In fact, as far as I know, most desktop platform players cannot parse such an unusual video stream.

And fell free to send a sample link here. I am interested in disguised HLS stream.

**Comment by tiltmaster** [comment]
> @tiltmaster
> 
> The following response assumes that the file headers of your video stream are disguised.
> 
> If your video stream's file headers are disguised, and you cannot correctly play the stream using mpv on Windows, then media_kit will also be unable to do so. The hosting location does not affect the format of the video stream itself or whether it is disguised. This kind of disguise is applied to the TS segments. In fact, as far as I know, most desktop platform players cannot parse such an unusual video stream.
> 
> And fell free to send a sample link here. I am interested in disguised HLS stream.

Sure, this is a link from my collection with auth (It will expire within 1 hour) : link: https://vz-43157b54-d1e.b-cdn.net/bcdn_token=w3Qii_mbxrWlUShYqDAwSeFmqv2SV4W7qr82WmotqDw&expires=1724910008&token_path=%2F378c87e4-54db-4fb4-84ee-82f19bb7cfd1%2F/378c87e4-54db-4fb4-84ee-82f19bb7cfd1/playlist.m3u8, i dont think its hidden tho.

**Comment by Predidit** [comment]
```
[h264 @ 000002CB296AB980] Reinit context to 1440x1088, pix_fmt: yuv420p
Input #0, mpegts, from 'D:\Download\video0.ts':
  Duration: 00:00:01.75, start: 1.466667, bitrate: 3255 kb/s
  Program 1
    Metadata:
      service_name    : Service01
      service_provider: FFmpeg
  Stream #0:0[0x100]: Video: h264, 1 reference frame ([27][0][0][0] / 0x001B), yuv420p(tv, bt470bg/bt470bg/smpte170m, progressive, left), 1440x1080, 30 fps, 30 tbr, 90k tbn
  Stream #0:1[0x101]: Audio: aac ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 206 kb/s
[AVIOContext @ 000002CB2968D180] Statistics: 961768 bytes read, 2 seeks
```

This is a standard H.264 stream without any disguise, and it's not an H.264 raw stream either, but it still seems unplayable. Maybe we need @abdelaziz-mahdy 's help.

**Comment by tiltmaster** [comment]
> ```
> [h264 @ 000002CB296AB980] Reinit context to 1440x1088, pix_fmt: yuv420p
> Input #0, mpegts, from 'D:\Download\video0.ts':
>   Duration: 00:00:01.75, start: 1.466667, bitrate: 3255 kb/s
>   Program 1
>     Metadata:
>       service_name    : Service01
>       service_provider: FFmpeg
>   Stream #0:0[0x100]: Video: h264, 1 reference frame ([27][0][0][0] / 0x001B), yuv420p(tv, bt470bg/bt470bg/smpte170m, progressive, left), 1440x1080, 30 fps, 30 tbr, 90k tbn
>   Stream #0:1[0x101]: Audio: aac ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 206 kb/s
> [AVIOContext @ 000002CB2968D180] Statistics: 961768 bytes read, 2 seeks
> ```
> 
> This is a standard H.264 stream without any disguise, and it's not an H.264 raw stream either, but it still seems unplayable. Maybe we need @abdelaziz-mahdy 's help.

See what I mean? i am using a standard way of streaming using BunnyCDN, which is really good and not shady. but errors arise on media_kit, tho i would love to use it instead of a off-brand BetterPlayer lol.

**Comment by abdelaziz-mahdy** [comment]
> > ```
> > [h264 @ 000002CB296AB980] Reinit context to 1440x1088, pix_fmt: yuv420p
> > Input #0, mpegts, from 'D:\Download\video0.ts':
> >   Duration: 00:00:01.75, start: 1.466667, bitrate: 3255 kb/s
> >   Program 1
> >     Metadata:
> >       service_name    : Service01
> >       service_provider: FFmpeg
> >   Stream #0:0[0x100]: Video: h264, 1 reference frame ([27][0][0][0] / 0x001B), yuv420p(tv, bt470bg/bt470bg/smpte170m, progressive, left), 1440x1080, 30 fps, 30 tbr, 90k tbn
> >   Stream #0:1[0x101]: Audio: aac ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 206 kb/s
> > [AVIOContext @ 000002CB2968D180] Statistics: 961768 bytes read, 2 seeks
> > ```
> > 
> > This is a standard H.264 stream without any disguise, and it's not an H.264 raw stream either, but it still seems unplayable. Maybe we need @abdelaziz-mahdy 's help.
> 
> See what I mean? i am using a standard way of streaming using BunnyCDN, which is really good and not shady. but errors arise on media_kit, tho i would love to use it instead of a off-brand BetterPlayer lol.

Can you show me the logs from the stream maybe it will show the problem

**Comment by tiltmaster** [comment]
> > > ```
> > > [h264 @ 000002CB296AB980] Reinit context to 1440x1088, pix_fmt: yuv420p
> > > Input #0, mpegts, from 'D:\Download\video0.ts':
> > >   Duration: 00:00:01.75, start: 1.466667, bitrate: 3255 kb/s
> > >   Program 1
> > >     Metadata:
> > >       service_name    : Service01
> > >       service_provider: FFmpeg
> > >   Stream #0:0[0x100]: Video: h264, 1 reference frame ([27][0][0][0] / 0x001B), yuv420p(tv, bt470bg/bt470bg/smpte170m, progressive, left), 1440x1080, 30 fps, 30 tbr, 90k tbn
> > >   Stream #0:1[0x101]: Audio: aac ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 206 kb/s
> > > [AVIOContext @ 000002CB2968D180] Statistics: 961768 bytes read, 2 seeks
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > This is a standard H.264 stream without any disguise, and it's not an H.264 raw stream either, but it still seems unplayable. Maybe we need @abdelaziz-mahdy 's help.
> > 
> > 
> > See what I mean? i am using a standard way of streaming using BunnyCDN, which is really good and not shady. but errors arise on media_kit, tho i would love to use it instead of a off-brand BetterPlayer lol.
> 
> Can you show me the logs from the stream maybe it will show the problem

i would have to check and get back on this, but it was sure an error with ExoPlayer and source.

**Comment by abdelaziz-mahdy** [comment]
> > > > ```
> > > > [h264 @ 000002CB296AB980] Reinit context to 1440x1088, pix_fmt: yuv420p
> > > > Input #0, mpegts, from 'D:\Download\video0.ts':
> > > >   Duration: 00:00:01.75, start: 1.466667, bitrate: 3255 kb/s
> > > >   Program 1
> > > >     Metadata:
> > > >       service_name    : Service01
> > > >       service_provider: FFmpeg
> > > >   Stream #0:0[0x100]: Video: h264, 1 reference frame ([27][0][0][0] / 0x001B), yuv420p(tv, bt470bg/bt470bg/smpte170m, progressive, left), 1440x1080, 30 fps, 30 tbr, 90k tbn
> > > >   Stream #0:1[0x101]: Audio: aac ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 206 kb/s
> > > > [AVIOContext @ 000002CB2968D180] Statistics: 961768 bytes read, 2 seeks
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > This is a standard H.264 stream without any disguise, and it's not an H.264 raw stream either, but it still seems unplayable. Maybe we need @abdelaziz-mahdy 's help.
> > > 
> > > 
> > > See what I mean? i am using a standard way of streaming using BunnyCDN, which is really good and not shady. but errors arise on media_kit, tho i would love to use it instead of a off-brand BetterPlayer lol.
> > 
> > Can you show me the logs from the stream maybe it will show the problem
> 
> i would have to check and get back on this, but it was sure an error with ExoPlayer and source.

Try it on the package example and just add the logs part.

**Comment by alexmercerind** [comment]
Landed on `main`.

**Comment by ferraridamiano** [comment]
Flutter 3.27 just dropped with impeller enabled by default on android. When will the next version be released on pub.dev @alexmercerind
