### ISSUE TITLE
Videos not adding to playlist as expected | Windows 11

### ISSUE THREAD

**Issue by isaacy13** [media-kit/media-kit#708]
Howdy all,

I'm running into an issue where calling `player.add(Media(...))` isn't adding the media to the playlist, despite no error being thrown in `.onError`

- media_kit 1.1.10
- media_kit_video 1.2.4
- media_kit_libs_video 1.0.4

** was previously using older versions of library & running into same issue, updating to latest did not resolve behavior

Repo steps:
- `await player.open(Playlist([Media(...)]), play: true)`
- `await player.add(Media(...))`
- `await player.add(Media(...))`
- `await player.add(Media(...))`
- Even though `.onError` will not be called & `.then` will execute, the playlist will only have 3 items

Notes:
- in my actual code, I'm limited to two items -- so # of videos don't seem to be issue
- if you change order you open videos (e.g.: D, C, B, A instead of A, B, C, D) this behavior still occurs -- so issues don't seem to be with video files

**Comment by isaacy13** [comment]
Longer example:

--- main.dart
```
void main(List<String> args) {
   MediaKit.ensureInitialized();
   runApp(ReproApp);
}
```
--- end main.dart


--- repro_app.dart
[example.txt](https://github.com/media-kit/media-kit/files/14324427/example.txt)
--- end repro_app.dart

**Comment by zezo357** [comment]
can you provide logs? 
 player =
        Player(configuration: PlayerConfiguration(logLevel: MPVLogLevel.debug));
    player.stream.log.listen((event) {
      print("log $event");
    });
    
    just incase its a problem with mpv

**Comment by isaacy13** [comment]
Ah yeah, looks like path character issue (emojis and/or apostrophes)
- first video with apostrophe worked, but second video with apostrophes in path had fatal error
- confirmed removing special characters fixed issue

<img width="700" alt="image" src="https://github.com/media-kit/media-kit/assets/65752735/5b48b3ee-4504-4025-9158-61f7153c993d">

[media_kit_video_logs.txt](https://github.com/media-kit/media-kit/files/14324525/media_kit_video_logs.txt)

**Comment by zezo357** [comment]
nice, glad it got fixed

**Comment by isaacy13** [comment]
Sorry just got back to this

Any chance there'd be plans to support files with special characters in them? (e.g.: apostrophes, emojis, etc.)
