### ISSUE TITLE
ld: framework not found Mpv

### ISSUE THREAD

**Issue by hndrbrm** [media-kit/media-kit#709]
When run with target macos, throws this error

```
Launching lib/main.dart on macOS in debug mode...
Running pod install...
Building macOS application...
Command CompileSwiftSources failed with a nonzero exit code
Command CompileSwiftSources failed with a nonzero exit code
ld: warning: directory not found for option '-F/Users/eyem/Downloads/shortcam/shortcam_lite_frontend/macos/Pods/../Flutter/ephemeral/.symlinks/plugins/media_kit_libs_macos_video/macos/Frameworks/.symlinks/mpv/macos'
ld: framework not found Mpv
clang: error: linker command failed with exit code 1 (use -v to see invocation)
** BUILD FAILED **

Error: Build process failed
```

Further investigate, found out that theres error in here:
https://github.com/media-kit/media-kit/blob/63c6ebe8366db7ecfbd13ab9ce76b11dd86dae48/libs/macos/media_kit_libs_macos_video/macos/create_framework_symlinks.sh#L64

`NAME="$(echo "${SLUG}" | cut -d '-' -f 1 -f 3)"`
When i try to run that in terminal it throws error
```
cut: only one list may be specified
Try 'cut --help' for more information.
```

The solution is obvious the `-f 1 -f 3` should be `-f 1,3`:
`NAME="$(echo "${SLUG}" | cut -d '-' -f 1,3)"`

After that run it:
`sh create_framework_symlinks.sh Frameworks/Mpv.xcframework Frameworks/.symlinks/mpv`
Then its working.

Somehow i must manually run above script once time.
But if i clear the flutter cache (package cache), i need to manually run above script, to symlink the mpv.
Somehow i could not just click run button inside android studio without error, the first time i use media kit.
But after successfull running, its cached, no need to run it anymore.

**Comment by zezo357** [comment]
@birros can you check this? since i have no knowledge in ios/macos

**Comment by lucasjinreal** [comment]
ld: framework 'Mpv' not found

**Comment by abdelaziz-mahdy** [comment]
> ld: framework 'Mpv' not found

I don't know what you mean, but if you are using media_kit from pub 
Use it from GitHub main branch

**Comment by lucasjinreal** [comment]
I  just run APPFlowy build flutter whihc uses media-kit, just claims me thi error...

**Comment by abdelaziz-mahdy** [comment]
> APPFlowy

can you share you pubspec?

**Comment by lucasjinreal** [comment]
it might not related to media-kit, but applfowy, I just clone their repo and build got error.

**Comment by abdelaziz-mahdy** [comment]
> it might not related to media-kit, but applfowy, I just clone their repo and build got error.

If you are using media_kit from pub it may be the problem, since the pr mentioned here was not published on pub yet, this is why I am mentioning to get media_kit from main branch

**Comment by vmwsree** [comment]
I still have this issue, I pointed it to use github but same error perisist

**Comment by cpfeiffer** [comment]
If someone still experiences this error, here's why we had it:

The package media_kit_libs_macos_video (1.1.4 at least) contains the script `create_framework_symlinks.sh` with carriage return line endings (see #338). The bad line endings are supposed to be fixed client-side with a `sed` command.

However this sed-command only works with BSD sed. If you have GNU sed first in your PATH, it will silently fail. The fix is to put BSD sed first in the PATH or use a wrapper script to decide which sed to use.
