### ISSUE TITLE
Request Feature: Custom parameter passed to mpv

### ISSUE THREAD

**Issue by hndrbrm** [media-kit/media-kit#710]
In class `NativeVideoController` the creation of the MPV

```dart
    NativeLibrary.ensureInitialized();
    final mpv = MPV(DynamicLibrary.open(NativeLibrary.path));
    final values = {
      'vo': configuration.vo ?? 'libmpv',
      'hwdec': configuration.hwdec ?? 'auto',
      'vid': 'auto',
    };
```

I need to pass low latency parameter in there, since i want to stream live rtsp.
Something like this:
```dart
    final values = {
      'vo': configuration.vo ?? 'libmpv',
      'hwdec': configuration.hwdec ?? 'auto',
      'vid': 'auto',

      // Add this
      'profile': 'low-latency',
      'untimed': '',
      'no-cache': '',
      'no-demuxer-thread': '',
      'vd-lavc-threads': '1',
      
    };
```
I tried parameter above and its worked, the video stream with low latency.

Is it possible to add some mechanism for that, something like this:
```dart
    final values = {
      'vo': configuration.vo ?? 'libmpv',
      'hwdec': configuration.hwdec ?? 'auto',
      'vid': 'auto',
      
      // Add something like this,
      // so the user could add any probable native parameter in there
      if (configuration.extras != null)
      ...configuration.extras,
    };
```

**Comment by zezo357** [comment]
feel free to open a pr

**Comment by reteset** [comment]
> In class `NativeVideoController` the creation of the MPV
> 
> ```dart
>     NativeLibrary.ensureInitialized();
>     final mpv = MPV(DynamicLibrary.open(NativeLibrary.path));
>     final values = {
>       'vo': configuration.vo ?? 'libmpv',
>       'hwdec': configuration.hwdec ?? 'auto',
>       'vid': 'auto',
>     };
> ```
> 
> I need to pass low latency parameter in there, since i want to stream live rtsp. Something like this:
> 
> ```dart
>     final values = {
>       'vo': configuration.vo ?? 'libmpv',
>       'hwdec': configuration.hwdec ?? 'auto',
>       'vid': 'auto',
> 
>       // Add this
>       'profile': 'low-latency',
>       'untimed': '',
>       'no-cache': '',
>       'no-demuxer-thread': '',
>       'vd-lavc-threads': '1',
>       
>     };
> ```
> 
> I tried parameter above and its worked, the video stream with low latency.
> 
> Is it possible to add some mechanism for that, something like this:
> 
> ```dart
>     final values = {
>       'vo': configuration.vo ?? 'libmpv',
>       'hwdec': configuration.hwdec ?? 'auto',
>       'vid': 'auto',
>       
>       // Add something like this,
>       // so the user could add any probable native parameter in there
>       if (configuration.extras != null)
>       ...configuration.extras,
>     };
> ```
Hi
You can use something like below 
```
final player = Player();
NativePlayer native = player.platform as NativePlayer;
native.setProperty('profile', 'low-latency');
```

**Comment by syleishere** [comment]
can we just have a mpv.conf file in a directory to just add whatever options we like like how it is done with mpv?
