### ISSUE TITLE
m3u8 file with #EXT-X-DISCONTINUITY, controller.value.position is wrong

### ISSUE THREAD

**Issue by aaronxmc** [media-kit/media-kit#713]
I have a m3u8 file:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:10
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-PROGRAM-DATE-TIME:2024-02-22T04:28:17.495
#EXTINF:10.0,
https://...._0.ts,
#EXTINF:10.0,
https://...._1.ts
#EXTINF:10.0,
https://...._2.ts,
#EXT-X-DISCONTINUITY
https://...._0.ts,
https://...._1.ts
https://...._2.ts`
```

After #EXT-X-DISCONTINUITY , controller.value.position  go back to 0:00:00.000000

I have test same m3u8 file with video_player, Its position is correct.

My operating system is Flutter (Channel stable, 3.16.0, on macOS 14.2.1 23C71 darwin-arm64)

**Comment by zezo357** [comment]
```
 player =
        Player(configuration: PlayerConfiguration(logLevel: MPVLogLevel.debug));
    player.stream.log.listen((event) {
      print("log $event");
    });
 ```
 
 check the logs it may show the reason for the failure

**Comment by zezo357** [comment]
Can you try two things 


First try to disable hardware decoding



And maybe remove the the tag that causes the file to fail and play it 


Let me know if either worked for you

**Comment by aaronxmc** [comment]
@zezo357 
I set hwdec: 'no'
`controller = VideoController(player,
        configuration: const VideoControllerConfiguration(hwdec: 'no'));`

controller.value.position still back  to 0:00:00.000000

And I see log:
```
`flutter: log PlayerLog(prefix: ad, level: warn, text: Invalid audio PTS: 180.431093 -> 0.000000)
flutter: log PlayerLog(prefix: cplayer, level: warn, text: Reset playback due to audio timestamp reset.)
flutter: log PlayerLog(prefix: cplayer, level: v, text: blocked, waiting for old audio to play)
flutter: log PlayerLog(prefix: cplayer, level: v, text: audio ready)
flutter: log PlayerLog(prefix: ffmpeg/video, level: debug, text: h264: Reinit context to 1920x1088, pix_fmt: yuv420p)
flutter: log PlayerLog(prefix: ffmpeg/video, level: error, text: h264: co located POCs unavailable)
flutter: log PlayerLog(prefix: ffmpeg/video, level: error, text: h264: co located POCs unavailable)
flutter: log PlayerLog(prefix: ffmpeg, level: error, text: tcp: ffurl_read returned 0xdfb9b0bb)`
```

additional information:
When the video start,  log:
```
`flutter: log PlayerLog(prefix: ffmpeg, level: debug, text: resize stream to 131072 bytes, drop 0 bytes)
flutter: log PlayerLog(prefix: ffmpeg, level: v, text: Mime-type: 'application/vnd.apple.mpegurl;charset=UTF-8')
flutter: log PlayerLog(prefix: ffmpeg, level: debug, text: Stream opened successfully.)
flutter: log PlayerLog(prefix: demux, level: v, text: Trying demuxers for level=normal.)
flutter: log PlayerLog(prefix: demux, level: debug, text: Trying demuxer: disc (force-level: normal))
flutter: log PlayerLog(prefix: demux, level: debug, text: Trying demuxer: edl (force-level: normal))
flutter: log PlayerLog(prefix: demux, level: debug, text: Trying demuxer: cue (force-level: normal))
flutter: log PlayerLog(prefix: demux, level: debug, text: Trying demuxer: rawaudio (force-level: normal))
flutter: log PlayerLog(prefix: demux, level: debug, text: Trying demuxer: rawvideo (force-level: normal))
flutter: log PlayerLog(prefix: demux, level: debug, text: Trying demuxer: mkv (force-level: normal))
flutter: log PlayerLog(prefix: demux, level: debug, text: Trying demuxer: lavf (force-level: normal))
flutter: log PlayerLog(prefix: lavf, level: v, text: Found 'hls' at score=100 size=2048.)
flutter: log PlayerLog(prefix: ffmpeg, level: debug, text: tcp: Starting connection attempt to 54.223.139.65 port 443)
flutter: log PlayerLog(prefix: ffmpeg, level: debug, text: tcp: Successfully connected to 54.223.139.65 port 443)
flutter: log PlayerLog(prefix: ffmpeg/demuxer, level: v, text: hls: Skip ('#EXT-X-VERSION:3'))
flutter: log PlayerLog(prefix: ffmpeg/demuxer, level: v, text: hls: Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-02-22T04:28:17.495'))
flutter: log PlayerLog(prefix: ffmpeg/demuxer, level: v, text: hls: Skip ('#EXT-X-DISCONTINUITY'))
flutter: log PlayerLog(prefix: ffmpeg/demuxer, level: v, text: hls: Skip ('#EXT-X-DISCONTINUITY'))
flutter: log PlayerLog(prefix: ffmpeg/demuxer, level: v, text: hls: Skip ('#EXT-X-DISCONTINUITY'))
flutter: log PlayerLog(prefix: ffmpeg/demuxer, level: v, text: hls: Skip ('#EXT-X-DISCONTINUITY'))
flutter: log PlayerLog(prefix: ffmpeg/demuxer, level: v, text: hls: Skip ('#EXT-X-DISCONTINUITY'))`
```

**Comment by zezo357** [comment]
issues on mpv related to your issue 
https://github.com/mpv-player/mpv/issues/5126

https://github.com/mpv-player/mpv/issues/11024


try removing the tag and see if it will work for you, other than that looks like you will wait for @alexmercerind since he has better knowledge in that matter than me

**Comment by aaronxmc** [comment]
@zezo357 
Thanks 
remove tag #EXT-X-DISCONTINUITY ,  the video can play ok

**Comment by zezo357** [comment]
glad to know that it worked

**Comment by zezo357** [comment]
> @zezo357 
> I set 'hwdec' no and remove tag #EXT-X-DISCONTINUITY 
> Unfortunately, I found that the modification did not take effect today.
> The previous one can play ok like a special phenomenon.
> still get error log:
> ```
> `flutter: log PlayerLog(prefix: ad, level: warn, text: Invalid audio PTS: 114.048000 -> 0.000000)
> flutter: log PlayerLog(prefix: cplayer, level: warn, text: Reset playback due to audio timestamp reset.)
> flutter: log PlayerLog(prefix: cplayer, level: v, text: blocked, waiting for old audio to play)
> flutter: log PlayerLog(prefix: cplayer, level: v, text: audio ready)`
> ```
> 
> 

Sadly I don't know more, even the issues on mpv didn't get fixed or used the fix I mentioned

**Comment by alexmercerind** [comment]
This may or may not work, but try to delete this line locally:

https://github.com/media-kit/media-kit/blob/63c6ebe8366db7ecfbd13ab9ce76b11dd86dae48/media_kit/lib/src/player/native/player/real.dart#L2442

**Comment by alexmercerind** [comment]
https://ffmpeg.org/pipermail/ffmpeg-devel/2018-March/226706.html
