### ISSUE TITLE
Media-Kit build issue for Mac Build within MS App Center CI

### ISSUE THREAD

**Issue by sachindeorah** [media-kit/media-kit#714]
[command]/usr/local/lib/ruby/gems/3.0.0/bin/pod install --repo-update
Updating local specs repositories
Analyzing dependencies
make: Nothing to be done for `all'.
make: Nothing to be done for `all'.
media_kit: ERROR: No pubspec.lock was found: ENV["PWD"] = "/"
[!] Failed to load 'media_kit_native_event_loop' podspec: 
[!] Invalid `media_kit_native_event_loop.podspec` file: media_kit: ERROR: No pubspec.lock was found: ENV["PWD"] = "/".

 #  from /Users/runner/work/1/s/macos/Flutter/ephemeral/.symlinks/plugins/media_kit_native_event_loop/macos/media_kit_native_event_loop.podspec:13
 #  -------------------------------------------
 #    # Initialize `MediaKitUtils`
 >    mku = MediaKitUtils.new(MediaKitUtils::Platform::MACOS)
 #  
 #  -------------------------------------------

##[error]The process '/usr/local/lib/ruby/gems/3.0.0/bin/pod' failed with exit code 1
##[error]The 'pod' command failed with error: The process '/usr/local/lib/ruby/gems/3.0.0/bin/pod' failed with exit code 1

**Comment by sachindeorah** [comment]
Hi Jonas,

It works. Thank you!

Suggestion: Please add this info to https://pub.dev/packages/media_kit too.

Regards,
Sachin Deorah

**Comment by nikunjramiweave** [comment]
Facing the same issue. Flutter as module added

!] Failed to load 'media_kit_video' podspec: 
[!] Invalid `media_kit_video.podspec` file: media_kit: ERROR: No pubspec.lock was found: ENV["PWD"] = "/Users/BIT/Desktop/Projects/BIT/mobile-ios".


<img width="938" alt="Image" src="https://github.com/user-attachments/assets/84d2f01b-c122-47fa-91a6-81fe94db1d33" />
