### ISSUE TITLE
how to read file from RES/RAW platform android folder

### ISSUE THREAD

**Issue by mayouf** [media-kit/media-kit#720]
**Context**
My version : `Channel stable, 3.19.2`
Platform : `ANDROID`
Lib version : 
```
media_kit_video: ^1.2.4 
media_kit_native_event_loop: ^1.0.8 
media_kit_libs_android_video: ^1.3.6
media_kit_libs_ios_video: ^1.1.4
```

**Describe the bug**

I created a method channel to fetch a file from the android `res/raw` folder.
This method returns this path : 
`android.resource://com.example.project/2131689472`

But this path does not work.

My question is how to read a video file which is in the android platform folder like this:
`/android/app/src/main/res/raw/video.mp4`

**Comment by alexmercerind** [comment]
This is a Flutter library... This goes outside the use-case.
