### ISSUE TITLE
[media_kit v1.1.10] Player .add() doesn't accept paths with spaces in them

### ISSUE THREAD

**Issue by isaacy13** [media-kit/media-kit#722]
Howdy all,

calling `_player.add()` on files with spaces in its path causes the `loadfile` command to error out

to resolve issue, used existing `_command(...)` function and it seems to be working
- other functions in this file use `mpv_command_string` as well but none involve user-inputted strings
  - not sure if this info is also something that might be useful in other files too

`native/player/real.dart`
Old
![image](https://github.com/media-kit/media-kit/assets/65752735/bf3ee09c-0f5d-4142-9a43-923707499f25)

New
![image](https://github.com/media-kit/media-kit/assets/65752735/abe719a2-5d0a-4bdd-8f68-aff21fba0599)

**Comment by isaacy13** [comment]
Just throwing it out there -- might be a minor security risk given a malicious file path

Given `path/example/example; execute cmd here.mp4`, the following is output

![image](https://github.com/media-kit/media-kit/assets/65752735/6802a984-b755-43bf-9748-7c685b28771b)

**Comment by isaacy13** [comment]
Using _command() doesn't seem to have this issue, the semicolon doesn't escape the command

![image](https://github.com/media-kit/media-kit/assets/65752735/e0f4a0d1-724b-45bf-86cf-7884ca5d18ff)

**Comment by isaacy13** [comment]
May or may not also fix https://github.com/media-kit/media-kit/issues/708

Will test later and report back

**Comment by alexmercerind** [comment]
Seems to be a regression since https://github.com/media-kit/media-kit/commit/e959173f49008f5d7a1cf92d8bc1576c26bb5bb8.

**Comment by alexmercerind** [comment]
Build against main branch.
