### ISSUE TITLE
在安卓6的 OPPO A57 2016 上音视频不同步

### ISSUE THREAD

**Issue by xfdyd** [media-kit/media-kit#723]
在安卓6的 OPPO A57 2016 上音视频不同步。开始播放0.5秒后视频卡住，音频继续。1秒后，视频继续。这样以后，视频就始终慢1秒。跳转位置，依然这样不同步。硬解软解都一样。

**Comment by alexmercerind** [comment]
Are you using HLS?

**Comment by xfdyd** [comment]
because use audiotrack, not opensl.
