### ISSUE TITLE
External player support?

### ISSUE THREAD

**Issue by Bonfra04** [media-kit/media-kit#724]
Are there plans to implement the ability to add custom players overriding the default ones? Take for example the case where an implementation connects to a Bluetooth display, or a Chromecast, or even something else completely custom. The ability to switch at runtime (while playing) the player platform and continue playing on that one could be useful in this case. One could override a class that is used to provide the basic functionalities of a player (play, pause, seek, current pos, buffer ...)
I'm sorry if this feature already exists or has been already proposed but I could not find any reference or issue.
Also, yea forking the library and doing it manually is an option but it's pretty messy, a unified and well-done API could be nice.

**Comment by alexmercerind** [comment]
> Also, yea forking the library and doing it manually is an option.

I'm also human, I'd do it manually too. 

The use case of this library is very simple & described in description of this repository. That's it.
