### ISSUE TITLE
when i use 3.19.3 ,i found a lot of issues  

### ISSUE THREAD

**Issue by kahn1231** [media-kit/media-kit#729]
../../.pub-cache/hosted/pub.flutter-io.cn/media_kit_video-1.2.4/lib/src/video_controller/android_video_controller/real.dart:396:22: Error: Type 'VideoParams' not found.
  StreamSubscription<VideoParams>? _subscription;
                     ^^^^^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/media_kit_video-1.2.4/lib/src/video_controller/android_video_controller/real.dart:81:14: Error: The getter 'onLoadHooks' isn't defined for the class 'NativePlayer'.
 - 'NativePlayer' is from 'package:media_kit/src/player/native/player/real.dart' ('../../.pub-cache/hosted/pub.flutter-io.cn/media_kit-1.1.5/lib/src/player/native/player/real.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'onLoadHooks'.
    platform.onLoadHooks.add(() {
             ^^^^^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/media_kit_video-1.2.4/lib/src/video_controller/android_video_controller/real.dart:152:14: Error: The getter 'onUnloadHooks' isn't defined for the class 'NativePlayer'.
 - 'NativePlayer' is from 'package:media_kit/src/player/native/player/real.dart' ('../../.pub-cache/hosted/pub.flutter-io.cn/media_kit-1.1.5/lib/src/player/native/player/real.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'onUnloadHooks'.
    platform.onUnloadHooks.add(() {
             ^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/media_kit_video-1.2.4/lib/src/video_controller/android_video_controller/real.dart:396:22: Error: 'VideoParams' isn't a type.
  StreamSubscription<VideoParams>? _subscription;
                     ^^^^^^^^^^^

My Computer Config
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.3, on macOS 14.4 23E214 darwin-arm64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.5)
[✓] Connected device (4 available)
[✓] Network resources

**Comment by alexmercerind** [comment]
Don't import anything other than package:media_kit/media_kit.dart

**Comment by kahn1231** [comment]
ok ,tks
