### ISSUE TITLE
Seekbar

### ISSUE THREAD

**Issue by kahn1231** [media-kit/media-kit#731]
i want to create own SeekBar ,what should  i do? 
i wang to Adjust Layout (example :    playbtn      seekbar       fullscreen )

**Comment by alexmercerind** [comment]
> What should i do?

Learn Flutter.

**Comment by zezo357** [comment]
> i want to create own SeekBar ,what should i do? i wang to Adjust Layout (example : playbtn seekbar fullscreen )

check this https://github.com/media-kit/media-kit?tab=readme-ov-file#video-controls

you can edit any part of the provided controls or create a new one if you need
