### ISSUE TITLE
Exception caught by widgets library

### ISSUE THREAD

**Issue by kahn1231** [media-kit/media-kit#734]
flutter: VideoOutput.Resize
flutter: {handle: 5985293872, id: 0, rect: {height: 0.0, top: 0.0, left: 0.0, width: 0.0}}
flutter: NativeVideoController: Texture ID: 0
flutter: media_kit: wakelock: _count = 1
flutter: Could not open/initialize audio device -> no sound.
flutter: VideoOutput.Resize
flutter: {handle: 5985293872, id: 0, rect: {height: 1282.0, top: 0.0, width: 720.0, left: 0.0}}
Failed to change device orientation: Error Domain=UISceneErrorDomain Code=101 "None of the requested orientations are supported by the view controller. Requested: landscapeLeft, landscapeRight; Supported: portrait" UserInfo={NSLocalizedDescription=None of the requested orientations are supported by the view controller. Requested: landscapeLeft, landscapeRight; Supported: portrait}

======== Exception caught by widgets library =======================================================
The following _TypeError was thrown building LayoutBuilder:
type 'Null' is not a subtype of type 'String' in type cast

The relevant error-causing widget was: 
  MaterialApp MaterialApp:file:///Users/xiaofeng/AndroidStudioProjects/media_kit/lib/main.dart:42:12
When the exception was thrown, this was the stack: 
#0      ListIterator.current (dart:_internal/iterable.dart:342:29)
#1      SubtitleViewState.build.<anonymous closure> (package:media_kit_video/src/subtitle/subtitle_view.dart)
#2      _LayoutBuilderElement._layout.layoutCallback (package:flutter/src/widgets/layout_builder.dart:139:77)
#3      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2844:19)
#4      _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:173:12)
#5      RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2686:59)
#6      PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1097:15)
#7      RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2686:14)
#8      RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:248:7)
#9      _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:331:5)
#10     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#11     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#12     RenderStack.layoutPositionedChild (package:flutter/src/rendering/stack.dart:516:11)
#13     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:622:30)
#14     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#15     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#16     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#17     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#18     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#19     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:280:14)
#20     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#21     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#22     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#23     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#24     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#25     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#26     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1440:11)
#27     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#28     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#29     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#30     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#31     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#33     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#34     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#35     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#36     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#37     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#39     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#40     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#41     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#42     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3728:13)
#43     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#44     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#45     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#46     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#47     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#48     _RenderTheaterMixin.layoutChild (package:flutter/src/widgets/overlay.dart:968:13)
#49     _RenderTheater.performLayout (package:flutter/src/widgets/overlay.dart:1282:9)
#50     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2414:7)
#51     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1051:18)
#52     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1064:15)
#53     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:582:23)
#54     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:991:13)
#55     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:448:5)
#56     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386:15)
#57     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1311:9)
#58     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1169:5)
#59     _invoke (dart:ui/hooks.dart:312:13)
#60     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:399:5)
#61     _drawFrame (dart:ui/hooks.dart:283:31)
====================================================================================================

[✓] Flutter (Channel stable, 3.19.3, on macOS 14.4 23E214 darwin-arm64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.5)
[✓] Connected device (4 available)
[✓] Network resources

when i  perform full screen switching   ,my app  abnormal exit .       i  use ios simulator .

**Comment by alexmercerind** [comment]
Doesn't happen.
