### ISSUE TITLE
how to play a file in memory?

### ISSUE THREAD

**Issue by txyd** [media-kit/media-kit#735]
hello , how to play a file in memory ?
<img width="1212" alt="iShot_2024-03-20_23 31 46" src="https://github.com/media-kit/media-kit/assets/20138981/1716fcd6-35d2-43a3-a86a-493e7ad15a22">

I can't find the function ……

**Comment by HexaJohn** [comment]
Same issue here, being able to playback a Uint8List from memory would be great

**Comment by GleammerRay** [comment]
This is a very poor implementation and must be rewritten or revoked. The `memory()` constructor simply creates a new file on disk storage and plays the video back from there.

**Comment by alexmercerind** [comment]
> This is a very poor implementation and must be rewritten or revoked. The `memory()` constructor simply creates a new file on disk storage and plays the video back from there.

What have you done about it?

**Comment by GleammerRay** [comment]
Currently I am creating a local HTTPS server with a fake certificate for encryption, which feeds video bytes into the player. I tried using hex playback before but it breaks scrubbing.
