### ISSUE TITLE
Simulator screen recorded video (iPad) not playing from URL for Web in Windows OS

### ISSUE THREAD

**Issue by amittumkur** [media-kit/media-kit#737]
I have a screen recording video of the _iPad simulator_ being played from the Amazon S3 bucket URL.
Media kit plays video from URL without any issue in Flutter Web on MacBook. But the same video gets stuck after 5-6 seconds of buffering in Windows OS (Laptop/Desktop).
I have attached the same video file to test or reproduce.

https://github.com/media-kit/media-kit/assets/64529278/c7ee4f12-bcd0-40c3-bccc-d1686074ce9d

Below are the video details
<img width="600" alt="Screenshot 2024-03-21 at 1 58 36 PM" src="https://github.com/media-kit/media-kit/assets/64529278/91928b15-aa0b-430b-9e1a-230ead59a0b8">

**Comment by alexmercerind** [comment]
Need sample.
