### ISSUE TITLE
[windows] build error Integrity check failed

### ISSUE THREAD

**Issue by bingzhao0719** [media-kit/media-kit#738]
My version is already the latest, but it still frequently fails to compile

```
media_kit: 1.1.10+1        
media_kit_video: 1.2.4     
media_kit_libs_video: 1.0.4
```

```
CMake Error at flutter/ephemeral/.plugin_symlinks/media_kit_libs_windows_video/windows/CMakeLists.txt:40 (message):
  C:/Users/PC/StudioProjects/byme/template_factory/build/windows/mpv-dev-x86_64-20230924-git-652a1dd.7z
  Integrity check failed, please try to re-build project again.
Call Stack (most recent call first):
  flutter/ephemeral/.plugin_symlinks/media_kit_libs_windows_video/windows/CMakeLists.txt:74 (download_and_verify)
Exception: Unable to generate build files
```

My Flutter Version is 3.13.9，please help！

**Comment by bingzhao0719** [comment]
My version is already the latest, but it still frequently fails to compile

` media_kit: 1.1.10+1        
 media_kit_video: 1.2.4     
 media_kit_libs_video: 1.0.4`

`CMake Error at flutter/ephemeral/.plugin_symlinks/media_kit_libs_windows_video/windows/CMakeLists.txt:40 (message):
  C:/Users/PC/StudioProjects/byme/template_factory/build/windows/mpv-dev-x86_64-20230924-git-652a1dd.7z
  Integrity check failed, please try to re-build project again.
Call Stack (most recent call first):
  flutter/ephemeral/.plugin_symlinks/media_kit_libs_windows_video/windows/CMakeLists.txt:74 (download_and_verify)
Exception: Unable to generate build files`

My Flutter Version is 3.13.9

**Comment by isaacy13** [comment]
Hey @bingzhao0719 

Looks like your error message might be because the MD5 hash doesn't match the checksum of the file

If the MD5 hash in the CMakeLists.txt file and the MD5 checksum of the `mpv-dev-x86_64-20230924-git-652a1dd.7z` don't match, then it'll not compile on purpose (for security reasons)

https://github.com/media-kit/media-kit/blob/77a130b1d7ce733b47d2133b57563716090450d0/libs/windows/media_kit_libs_windows_video/windows/CMakeLists.txt#L67
- LIBMPV_MD5 should be set to the correct value for the given LIBMPV_URL

**Comment by bingzhao0719** [comment]
@isaacy13 Thank you for your answer, but I have checked the local CMakeLists.txt and it has been set correctly。
```
# libmpv archive containing the pre-built shared libraries & headers.
set(LIBMPV "mpv-dev-x86_64-20230924-git-652a1dd.7z")

# Download URL & MD5 hash of the libmpv archive.
set(LIBMPV_URL "https://github.com/media-kit/libmpv-win32-video-build/releases/download/2023-09-24/${LIBMPV}")
set(LIBMPV_MD5 "a832ef24b3a6ff97cd2560b5b9d04cd8")

# Download location of the libmpv archive.
set(LIBMPV_ARCHIVE "${CMAKE_BINARY_DIR}/${LIBMPV}")
set(LIBMPV_SRC "${CMAKE_BINARY_DIR}/libmpv")
```

**Comment by zezo357** [comment]
most probably its an internet issue, so try rebuilding the project again and check your network

**Comment by bingzhao0719** [comment]
@zezo357 There is no problem with the internet, all web pages open quickly, and GitHub can also access them normally. There is no problem downloading the mpv-dev-x86_64-20230924-git-652a1dd.7z file using a browser, and even in the build folder under build \ windows, you can see that the mpv-dev-x86_64-20230924-git-652a1dd.7z file has been downloaded correctly

**Comment by zezo357** [comment]
our ci works https://github.com/media-kit/media-kit/actions/runs/8131708780/job/23048786165 so it cant be a problem with the file itself so it should be a problem with the file on your side, and that can only happen if the file is corrupted during download 


i re ran the workflow on windows to be 100% sure if it passes then its a problem on your side :_( 
and it passes as you can see in the link provided 

try flutter clean and rebuilding again 

or rebuilt each time it fails and see if the file with the problem is changed (if it moves on to a different file then the first one was successful )

**Comment by dht-hedaihua** [comment]
maybe your mpv-dev-x86_64-20230924-git-652a1dd.7z file is 0 Kb ?

**Comment by bingzhao0719** [comment]
@zezo357 Okay, thank you for your answer. Let me confirm my network situation again

**Comment by isaacy13** [comment]
You can also calculate the MD5 checksum of the downloaded file
- can google "MD5 checksum calculator"
- or can figure out command line to do it

If it doesn't match, then like other folks are saying, for one reason or another the file is likely corrupted

**Comment by huangxulei** [comment]
> @zezo357 There is no problem with the internet, all web pages open quickly, and GitHub can also access them normally. There is no problem downloading the mpv-dev-x86_64-20230924-git-652a1dd.7z file using a browser, and even in the build folder under build \ windows, you can see that the mpv-dev-x86_64-20230924-git-652a1dd.7z file has been downloaded correctly

奇奇怪怪的, 确实, 我一个项目,之前能运行的,clean 之后又不行了. 我建立了另外一个测试项目又能,这个又不行了. 而且有时候可以 有时候不行 大概率好像是网络问题. 哎 很苦恼. 不知道要不要放弃这个插件.浪费很多时间.

**Comment by abdelaziz-mahdy** [comment]
> > @zezo357 There is no problem with the internet, all web pages open quickly, and GitHub can also access them normally. There is no problem downloading the mpv-dev-x86_64-20230924-git-652a1dd.7z file using a browser, and even in the build folder under build \ windows, you can see that the mpv-dev-x86_64-20230924-git-652a1dd.7z file has been downloaded correctly
> 
> 奇奇怪怪的, 确实, 我一个项目,之前能运行的,clean 之后又不行了. 我建立了另外一个测试项目又能,这个又不行了. 而且有时候可以 有时候不行 大概率好像是网络问题. 哎 很苦恼. 不知道要不要放弃这个插件.浪费很多时间. 

Can you test with this 

use overrides from github 
```
dependency_overrides:
  media_kit: 
    git:
      url: https://github.com/media-kit/media-kit
      path: media_kit
  media_kit_video: 
    git:
      url: https://github.com/media-kit/media-kit
      path: media_kit_video
  media_kit_libs_video: 
    git:
      url: https://github.com/media-kit/media-kit
      path: libs/universal/media_kit_libs_video
```

I don't remember if the improved code was released or not, so try with the GitHub version and let me know if it's better or not

**Comment by huangxulei** [comment]
> > > @zezo357 There is no problem with the internet, all web pages open quickly, and GitHub can also access them normally. There is no problem downloading the mpv-dev-x86_64-20230924-git-652a1dd.7z file using a browser, and even in the build folder under build \ windows, you can see that the mpv-dev-x86_64-20230924-git-652a1dd.7z file has been downloaded correctly
> > 
> > 
> > 奇奇怪怪的, 确实, 我一个项目,之前能运行的,clean 之后又不行了. 我建立了另外一个测试项目又能,这个又不行了. 而且有时候可以 有时候不行 大概率好像是网络问题. 哎 很苦恼. 不知道要不要放弃这个插件.浪费很多时间.
> 
> Can you test with this
> 
> use overrides from github
> 
> ```
> dependency_overrides:
>   media_kit: 
>     git:
>       url: https://github.com/media-kit/media-kit
>       path: media_kit
>   media_kit_video: 
>     git:
>       url: https://github.com/media-kit/media-kit
>       path: media_kit_video
>   media_kit_libs_video: 
>     git:
>       url: https://github.com/media-kit/media-kit
>       path: libs/universal/media_kit_libs_video
> ```
> 
> I don't remember if the improved code was released or not, so try with the GitHub version and let me know if it's better or not

thank you! now it's fine, maybe network  issue.

**Comment by bingzhao0719** [comment]
It is indeed a network issue. The company's network access to GitHub is very slow, basically due to download failure. There are two ways I can think of: 
1. Open a VPN proxy to ensure that the script can access GitHub. 
3. If it doesn't work, rely locally and modify the download address

**Comment by alexmercerind** [comment]
Your network is unstable.
