### ISSUE TITLE
FEATURE: ADD A PLAY BUTTON INDICATOR WHEN VIDEO IS PAUSE AT FIRST INITIALIZE

### ISSUE THREAD

**Issue by moshOntong-IT** [media-kit/media-kit#744]
``` dart
 player.open(
      Media(
        AppwriteClient.getUrl(
          bucketId: attachment.bucketId,
          fileID: attachment.id,
        ),
        httpHeaders: {
          "x-appwrite-jwt": attachment.token,
        },
      ),
      play: false,
    );
```
    
 ``` dart
      return AspectRatio(
      aspectRatio: 16 / 9,
      child: Video(
        controller: videoController,
      ),
    );
```
    
is it possible to improve the Video widget from mediakit. For instance, as you can see in my code in default the player play is false. So in that case the Video must shows something like play button. Because as of now we need to hover that Video widget so that the Play button will appear. 
![image](https://github.com/media-kit/media-kit/assets/57244338/7534860a-0e1e-4c46-bbb4-77b6abe43737)
![image](https://github.com/media-kit/media-kit/assets/57244338/ea37bb53-4f98-44d5-a43f-13fc8a588972)

As the two picture shows, the first one is the mouse does not hover the Video widget. So the user might think that this Media is an images. The second picture shows that when the mouse hover the video widget then the video's controls will show up this time. This might get a bad user experience. 
We might need to improve the video widget. If the initState of the Player 'play' is false, then the Video widget should visible the Play button icon. So that the user aware that this component or media is a video
In my case, I have this medias such as images, gif, and video. As you can see the user will confuse "where could be the video media here"

![image](https://github.com/media-kit/media-kit/assets/57244338/dd2925c4-b6a3-43f3-8a0a-06b453e320b7)
These are the video but first it might think Image media

![image](https://github.com/media-kit/media-kit/assets/57244338/81d96a62-22ee-4d12-83b4-1a2cd8d66817)

This is something I want in Video play widget. It just something like an awareness that this component is a video.
![image](https://github.com/media-kit/media-kit/assets/57244338/d7ab47be-d03d-48a0-b119-acf6be699d75)
If the Video widget is not playing at first then we have to put some Play button icon in center of that widget

ALTERNATIVE SOLUTIONS:
>  wrap the controls to show that widget if player is not playing
just listen to player state and based on it show that button/overlay or not

**Comment by alexmercerind** [comment]
Just display another widget (stack with icon & image), and make `Video` visible only when clicked on it.
