### ISSUE TITLE
I have a question about full screen display of notch screen.

### ISSUE THREAD

**Issue by user1121114685** [media-kit/media-kit#746]
How can I occupy the entire screen including the camera area on the notch screen when playing a video on Android?

**Comment by zezo357** [comment]
This is not related to the package, it's just android it self 


Check this https://github.com/flutter/flutter/issues/46486#issuecomment-654796115

**Comment by user1121114685** [comment]
Thanks for the reply and have a nice day!

**Comment by LNA-DEV** [comment]
@user1121114685 Did you get it to work?

In my case it seems to change nothing.

**Comment by user1121114685** [comment]
> @user1121114685 Did you get it to work?
> 
> In my case it seems to change nothing.

its work for me .
