### ISSUE TITLE
Hide control bar in code

### ISSUE THREAD

**Issue by hupo376787** [media-kit/media-kit#763]
Hi, I'm playing live m3u8, so the control bar useless.
So how to hide it when playing live streams?

**Comment by alexmercerind** [comment]
> So how to hide it when playing live streams.

By reading docs.

**Comment by hupo376787** [comment]
Thx.
![image](https://github.com/media-kit/media-kit/assets/14960168/1760d08c-4808-4a73-8665-586e932ae9a1)
