### ISSUE TITLE
Wrap video in Inkwell, onTap not working

### ISSUE THREAD

**Issue by hupo376787** [media-kit/media-kit#764]
Hi, I wrap the video widget in Inkwell, then I can't fire onTap event.
So how to fix it, or get the event when click ton the video?

```
InkWell(
                    onTap: () {
                      debugPrint('onTap InkWell');
                      setState(() {
                        menuVisible = !menuVisible;
                      });
                    },
                    child: SizedBox(
                      width: MediaQuery.of(context).size.width,
                      height: MediaQuery.of(context).size.width * 9.0 / 16.0,
                      child: Video(
                        controller: controller,
                      ),
                    ),
                  )
```

**Comment by hupo376787** [comment]
Seems `AdaptiveVideoControls` has overlayed all area.
When I use `NoVideoControls`, `onTap` event works.
![image](https://github.com/media-kit/media-kit/assets/14960168/3a4a0547-e9d8-4408-bd21-e49b205daf07)

**Comment by sevenrats** [comment]
your Inkwell's internal GestureDetector needs to have it's hittestbehavior set to translucent. i dont think it has anything to do with media-kit
