### ISSUE TITLE
the seek function doesn't work

### ISSUE THREAD

**Issue by Anto-2004** [media-kit/media-kit#767]
I did all the possible tests, I even changed the version of flutter, I can't understand I'm passing the example code from the documentation to show the video the only thing I want and set the initial position with the seek method but it doesn't work always starts from scratch.
I put the code I have, if anyone can give me some suggestions, I can't understand.

  Code:
    import 'package:flutter/material.dart';
    
    import 'package:media_kit/media_kit.dart';                      // Provides [Player], [Media], [Playlist] etc.
    import 'package:media_kit_video/media_kit_video.dart';          // Provides [VideoController] & [Video] etc.        
    
    void main() {
      WidgetsFlutterBinding.ensureInitialized();
      // Necessary initialization for package:media_kit.
      MediaKit.ensureInitialized();
      runApp(
        const MaterialApp(
          home: MyScreen(),
        ),
      );
    }
    
    class MyScreen extends StatefulWidget {
      const MyScreen({Key? key}) : super(key: key);
      @override
      State<MyScreen> createState() => MyScreenState();
    }
    
    class MyScreenState extends State<MyScreen> {
      // Create a [Player] to control playback.
      late final player = Player();
      // Create a [VideoController] to handle video output from [Player].
      late final controller = VideoController(player);
  
    void initAll() async {
  
      player.open(Media('example-url'));
  
      await player.seek(
        const Duration(
          seconds: 90,
        ),
      );
  
    }
  
    @override
    void initState() {
      super.initState();
  
      initAll();
    }
  
    @override
    void dispose() {
      player.dispose();
      super.dispose();
    }
  
    @override
    Widget build(BuildContext context) {
      return Center(
        child: SizedBox(
          width: MediaQuery.of(context).size.width,
          height: MediaQuery.of(context).size.width * 9.0 / 16.0,
          // Use [Video] widget to display video output.
          child: Video(controller: controller),
        ),
      );
    }
   }

**Comment by sevenrats** [comment]
this title is a bit misleading. the seek function works fine, what you want is called something more like "start time"
we implement start times in our fork, I happen to be investigating the feasibility of upstreaming as we speak:
https://github.com/jellyflix-app/media-kit

**Comment by 23doors** [comment]
Start/end time was implemented in main repo here: https://github.com/media-kit/media-kit/pull/581
It just wasn't released yet. To use it one needs to use dependency_overrides like for example here: https://github.com/media-kit/media-kit/pull/581#issuecomment-1951650794

**Comment by sevenrats** [comment]
@23doors thank you for taking the time to clarify. Sorry to FUD.  I've just joined this other project and am still wrapping my head around why we even have a fork.

**Comment by Anto-2004** [comment]
I found the solution, since at the moment it is not possible to select the start minute, when they update the library I will change it
```
await player.open(Media(widget.videoUrl));
controller.player.stream.duration.listen((event) async {
  if (event.inSeconds > 0){
    await player.seek(position);
  }
});
```

**Comment by Anto-2004** [comment]
I found the solution, since at the moment it is not possible to select the start minute, when they update the library I will change it
```
await player.open(Media(widget.videoUrl));
controller.player.stream.duration.listen((event) async {
  if (event.inSeconds > 0){
    await player.seek(position);
  }
});
```
