### ISSUE TITLE
windows fullscreen is abnormal when use window_manager set titlebar hide

### ISSUE THREAD

**Issue by lunxinfeng** [media-kit/media-kit#770]
enter fullscreen on windows,  the edges will has blank when use window_manager set titlebar hide, I donot understand the windows sdk, can you help me? 

![fullscreen](https://github.com/media-kit/media-kit/assets/20685167/ee59d666-5b7e-4cb7-93a5-22a5540b55f6)

`
``yaml
dependencies:
  media_kit: ^1.1.10                             # Primary package.
  media_kit_video: ^1.2.4                        # For video rendering.
  media_kit_libs_video: ^1.0.4  
  window_manager: ^0.3.8
```

here is the setTitleBar code  from window_manager:
```c++
void WindowManager::SetTitleBarStyle(const flutter::EncodableMap& args) {
  title_bar_style_ =
      std::get<std::string>(args.at(flutter::EncodableValue("titleBarStyle")));
  // Enables the ability to go from setAsFrameless() to
  // TitleBarStyle.normal/hidden
  is_frameless_ = false;

  MARGINS margins = {0, 0, 0, 0};
  HWND hWnd = GetMainWindow();
  RECT rect;
  GetWindowRect(hWnd, &rect);
  DwmExtendFrameIntoClientArea(hWnd, &margins);
  SetWindowPos(hWnd, nullptr, rect.left, rect.top, 0, 0,
               SWP_NOZORDER | SWP_NOOWNERZORDER | SWP_NOMOVE | SWP_NOSIZE |
                   SWP_FRAMECHANGED);
}
```

**Comment by lunxinfeng** [comment]
The problem should be with window_manager， I will close this issue first

**Comment by marcov-dart** [comment]
Yeah, so I just ran into the same issue. I quickly realised that the problem here is, that window_manager doesn't know about the applications going full-screen. I solved it by passing onEnterFullscreen and onExitFullscreen to the Video widget that simply call windowManager.setFullscreen first and then call the default function, like this:

```
      Video(
        onEnterFullscreen: () async {
          await windowManager.setFullScreen(true);
          return defaultEnterNativeFullscreen();
        },
        onExitFullscreen: () async {
          await windowManager.setFullScreen(false);

          return defaultExitNativeFullscreen();
        },
      ),
```
