### ISSUE TITLE
Kolin gradle 9 breaking compile

### ISSUE THREAD

**Issue by syleishere** [media-kit/media-kit#771]
After upgrading kotlin gradle Android studio, no longer compiles, also new version of wakelock available

**Comment by syleishere** [comment]
Updating to latest wakelock_plus resolves the issue I have found with version 1.2.4, if author can update plugin would be much appreciated...

**Comment by abdelaziz-mahdy** [comment]
since this is not a major version, shouldnt flutter pub upgrade get that version you need?

**Comment by syleishere** [comment]
You would think so right. However in flet project I was working on other dependencies prevented the update, forcing me to force package upgrades in the cache.

As of this current time, anything below 1.2.4 will break with Android studio/kotlin new version, so thought it prudent to let maintainer know to set that as minimum version in pubspec.yaml

**Comment by abdelaziz-mahdy** [comment]
That will break other people code, so that's not a viable workaround, 

You can set the dependency override to the version you want and that will work correctly, and since the code works for me and other people using the current version, even on cli, 

I think it may be personal configuration on your side

**Comment by syleishere** [comment]
You would think so, but I put that to test other night. I had an old laptop I hadn't used in long time, so I fresh installed windows 11 on it. Added all the flutter dependencies and went to compile it again, same thing happened.

Originally this happened because I upgraded gradle while on an old flutter project, but now seems anyone with fully upgraded configuration it will happen to

**Comment by abdelaziz-mahdy** [comment]
sadly i cant help with that, if even override didnt work then i dont think its a problem with the version

**Comment by syleishere** [comment]
Either way I agree with you, this is flet issue not having done a pub update in sometime. Trying to switch off flutter to python as I realize mojo has been open sourced as of a few weeks ago as a superset to python, and is faster than rust and c++, so want to get a head start on AI

**Comment by abdelaziz-mahdy** [comment]
good luck then and feel free to ask if you found something

**Comment by alexmercerind** [comment]
Don't bring other project's issues here.
