### ISSUE TITLE
horizontally flip a video in player

### ISSUE THREAD

**Issue by vadapalliravikumar** [media-kit/media-kit#772]
Is it possible to horizontally flip (mirror) a video in the video player ? Use case is to let the users dynamically select the flipped view or normal view of the selfie video recording.

**Comment by Gieted** [comment]
Mpv has command `vf toggle hflip`. To execute command do:
```dart
final nativePlayer = player.platform as NativePlayer;
  final command = 'vf toggle hflip'.toNativeUtf8();
  nativePlayer.mpv.mpv_command_string(
    nativePlayer.ctx,
    command.cast(),
  );
  calloc.free(command);
```

Hope it works, haven't tested that.

**Comment by flymzero** [comment]
hflip not exist

**Comment by alexmercerind** [comment]
https://api.flutter.dev/flutter/widgets/Transform/Transform.flip.html

I don't know why y'all use Flutter if you aren't aware of its built-in features.
