### ISSUE TITLE
Enable --vo=gpu-next Support on Darwin to Reshape Dolby Vision Content

### ISSUE THREAD

**Issue by shivabohemian** [media-kit/media-kit#777]
In the latest version of `mpv 0.38`, the issue with Vulkan instance creation on macOS has been fixed ([the pr](https://github.com/mpv-player/mpv/pull/13829)). Here, we can use `--vo=gpu-next` to support content reshaping for Dolby Vision (you can use test videos [here](https://www.demolandia.net/4k-video-test/dolby-vision/page-2.html)). I noticed that the darwin builds of the `media-kit` package are using an older version of mpv and Vulkan is not enabled. So, do we need to update `libmpv-darwin-build`?

**Comment by birros** [comment]
See media-kit/libmpv-darwin-build#28.

Unfortunately, I don't think libmpv uses Vulkan, but only OpenGL like previous versions. It seems to me that Vulkan is only for direct rendering in a native view.

To use Vulkan in media-kit, we need to :
- Wait for libmpv to replace OpenGL with Vulkan
- Or use a Platform View from Flutter, but I don't think this API is yet stable for macOS, and that it would be as efficient

**Comment by shivabohemian** [comment]
All right. It looks like `gpu-next` is still not supported in the rendering API (https://github.com/mpv-player/mpv/issues/10810).  So, as it stands, it appears that Dolby Vision tone mapping is also not properly supported on the `medit-kit`.
