### ISSUE TITLE
[Feature] Specify custom user-agent

### ISSUE THREAD

**Issue by tomekit** [media-kit/media-kit#781]
I was wondering if there is anyway to specify custom: `user-agent` header?

At the moment player (at least on Linux) sets it to default: `libmpv`.

**Comment by abdelaziz-mahdy** [comment]
Set it using the headers it should be set

**Comment by alexmercerind** [comment]
The `Media` constructor allows to specify `httpHeaders`.

**Comment by tomekit** [comment]
Thank you. `Media(url, httpHeaders: headers)` works flawlessly.
