### ISSUE TITLE
excuse me! I want to know a question about the use of subtitles

### ISSUE THREAD

**Issue by user1121114685** [media-kit/media-kit#801]
excuse me! I would like to know a question about the use of subtitles?

When I enabled libass, I could not move the upper and lower positions of the subtitles and set the font size by configuring the subtitle properties. The official mpv documentation mentioned that the subtitles could be moved using pos-sub 10. But I don't know how to implement this in media-kit.

Sorry to disturb everyone. If anyone knows or wants to discuss it, please reply to me.

**Comment by abdelaziz-mahdy** [comment]
i think that should help, https://github.com/media-kit/media-kit?tab=readme-ov-file#customize-subtitles no need to change it from mpv it self

**Comment by alexmercerind** [comment]
Hi,

The only way to customize libass font rendering is to use the `setProperty` API. No support for that will be provided.

**Comment by user1121114685** [comment]
thx all.
