### ISSUE TITLE
Seek is not working on release mode

### ISSUE THREAD

**Issue by BTMuli** [media-kit/media-kit#804]
I use the code below:
```dart
await player.open(Playlist(hive.allMedia, index: hive.index), play: play);
var progress = hive.getProgress(index);
if (progress != 0) {
  debugPrint('跳转到上次播放进度: $progress');
  await player.seek(Duration(milliseconds: progress));
  // Here's a custom snackbar widget
  await Infobar(context, '已跳转到上次播放进度 $progress');
}
```

And it runs normally in debugMode and profileMode,but when I bundle my app in release,it show the snackbar but the video play from 0 instead of jump to the true position.

**Comment by BTMuli** [comment]
It is so strange that it works well in profile mode but got wrong under release.🤔

**Comment by abdelaziz-mahdy** [comment]
your problem is that video is not loaded before you seek check this for possible fixes 
https://github.com/media-kit/media-kit/issues/228

for me i use        

 `await player.stream.buffer.first;`

your code will be 
```
await player.open(Playlist(hive.allMedia, index: hive.index), play: play);
await player.stream.buffer.first;
var progress = hive.getProgress(index);
if (progress != 0) {
  debugPrint('跳转到上次播放进度: $progress');
  await player.seek(Duration(milliseconds: progress));
  // Here's a custom snackbar widget
  await Infobar(context, '已跳转到上次播放进度 $progress');
}
```

for me it works correctly.

**Comment by BTMuli** [comment]
> `await player.stream.buffer.first;`

Thanks,I'll try it,but why I could seek directly in profile mode?

**Comment by abdelaziz-mahdy** [comment]
i think because the video was cached? thats the only think i could think of

**Comment by BTMuli** [comment]
Thanks!`await player.stream.buffer.first;` really works.
