### ISSUE TITLE
Can not get AudioDevice list on Window & MacOS

### ISSUE THREAD

**Issue by spinsirr** [media-kit/media-kit#806]
I tried to get the audioDevices using the code below:
`var devices = player.state.audioDevices;`
but the audioDevices list I got is 
##### [AudioDevice(auto, )]
According to the constructor of playerState this means that the AudioDevices list is not initialized properly 
@alexmercerind

**Comment by alexmercerind** [comment]
Use the stream. That getter is only for instantaneous use.
