### ISSUE TITLE
How to make a custom responsive button on controller?

### ISSUE THREAD

**Issue by BTMuli** [media-kit/media-kit#808]
I need to change the color of indicator to make it the same as theme accentcolor.

I try the code below:
```dart
// some code
return MaterialDesktopVideoControlsTheme(
  normal: MaterialDesktopVideoControlsThemeData(
    seekBarThumbColor: FluentTheme.of(context).accentColor.lighter,
    seekBarPositionColor: FluentTheme.of(context).accentColor.darker,
// some code
```

But it not change when `FluentTheme.of(context).accentColor` change🤔

**Comment by aiJiaou** [comment]
MaterialDesktopVideoControlsTheme(
                  normal: const MaterialDesktopVideoControlsThemeData(
                    toggleFullscreenOnDoublePress: false,
                    automaticallyImplySkipNextButton: false,
                    bottomButtonBar: [
                      MaterialDesktopSkipPreviousButton(),
                      MaterialDesktopPlayOrPauseButton(),
                      MaterialDesktopSkipNextButton(),
                      MaterialDesktopVolumeButton(),
                      MaterialDesktopPositionIndicator(),
                      Text("视频截图"),
                    ],
                  ),
                  fullscreen:const MaterialDesktopVideoControlsThemeData(
                    //全屏按钮
                    bottomButtonBar: [
                      MaterialDesktopSkipPreviousButton(),
                      MaterialDesktopPlayOrPauseButton(),
                      MaterialDesktopSkipNextButton(),
                      MaterialDesktopVolumeButton(),
                      MaterialDesktopPositionIndicator(),
                    ],
                  ),
                  child: Video(
                      controller: controller,
                      width: MediaQuery.of(context).size.width,
                      height: MediaQuery.of(context).size.width * 9.0 / 16.0,
                      fit: BoxFit.fitWidth),
                ),
