### ISSUE TITLE
[android] how to enable libass on Android?

### ISSUE THREAD

**Issue by wiedymi** [media-kit/media-kit#835]
I have such configuration, but it does not work in android? Could you help me?

 ![image](https://github.com/media-kit/media-kit/assets/42713027/20bd0356-027f-4c88-9ddb-be94c924c9b3)
 
 
![image](https://github.com/media-kit/media-kit/assets/42713027/6d9425b5-08c8-4fe6-a243-91aca239147a)

I suppose the problem with fonts. How to setup default font for libass?

**Comment by wiedymi** [comment]
It works on macos, but not on android

**Comment by abdelaziz-mahdy** [comment]
https://github.com/media-kit/media-kit/issues/255#issuecomment-1646868981

try with libass as false or check that above issue for further clues for your problem

**Comment by wiedymi** [comment]
@abdelaziz-mahdy i've checked logs and it seems that font has been used as expected. Any ideas why it does not work on Android?

**Comment by abdelaziz-mahdy** [comment]
for me i use the widget renderer instead of libass, so i dont know sadly, if the logs doesnt show a problem, then it should work

**Comment by wiedymi** [comment]
The logs do not show that libass was initialized

**Comment by wiedymi** [comment]
```
flutter: log PlayerLog(prefix: sub/ass, level: v, text: fontselect: (Montserrat Bold, 400, 0) -> /Users/uyakauleu/Library/Fonts/Montserrat-Bold.ttf, -1, Montserrat-Bold)
flutter: log PlayerLog(prefix: sub/ass, level: v, text: mangling colors like vsfilter: RGB -> bt.601 limited -> bt.709 bt.601 -> RGB)
```
On macos I see such lines in logs, but on android nothing

**Comment by abdelaziz-mahdy** [comment]
if you dont set your font on android does it work?, also did you recompile ?

**Comment by wheremyfiji** [comment]
@wiedymi 
check this and dont set libassAndroidFont 
https://github.com/wheremyfiji/ShikiWatch/blob/99fcc92390f9d2fd4ddcc8dd41da5c0d62c99ad1/lib/src/presentation/pages/player/player_provider.dart#L890
https://github.com/wheremyfiji/ShikiWatch/blob/99fcc92390f9d2fd4ddcc8dd41da5c0d62c99ad1/lib/src/utils/player/player_utils.dart#L26

**Comment by wiedymi** [comment]
Subtitle file: ```https://subtitles.anibel.net/96f73e63-a0e7-415f-a59a-79b6d13f0fbb/субцітры.ass```
Video file: ```https://n2.anibel.stream/dash/96f73e63-a0e7-415f-a59a-79b6d13f0fbb/manifest.mpd```

**Comment by wiedymi** [comment]
> @wiedymi check this and dont set libassAndroidFont https://github.com/wheremyfiji/ShikiWatch/blob/99fcc92390f9d2fd4ddcc8dd41da5c0d62c99ad1/lib/src/presentation/pages/player/player_provider.dart#L890 https://github.com/wheremyfiji/ShikiWatch/blob/99fcc92390f9d2fd4ddcc8dd41da5c0d62c99ad1/lib/src/utils/player/player_utils.dart#L26

Could you explain it more?

**Comment by wheremyfiji** [comment]
you should use font file not from assets, just put the file in the application folder (use path_provider package for example). 
then specify path to this file in player during initialization
![image](https://github.com/media-kit/media-kit/assets/26019782/5066d0f2-c8f1-4ea3-9c5f-148214f13cec)

and just set libass to true
![image](https://github.com/media-kit/media-kit/assets/26019782/57c23418-bbf0-4df7-bee3-2f67bd277e52)

**Comment by wiedymi** [comment]
I can close the topic.
Now it works, like this.

![image](https://github.com/media-kit/media-kit/assets/42713027/55656533-bb95-4c74-9c9d-b4641a65ca91)

**Comment by wiedymi** [comment]
> I can close the topic. Now it works, like this.
> 
> ![image](https://private-user-images.githubusercontent.com/42713027/332475264-55656533-bb95-4c74-9c9d-b4641a65ca91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMDM5NzksIm5iZiI6MTcxNjMwMzY3OSwicGF0aCI6Ii80MjcxMzAyNy8zMzI0NzUyNjQtNTU2NTY1MzMtYmI5NS00Yzc0LTljOWQtYjQ2NDFhNjVjYTkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDE1MDExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiYTc1NTM1MWIzMmM0NjhjMzM5NDM2NmVlZWQyNGUwMTM3MThmYWYxM2I3MTAwMzRkNDlmODc4OTk3ZTc2YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DcD5m8WJCtTpic-e4qDlqrpjEzqwRl4BB003gEANCqo)

Reopen.  Because it does not help

**Comment by JasperElton** [comment]
Same here it seems like on Android subtitles are not appearing but on iOS it works fine. Already did set libass to true and I do not use fonts.

**Comment by JasperElton** [comment]
Where do I even get the subtitle.ttf file? been struggling since last week

**Comment by alexmercerind** [comment]
They changed the name of properties in mpv, I think someone brought this up.

**Comment by JasperElton** [comment]
Would you mind to help me here? @alexmercerind
