### ISSUE TITLE
VideoController scale, width, and height not being set

### ISSUE THREAD

**Issue by isaacy13** [media-kit/media-kit#839]
Howdy,

I noticed the `scale` property in the VideoControllerConfiguration seems to be unused and not have any effect
![image](https://github.com/media-kit/media-kit/assets/65752735/11dfb3d7-425b-4d2f-81c3-eb182f138d55)

Additionally, the VideoController::setSize method only works if you set a non-null value for both width and height (as expected behavior by code) -- might not hurt to add to function documentation

nothing will happen
![image](https://github.com/media-kit/media-kit/assets/65752735/911c54a4-dd3f-4cc7-9789-60ad8c8e85be)

width/height will be set
![image](https://github.com/media-kit/media-kit/assets/65752735/711b9f45-63dc-4493-8a50-d5b9c2d9b55d)

**Comment by isaacy13** [comment]
Also, VideoViewParameters aren't being set either (widget redraws but _videoViewParametersNotifier isn't being updated)

Although might not be super efficient, currently calling update in Video widget's build. Checking if any parameter has changed and updating it accordingly

![image](https://github.com/media-kit/media-kit/assets/65752735/6a7b1a04-964a-4073-a095-5dff637ac7c5)

**Comment by abdelaziz-mahdy** [comment]
> Also, VideoViewParameters aren't being set either (widget redraws but _videoViewParametersNotifier isn't being updated)
> 
> Although might not be super efficient, currently calling update in Video widget's build. Checking if any parameter has changed and updating it accordingly
> 
> ![image](https://private-user-images.githubusercontent.com/65752735/335780603-6a7b1a04-964a-4073-a095-5dff637ac7c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMzg3NTAsIm5iZiI6MTcxNzIzODQ1MCwicGF0aCI6Ii82NTc1MjczNS8zMzU3ODA2MDMtNmE3YjFhMDQtOTY0YS00MDczLWEwOTUtNWRmZjYzN2FjN2M1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDEwNDA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0MjE2NTVkN2Q4MDRkYWQ4OWIzNTAzN2E0NTBmZGY5ZGI4Y2FlMTc0YWJhZmZjODU3ZjQyNmFlYWQ0OGViMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LTUYngnPbojtAP6tJ9v2nMKtPg3rNrAlOF8In8la-AQ)

What is the specific parameters you change?
I tested fit and subtitle view

**Comment by isaacy13** [comment]
I was just testing fit, but I think it'd apply to all those parameters?

To clarify, the initial setting of the parameters works as expected

e.g: Video(fit: Boxfit.cover)

However, updating the parameter doesn't seem to take effect/update

e.g: 
var _fit = Boxfit.cover
...
Video(fit: _fit)
...
setState ({
   _fit = Boxfit.fill
})

**Comment by abdelaziz-mahdy** [comment]
Fit works as expected in my case, can you check example 11?

**Comment by abdelaziz-mahdy** [comment]
> I was just testing fit, but I think it'd apply to all those parameters?
> 
> To clarify, the initial setting of the parameters works as expected
> 
> e.g: Video(fit: Boxfit.cover)
> 
> However, updating the parameter doesn't seem to take effect/update
> 
> e.g: var _fit = Boxfit.cover ... Video(fit: _fit) ... setState ({ _fit = Boxfit.fill })

updating the parameter will not work on full screen mode, you should use the .update method

**Comment by isaacy13** [comment]
Ah I did not see that, I suppose it was designed this way for performance reasons

Thank you!
