### ISSUE TITLE
Exclude support for unused codecs

### ISSUE THREAD

**Issue by brookman** [media-kit/media-kit#846]
Hi media_kit team,

Thank you for providing this awesome Flutter package!

We are building an app for Windows and noticed that including media_kit bundles a large number of DLLs (see [here](https://github.com/media-kit/media-kit/blob/e7903a86f12ac179a0a35f6a8b1bfa2785f4ec46/libs/windows/media_kit_libs_windows_video/windows/CMakeLists.txt#L167-L231)). It seems that some of these DLLs conflict with other dependencies of our app and cause crashes. Additionally, packaging all those DLLs significantly increases the bundle size.

In our app, we only use h265 (without sound). Our current workaround is deleting the following DLLs after a build:
```
api-ms-*.dll
concrt140.dll
msvcp*.dll
ucrtbas*.dll
vc*.dll
```
With this, the app still works but does not crash anymore.

Is there a more elegant way to exclude certain, unneeded codecs?

Thank you!

**Comment by alexmercerind** [comment]
Interesting. Those are [MSVCP](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist) & [UCRT](https://learn.microsoft.com/en-us/cpp/windows/universal-crt-deployment) from Microsoft, they don't provide any codec support etc. I included them to make application run out-of-the-box, in-fact I think ANGLE also bundles them by default.

**Comment by alexmercerind** [comment]
Build against main branch.
