### ISSUE TITLE
Crashes on linux - seems related to VideoController?

### ISSUE THREAD

**Issue by CyanEbi** [media-kit/media-kit#852]
Arch linux (EndeavourOS)
Dart 3.4.0 (pacman)
Flutter 3.22.1 (from flutter.dev, but the same issue occurs with AUR version)
VSCodium 1.89.1
media_kit: ^1.1.10+1
media_kit_video: ^1.2.4
media_kit_libs_video: ^1.0.4

I'm making a Linux app, but the app crashes whenever I make use of the media-kit player. Unfortunately the app crashes silently, so I don't know a lot about what is causing the crashes. I have found some consistent ways to provoke this crash that lead me to believe that it's somehow related to VideoController. The app only crashes while a video is playing, and does so consistently when:
1. The VideoController is hidden and I move the mouse inside the player (which would make the VideoController appear)
2. The VideoController is hidden and I click the mouse button inside the player (seems to make the VideoController appear if it hasn't yet been shown at any previous point - not sure why it behaves like that)
3. The VideoController is visible and I let the mouse idle for a few seconds (making the VideoController disappear)
4. The VideoController is visible and I move the mouse outside the player (making the VideoController disappear)

In the below recording I show the four cases in that order. After those four cases I show two cases where I can't provoke a crash:
1. If the video is not playing
2. If the Video's `controls` parameter is NoVideoControls

https://github.com/media-kit/media-kit/assets/159061101/ae8fa73c-5386-4fca-bac1-cb27f602e39f

For the recording I used the tl;dr example in a fresh VSCodium flutter project. The player behaves similarly in my own app, EXCEPT my own app also crashes when `controls` is NoVideoControls (it crashes immediately). The example runs without issue in the Chromium browser when built for web.

Let me know if there's a way for me to provide more information.

**Comment by qixiaoo** [comment]
I also encountered a similar crash problem on my Manjaro Linux recently.

When I execute `flutter run` under the `video_player_media_kit/example` directory of this project, the example can start correctly. However, when I switch to the "List example" tab of the example program and scroll down the list, the crash problem occurs. `coredumpctl debug` indicates that there is a segment fault in `libnvidia-glcore.so.550.78`.

---

Update:

My problem seems related to the flutter version. After switching to the flutter 3.19.6, the crash problem disappeared.

flutter version before:

```
❯ flutter --version
Flutter 3.22.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision a14f74ff3a (2 weeks ago) • 2024-05-22 11:08:21 -0500
Engine • revision 55eae6864b
Tools • Dart 3.4.1 • DevTools 2.34.3
```
flutter version after:

```
❯ fvm flutter --version
Flutter 3.19.6 • channel stable •
https://github.com/flutter/flutter.git
Framework • revision 54e66469a9 (7 weeks ago) • 2024-04-17 13:08:03
-0700
Engine • revision c4cd48e186
Tools • Dart 3.3.4 • DevTools 2.31.1
```

**Comment by CyanEbi** [comment]
Thanks a lot for the tip! 
3.19.6 works perfectly for me while 3.22.0 and 3.22.1 has the problem

**Comment by nrbnlulu** [comment]
Encountered this as well. 
if someone has more details about why 
>  libnvidia-glcore.so.550.78.
segault occurred  I would be happy to help.

**Comment by NavaNair** [comment]
I had a similar issue and solved it by downgrading libmpv-dev package:

`sudo apt-get install libmpv-dev:0.34.1-1ubuntu3`
`sudo apt-mark hold libmpv-dev` to block upgrades.

Not sure if this helps the discussion but just wanted to highlight what worked for me back then.

**Comment by Predidit** [comment]
The root cause doesn't seem to be libnvidia-glcore.so but rather libflutter_linux_gtk.so. It appears to be an issue with Flutter itself. This is not caused by an error in VideoController. The crash occurs when Flutter animations are overlayed on textures.

Perhaps reporting to flutter is the correct way to solve the problem. But I am not clear about the specific implementation of media_kit and lack experience in the related field. Moreover, the official Flutter team does not accept bug reports with third-party dependencies.

@abdelaziz-mahdy Could you please open an issue in flutter repo?

**Comment by abdelaziz-mahdy** [comment]
I don't have the knowledge to report to flutter repo

**Comment by Predidit** [comment]
This is really frustrating. Linux is already a second-class citizen on the Flutter platform, so this issue might go unnoticed for a long time. It seems that the problem only occurs when using textures, which means it’s primarily triggered by media players. Only the maintainers of media players would have the ability to report this issue.

@abdelaziz-mahdy Sorry to bother you again. Could this issue be reported by other maintainers of media_kit?

**Comment by abdelaziz-mahdy** [comment]
> This is really frustrating. Linux is already a second-class citizen on the Flutter platform, so this issue might go unnoticed for a long time. It seems that the problem only occurs when using textures, which means it’s primarily triggered by media players. Only the maintainers of media players would have the ability to report this issue.
> 
> @abdelaziz-mahdy Sorry to bother you again. Could this issue be reported by other maintainers of media_kit?

I think only Alex will be able to do so, since he made the internals of it

**Comment by GleammerRay** [comment]
Can confirm, doesn't work with flutter 3.22.2, works on master.

**Comment by HankG** [comment]
There was a GTK regression in 3.22 that I reported that has been fixed. I wonder if it is related to that... https://github.com/flutter/flutter/issues/148653

**Comment by Andreas02-dev** [comment]
> Can confirm, doesn't work with flutter 3.22.2, works on master.

Could you please verify if 3.22.3 contains the fix?

**Comment by GleammerRay** [comment]
Hello @Andreas02-dev !
Confirmed, Flutter SDK rolled to https://github.com/flutter/flutter/releases/tag/3.22.3
App launches and plays video.
```
Flutter 3.22.3 • channel [user-branch] • unknown source
Framework • revision b0850beeb2 (4 days ago) • 2024-07-16 21:43:41 -0700
Engine • revision 235db911ba
Tools • Dart 3.4.4 • DevTools 2.34.3
```

**Comment by CyanEbi** [comment]
Sorry for taking a while to get back on this. After recently updating to flutter 3.22.3 I haven't had any issues using media-kit

**Comment by Andreas02-dev** [comment]
> Sorry for taking a while to get back on this. After recently updating to flutter 3.22.3 I haven't had any issues using media-kit

No problem. Also not with disposing? For me, the application just freezes most of the time right after trying to dispose

**Comment by alexmercerind** [comment]
> Can confirm, doesn't work with flutter 3.22.2, works on master.

I just don't know... Flutter for GNU/Linux keeps on breaking randomly. They need to test things before they roll it.
