### ISSUE TITLE
Error Screen 

### ISSUE THREAD

**Issue by AdarshEduport** [media-kit/media-kit#855]
How can we implement an error screen and retry functionality when loading fails? Here's what I've done so far: There is already a listener for errors. I've utilized this error listener to display an error screen. When the user clicks on the error, the player opens with the same media using await player.open(media);. However, the playback occurs in the background, and the error listener does not get updated with a null value (indicating no error).

**Comment by abdelaziz-mahdy** [comment]
provide an example code if you want help with your code :) since none can help without seeing the code
