### ISSUE TITLE
Crash/Freeze on Windows

### ISSUE THREAD

**Issue by Andrekarma** [media-kit/media-kit#857]
I have a Windows application that after some time freeze completly.
I have 2 different Player instances that switches beetwen them when the other has finished to play his content
Every time one Player finish i dispose it and recreate it with a new video from local file.

I tried to not dispose the player without recreating a new one changing only the content that needs to show
With this implementation i dont have any more crashes but the ram usage goes to the sky

So i think that the problem is with the dispose of the player
 
(The time of the crash is random and seems to vary based on the computer, it could be hours, it could be minutes)

**Comment by abdelaziz-mahdy** [comment]
> I have a Windows application that after some time freeze completly. I have 2 different Player instances that switches beetwen them when the other has finished to play his content Every time one Player finish i dispose it and recreate it with a new video from local file.
> 
> I tried to not dispose the player without recreating a new one changing only the content that needs to show With this implementation i dont have any more crashes but the ram usage goes to the sky
> 
> So i think that the problem is with the dispose of the player
> 
> (The time of the crash is random and seems to vary based on the computer, it could be hours, it could be minutes)

i dont know the cause of the crash, maybe related to this https://github.com/media-kit/media-kit/issues/842 ?

**Comment by Andrekarma** [comment]
I would say that this seems a different problem

i removed the media_kit_native_event_loop.dll as suggested here https://github.com/media-kit/media-kit/issues/591 but nothing changed

One issue is that there is no logs when the freeze occurs, do you have any idea or advice?

**Comment by abdelaziz-mahdy** [comment]
this will show more logs, but it will only show mpv logs so it may not show the crash problem if its not related to mpv itself
```
player =
       Player(configuration: PlayerConfiguration(logLevel: MPVLogLevel.debug));
   player.stream.log.listen((event) {
     print("log $event");
   });
   ```

**Comment by Andrekarma** [comment]
I removed the media_kit_native_event_loop like said on this issue https://github.com/media-kit/media-kit/issues/591

But the freezing/crashing is still randomly happening

**Comment by abdelaziz-mahdy** [comment]
> @abdelaziz-mahdy the fact that i need to dispose the player even if i just want to mantain the same instance of the player changing the content playing, seems like a memory leak problem



> @abdelaziz-mahdy the fact that i need to dispose the player even if i just want to mantain the same instance of the player changing the content playing, seems like a memory leak problem

i dont know the crash problem and i dont know how to fix it :_( alex is the one who made it so he knows it much better

**Comment by Andrekarma** [comment]
@alexmercerind

**Comment by cybrox** [comment]
I am facing the same issue as @Andrekarma very consistently on Windows 11 (`23H2` `22631.3737`).    
Disposing of a player results in a crash 75%+ of the time.

I have created a repository that allows reproducing this issue at [cybrox/flutter_media_kit_857](https://github.com/cybrox/flutter_media_kit_857). The main app toggles its body between a `VideoWidget` and a `Text`, causing the `VideoWidget` to dispose upon toggling. This crashes most of the time.

## Log output
The only real log output I consistently get is this:
```
flutter: media_kit: wakelock: _count = 0
flutter: ### Disposing Video Widget
D:\a\_work\1\s\src\vctools\crt\github\stl\src\mutex.cpp(61): mutex destroyed while busy
```

## Output of `flutter doctor -v`
```
C:\Development\media_kit_test>flutter doctor -v
[!] Flutter (Channel [user-branch], 3.16.6, on Microsoft Windows [Version 10.0.22631.3737], locale en-CH)
    ! Flutter version 3.16.6 on channel [user-branch] at C:\Flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at
      https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision 46787ee49c (5 months ago), 2024-01-09 14:36:07 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.7.34202.233
    • Windows 10 SDK version 10.0.22621.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.88.1)
    • VS Code at C:\Users\User\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.90.0

[√] Connected device (1 available)
    • Windows (desktop) • windows • windows-x64 • Microsoft Windows [Version 10.0.22631.3737]

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
```

**Comment by Andrekarma** [comment]
It is happening in release mode
Since switching to the master from github, the situation seems better. 
Maybe related to this: https://github.com/media-kit/media-kit/pull/803 
But still the crashes are not resolved 100%

**Comment by seungsoon** [comment]
in my case
1. In the file “media_kit_native_event_loop.cc”
2. In the “MediaKitEventLoopHandler::Dispose()” function
3. "std::this_thread::sleep_for(std::chrono::seconds(5));" I commented out that line and it worked fine.

**Comment by isaacy13** [comment]
Was facing the same issue, but think #803 did resolve it for me

Validated:
- using latest version (currently 50c510d018cc5286eb6730f3ea165290f19dc5f6)
- (optional) `flutter pub cache clear && flutter clean && rm pubspec.lock && flutter pub get`
  - was running into issues on my fork, you (probably) don't have to do this as long as you're certain you're using latest unmodified version of media_kit
- build project and verify `media_kit_native_event_loop.dll` is being built & opened correctly
  - **IMPORTANT!** Previously stopped building this dll (as per previous recommendation in this thread). Make sure your project is building and opening this file correctly
  - Ensures `InitializerNativeEventLoop` is used, and not falling back to `InitializerIsolate`
    - `InitializerIsolate` still seems to have crash/freeze issues
    - Fix in #803 only applies to `InitializerNativeEventLoop`

After this, my usual tricks that'd get my app to freeze up stopped working

**Comment by alexmercerind** [comment]
Build against main branch.

**Comment by DryveLyve** [comment]
Likely the same root cause. Player.dispose() leaves COM uninitialized on Windows — see #1449 for a minimal reproduction and a workaround.
