### ISSUE TITLE
App crash after 1~2 seconds of playing a video on linux.

### ISSUE THREAD

**Issue by nrbnlulu** [media-kit/media-kit#859]
I have cloned the repo and followed all the steps for setting up linux environment
including
- install flutter manually https://docs.flutter.dev/get-started/install/linux#method-2-manual-installation
- run `sudo apt-get install libgtk-3-dev`
- run `sudo apt install libstdc++-12-dev`
- run `sudo apt install libmpv-dev mpv`
- add this to linux CMakeLists 
```cmake
target_link_libraries(${BINARY_NAME} PRIVATE ${MIMALLOC_LIB})
```

I ran the example in [here](https://github.com/media-kit/media-kit/blob/main/media_kit_test/lib/main.dart) and 
on debug mode after 2 seconds the app crash and in release mode in a few ms.
This is the crash log
```log
package:media_kit_libs_linux registered.
media_kit: VideoOutput: video_output_new: 2795186124368
Cannot load libcuda.so.1
media_kit: VideoOutput: Using H/W rendering.
flutter: VideoOutput.Resize
flutter: {handle: 2795186124368, id: 2795057625296, rect: {left: 0, top: 0, width: 1, height: 1}}
flutter: NativeVideoController: Texture ID: 2795057625296
flutter: media_kit: wakelock: _count = 1
media_kit: TextureGL: Resize: (854, 480)
flutter: VideoOutput.Resize
flutter: {handle: 2795186124368, id: 2795057625296, rect: {left: 0, top: 0, width: 854, height: 480}}
Segmentation fault (core dumped)
```
I am running ubuntu 22.04

Have I missed something?

PS: The example binary works fine on my machine.

**Comment by abdelaziz-mahdy** [comment]
check https://github.com/media-kit/media-kit/issues/852

**Comment by nrbnlulu** [comment]
yep. Thanks.
