### ISSUE TITLE
Run failed on linux

### ISSUE THREAD

**Issue by lrd7512369** [media-kit/media-kit#871]
`parallels@parallels-Parallels-Virtual-Platform:~/Desktop/ltcs$ flutter doctor -v
[✓] Flutter (Channel stable, 3.22.2, on Ubuntu 20.04.6 LTS 5.15.0-107-generic, locale zh_CN.UTF-8)
    • Flutter version 3.22.2 on channel stable at /usr/bin/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (2 周前), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/parallels/Android/Sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2023.3)
    • Android Studio at /home/parallels/Downloads/android-studio-2023.3.1.18-linux/android-studio
    • Flutter plugin version 79.0.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Ubuntu 20.04.6 LTS 5.15.0-107-generic

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
parallels@parallels-Parallels-Virtual-Platform:~/Desktop/ltcs$ flutter run
Launching lib/main.dart on Linux in debug mode...
/home/parallels/Desktop/ltcs/linux/flutter/ephemeral/.plugin_symlinks/media_kit_video/linux/include/media_kit_video/video_output.h:23:44: error: converting to non-pointer type ‘long int’ from NULL [-Werror=conversion-null]
/home/parallels/Desktop/ltcs/linux/flutter/ephemeral/.plugin_symlinks/media_kit_video/linux/include/media_kit_video/video_output.h:24:45: error: converting to non-pointer type ‘long int’ from NULL [-Werror=conversion-null]
/home/parallels/Desktop/ltcs/linux/flutter/ephemeral/.plugin_symlinks/media_kit_video/linux/media_kit_video_plugin.cc:43:53: error: converting to non-pointer type ‘long int’ from NULL [-Werror=conversion-null]
/home/parallels/Desktop/ltcs/linux/flutter/ephemeral/.plugin_symlinks/media_kit_video/linux/media_kit_video_plugin.cc:43:53: error: converting to non-pointer type ‘long int’ from NULL [-Werror=conversion-null]
/home/parallels/Desktop/ltcs/linux/flutter/ephemeral/.plugin_symlinks/media_kit_video/linux/include/media_kit_video/video_output.h:23:44: error: converting to non-pointer type ‘long int’ from NULL [-Werror=conversion-null]
/home/parallels/Desktop/ltcs/linux/flutter/ephemeral/.plugin_symlinks/media_kit_video/linux/include/media_kit_video/video_output.h:24:45: error: converting to non-pointer type ‘long int’ from NULL [-Werror=conversion-null]
/home/parallels/Desktop/ltcs/linux/flutter/ephemeral/.plugin_symlinks/media_kit_video/linux/texture_sw.cc:52:29: error: comparison of integer expressions of different signedness: ‘guint32’ {aka ‘unsigned int’} and ‘gint32’ {aka ‘int’} [-Werror=sign-compare]
/home/parallels/Desktop/ltcs/linux/flutter/ephemeral/.plugin_symlinks/media_kit_video/linux/texture_sw.cc:53:30: error: comparison of integer expressions of different signedness: ‘guint32’ {aka ‘unsigned int’} and ‘gint32’ {aka ‘int’} [-Werror=sign-compare]
/home/parallels/Desktop/ltcs/linux/flutter/ephemeral/.plugin_symlinks/media_kit_video/linux/include/media_kit_video/video_output.h:23:44: error: converting to non-pointer type ‘long int’ from NULL [-Werror=conversion-null]
/home/parallels/Desktop/ltcs/linux/flutter/ephemeral/.plugin_symlinks/media_kit_video/linux/include/media_kit_video/video_output.h:24:45: error: converting to non-pointer type ‘long int’ from NULL [-Werror=conversion-null]
/home/parallels/Desktop/ltcs/linux/flutter/ephemeral/.plugin_symlinks/media_kit_video/linux/texture_gl.cc:72:43: error: comparison of integer expressions of different signedness: ‘guint32’ {aka ‘unsigned int’} and ‘gint32’ {aka ‘int’} [-Werror=sign-compare]
/home/parallels/Desktop/ltcs/linux/flutter/ephemeral/.plugin_symlinks/media_kit_video/linux/texture_gl.cc:73:44: error: comparison of integer expressions of different signedness: ‘guint32’ {aka ‘unsigned int’} and ‘gint32’ {aka ‘int’} [-Werror=sign-compare]
Building Linux application...                                           
Error: Build process failed
`

**Comment by alexmercerind** [comment]
Doesn't happen for me... the CI succeeds.
