### ISSUE TITLE
Volume Slider Issue

### ISSUE THREAD

**Issue by pvogt** [media-kit/media-kit#872]
Platform: Windows 11
Issue: The volume slider seems to be affected by the click and dragging of the thumb button on the seek bar and also click and dragging anywhere on the video screen. This is happening on all the test packages that have the volume slider.
Click and dragging of the volume slider thumb button doesn't affect the seek bar slider.

I've attached a short video on what is happening.

https://github.com/media-kit/media-kit/assets/1979645/0c04d695-40fd-469f-80a2-dfbf048d35bb

**Comment by abdelaziz-mahdy** [comment]
i think in the themes you can set `modifyVolumeOnScroll` to false.

**Comment by pvogt** [comment]
> i think in the themes you can set `modifyVolumeOnScroll` to false.

Thank you. This fixed the issue.

Is this a situation of having one or the other? Or does the code need to be 'fixed' so one can use both the mouse wheel to control volume and to be able to drag the seek bar thumb without it affecting the volume?

**Comment by abdelaziz-mahdy** [comment]
I don't know why it was added too, personally I didn't face the issue, so thanks for your mention anyway. Glad you found a fix , you can make a pr if you like

**Comment by alexmercerind** [comment]
Send a PR.
