### ISSUE TITLE
on windows11  issue

### ISSUE THREAD

**Issue by 329521** [media-kit/media-kit#873]
media_kit: ^1.1.10+1                            
  media_kit_video: ^1.2.4                       
  media_kit_libs_video: ^1.0.4
  media_kit_libs_windows_audio: ^1.0.4
  media_kit_libs_windows_video: ^1.0.4

CMake Error at flutter/ephemeral/.plugin_symlinks/media_kit_libs_windows_video/windows/CMakeLists.txt:40 (message):

  F:/mynotebook/notebookx/build/windows/x64/mpv-dev-x86_64-20230924-git-652a1dd.7z
  Integrity check failed, please try to re-build project again.
Call Stack (most recent call first):
  flutter/ephemeral/.plugin_symlinks/media_kit_libs_windows_video/windows/CMakeLists.txt:74 (download_and_verify)

**Comment by daimaxiaofeng** [comment]
I have the same problem, is there a solution?

**Comment by abdelaziz-mahdy** [comment]
this is a network problem, please check your internet, and rebuild again 

maybe use a vpn or something like this https://one.one.one.one/

**Comment by alexmercerind** [comment]
Build against main branch.
