### ISSUE TITLE
[Linux] black screen outside player

### ISSUE THREAD

**Issue by pkozlovskiy** [media-kit/media-kit#876]
If cursor going outside player, or without any move after second. 
Trying to find mpv options to prevent auto fullscreen mode, but nothing helps

![image](https://github.com/media-kit/media-kit/assets/1486167/9a52141a-491e-4712-a3f3-50ff3b4fc383)

**Comment by alexmercerind** [comment]
I can't make this happen... Ubuntu 22.04.3 LTS.

**Comment by mikewach** [comment]
I was observing the same issue when compiling with Flutter 3.22 however after upgrading to 3.24 the issue appears to be resolved
