### ISSUE TITLE
[media_kit_video] Difference in files between git tag and pub release

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [media-kit/media-kit#879]
I noticed the files from the release on pub.dev and the corresponding git tag differ :

- https://github.com/media-kit/media-kit/blob/media_kit_video-v1.2.3/media_kit_video/lib/media_kit_video_controls/src/controls/cupertino.dart

If you look into the dump downloaded from pub.dev on tag 1.2.3, the file does only contain an empty header.

**Comment by abdelaziz-mahdy** [comment]
released.
