### ISSUE TITLE
Is there a way to get opened video duration?

### ISSUE THREAD

**Issue by kostov** [media-kit/media-kit#888]
1) **player.state.duration** is a current pos duration from start, but I need _total_ duration (if video is a file f.e.).
2) **player.seek(value)** -- what happens if value is bigger than _total_ duration? May be there is some way to seek at end?

**Comment by Ansh-Rathod** [comment]
as i remember `player.state.position` is current pos, `player.state.duration` is total duration of video. you might be getting 00:00:00 both you need to check if it's buffering or not. use `StreamSubscription` and `player.stream.duration` to get total duration.

**Comment by kostov** [comment]
@Ansh-Rathod
Thank you! You are right: player.stream.duration subscription works perfectly.
