### ISSUE TITLE
[Ubuntu] crash when move the mouse

### ISSUE THREAD

**Issue by Turing-jiang** [media-kit/media-kit#895]
Thanks for your work.
i want to use media-kit to play a video in my ubuntu desktop program.
when i use `fvm flutter run -d linux`, if i didn't touch the mouse, sometimes the video played well,
but if i moved the mouse, the program would be crashed.

OS: ubuntu 20.04
fvm:3.1.5
flutter:Flutter 3.22.1 • channel stable • https://github.com/flutter/flutter.git
            Framework • revision a14f74ff3a (6 weeks ago) • 2024-05-22 11:08:21 -0500
            Engine • revision 55eae6864b
            Tools • Dart 3.4.1 • DevTools 2.34.3

i tried:
```dart 
late final controller = VideoController(player,
      configuration: const VideoControllerConfiguration(
          enableHardwareAcceleration: false));
```

but it was also crashed.

**Comment by Turing-jiang** [comment]
if i change the flutter version to 3.19.1, and use the same source code, the player worked well.
i think it is a bug.

**Comment by alexmercerind** [comment]
Not happening now.
