### ISSUE TITLE
player.seek future takes too much time. 

### ISSUE THREAD

**Issue by Ansh-Rathod** [media-kit/media-kit#896]
Hi, is there a way to seek the position without buffering?

I'm building a kinda of video_editor app and using this plugin for it but I want to have the functionality to seek by hovering to the timeline. I implemented that using the hover events but controller.player.seek takes more time to get there. the buffering time is too long.

here is the video from the movie also most of the video players/editors don't take this much time to seek to position as I noticed. 

https://github.com/media-kit/media-kit/assets/67627096/defb89b9-9296-4b14-888e-7b41a4f3b8e9

**Comment by Joseph-Nathan** [comment]
any news ?

**Comment by alexmercerind** [comment]
Solved on `main` branch.
