### ISSUE TITLE
[Linux][Kubuntu 22.04] Regular Crashes During Video Load

### ISSUE THREAD

**Issue by oliver-hrkltz** [media-kit/media-kit#898]
Hello,

we are using your package to play some videos from a network source with vaapi hw acceleration.

The player regularly crashes on our devices running Kubuntu 22.04. I seen some issue reporting similar cases here.

Could you please provide which version of Linux you are using for testing and which version of libmpv-dev and mpv is installed on your devices? As you see for example here it would make a difference if you testing it on Ubuntu 20.04 or 22.04: https://packages.ubuntu.com/search?keywords=libmpv-dev

Our test was based on regular reloads by removing the video widget and adding it again based on a timer feeded with a random delay from 2-3 seconds. The player/flutter application mostly freeze after 200-300 iterations.

Device: https://www.lattepanda.com/lattepanda-delta (Intel N4100 with UHD 600 GPU)
OS: Kubuntu 22.04.4 LTS with libmpv-dev version 0.34.1-1ubuntu3
Flutter: 3.22.2

Best Regards

Oli

**Comment by oliver-hrkltz** [comment]
Here the logs:
1. A successful run
```
flutter: Iteration: 176
media_kit: VideoOutput: video_output_new: 2605402175056
Cannot load libcuda.so.1
media_kit: VideoOutput: Using H/W rendering.
flutter: VideoOutput.Resize
flutter: {handle: 2605402175056, id: 2605252430672, rect: {left: 0, top: 0, width: 1080, height: 1920}}
flutter: NativeVideoController: Texture ID: 2605252430672
flutter: media_kit: wakelock: _count = 1
media_kit: TextureGL: Resize: (1080, 1920)
flutter: VideoOutput.Resize
flutter: {handle: 2605402175056, id: 2605252430672, rect: {left: 0, top: 0, width: 1080, height: 1920}}
flutter: media_kit: wakelock: _count = 0
media_kit: VideoOutput: video_output_dispose: 2605402175056
MediaKitEventLoopHandler::Register: std::thread exit: 2605402175056
MediaKitEventLoopHandler::Dispose: 2605402175056
```

2. The failed run
```
flutter: Iteration: 177
media_kit: VideoOutput: video_output_new: 2605402172496
Cannot load libcuda.so.1
media_kit: VideoOutput: Using H/W rendering.
flutter: VideoOutput.Resize
flutter: {handle: 2605402172496, id: 2605252430480, rect: {left: 0, top: 0, width: 1080, height: 1920}}
flutter: NativeVideoController: Texture ID: 2605252430480
flutter: media_kit: wakelock: _count = 1
media_kit: TextureGL: Resize: (1080, 1920)
flutter: VideoOutput.Resize
flutter: {handle: 2605402172496, id: 2605252430480, rect: {left: 0, top: 0, width: 1080, height: 1920}}
flutter: media_kit: wakelock: _count = 0
media_kit: VideoOutput: video_output_dispose: 2605402172496
```

**Comment by oliver-hrkltz** [comment]
Update: I let it run without HW acceleration. Same behaviour so therefore I guess it is unrelated to the libmpv-dev version. But still would be nice to known which version you are using. :)

**Comment by oliver-hrkltz** [comment]
Update: I could do some additonal runs yesterday evening.

- 3x without vaapi but HW acceleration enabled (356, 268, 9450 iterations)
- 1x with disabled HW acceleration (49 iterations)

Somehow i have the feeling is connected to the loading of the video because if it freeze it's always before the video get shown on the UI. Never had the case that it was freezing during playback.

**Comment by oliver-hrkltz** [comment]
I think i found the source: A deadlock in this part of the code:

media_kit_native_event_loop.cc

```
// Check if this |handle| has been marked to exit.
mutex_.lock();
auto exit = exit_handles_.find(context) != exit_handles_.end();
mutex_.unlock();
if (exit) {
  std::cout << "MediaKitEventLoopHandler::Register: std::thread exit: " << reinterpret_cast<int64_t>(context)
            << std::endl;
  break;
}
```

**Comment by seungsoon** [comment]
I am in a Windows environment, but the freezing issue was resolved through two modifications.

1. https://github.com/flutter/flutter/issues/124194
  - Runs on NVIDA graphics cards, not Intel
2. https://github.com/media-kit/media-kit/tree/main/media_kit_native_event_loop/src/media_kit_native_event_loop.cc
  - Delete line 137 => std::this_thread::sleep_for(std::chrono::seconds(5));

in google translate

**Comment by oliver-hrkltz** [comment]
Looks like we found a solution by switching to Kubuntu 24.04 with libmpv-dev in version 0.37.0-1ubuntu4 (same device).

Already crossed 1k iterations. I will let it run overnight.

**Comment by alexmercerind** [comment]
Unfortunately, we use libmpv from the package manager on GNU/Linux... There's always some sort of mismatch between what we actually intended, unless the version exactly matches.

If someone has time & resources, do try to have some static libmpv builds for GNU/Linux.

**Comment by alexmercerind** [comment]
Please try running against main branch... a lot of things are changed.
