### ISSUE TITLE
add support for mpv custom stream api

### ISSUE THREAD

**Issue by AlaaAlHallaq** [media-kit/media-kit#899]
Mpv have a robust, easy to use native api for registering custom protocol for reading custom stream using:

```
int mpv_stream_cb_add_ro(
    mpv_handle *ctx,
    const char *protocol,
    void *user_data,
    mpv_stream_cb_open_ro_fn open_fn
);
```
function, I tested it on macos with swift & it was very easy to use & very performant.
It would be a great addition to be supported in this comprehensive library.

**Comment by AlaaAlHallaq** [comment]
@alexmercerind can you please give your thoughts about this

**Comment by alexmercerind** [comment]
We don't have time & resources.
