### ISSUE TITLE
SBG files do not play

### ISSUE THREAD

**Issue by moriciogithub** [media-kit/media-kit#902]
Hello everybody.

Tried this:

`player.open(Media('asset:///assets/prog-spin-1.sbg'));`

But only the progress indicator is shown. MPV seems to play this type of files and it is indicated in the media_kit readme that it does.

What may be the situation?

Thanks

**Comment by moriciogithub** [comment]
Hello and thank you for your prompt answer.

Here is the debug log after running the app in a new machine, generating for Windows. Also tried in an Android phone. Same results.

`flutter: log PlayerLog(prefix: lavf, level: v, text: No format found, try lowering probescore or forcing the format.)
flutter: log PlayerLog(prefix: demux, level: debug, text: Trying demuxer: mf (force-level: unsafe))
flutter: log PlayerLog(prefix: demux, level: debug, text: Trying demuxer: playlist (force-level: unsafe))
flutter: log PlayerLog(prefix: demux, level: debug, text: Trying demuxer: null (force-level: unsafe))
flutter: log PlayerLog(prefix: cplayer, level: v, text: Opening failed or was aborted: C:\Users\moric\Development\Test\media_kit_1\build\windows\x64\runner\Debug\data\flutter_assets\assets\ts-brain-delta.sbg)
flutter: log PlayerLog(prefix: cplayer, level: v, text: Running hook: main/on_unload)
flutter: log PlayerLog(prefix: cplayer, level: v, text: Set property: http-header-fields=null -> -2)
flutter: log PlayerLog(prefix: cplayer, level: v, text: finished playback, unrecognized file format (reason 4))
flutter: log PlayerLog(prefix: cplayer, level: error, text: Failed to recognize file format.)
flutter: log PlayerLog(prefix: cplayer, level: info, text: )`

The line `text: finished playback, unrecognized file format (reason 4))`  summarizes the problem.

I have played the files directly with mpv and they play but not from inside media_kit.

Any ideas?

Thanks again

Mauricio

**Comment by moriciogithub** [comment]
Additional notes:

I have used MacOS, Ubuntu 22.04 and Windows 10 and same results.

`flutter: log PlayerLog(prefix: lavf, level: v, text: No format found, try lowering probescore or forcing the format.)` 

How do I force format from inside media_kit?

Thanks

Mauricio

**Comment by moriciogithub** [comment]
Hello.

Does anybody know what is happening with this issue?

I have no clue on where to get from here and really stuck.

Thanks to anybody who can give me a hint.

Thanks-.

Mauricio

**Comment by moriciogithub** [comment]
Hello. 

Info: After reviewing the builder for the mpv lib used in the media_kit plugin I discovered that not all the codecs are enabled and SBaGen is not one of the enabled ones.

Does anybody can point me in the direction to make my own builds?

Thanks

Mauricio

**Comment by abdelaziz-mahdy** [comment]
> Hello. 
> 
> Info: After reviewing the builder for the mpv lib used in the media_kit plugin I discovered that not all the codecs are enabled and SBaGen is not one of the enabled ones.
> 
> Does anybody can point me in the direction to make my own builds?
> 
> Thanks
> 
> Mauricio

Check if fvp fits your use case, since I don't know how to configure the build

**Comment by moriciogithub** [comment]
Hi. What exactly is fpv? Thanks

mauricio

**Comment by alexmercerind** [comment]
We don't have every single decoder enabled...
