### ISSUE TITLE
Libmpv.so issue every time

### ISSUE THREAD

**Issue by teeeemj** [media-kit/media-kit#905]
When im running my project I have the same issue _Exception (Exception: Cannot find libmpv.so. Please ensure its presence in the APK.) like this when I use this line in main.dart   MediaKit.ensureInitialized();

**Comment by abdelaziz-mahdy** [comment]
you will have to rebuild apk when adding the package

so a restart is needed i think

**Comment by alexmercerind** [comment]
If you are using a debugger, DO NOT STOP FOR CAUGHT EXCEPTIONS.
