### ISSUE TITLE
A problem occurred evaluating project ':media_kit_libs_android_video'

### ISSUE THREAD

**Issue by esepai** [media-kit/media-kit#906]
* What went wrong:
A problem occurred evaluating project ':media_kit_libs_android_video'.
> media_kit: x86 JAR verification failed.

**Comment by zhahouming** [comment]
I encountered the same issue while compiling the Android client. Upon checking the error, I found that one of the four packages: default-arm64-v8a.jar, default-armeabi-v7a.jar, default-x86_64.jar, or default-x86.jar, is always 0 bytes, which causes the validation to fail. Is it possible that there is a bug in the download-related code logic?

**Comment by iamshivkumar** [comment]
....pub-cache/hosted/pub.dev/media_kit_libs_android_video-1.3.6/android/build.gradle' line: 108

* What went wrong:
A problem occurred evaluating project ':media_kit_libs_android_video'.
> media_kit: x86_64 JAR verification failed.

I am also facing similar issue
