### ISSUE TITLE
Add a way to receive one-time controller callbacks

### ISSUE THREAD

**Issue by shubhamsinghshubham777** [media-kit/media-kit#910]
First up, I want to thank you for your hard work and this amazing library!

Secondly, I would like to request that you please add one-time callback events in at least one of the pre-defined video controls (most likely [MaterialVideoControls](https://github.com/media-kit/media-kit/blob/main/media_kit_video/lib/media_kit_video_controls/src/controls/material.dart)). I have a use-case that cannot be sufficed by observing `player.stream`.

The following API is expected:
```dart
return Video(
    controller: _controller,
    controls: (state) {
        return MaterialVideoControls(
            state,
            onPlayPause: (isPlaying) {},
            onSeek: (position) {},
            ... // And all other state events like this
        );
    },
);
```

I would request your guidance on whether a way to get one-time user interaction events already exists.

**Comment by alexmercerind** [comment]
Just pass own buttons into the existing options we provided, to override default actions (if you really want to).
