### ISSUE TITLE
2 major issues, what song is playing and background video/audio play

### ISSUE THREAD

**Issue by syleishere** [media-kit/media-kit#913]
First of all thank-you for great plugin, 2 major issues however with media_kit is:
1) Lack of knowing what song is playing within the playlist, when I tried the video.track function always just comes back returning null.
2) Lack of background audio/video support on android/IOS.

I propose media_kit be wrapped with audio_service, solves issue 1 with a queue management system, will always know what song is playing. Also solves background playback issue for 2.

**Comment by syleishere** [comment]
I solved first issue of getting song playing, just leaves background audio play issue on android

**Comment by alexmercerind** [comment]
I always wanted to have `media_kit_os_controls`... let's see.

**Comment by syleishere** [comment]
That would be a great name, background audio play on android and IOS, samba/nfs support for people's NAS's etc.
