### ISSUE TITLE
在iphone上，调用screenshot截图，视频是竖向的，但是截图是横向的

### ISSUE THREAD

**Issue by wengxianxun** [media-kit/media-kit#914]
在iphone上，调用screenshot截图，视频是竖向的，但是截图是横向的，

视频：
<img width="398" alt="image" src="https://github.com/user-attachments/assets/9a576bd9-a917-4857-8f59-96be70af1cee">

截图：
<img width="423" alt="image" src="https://github.com/user-attachments/assets/b792c25d-58b4-4526-9936-53d4d1cbe31b">

**Comment by alexmercerind** [comment]
Me no understand.
