### ISSUE TITLE
Do not want to request permission

### ISSUE THREAD

**Issue by LiuDongCai** [media-kit/media-kit#915]
I just want to play an MP4 link, why do I need to request permission?

`
if (await Permission.videos.isDenied || await Permission.videos.isPermanentlyDenied) {
    final state = await Permission.videos.request();
    if (!state.isGranted) {
      await SystemNavigator.pop();
    }
  `}`
 `

If permission is not requested, it will crash on Android devices.

**Comment by LiuDongCai** [comment]
targetSdkVersion 34

**Comment by alexmercerind** [comment]
It's an Android related question, go to stackoverflow.

**Comment by gaganyadav80** [comment]
I think it's related to the README where it is not mentioned why it is suggested to add those permissions.

**Comment by alexmercerind** [comment]
> I think it's related to the README where it is not mentioned why it is suggested to add those permissions.

That README is for developers.
