### ISSUE TITLE
Linux Build Failed on ubuntu 24.04 links to target "PkgConfig::mpv" but the   target was not found. 

### ISSUE THREAD

**Issue by hansyulian** [media-kit/media-kit#919]
in my ARM64 ubuntu 24.04, i get the following error:
```
CMake Error at flutter/ephemeral/.plugin_symlinks/media_kit_video/linux/CMakeLists.txt:16 (add_library):
  Target "media_kit_video_plugin" links to target "PkgConfig::mpv" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
```
In the other hand, i manage to create a build on ubuntu 22.04 but when i try to run it in my ubuntu 22.04, it says "libmpv.so.1" not found. So apparently when i checked, the uBuntu 24.04 is no longer supporting or bring the libmpv1, instead they use libmpv2 right now. 
so i do 
```
sudo ln -s /usr/lib/aarch64-linux-gnu/libmpv.so /usr/lib/aarch64-linux-gnu/libmpv.so.1
```
and it can run, so i guess somehow we need to update the libmpv usage on ubuntu 24.04?

**Comment by hansyulian** [comment]
ok not sure why, but apparently doing the installation of flutter from github fix the issue and some other weird issue. Instead of downloading as the instruction in https://docs.flutter.dev/get-started/install/linux/desktop

so this is the working flutter installation on my ARM64 SBC:
```
git clone https://github.com/flutter/flutter.git -b stable
```
then link the `flutter/bin` to PATH and done

**Comment by ruslan-gennadievich** [comment]
Try to install mpv-devel
