### ISSUE TITLE
Documentation website

### ISSUE THREAD

**Issue by alexmercerind** [media-kit/media-kit#92]
[package:media_kit](https://github.com/alexmercerind/media_kit) is becoming really large & there are a large number of features that need good documentation. As the project is growing further, it might be a good idea to provide documentation separately on a website; instead of GitHub README.

**Comment by solsticedhiver** [comment]
I can share a few tip.

- To **select a given resolution of a HLS stream**, I had to look at the bitrate specified in the .m3u8 as BANDWIDTH and use that value to pass it to the mpv backend with `.setProperty('hls-bitrate', 'xxxx')`

        #EXT-X-STREAM-INF:BANDWIDTH=xxxx,AVERAGE-BANDWIDTH=yyyy,VIDEO-RANGE=SDR,CODECS="avc1.4d401e,mp4a.40.2",RESOLUTION=zzzxzzz,FRAME-RATE=25.000,AUDIO="program_audio_0",SUBTITLES="subs"

  You select the line above, given the resolution you are targeting (zzzxzzz), and then use the xxxx in the example above

  the .m3u8 is simple to parse yourself, or there is *flutter_hls_parser* which is good, to get other interesting value from the HLS  .m3u8

- To set the **user-agent**, I am just using

      final pp = player.platform as libmpvPlayer;
      pp.setProperty('user-agent', 'MyFunkyAgent 0.1 +https://example.com');

  I was not able to double check this is actually working.

**Comment by RA341** [comment]
I would like to help, is anyone already working on this or should I start

**Comment by alexmercerind** [comment]
Hi @RA341,

Thanks for your interest. This issue is now quite old, back then there was not any documentation for the project (to help developers use the library in their projects). Now, I've added a ["Guide" section in the README](https://github.com/media-kit/media-kit#guide) which provides tutorial-like reference material to the developers. It's still not _complete_ by any means.

We're welcome to any improvements or changes that you provide us. The developers who are using package:media_kit can share their improvements to the documentation so that it's beginner friendly for everyone.

A dedicated website can be really good too (at some point, it should be necessary). [Docusaurus](https://docusaurus.io/), [Material MkDocs](https://squidfunk.github.io/mkdocs-material/) seem like good choices.

**Comment by alexmercerind** [comment]
You may get in touch with us & join the discussion:

[![](https://img.shields.io/discord/1079685977523617792?color=33cd57&label=Discord&logo=discord&logoColor=discord)](https://discord.gg/h7qf2R9n57)

**Comment by aaronkelton** [comment]
Why not use a GitHub Wiki? Sidekiq does a great job using a wiki https://github.com/sidekiq/sidekiq/wiki
