### ISSUE TITLE
Feature request: image streams

### ISSUE THREAD

**Issue by saad-palapa** [media-kit/media-kit#921]
I am working on a computer vision project where I run a machine learning model on frames from an RTSP stream.

Currently I am achieving this by taking screenshots periodically like so:
```
Timer.periodic(Duration(milliseconds: 33), (_) async {
  if (inferencing) return;
  inferencing = true;

  final data = await controller.player.screenshot(format: null);
  // do ML stuff here

  inferencing = false;
});
```

Is there a more efficient way to do this?

Is it possible to create a stream similar to how the [Camera](https://github.com/flutter/packages/blob/4b00343963a1529598e602f0e3954c9fee9ec7d5/packages/camera/camera/lib/src/camera_controller.dart#L487) plugin does it?

**Comment by alexmercerind** [comment]
Too much to ask. Video rendering happens on the GPU... it's not really efficient to pass each frame as pixel buffer.

I will instead recommend to use some Flutter's screenshot API.
