### ISSUE TITLE
[media_kit v1.1.10] play/pause state bug when de-queueing while paused

### ISSUE THREAD

**Issue by isaacy13** [media-kit/media-kit#922]
Howdy,

isPlaying is true when popping from front of playlist while paused

repro steps:
- queue two medias
- pause
- pop from front of playlist

listening to `player.stream.playing` is true but the video is not playing

`player.state.playing` is true

Debug dump

Windows 11 Pro | 23H2 | 22631.3880
Flutter 3.22.3
Dart 3.4.4
media_kit v1.1.10 (https://github.com/media-kit/media-kit/commit/ff00dae2b9bb6e66cdf15a7ecc1f99d0b7d6e3b4)

**Comment by isaacy13** [comment]
```
flutter: player.remove() called
flutter: copyWith() called - playing true -> false
#0      PlayerState.copyWith (package:media_kit/src/models/player_state.dart:139:74)
#1      NativePlayer.pause.function (package:media_kit/src/player/native/player/real.dart:431:21)
<asynchronous suspension>
#2      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:33:16)
<asynchronous suspension>

flutter: copyWith() called - playing false -> false
#0      PlayerState.copyWith (package:media_kit/src/models/player_state.dart:139:74)
#1      NativePlayer._handler (package:media_kit/src/player/native/player/real.dart:1629:25)
#2      InitializerNativeEventLoop._receiver.<anonymous closure> (package:media_kit/src/player/native/core/initializer_native_event_loop.dart:140:37)
flutter: copyWith() called - playing false -> true
#0      PlayerState.copyWith (package:media_kit/src/models/player_state.dart:139:74)
#1      NativePlayer._handler (package:media_kit/src/player/native/player/real.dart:1588:23)
#2      InitializerNativeEventLoop._receiver.<anonymous closure> (package:media_kit/src/player/native/core/initializer_native_event_loop.dart:140:37)
flutter: received event _player.stream.playing -> true
```

[real.dart:431](https://github.com/media-kit/media-kit/blob/ff00dae2b9bb6e66cdf15a7ecc1f99d0b7d6e3b4/media_kit/lib/src/player/native/player/real.dart#L431)

[real.dart:1629](https://github.com/media-kit/media-kit/blob/ff00dae2b9bb6e66cdf15a7ecc1f99d0b7d6e3b4/media_kit/lib/src/player/native/player/real.dart#L1629)

[real.dart:1588](https://github.com/media-kit/media-kit/blob/ff00dae2b9bb6e66cdf15a7ecc1f99d0b7d6e3b4/media_kit/lib/src/player/native/player/real.dart#L1588)

**Comment by isaacy13** [comment]
Additional small bug I noticed when testing

repro:
- open media
- remove media

listening to player.stream.playing - no events received

player.state.playing is true


```
flutter: player.remove() called
```

**Comment by isaacy13** [comment]
> Howdy,
> 
> isPlaying is true when popping from front of playlist while paused
> 
> repro steps:
> 
> * queue two medias
> * pause
> * pop from front of playlist
> 
> listening to `player.stream.playing` is true but the video is not playing
> 
> `player.state.playing` is true
> 
> Debug dump
> 
> Windows 11 Pro | 23H2 | 22631.3880 Flutter 3.22.3 Dart 3.4.4 media_kit v1.1.10 ([ff00dae](https://github.com/media-kit/media-kit/commit/ff00dae2b9bb6e66cdf15a7ecc1f99d0b7d6e3b4))

For this, I deleted [line 1589](https://github.com/media-kit/media-kit/blob/ff00dae2b9bb6e66cdf15a7ecc1f99d0b7d6e3b4/media_kit/lib/src/player/native/player/real.dart#L1589)

I will do more extensive testing, but it makes sense to me to delete it
- e.g.: a new media source being loaded doesn't always mean it's playing

**Comment by isaacy13** [comment]
> Additional small bug I noticed when testing
> 
> repro:
> 
> * open media
> * remove media
> 
> listening to `player.stream.playing` - no events received
> 
> `player.state.playing` is true
> 
> ```
> flutter: player.remove() called
> ```

For this, I inserted the following into [line 589](https://github.com/media-kit/media-kit/blob/ff00dae2b9bb6e66cdf15a7ecc1f99d0b7d6e3b4/media_kit/lib/src/player/native/player/real.dart#L589)


```
<snip>
// If playlist is empty then change player state to paused
if (state.playlist.medias.isEmpty) {
  state = state.copyWith(playing: false);
  if (!playingController.isClosed) {
    playingController.add(false);
  }
}

final command = 'playlist-remove $index'.toNativeUtf8();
<snip>
```

**Comment by isaacy13** [comment]
TODO: when revisit, implement these changes for native & if required similar changes for web

Validate unit tests pass and create new ones for these scenarios

**Comment by alexmercerind** [comment]
Feel free to send a pull-request... I don't really have time.
