### ISSUE TITLE
Packae doesn't compile on Fedora 40

### ISSUE THREAD

**Issue by lbulej3** [media-kit/media-kit#925]
When trying to compile a project with this package on Fedora 40, I get the following error:

`<command line>:1:9: error: macro name must be an identifier`

From [this issues](https://github.com/flutter/flutter/issues/138665) from the Flutter repo it seems it might be a problem with clang 17 and higher.

### Steps to reproduce:
- Use Fedora 40 and clang 18
- Add the following dependencies: 
` media_kit: ^1.1.10+1
  media_kit_libs_video: ^1.0.4
  media_kit_video: ^1.2.4`
- Install `mpv`, `mpv-lib`, and `mpv-devel` with dnf
- Try to build project for Linux

**Comment by alexmercerind** [comment]
I don't know how to run your favorite GNU/Linux distribution.
