### ISSUE TITLE
How to play H264 raw stream?

### ISSUE THREAD

**Issue by imyyq-star** [media-kit/media-kit#927]
Hello, my H264 data is transmitted through WebSocket. Can I play H264 raw stream through media_kit? How to do it?

**Comment by imyyq-star** [comment]
Can anyone help me?

**Comment by alexmercerind** [comment]
Maybe feed that into local HTTP server... and pass it as a response (URL) to `Media(...)`.

**Comment by hesa2020** [comment]
Hello @imyyq-star have you found a solution, I also need to play live streams using websocket mse_ld with low latency.
