### ISSUE TITLE
How to enable full-xxx.jar

### ISSUE THREAD

**Issue by chicring** [media-kit/media-kit#928]
media_kit_libs_video How to switch from default-xxx.jar to full-xxx.jar

**Comment by toutoumu** [comment]
def urlDefaultARM64 = "https://github.com/media-kit/libmpv-android-video-build/releases/download/v1.1.5/full-arm64-v8a.jar"
    def urlDefaultARMEABI = "https://github.com/media-kit/libmpv-android-video-build/releases/download/v1.1.5/full-armeabi-v7a.jar"
    def urlDefaultX86_64 = "https://github.com/media-kit/libmpv-android-video-build/releases/download/v1.1.5/full-x86_64.jar"
    def urlDefaultX86 = "https://github.com/media-kit/libmpv-android-video-build/releases/download/v1.1.5/full-x86.jar"

**Comment by chicring** [comment]
> def urlDefaultARM64 = “ https://github.com/media-kit/libmpv-android-video-build/releases/download/v1.1.5/full-arm64-v8a.jar ” def urlDefaultARMEABI = “ https://github.com/media-kit/libmpv-android-video-build/releases/download/v1.1.5/full-armeabi-v7a.jar ” def urlDefaultX86_64 = “ https://github.com/media-kit/libmpv-android-video-build/releases/download/v1.1.5/full-x86_64.jar ” def urlDefaultX86 = “ https://github.com/media-kit/libmpv-android-video-build/releases/download/v1.1.5/full-x86.jar ”

thanks

**Comment by alexmercerind** [comment]
No support. Read the code & figure out.
