### ISSUE TITLE
Error when reproduce a video The 'com.alexmercerind/media_kit_video' channel sent a message from native to Flutter on a non-platform thread

### ISSUE THREAD

**Issue by ksanchez9306** [media-kit/media-kit#929]
Hi guys, i use the media kit to reproduce video in flutter app but when click a video to reproduce appear this 
[ERROR:flutter/shell/common/shell.cc(1055)] The 'com.alexmercerind/media_kit_video' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.
See https://docs.flutter.dev/platform-integration/platform-channels#channels-and-platform-threading for more information.
this is my current implementation to use media kit in a custom widget

import 'package:flutter/material.dart';
import 'package:media_kit/media_kit.dart';
import 'package:media_kit_video/media_kit_video.dart';

class CustomMediaKitVideoPlayer extends StatefulWidget {
  final String videoUrl;
  final bool isAutoPlay;
  final List<Widget> overlays;
  final VoidCallback? onLongPress;

  const CustomMediaKitVideoPlayer({
    Key? key,
    required this.videoUrl,
    this.isAutoPlay = false,
    this.overlays = const [],
    this.onLongPress,
  }) : super(key: key);

  @override
  _CustomMediaKitVideoPlayerState createState() =>
      _CustomMediaKitVideoPlayerState();
}

class _CustomMediaKitVideoPlayerState extends State<CustomMediaKitVideoPlayer> {
  late final Player _player;
  late final VideoController _videoController;
  bool _isInitialized = false;
  bool _hasError = false;

  @override
  void initState() {
    super.initState();
    _initializePlayer();
  }

  Future<void> _initializePlayer() async {
    try {
      MediaKit.ensureInitialized();
      _player = Player();
      _videoController = VideoController(_player);

      await _player.open(
        Media(widget.videoUrl),
        play: widget.isAutoPlay,
      );

      _player.stream.error.listen((error) {
        setState(() {
          _hasError = true;
        });
        debugPrint('Video player error: $error');
      });

      setState(() {
        _isInitialized = true;
      });
    } catch (e) {
      debugPrint('Error initializing video player: $e');
      setState(() {
        _hasError = true;
      });
    }
  }

  @override
  void dispose() {
    _player.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (_hasError) {
      return Center(
        child: Text(
          'Error loading video',
          style: TextStyle(color: Colors.red),
        ),
      );
    }

    if (!_isInitialized) {
      return const Center(child: CircularProgressIndicator());
    }

    return GestureDetector(
      onLongPress: widget.onLongPress,
      child: Stack(
        children: [
          Video(
            controller: _videoController,
            fit: BoxFit.cover,
            width: double.infinity,
            height: double.infinity,
          ),
          ...widget.overlays,
        ],
      ),
    );
  }
}

**Comment by alexmercerind** [comment]
Build against main branch.

**Comment by alexmercerind** [comment]
That's a logging... Flutter team hasn't provided a way... What's point of having platform channels if I can't call them from native side. What even is a platform thread?
