### ISSUE TITLE
media_kit: arm64-v8a JAR verification failed - BUG

### ISSUE THREAD

**Issue by fsmdeveloper** [media-kit/media-kit#930]
**media_kit: ^1.1.11 # Primary package.
  media_kit_video: ^1.2.5 # For video rendering.
  media_kit_libs_video: ^1.0.5 # Native video dependencies.**

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\xxxxxx\AppData\Local\Pub\Cache\hosted\pub.dev\media_kit_libs_android_video-1.3.6\android\build.gradle' line: 102

* What went wrong:
A problem occurred evaluating project ':media_kit_libs_android_video'.
> media_kit: arm64-v8a JAR verification failed.

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.0, on Microsoft Windows [Version 10.0.26257.5000], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.0 Preview 4.0)
[√] Android Studio (version 2024.1)
[√] VS Code (version 1.92.2)
[√] Connected device (4 available)
[√] Network resources

• No issues found!

**Comment by abdelaziz-mahdy** [comment]
its an internet problem on your side, the needed deps failed to get downloaded, rebuilding should fix the issue (maybe flutter clean and rebuild is better cases may vary)
