### ISSUE TITLE
Inconsistent Position Update When Using `player.seek(duration)` or tapping seekbar on paused video

### ISSUE THREAD

**Issue by fadone** [media-kit/media-kit#937]
### Description
When listening to player.stream.position and calling player.seek(duration), the video position updates correctly to the specified duration. However, immediately after this, the stream emits another position event with a slight deviation from the intended duration, ranging from +/- 1 to 35 milliseconds.

### Expected Behavior
After calling player.seek(duration), the position reported by player.stream.position should match the exact duration passed to the seek method without any deviation.

### Actual Behavior
The position initially updates to the correct duration but then quickly receives another event with a minor deviation, typically within +/- 1 to 35 milliseconds from the original duration.

### Steps to Reproduce
1. Listen to the position stream using player.stream.position.
2. Call player.seek(duration) with a specific duration.
3. Observe the position reported by the stream immediately after the seek operation.

```
// Listening to the position stream
player.stream.position.listen((position) {
  print('Current position: $position');
});

// Seeking to a specific duration
player.seek(Duration(seconds: 10));
```
### Environment
Package Version:
```
media_kit: ^1.1.11
media_kit_video: ^1.2.5
media_kit_libs_video: ^1.0.5
```
Flutter Version: `3.22.1`
Platform: `Android`

**Comment by alexmercerind** [comment]
Which platform? Web?

**Comment by fadone** [comment]
> Which platform? Web?

Android

**Comment by denizdurmaz1** [comment]
Same issue here

**Comment by alexmercerind** [comment]
Build against main branch.

**Comment by fadone** [comment]
Still getting this problem

**Comment by fadone** [comment]
Getting indefinite circular loading on calling `player.pause()` on latest build.

**Comment by alexmercerind** [comment]
Yeah... Haven't fully figured out how to solve that. It is a blocker for release.
