### ISSUE TITLE
Internal Video Card uses 100%, External Video Card uses 0% 

### ISSUE THREAD

**Issue by Beladras** [media-kit/media-kit#943]
Hello, I've developed an application that plays videos in 1-4 panels. While playing the videos, it only uses the integrated graphics card (Intel UHD Graphics). Despite utilizing 100% of the internal graphics card, it doesn't use the external graphics card (3050ti) at all. there's a lagging issue. VideoControllerConfiguration parameters are at their default settings.

Has anyone encountered this situation, and how did you resolve it?

**Comment by alexmercerind** [comment]
Build against main.
