### ISSUE TITLE
Process to use the full MPV release

### ISSUE THREAD

**Issue by azukaar** [media-kit/media-kit#944]
Hello!
I gathered while skimming through the issues that the MPV version used is a lightweight/free-only version.
I was able to upgrade to the full MPV release by replacing the dll after the build. Which tbh is not an ideal setup since I have to manually edit the build folder after the build. I am sure there is a better way to do this.
Which brings me to the point of the ticket: it would be good to have documentations on how to upgrade MPV for each platform.
Thanks!

**Comment by alexmercerind** [comment]
See through some build files e.g. build.gradle for Android. We only distribute LGPL variants with specific decoders.
