### ISSUE TITLE
Total Duration Of Player

### ISSUE THREAD

**Issue by iAkashPattnaik** [media-kit/media-kit#948]
```
final player = Player(Media("Network Audio Link"));
```

How to get the total duration of the audio?

**Comment by kalismeras61** [comment]
player.stream.duration or player.state.duration

**Comment by iAkashPattnaik** [comment]
state.duration is giving the current elapsed duration and stream gives as a stream, is there any way to get the totalDuraiton of the audio file, as a int of milliseconds (or Duration) as a Future?

**Comment by alexmercerind** [comment]
There's position & duration.
