### ISSUE TITLE
Preloading/Check whether it is live or not

### ISSUE THREAD

**Issue by GG139** [media-kit/media-kit#949]
I have few questions:
- is it possible to preload next video for smooth transition?
- is it possible to check whether current HLS Stream is seekable or not?

Also, if there is any way to get HLS Stream duration when i'm requesting something like this:
index-1725899999-now.fmp4.m3u8 (from timestamp to now).
Right now video player returns only buffered duration starting from zero, instead of real duration until now.

Thanks.

**Comment by alexmercerind** [comment]
1. https://www.reddit.com/r/mpv/comments/uxhk3a/comment/i9xor5i/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
2. No.

**Comment by gaganyadav80** [comment]
Hi @alexmercerind, 

From your comment above and the reddit suggestion it is not clear to me how to use those parameters with your package?
