### ISSUE TITLE
Play multiple videos simultaneously with sync.

### ISSUE THREAD

**Issue by tuannn2507** [media-kit/media-kit#950]
Hi team,

I have videos of the same length and resolution. Now I need them to run in parallel in a synchronized way. Meaning when I press "play", all videos should start and have the same playback position.  

I tried using [05.stress_test](https://github.com/media-kit/media-kit/blob/main/media_kit_test/lib/tests/05.stress_test.dart) example. The app can play multiple videos, but the videos have slightly different playback position.

 Is there a way to play multiple videos and keep them synced?

Thank you.

**Comment by alexmercerind** [comment]
I don't know the answer.
