### ISSUE TITLE
Phone Overheating During Video Playback 

### ISSUE THREAD

**Issue by kalismeras61** [media-kit/media-kit#951]
I am experiencing a significant issue with the media_kit plugin while using it for video playback in my Flutter app. The device gets extremely hot during video playback, especially after a few minutes of continuous usage. Here are the details of the issue:

Platform: IOS
Device: Iphone 15 pro max
Flutter Version: latest stable.
media_kit Version: latest
Issue: The phone heats up significantly after a short duration of video playback. This happens regardless of video resolution or file size, and seems to occur consistently across different video files.

**Steps to Reproduce:**

Start playing any video using media_kit.
After a few minutes of playback, the phone starts to heat up considerably.

Expected Behavior: The video should play without causing the device to overheat.

Observed Behavior: The phone gets unusually hot during video playback.

Additional Information:

I've tested on multiple devices, and the issue persists.
No performance issues (such as stuttering or frame drops), but the heating issue is concerning.
Please let me know if you need additional logs or information.

**Comment by Zensonaton** [comment]
Are you able to provide link to the video that you are trying to play? I have a feeling that you are dealing with codec issue, or something like that.

**Comment by kalismeras61** [comment]
This is happens when i set   enableHardwareAcceleration: false,

**Comment by 23doors** [comment]
> This is happens when i set enableHardwareAcceleration: false,

Why would you do that though? This will always cause a much, much bigger strain for any device.

**Comment by alexmercerind** [comment]
I think answer above makes it pretty clear.

**Comment by kalismeras61** [comment]
> > This is happens when i set enableHardwareAcceleration: false,
> 
> Why would you do that though? This will always cause a much, much bigger strain for any device.



> > This is happens when i set enableHardwareAcceleration: false,
> 
> Why would you do that though? This will always cause a much, much bigger strain for any device.

Because i adapt your pip changes to latest media-kit it is working fine iphone 15 pro max but lower than 15 pro max it is not supporting hardware acceleration. If i change to false it is working all devices but i having issue with performance…
