### ISSUE TITLE
No sound when play TrueHD track in MKV

### ISSUE THREAD

**Issue by singnoo** [media-kit/media-kit#952]
No sound when play TrueHD track in MKV. Same file is ok to play with PotPlayer.

  media_kit: ^1.1.11
  media_kit_video: ^1.2.5
  media_kit_libs_video: ^1.0.5
  media_kit_libs_audio: ^1.0.5

Tested on both Windows (with headphone) and Android.

Attached a 10-second file for testing. It's extracted with ffmpeg 4.4.4. It's a zip file. After decompressing, there's test.mkv.
[test.zip](https://github.com/user-attachments/files/17000840/test.zip)

It's loaded as external audio track in flutter as: player.setAudioTrack(AudioTrack.uri("..../test.mkv"));

It's ok to play DTS-X, DDP in same method though. When load TrueHD track, flutter is able to show codec is truehd, however no sound. I guess that it's caused by wrong audio channel mapping. Currently I bypass this problem temporarily to re-encode TrueHD track to AAC format.

**Comment by singnoo** [comment]
Update: I tried to update libmpv-2.dll from different mpv windows build sites. However it still does not work.

For example:

mpv.exe in [mpv-x86_64-v3-20240913-git-2b8da78.7z](https://github.com/dyphire/mpv-winbuild/releases/download/mpv_own-2024-09-13/mpv-x86_64-v3-20240913-git-2b8da78.7z) works well with TrueHD in test.mkv.

libmpv-2.dll in [mpv-dev-x86_64-v3-20240913-git-2b8da78.7z](https://github.com/dyphire/mpv-winbuild/releases/download/mpv_own-2024-09-13/mpv-dev-x86_64-v3-20240913-git-2b8da78.7z) does not work with TrueHD in test.mkv, no sound, quiet output.

I tried to turn media_kit into customized flutter package, and modified LIBMPV* in media-kit/libs/windows/media_kit_libs_windows_video/pubspec.yaml. After modification and clean and rebuild, I noticed libmpv-2.dll has been correctly updated to larger file. And the file itself should support TrueHD format. However still no sound with TrueHD track.

**Comment by alexmercerind** [comment]
Hi @singnoo, 

If you found a solution, may you write it here as well for future visitors?

Thanks.

**Comment by singnoo** [comment]
The solution to this problem:

1. Download media-kit
`mkdir plugins
cd plugins
git clone https://github.com/media-kit/media-kit
cd ..`

2. Modify ./pubspec.yaml to use customized media-kit plugin:
`dependencies:
  media_kit: ^1.1.11
  media_kit_video:
    path: ./plugins/media-kit/media_kit_video
  media_kit_libs_video:
    path: ./plugins/media-kit/libs/universal/media_kit_libs_video`

3. Modify ./plugins/media-kit/libs/universal/media_kit_libs_video/pubspec.yaml to use customized media-kit plugin:
`dependencies:
  media_kit_libs_android_video:
    path: ../../android/media_kit_libs_android_video
  media_kit_libs_ios_video:
    path: ../../ios/media_kit_libs_ios_video
  media_kit_libs_linux:
    path: ../../linux/media_kit_libs_linux
  media_kit_libs_macos_video:
    path: ../../macos/media_kit_libs_macos_video
  media_kit_libs_windows_video:
    path: ../../windows/media_kit_libs_windows_video
  media_kit_native_event_loop:
    path: ../../../media_kit_native_event_loop`

4. Modify ./plugins/media-kit/libs/windows/media_kit_libs_windows_video/windows/CMakeLists.txt to use other mpv on windows:

Part1:
`# libmpv archive containing the pre-built shared libraries & headers.
#set(LIBMPV "mpv-dev-x86_64-20230924-git-652a1dd.7z")
set(LIBMPV "mpv-dev-x86_64-v3-20240913-git-2b8da78.7z")

# Download URL & MD5 hash of the libmpv archive.
#set(LIBMPV_URL "https://github.com/media-kit/libmpv-win32-video-build/releases/download/2023-09-24/${LIBMPV}")
#set(LIBMPV_MD5 "a832ef24b3a6ff97cd2560b5b9d04cd8")
set(LIBMPV_URL "https://github.com/dyphire/mpv-winbuild/releases/download/mpv_own-2024-09-13/${LIBMPV}")
set(LIBMPV_MD5 "863d1f4bd4f2ddf4647945c3b390e05a")`

Part2:
`set(
  media_kit_libs_windows_video_bundled_libraries
  "${LIBMPV_SRC}/libmpv-2.dll"
  "${LIBMPV_SRC}/lua51.dll"
  "${ANGLE_SRC}/api-ms-win-core-console-l1-1-0.dll"`

6. Modify ./plugins/media-kit/libs/android/media_kit_libs_android_video/android/build.gradle to use full mpv on android:

Part1:
`// Download all *.jar dependencies & verify their MD5 checksums.

    /*
    def urlDefaultARM64 = "https://github.com/media-kit/libmpv-android-video-build/releases/download/v1.1.5/default-arm64-v8a.jar"
    def urlDefaultARMEABI = "https://github.com/media-kit/libmpv-android-video-build/releases/download/v1.1.5/default-armeabi-v7a.jar"
    def urlDefaultX86_64 = "https://github.com/media-kit/libmpv-android-video-build/releases/download/v1.1.5/default-x86_64.jar"
    def urlDefaultX86 = "https://github.com/media-kit/libmpv-android-video-build/releases/download/v1.1.5/default-x86.jar"

    def destDefaultARM64 = file("$buildDir/v1.1.5/default-arm64-v8a.jar")
    def destDefaultARMEABI = file("$buildDir/v1.1.5/default-armeabi-v7a.jar")
    def destDefaultX86_64 = file("$buildDir/v1.1.5/default-x86_64.jar")
    def destDefaultX86 = file("$buildDir/v1.1.5/default-x86.jar")
     */

    def urlDefaultARM64 = "https://github.com/media-kit/libmpv-android-video-build/releases/download/v1.1.5/full-arm64-v8a.jar"
    def urlDefaultARMEABI = "https://github.com/media-kit/libmpv-android-video-build/releases/download/v1.1.5/full-armeabi-v7a.jar"
    def urlDefaultX86_64 = "https://github.com/media-kit/libmpv-android-video-build/releases/download/v1.1.5/full-x86_64.jar"
    def urlDefaultX86 = "https://github.com/media-kit/libmpv-android-video-build/releases/download/v1.1.5/full-x86.jar"

    def destDefaultARM64 = file("$buildDir/v1.1.5/full-arm64-v8a.jar")
    def destDefaultARMEABI = file("$buildDir/v1.1.5/full-armeabi-v7a.jar")
    def destDefaultX86_64 = file("$buildDir/v1.1.5/full-x86_64.jar")
    def destDefaultX86 = file("$buildDir/v1.1.5/full-x86.jar")`

Part 2:
`    //if (md5DefaultARM64 != "5f521b08692d7fef73c5df9bcc00ca4d") {
    if (md5DefaultARM64 != "2f6f8019061b0deedac14372bcbea0ad") {
        throw new GradleException("media_kit: arm64-v8a JAR verification failed.")
    }
    //if (md5DefaultARMEABI != "08d500ca1116c13e9c1296cc6f2207b0") {
    if (md5DefaultARMEABI != "f8ddb68ed125325a2d31f760db9f115d") {
        throw new GradleException("media_kit: armeabi-v7a JAR verification failed.")
    }
    //if (md5DefaultX86_64 != "0880d5fbc3ff0053409704617f54cb55") {
    if (md5DefaultX86_64 != "1cf34ae184d01a0c28e2d7bc5818ed62") {
        throw new GradleException("media_kit: x86_64 JAR verification failed.")
    }
    //if (md5DefaultX86 != "f6f51aa42b30d747099506cdc3277352") {
    if (md5DefaultX86 != "e098f38ac524806e4e873c4f64dcaf2f") {
        throw new GradleException("media_kit: x86 JAR verification failed.")
    }`

Do flutter clean and then rebuild. After rebuilding, TrueHD will work on both Windows and Android.

**Comment by andynvt** [comment]
@singnoo Does this way support hdmv_pgs subtitle? It seems not working to me. I verified `transitive dependencies` and local build folder, it shows full-xxx.jar packages. But the hdmv_pgs
![ScreenShot 2024-11-08 at 15 01 44](https://github.com/user-attachments/assets/9078e976-98e1-44ff-9134-20c53a977729)
![ScreenShot 2024-11-08 at 15 04 03](https://github.com/user-attachments/assets/fa408ec3-7f1c-4c29-bdae-bae99cfc0698)

**Comment by singnoo** [comment]
Sorry but I do not have any file with hdmv_pgs to do test. If you could provide a short test file, I could test it on my build.

I did notice difference between windows build and android *.jar build. For example, Dolby Vision encoded file will be decoded as Dolby Vision in windows build, however it's only decoded as compatible HDR in android build. So I guess that current "full" android build is bundled with earlier mpv or with fewer features.

You may test it on windows build. If it works on windows build, you may have to rebuild anroid build with newer mpv and extra features enabled.

For subtitle processing, I load external srt file to an overlay in flutter, to archieve better result, such as, sharp font rendering, regular/3D, HDR color, bilingual colored rendering.

**Comment by andynvt** [comment]
@singnoo thanks for your reply, can you try this? Thank you
https://drive.google.com/file/d/1HsAcaTw9RJm605PcF2RldNkm1Tc48gkL/view?usp=drive_link

Screenshot is in macOS MPV app

![ScreenShot 2024-11-09 at 11 12 03](https://github.com/user-attachments/assets/1d2fa459-f1cd-43fd-add4-bcc5963acd0a)

**Comment by singnoo** [comment]
I tested your file on both windows build and android build. Both builds could recognize the subtitle track correctly. However it's not rendered. You may have to do it as a flutter overlay by yourself.

`for (final t in player.state.tracks.subtitle) {`
`  print(t);`
`  if (t.id == "3") {`
`    player.setSubtitleTrack(t);`
`  }`
`}`

`flutter: SubtitleTrack(3, AI Vietnamese, vi-x-nm21, image: false, albumart: false, codec: hdmv_pgs_subtitle, decoder: null, w: null, h: null, channelscount: null, channels: null, samplerate: null, fps: null, bitrate: null, rotate: null, par: null, audiochannels: null)`

**Comment by andynvt** [comment]
@singnoo I did. But it's not rendered on my android phone. Is your phone rendering it? (With full-x mpv lib)

**Comment by singnoo** [comment]
No, It's not rendered on android phone. It's also not rendered on windows.

I guess that you may have to implement that with flutter overlay by yourself.

**Comment by andynvt** [comment]
Thank you @singnoo it seems I have to extract it as an external subtitle file

**Comment by alexmercerind** [comment]
@andynvt 

You likely need to enable libass:

https://github.com/media-kit/media-kit/blob/e1c5f5dc8b9c4174c59530bdf192e2f95622f702/media_kit/lib/src/player/platform_player.dart#L474-L479

**Comment by andynvt** [comment]
> @andynvt 
> 
> 
> 
> You likely need to enable libass:
> 
> 
> 
> https://github.com/media-kit/media-kit/blob/e1c5f5dc8b9c4174c59530bdf192e2f95622f702/media_kit/lib/src/player/platform_player.dart#L474-L479

But it's not working on other platforms, right?

**Comment by alexmercerind** [comment]
Wdym?

**Comment by andynvt** [comment]
oh thank you @alexmercerind it works

**Comment by andynvt** [comment]
@alexmercerind I've checked https://github.com/media-kit/media-kit/issues/255#issuecomment-1646868981 and https://github.com/media-kit/media-kit/issues/952#issuecomment-2466067518

But the `libassAndroidFont` not working with assets ttf file.

**Comment by andynvt** [comment]
@alexmercerind  Here is what I found in the log

```log
I/flutter ( 8266): [LOG] PlayerLog(prefix: global, level: debug, text: config path: 'fonts' -/-> '/data/user/0/package.name/files/com.alexmercerind.media_kit/fonts')
I/flutter ( 8266): [LOG] PlayerLog(prefix: sub/ass, level: debug, text: ASS library version: 0x1701000 (runtime 0x1701000))
I/flutter ( 8266): [LOG] PlayerLog(prefix: sub/ass, level: v, text: libass API version: 0x1701000)
I/flutter ( 8266): [LOG] PlayerLog(prefix: sub/ass, level: v, text: libass source: commit: 0.17.1-0-ge8ad72accd3a84268275a9385beb701c9284e5b3)
I/flutter ( 8266): [LOG] PlayerLog(prefix: sub/ass, level: v, text: Shaper: FriBidi 1.0.12 (SIMPLE) HarfBuzz-ng 7.2.0 (COMPLEX))
I/flutter ( 8266): [LOG] PlayerLog(prefix: global, level: debug, text: config path: 'subfont.ttf' -/-> '/data/user/0/package.name/files/com.alexmercerind.media_kit/subfont.ttf')
I/flutter ( 8266): [LOG] PlayerLog(prefix: global, level: debug, text: config path: 'fonts.conf' -/-> '/data/user/0/package.name/files/com.alexmercerind.media_kit/fonts.conf')
I/flutter ( 8266): [LOG] PlayerLog(prefix: sub/ass, level: v, text: Setting up fonts...)
I/flutter ( 8266): [LOG] PlayerLog(prefix: sub/ass, level: v, text: Done.)
I/flutter ( 8266): [LOG] PlayerLog(prefix: cplayer, level: v, text: Starting playback...)
I/flutter ( 8266): [LOG] PlayerLog(prefix: mkv, level: v, text: queuing seek to 499.000000)
I/flutter ( 8266): [LOG] PlayerLog(prefix: cplayer, level: v, text: hr-seek, skipping to 499.000000)
I/flutter ( 8266): [LOG] PlayerLog(prefix: mkv, level: v, text: execute seek (to 499.000000 flags 32))
I/flutter ( 8266): [LOG] PlayerLog(prefix: ffmpeg, level: v, text: stream level seek from 31794 to 533813729)
I/flutter ( 8266): [LOG] PlayerLog(prefix: mkv, level: v, text: deselect track 3)
I/flutter ( 8266): [LOG] PlayerLog(prefix: mkv, level: v, text: select track 2)
I/flutter ( 8266): [LOG] PlayerLog(prefix: global, level: debug, text: config path: 'fonts' -/-> '/data/user/0/package.name/files/com.alexmercerind.media_kit/fonts')
I/flutter ( 8266): [LOG] PlayerLog(prefix: sub/ass, level: debug, text: ASS library version: 0x1701000 (runtime 0x1701000))
I/flutter ( 8266): [LOG] PlayerLog(prefix: sub/ass, level: v, text: libass API version: 0x1701000)
I/flutter ( 8266): [LOG] PlayerLog(prefix: sub/ass, level: v, text: libass source: commit: 0.17.1-0-ge8ad72accd3a84268275a9385beb701c9284e5b3)
I/flutter ( 8266): [LOG] PlayerLog(prefix: sub/ass, level: v, text: Shaper: FriBidi 1.0.12 (SIMPLE) HarfBuzz-ng 7.2.0 (COMPLEX))
I/flutter ( 8266): [LOG] PlayerLog(prefix: global, level: debug, text: config path: 'subfont.ttf' -/-> '/data/user/0/package.name/files/com.alexmercerind.media_kit/subfont.ttf')
I/flutter ( 8266): [LOG] PlayerLog(prefix: global, level: debug, text: config path: 'fonts.conf' -/-> '/data/user/0/package.name/files/com.alexmercerind.media_kit/fonts.conf')
I/flutter ( 8266): [LOG] PlayerLog(prefix: sub/ass, level: v, text: Setting up fonts...)
I/flutter ( 8266): [LOG] PlayerLog(prefix: ffmpeg, level: debug, text: tcp: Starting connection attempt to ip.ip port 443)
I/flutter ( 8266): [LOG] PlayerLog(prefix: sub/ass, level: v, text: Done.)


![ScreenShot 2024-11-12 at 10 09 50](https://github.com/user-attachments/assets/f71a91ba-c20f-411d-a504-e6ce26dbb4ed)

```

**Comment by alexmercerind** [comment]
Use main branch.

**Comment by andynvt** [comment]
@alexmercerind I want to use full libmpv, and with this customization, I cannot use main branch 
https://github.com/media-kit/media-kit/issues/952#issuecomment-2351386968

**Comment by andynvt** [comment]
I've fixed it by copying your main branch code here. Thanks @alexmercerind 

media_kit/lib/src/player/native/player/real.dart:
```dart
if (Platform.isAndroid &&
          configuration.libass &&
          configuration.libassAndroidFont != null &&
          configuration.libassAndroidFontName != null) {
        try {
          // On Android, the system fonts cannot be picked up by libass/fontconfig. This makes libass subtitle rendering fail.
          // We save the subtitle font to the application's cache directory and set `config` & `config-dir` to use it.
          final subfont = await AndroidAssetLoader.load(
            join(
              'flutter_assets',
              configuration.libassAndroidFont,
            ),
          );
          if (subfont.isNotEmpty) {
            final directory = dirname(subfont);
            // This asset is bundled as part of `package:media_kit_libs_android_video`.
            // Use it if located inside the application bundle, otherwise no worries.
            options.addAll(
              {
                'config': 'yes',
                'sub-fonts-dir': directory,
                'sub-font': configuration.libassAndroidFontName ?? '',
              },
            );
            print(subfont);
            print(directory);
          }
        } catch (exception, stacktrace) {
          print(exception);
          print(stacktrace);
        }
      }
```

**Comment by lookjoe** [comment]
> Flutter`Widget`的。

Can you display embedded hdmv_pgs_subtitle subtitles in android? I have used full-xxx.jar

**Comment by lookjoe** [comment]
> @singnoo我做到了。但它没有在我的 Android 手机上呈现。你的手机在呈现它吗？（使用 full-x mpv lib）

Can you display embedded hdmv_pgs_subtitle subtitles in Android? I have used full-xxx.jar

**Comment by lookjoe** [comment]
> @singnoo I did. But it's not rendered on my android phone. Is your phone rendering it? (With full-x mpv lib)

Do you know how to display embedded hdmv_pgs_subtitle subtitles in Android? I have the same problem. I have used full-xxx.jar

**Comment by lookjoe** [comment]
> @singnoo我做到了。但它没有在我的 Android 手机上呈现。你的手机在呈现它吗？（使用 full-x mpv lib）

我也遇到了同样的问题，我已经替换了full-xxx.jar，但是无法显示内嵌hdmv_pgs_subtitle，你现在知道如何显示吗

**Comment by lookjoe** [comment]
> @singnoo I did. But it's not rendered on my android phone. Is your phone rendering it? (With full-x mpv lib)
I have the same problem. I have replaced full-xxx.jar, but the embedded hdmv_pgs_subtitle cannot be displayed. Do you know how to display it now?

**Comment by lookjoe** [comment]
> @singnoo I did. But it's not rendered on my android phone. Is your phone rendering it? (With full-x mpv lib)

I have the same problem. I have replaced full-xxx.jar and can play Truehd audio successfully, but cannot display the embedded hdmv_pgs_subtitle. Do you know how to display it now?

**Comment by saifshaikh1805** [comment]
> Solved by replace libmpv.
> 
> On Windows: Modify LIBMPV* in media-kit/libs/windows/media_kit_libs_windows_video/pubspec.yaml. Replace libmpv-2.dll with [mpv-dev-x86_64-v3-20240913-git-2b8da78.7z](https://github.com/dyphire/mpv-winbuild/releases/download/mpv_own-2024-09-13/mpv-dev-x86_64-v3-20240913-git-2b8da78.7z)
> 
> On Android: Modify media-kit/libs/android/media_kit_libs_android_video/android/build.gradle to use full-arm64-v8a.jar, full-armeabi-v7a.jar, full-x86_64.jar, full-x86.jar.
> 
> Clean and rebuild. TrueHD works now on Windows and Android.



@singnoo Where can would I find "media-kit/libs/android/media_kit_libs_android_video/android/build.gradle"?

**Comment by saifshaikh1805** [comment]
> > [@singnoo](https://github.com/singnoo) I did. But it's not rendered on my android phone. Is your phone rendering it? (With full-x mpv lib)
> 
> I have the same problem. I have replaced full-xxx.jar and can play Truehd audio successfully, but cannot display the embedded hdmv_pgs_subtitle. Do you know how to display it now?

@lookjoe Please tell me what you did to fix the truehd issue.
