### ISSUE TITLE
Updating the media kit library to last version, generate a black screen in android.

### ISSUE THREAD

**Issue by ksanchez9306** [media-kit/media-kit#955]
: com.alexmercerind.media_kit_video.VideoOutputManager.createSurface: -5476376647881927840
I/flutter ( 6899): media_kit: wakelock: _count = 1
D/nteracpedia.app( 6899): PlayerBase::PlayerBase()
D/nteracpedia.app( 6899): TrackPlayerBase::TrackPlayerBase()
I/libOpenSLES( 6899): Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2)
E/libOpenSLES( 6899): Configuration error: unknown key
W/libOpenSLES( 6899): Leaving AndroidConfiguration::GetConfiguration (SL_RESULT_PARAMETER_INVALID)
 com.alexmercerind.media_kit_video.VideoOutputManager.setSurfaceTextureSize: -5476376647881927840 2160 3840media_kit: wakelock: _count = 0
D/nteracpedia.app( 6899): PlayerBase::stop() from IPlayer

when i reproduce a video in my flutter app not show the video but i can hear the audio of the video and pause but appear a black screen 

this is the flutter doctor -v 
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.6.1 23G93 darwin-arm64, locale es-419)
    • Flutter version 3.24.3 on channel stable at /Users/kevin_sanchez/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (8 days ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/kevin_sanchez/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/kevin_sanchez/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.93.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.96.0

[✓] Connected device (5 available)            
    • sdk gphone64 arm64 (mobile)     • emulator-5554             • android-arm64  • Android 14 (API 34) (emulator)
    • iPhone (mobile)                 • 00008110-001925423663801E • ios            • iOS 17.6.1 21G93
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.6.1 23G93 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.6.1 23G93 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 128.0.6613.138

[✓] Network resources
    • All expected network resources are available.

• No issues found!

and my configuration of settings gradle
pluginManagement {
    def flutterSdkPath = {
        def properties = new Properties()
        file("local.properties").withInputStream { properties.load(it) }
        def flutterSdkPath = properties.getProperty("flutter.sdk")
        assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
        return flutterSdkPath
    }
    settings.ext.flutterSdkPath = flutterSdkPath()

    includeBuild("${settings.ext.flutterSdkPath}/packages/flutter_tools/gradle")

    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }

    // plugins {
    //     id "dev.flutter.flutter-gradle-plugin" version "1.0.0" apply false
    // }
}

plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "7.3.0" apply false
    id "org.jetbrains.kotlin.android" version "1.8.22" apply false
    id "com.google.gms.google-services" version "4.3.14" apply false
    id "com.google.firebase.crashlytics" version "2.8.1" apply false
    id 'com.google.firebase.firebase-perf' version '1.4.2' apply false
}

include ":app"
------------------------------

app/gradle
plugins {
    id "com.android.application"
    id "kotlin-android"
    id "dev.flutter.flutter-gradle-plugin"
    id 'com.google.gms.google-services'
    id "com.google.firebase.crashlytics"
    id 'com.google.firebase.firebase-perf'
}

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    namespace = "com.interacpedia.app"
    compileSdk = flutter.compileSdkVersion
    ndkVersion  = flutter.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId = "com.interacpedia.app"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
        minSdk =  23 //flutter.minSdkVersion
        targetSdkVersion = flutter.targetSdkVersion
        versionCode = flutterVersionCode.toInteger()
        versionName = flutterVersionName
        // multiDexEnabled true
    }
    dependencies {
    implementation(platform("com.google.firebase:firebase-bom:33.1.0"))
    implementation 'com.google.firebase:firebase-analytics:21.5.0'
    implementation 'com.google.firebase:firebase-perf:20.0.0'
    // implementation 'com.google.android.exoplayer:exoplayer:2.19.1'
    implementation "org.jetbrains.kotlin:kotlin-stdlib:1.8.22"
    implementation "androidx.core:core-ktx:1.6.0"
    implementation "androidx.appcompat:appcompat:1.3.1"
    implementation "androidx.constraintlayout:constraintlayout:2.1.1"
    implementation "androidx.media3:media3-exoplayer:1.4.0"
    implementation "androidx.media3:media3-exoplayer-dash:1.4.0"
    implementation "androidx.media3:media3-ui:1.4.0"
    // implementation "androidx.media3:media3-datasource-cache:1.4.0"

}
and my pubspec yml

name: interacpedia
description: Interacpedia talent pitch app.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.0.10+1015

environment:
  sdk: ">=3.4.1 <4.0.0"
dependencies:
  amazon_cognito_identity_dart_2: 3.6.5
  animate_do: 3.3.4
  app_links: ^6.3.2
  app_tracking_transparency: ^2.0.6
  cached_network_image: ^3.4.0
  camera: 0.11.0+2
  cloud_firestore: 5.4.0
  connectivity_plus: 6.0.5
  contained_tab_bar_view: 0.8.0
  cron: 0.6.1
  cupertino_icons: 1.0.8
  custom_refresh_indicator: 3.1.0
  device_info_plus: ^10.1.2
  dio: 5.7.0
  dio_smart_retry: ^6.0.0
  dotted_border: 2.1.0
  easy_debounce: 2.0.3
  file_picker: ^8.1.2
  firebase_analytics: ^11.3.0
  firebase_core: ^3.4.0
  firebase_crashlytics: ^4.1.0
  firebase_dynamic_links: ^6.0.5
  firebase_messaging: ^15.1.0
  firebase_remote_config: ^5.1.0
  flutter:
    sdk: flutter
  media_kit: ^1.1.11
  media_kit_video: ^1.2.5
  media_kit_libs_video: ^1.0.5

**Comment by abdelaziz-mahdy** [comment]
if you have impeller enabled it may be the problem this is the pr for impeller support https://github.com/media-kit/media-kit/pull/824

**Comment by ksanchez9306** [comment]
> if you have impeller enabled it may be the problem this is the pr for impeller support #824



> if you have impeller enabled it may be the problem this is the pr for impeller support #824

 <meta-data
            android:name="io.flutter.embedding.android.EnableImpeller"
            android:value="false" />
            
   i have this in the android manifest for not use the impeller

**Comment by abdelaziz-mahdy** [comment]
can you remove it fully from the manifest just to be sure its not enabled  

https://github.com/flutter/flutter/issues/154252 seems like false is not working correctly in some cases

**Comment by ksanchez9306** [comment]
> can you remove it fully from the manifest just to be sure its not enabled , make it commented will work too
> 
> [flutter/flutter#154252](https://github.com/flutter/flutter/issues/154252) seems like false is not working correctly in some cases

Thanks abdelazis, i made the change and remove the code from manifest still appear the black screen 
and this logs

` 
I/media_kit(14058): package:media_kit_libs_android_video attached.
PlayerBase::PlayerBase()
D/nteracpedia.app(12988): TrackPlayerBase::TrackPlayerBase()
I/libOpenSLES(12988): Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2)
E/libOpenSLES(12988): Configuration error: unknown key
W/libOpenSLES(12988): Leaving AndroidConfiguration::GetConfiguration (SL_RESULT_PARAMETER_INVALID)
D/nteracpedia.app(12988): PlayerBase::stop() from IPlayer
D/AudioTrack(12988): stop(22): called with 0 frames delivered
I/media_kit(12988): com.alexmercerind.media_kit_video.VideoOutputManager.setSurfaceTextureSize: -5476376647883020672 720 1280
E/EGL_emulation(12988): tid 13588: eglCreateContext(1755): error 0x3004 (EGL_BAD_ATTRIBUTE)
E/EGL_emulation(12988): tid 13589: eglCreateContext(1755): error 0x3004 (EGL_BAD_ATTRIBUTE)
I/flutter (12988): media_kit: wakelock: _count = 1
D/EGL_emulation(12988): app_time_stats: avg=28.75ms min=5.77ms max=140.23ms count=34`

**Comment by abdelaziz-mahdy** [comment]
> > can you remove it fully from the manifest just to be sure its not enabled , make it commented will work too
> > 
> > [flutter/flutter#154252](https://github.com/flutter/flutter/issues/154252) seems like false is not working correctly in some cases
> 
> Thanks abdelazis, i made the change and remove the code from manifest still appear the black screen 
> and this logs
> 
> ` 
> I/media_kit(14058): package:media_kit_libs_android_video attached.
> PlayerBase::PlayerBase()
> D/nteracpedia.app(12988): TrackPlayerBase::TrackPlayerBase()
> I/libOpenSLES(12988): Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2)
> E/libOpenSLES(12988): Configuration error: unknown key
> W/libOpenSLES(12988): Leaving AndroidConfiguration::GetConfiguration (SL_RESULT_PARAMETER_INVALID)
> D/nteracpedia.app(12988): PlayerBase::stop() from IPlayer
> D/AudioTrack(12988): stop(22): called with 0 frames delivered
> I/media_kit(12988): com.alexmercerind.media_kit_video.VideoOutputManager.setSurfaceTextureSize: -5476376647883020672 720 1280
> E/EGL_emulation(12988): tid 13588: eglCreateContext(1755): error 0x3004 (EGL_BAD_ATTRIBUTE)
> E/EGL_emulation(12988): tid 13589: eglCreateContext(1755): error 0x3004 (EGL_BAD_ATTRIBUTE)
> I/flutter (12988): media_kit: wakelock: _count = 1
> D/EGL_emulation(12988): app_time_stats: avg=28.75ms min=5.77ms max=140.23ms count=34`
> 
> 

Sadly I don't understand the problem maybe if you provide a sample code where the problem happens we can figure it out, also are you sure it's not a problem with the video file?

**Comment by ksanchez9306** [comment]
> > > can you remove it fully from the manifest just to be sure its not enabled , make it commented will work too
> > > [flutter/flutter#154252](https://github.com/flutter/flutter/issues/154252) seems like false is not working correctly in some cases
> > 
> > 
> > Thanks abdelazis, i made the change and remove the code from manifest still appear the black screen
> > and this logs
> > `  I/media_kit(14058): package:media_kit_libs_android_video attached. PlayerBase::PlayerBase() D/nteracpedia.app(12988): TrackPlayerBase::TrackPlayerBase() I/libOpenSLES(12988): Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2) E/libOpenSLES(12988): Configuration error: unknown key W/libOpenSLES(12988): Leaving AndroidConfiguration::GetConfiguration (SL_RESULT_PARAMETER_INVALID) D/nteracpedia.app(12988): PlayerBase::stop() from IPlayer D/AudioTrack(12988): stop(22): called with 0 frames delivered I/media_kit(12988): com.alexmercerind.media_kit_video.VideoOutputManager.setSurfaceTextureSize: -5476376647883020672 720 1280 E/EGL_emulation(12988): tid 13588: eglCreateContext(1755): error 0x3004 (EGL_BAD_ATTRIBUTE) E/EGL_emulation(12988): tid 13589: eglCreateContext(1755): error 0x3004 (EGL_BAD_ATTRIBUTE) I/flutter (12988): media_kit: wakelock: _count = 1 D/EGL_emulation(12988): app_time_stats: avg=28.75ms min=5.77ms max=140.23ms count=34`
> 
> Sadly I don't understand the problem maybe if you provide a sample code where the problem happens we can figure it out, also are you sure it's not a problem with the video file?

`
class ObxTalentee extends StatefulWidget {
  final ConnectGeneralController controller;
  const ObxTalentee({super.key, required this.controller});

  @override
  State<ObxTalentee> createState() => _ObxTalenteeState();
}

class _ObxTalenteeState extends State<ObxTalentee> {
  int? _currentPlayingVideoIndex;
  final PageController pageController = PageController();
  bool _isTransitioning = false;

  @override
  void initState() {
    super.initState();
    MediaKit.ensureInitialized();

    // Initialize Player and Controller
    widget.controller.currentTalenteeVideoPlayer = Player();
    widget.controller.currentTalenteeVideoController =
        VideoController(widget.controller.currentTalenteeVideoPlayer!);

    // Listen for Talentees and Loading Changes
    _initializeSubscriptions();
  }

  void _initializeSubscriptions() {
    widget.controller.talentees.listen((talentees) {
      if (mounted && talentees.isNotEmpty) {
        _currentPlayingVideoIndex ??= 0; // Default to first video
        _playVideoAtIndex(_currentPlayingVideoIndex!);
      }
    });

    widget.controller.isLoadingTalentees.listen((isLoading) {
      if (mounted && !isLoading && _currentPlayingVideoIndex == null) {
        setState(() {
          _currentPlayingVideoIndex = 0;
        });
        _playVideoAtIndex(_currentPlayingVideoIndex!);
      }
    });
  }

  Future<void> _playVideoAtIndex(int index) async {
    if (index < widget.controller.talentees.length && mounted) {
      try {
        _isTransitioning = true;
        await widget.controller.currentTalenteeVideoPlayer!
            .stop(); // Stop any currently playing video
        await widget.controller.currentTalenteeVideoPlayer!.open(
            Media(widget.controller.talentees[index].videoUrl!),
            play: false); // Load the new video source without playing

        widget.controller.currentTalenteeVideoPlayer!.stream.buffering
            .listen((buffering) async {
          if (!buffering && mounted) {
            await Future.delayed(const Duration(milliseconds: 300));
            await widget.controller.currentTalenteeVideoPlayer!.play();
            setState(() {
              _isTransitioning = false;
            });
          }
        });
      } catch (e) {
        print('Error playing video at index $index: $e');
      }
    }
  }

  Future<void> _pauseCurrentVideo() async {
    if (_currentPlayingVideoIndex != null) {
      await widget.controller.currentTalenteeVideoPlayer!.pause();
    }
  }

  @override
  void dispose() {
    widget.controller.currentTalenteeVideoPlayer!.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    FirebaseAnalytics.instance.logEvent(name: 'screen_view', parameters: {
      'action': 'show_connect_talent',
      'connect': 'talent',
      'type': 'open_screen',
      'timestamp': DateTime.now().millisecondsSinceEpoch.toString(),
    });
    return Obx(() {
      if (widget.controller.isLoadingTalentees.value) {
        return const Center(
          child: TalentPitchLoading(
            isFullScreen: false,
            isLoading: false,
            loadingSize: 38,
            iconColor: Colors.white,
            indicatorColor: Colors.white,
          ),
        );
      } else if (widget.controller.talentees.isEmpty) {
        return const Center(
          child:
              Text('No talentees found', style: TextStyle(color: Colors.white)),
        );
      } else {
        return KeepAlivePage(
          child: PageView.builder(
            controller: pageController,
            itemCount: widget.controller.talentees.length,
            scrollDirection: Axis.vertical,
            onPageChanged: (page) async {
              await _pauseCurrentVideo();
              _currentPlayingVideoIndex = page;
              if (page < widget.controller.talentees.length && mounted) {
                setState(() {
                  _currentPlayingVideoIndex = page;
                });
                await _playVideoAtIndex(page);
              }
            },
            itemBuilder: (BuildContext context, int index) {
              final TalenteeModel talentee = widget.controller.talentees[index];
              return talentee.isVideo
                  ? VideoTalenteesWidget(
                      index: index,
                      controller: widget.controller,
                      player: widget.controller.currentTalenteeVideoPlayer!,
                      videoController:
                          widget.controller.currentTalenteeVideoController!,
                      videoUrl: talentee.videoUrl!,
                      autoplay: index == _currentPlayingVideoIndex,
                      context: context,
                      isTransitioning: _isTransitioning,
                    )
                  : ContentTalenteesWidget(
                      context: context,
                      index: index,
                      controller: widget.controller,
                    );
            },
          ),
        );
      }
    });
  }
}
`

-----------
videoTalenteeWidgets

`class VideoTalenteesWidget extends StatefulWidget {
  final int index;
  final ConnectGeneralController controller;
  final BuildContext context;
  final String videoUrl;
  final bool autoplay;
  final Player player; // Single shared Player instance
  final VideoController videoController; // Single shared VideoController instance
  String? videoTr;
  bool hasVisibility = false;
  final bool isTransitioning;

  VideoTalenteesWidget({
    super.key,
    required this.index,
    required this.controller,
    required this.context,
    required this.videoUrl,
    required this.player,
    required this.videoController,
    required this.autoplay,
    required this.isTransitioning,
  });

  @override
  State<VideoTalenteesWidget> createState() => _VideoTalenteesWidgetState();
}

class _VideoTalenteesWidgetState extends State<VideoTalenteesWidget> {
  bool _isLoading = true;
  final ValueNotifier<bool> _isPlayingNotifier = ValueNotifier<bool>(false);
  Duration _duration = Duration.zero;
  bool _sentLog = false;
  late Future<bool> _talenteeDetailsFuture;

  @override
  void initState() {
    super.initState();
    _talenteeDetailsFuture = getDataTalentee(widget.controller.talentees[widget.index]);
    _initializeVideo();
  }

  void _initializeVideo() {
    widget.player.stream.playing.listen((playing) {
      if (mounted) {
        _isPlayingNotifier.value = playing; // Update only the value
      }
    });

    widget.player.stream.buffering.listen((buffering) {
      if (mounted) {
        setState(() {
          _isLoading = buffering;
        });
      }
    });

    widget.player.stream.duration.listen((duration) {
      if (mounted) {
        _duration = duration;
        // setState(() {});
      }
    });

    widget.player.stream.position.listen((position) {
      if (mounted && _duration != Duration.zero && !_sentLog) {
        if (position >= _duration * 0.9) {
          _sentLog = true;
          sendLogVideoCompleted(widget.controller.talentees[widget.index]);
        }
      }
    });

    Future.microtask(() async {
      if (widget.player.platform is NativePlayer) {
        await (widget.player.platform as dynamic).setProperty('force-seekable', 'yes');
      }
      await _validateVideo(widget.videoUrl);
    });
  }

  Future<void> _validateVideo(String videoUrl) async {
    final values = await General.isRemoteFileExists(videoUrl);
    if (!values.$1 && !values.$2 && widget.videoTr == null) {
      return;
    }
    if (values.$1 && widget.videoTr == null) {
      widget.videoTr = '${widget.videoUrl}.tr.mp4';
    }
  }

  Future<void> sendLogVideoCompleted(TalenteeModel talentee) async {
    // Implementation of sending logs when video is completed...
    if (widget.controller.requestToken.userId == null ||
        widget.controller.requestToken.userId == 0) {
      return;
    }

    if (talentee.resume_id != null && talentee.resume_id != 0) {
      await LogsAPI.createLogEveryTime(
        logName: 'app',
        description: 'show resume on discover',
        subjectId: talentee.resume_id!,
        subjectType: LogsModels.resume,
        causerId: widget.controller.requestToken.userId,
        causerType: LogsModels.talentee,
        properties: [
          {
            'resume_id': talentee.resume_id.toString(),
            'index': widget.index.toString(),
          }
        ],
        url: '/discover',
        params: 'video',
        referer: '/discover',
        className: 'resumes',
        method: 'discover',
        verb: 'show-completed',
      );
    } else {
      await LogsAPI.createLogEveryTime(
        logName: 'app',
        description: 'show user on discover',
        subjectId: talentee.id!,
        subjectType: LogsModels.talentee,
        causerId: widget.controller.requestToken.userId,
        causerType: LogsModels.talentee,
        properties: [
          {
            'user_id': talentee.id.toString(),
            'index': widget.index.toString(),
          }
        ],
        url: '/discover',
        params: 'video',
        referer: '/discover',
        className: 'talents',
        method: 'discover',
        verb: 'show-completed',
      );
    }
  }

  void _togglePlayPause() {
    if (widget.player.state.playing) {
      widget.player.pause();
    } else {
      widget.player.play();
    }
  }

  @override
  Widget build(BuildContext context) {
    VisibilityDetectorController.instance.updateInterval = const Duration(seconds: 1);

    final TalenteeModel talentee = widget.controller.talentees[widget.index];
    final knowledges = talentee.knowledges!.join(', ');

    return VisibilityDetector(
      key: Key('videoTalenteesWidget-${talentee.id}-${widget.index}'),
      onVisibilityChanged: (visibilityInfo) async {
        if (visibilityInfo.visibleFraction >= 0.5 &&
            talentee.id != null &&
            talentee.id != 0 &&
            widget.controller.requestToken != null &&
            !widget.hasVisibility) {
          await sendLog(talentee);
        }
      },
      child: RepaintBoundary(
        child: Stack(
          alignment: Alignment.bottomCenter,
          children: [
            AnimatedSwitcher(
              key: Key('videoTalentees-${widget.index}'),
              duration: const Duration(milliseconds: 300),
              child: _isLoading
                  ? const ColoredBox(
                      color: Colors.transparent,
                      child: Center(
                        child: TalentPitchLoading(
                          isFullScreen: false,
                          isLoading: false,
                          loadingSize: 38,
                          iconColor: Colors.white,
                          indicatorColor: Colors.white,
                        ),
                      ),
                    )
                  : Video(
                      controller: widget.videoController,
                      fit: BoxFit.cover,
                      width: MediaQuery.of(context).size.width,
                      height: MediaQuery.of(context).size.height * 0.8,
                    ),
            ),
           
            _buildTalenteeDetails(talentee, knowledges),
            _buildAdditionalUI(),
            _buildResumeCounter(talentee),
          ],
        ),
      ),
    );
  }

  @override
  void dispose() {
    _isPlayingNotifier.dispose();
    super.dispose();
  }
`

**Comment by abdelaziz-mahdy** [comment]
i edited the comment of yours just to be able to read the code use ``` when wrapping code 


check this issue seems like the same problem but i see you did Initialize the video controller correctly maybe the location of the `MediaKit.ensureInitialized();` is the problem, it should be first think in the main function

**Comment by ksanchez9306** [comment]
now it's work i think that maybe the error is the initialized inside the component and not the main.dart

**Comment by abdelaziz-mahdy** [comment]
glad to hear it got fixed

**Comment by winimk** [comment]
@abdelaziz-mahdy could you help me as well please? i got almost same problem.. i use flutter 3.24.0, media_kit works like a charm in debug mode, but when i try it in release mode i can hear the audio of the video but it just appear black screen.

i use this version:
  media_kit: 1.1.10                           
  media_kit_video: 1.2.4                       
  media_kit_libs_video: 1.0.4
