### ISSUE TITLE
Zoom feature on Video

### ISSUE THREAD

**Issue by fsmdeveloper** [media-kit/media-kit#956]
is it possible to make zoom in / zoom out feature with this lib?

**Comment by abdelaziz-mahdy** [comment]
i think you can do that with flutter itself on the rendered video using your custom widget, if you explain your usecase more maybe another thing will work better

**Comment by alexmercerind** [comment]
Sounds like a Flutter question. Zoom `Video` widget just like another widget in Flutter.

**Comment by fsmdeveloper** [comment]
I would like to create a video player similar to YouTube's, with zoom in and zoom out functionality. Can you share an example of how to achieve this?

**Comment by abdelaziz-mahdy** [comment]
just wrapping the video widget with the zoom widget you want, but @alexmercerind i think the fullscreen will be a problem here, i looked into it and i thought of wrapping the controls but thats zooms in and out the controls not the underlying video, i think we need a way to wrap the video widget in normal mode and fullscreen (maybe a parameter to pass custom video wrapper?)

@fsmdeveloper if you dont need it to work on fullscreen, this should work (you will need to optimize it to fit your use case)
```
InteractiveViewer(
  boundaryMargin:
      const EdgeInsets.all(32.0),
  minScale: 1.0,
  maxScale: 3.0,
  child: Video(
    controller: controller,
  ),
),
```

**Comment by fsmdeveloper** [comment]
> just wrapping the video widget with the zoom widget you want, but @alexmercerind i think the fullscreen will be a problem here, i looked into it and i thought of wrapping the controls but thats zooms in and out the controls not the underlying video, i think we need a way to wrap the video widget in normal mode and fullscreen (maybe a parameter to pass custom video wrapper?)
> 
> @fsmdeveloper if you dont need it to work on fullscreen, this should work (you will need to optimize it to fit your use case)
> 
> ```
> InteractiveViewer(
>   boundaryMargin:
>       const EdgeInsets.all(32.0),
>   minScale: 1.0,
>   maxScale: 3.0,
>   child: Video(
>     controller: controller,
>   ),
> ),
> ```

The problem is, I want the zoom feature to be available only in full-screen mode. Do you know how I can do that?

**Comment by abdelaziz-mahdy** [comment]
For now I can't find a way to do it, a pr will need to be done with code changes to the way video widget works to allow wrapping the underlying video widget
