### ISSUE TITLE
When looping with a file video on Android, the video stucks after the buffers are full.

### ISSUE THREAD

**Issue by song011794** [media-kit/media-kit#959]
When looping with a file video on Android, the video stucks after the buffers are full.

Play 3 videos within 100MB each.

I tried changing the buffer to 128MB in the player settings, but it didn't help.

The video plays fine, but then stucks. The temporal frequency of the stucks is different each time, but they always happen eventually.

Release mode, profile mode, and debug mode are all reproduced.

`I/MediaCodec(19367): setCodecState state(0), called in 6
D/BufferPoolAccessor2.0(19367): bufferpool2 0xb40000719c077028 : 9(18874368 size) total buffers - 7(14680064 size) used buffers - 731/740 (recycle/alloc) - 9/732 (fetch/transfer)
D/BufferPoolAccessor2.0(19367): evictor expired: 1, evicted: 1`

<details>
<summary>flutter doctor</summary>
[✓] Flutter (Channel stable, 3.22.3, on macOS 14.6.1 23G93 darwin-arm64, locale ko-KR)
    • Flutter version 3.22.3 on channel stable at /Users/foodtech/fvm/versions/3.22.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (10 weeks ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/foodtech/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/foodtech/Library/Android/sdk
    • Java binary at: /opt/homebrew/opt/openjdk@17/bin/java
    • Java version OpenJDK Runtime Environment Homebrew (build 17.0.12+0)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS and macOS development.
      Download at: https://developer.apple.com/xcode/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2024.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 81.1.3
    • Dart plugin version 242.22855.32

[✓] IntelliJ IDEA Ultimate Edition (version 2024.1.4)
    • IntelliJ at /Users/foodtech/Library/Caches/JetBrains/Toolbox/backup/IDEA-U-241.18034.62-1904458635539506142
    • Flutter plugin version 80.0.2
    • Dart plugin version 241.18808

[✓] VS Code (version 1.91.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • SM X110 (mobile)            • R83WA00WM0W   • android-arm64  • Android 14 (API 34)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 14 (API 34) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 14.6.1 23G93 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 129.0.6668.59

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
</details>

**Comment by alexmercerind** [comment]
Not really happening for me...

**Comment by alexmercerind** [comment]
What happens if you disable hwdec?

**Comment by song011794** [comment]
Yes I disabled hwdec but I get the same symptoms.

```
configuration: const VideoControllerConfiguration(
  vo: 'mediacodec_embed',
  hwdec: 'mediacodec',
),
```

I tried this too, but it's the same.

**Comment by alexmercerind** [comment]
Try this guy's fix y'all:
https://github.com/media-kit/media-kit/issues/776#issuecomment-2072158673

If it works, I'll make it default.

Thanks.
