### ISSUE TITLE
Playback works in `debug` mode but not `release` on raspberry pi

### ISSUE THREAD

**Issue by noranraskin** [media-kit/media-kit#972]
Using `media-kit` for a Linux desktop app that is supposed to run on a raspberry pi 5.

Raspberry pi is running `Debian GNU/Linux 12 (bookworm) aarch64`. I also set up the project on my `Ubuntu 24` machine.

In both cases I installed mpv using `sudo apt install mpv`

Now I try running the app...

## On ubuntu laptop
`flutter run` works 
`flutter build linux` and then running the app (`./app`) works.

## On raspberry pi
`flutter run` works
`flutter build linux` and then running the app (`./app`) **does not work**. Where the video should be there's just a black box.

The video is an mp4 in h264 avc1 and it works on both platforms when I try to run it directly with mpv.

When I run the app there's always something like this in the output, regardless of whether the output works or not:
```
package:media_kit_libs_linux registered.
media_kit: VideoOutput: video_output_new: 140733596141904
media_kit: VideoOutput: Using H/W rendering.
flutter: VideoOutput.Resize
flutter: {handle: 140733596141904, id: 93827323281616, rect: {left: 0, top: 0, width: 1, height: 1}}
flutter: NativeVideoController: Texture ID: 93827323281616
flutter: media_kit: wakelock: _count = 1
MediaKitEventLoopHandler::Register: std::thread exit: 140733596141904
```

How can I debug this? Is there an option to create logs from mpv? Is it possible to get a more verbose output?

**Comment by alexmercerind** [comment]
Playing an asset?

**Comment by noranraskin** [comment]
Yes playing an asset

**Comment by alexmercerind** [comment]
Use asset:// instead.
