### ISSUE TITLE
Separate Playback Window Issue: Non-libmpv vo Setting Creates New Window

### ISSUE THREAD

**Issue by user1121114685** [media-kit/media-kit#975]
**Issue Description**
When the vo setting is not libmpv, a separate playback window is created, which is detached from the original playback window. I have tried various methods to resolve this issue but have not succeeded, so I am seeking help.

**Steps to Reproduce**
Configure the VideoController with the following code:

```

late final controller = VideoController(player,
    configuration: const VideoControllerConfiguration(
        vo: "gpu-next", androidAttachSurfaceAfterVideoParameters: true));

```
Run the program on a Windows system.

**Expected Behavior**
The playback window should remain consistent with the original window and not create a separate one.

**Actual Behavior**
A separate playback window is created, detached from the original playback window.

**Environment**

- Operating System: Windows
- VideoController Configuration: vo: "gpu-next"

I hope to get a solution soon, thank you!

![image](https://github.com/user-attachments/assets/be18e580-4dac-4468-af57-56921872fa13)

**Comment by alexmercerind** [comment]
No solution.
