### ISSUE TITLE
I have a black screen right after the video buffers

### ISSUE THREAD

**Issue by minhdang2803** [media-kit/media-kit#977]
[DEBUG] logger:DEBUG/MEDIA_KIT LOG: PlayerLog(prefix: ao/opensles, level: error, text: (*p->engine)->CreateAudioPlayer(p->engine, &p->player, &audio_source, &audio_sink, 2, iid_array, required): 3)
[DEBUG] logger:DEBUG/MEDIA_KIT LOG: PlayerLog(prefix: ao, level: error, text: Failed to initialize audio driver 'opensles')
[DEBUG] logger:DEBUG/MEDIA_KIT LOG: PlayerLog(prefix: cplayer, level: error, text: Could not open/initialize audio device -> no sound.)
[DEBUG]  logger:DEBUG/MEDIA_KIT LOG: PlayerLog(prefix: ao, level: error, text: Failed to initialize audio driver 'opensles')
[DEBUG]  logger:DEBUG/MEDIA_KIT LOG: PlayerLog(prefix: cplayer, level: error, text: Could not open/initialize audio device -> no sound.)

I have black screen before the video actually play

**Comment by ijashuzain** [comment]
Same issue here... I think this issue is related to impeller. Also in real devices its working fine not in emulators for me

**Comment by alexmercerind** [comment]
Emulators never work... Impeller support is on `main` branch only.
