### ISSUE TITLE
[Android] [Question] how to AudioAttributes to the player

### ISSUE THREAD

**Issue by Joseph-Nathan** [media-kit/media-kit#988]
when i change my AudioManager.allowedCapturePolicy = ALLOW_CAPTURE_BY_NONE
its override by package and i can't find the native player in libs to edit it,

if you can help , i need to prevent audio capturing in Android & IOS ,
if possible support {AVAudioSessionCategory , AVAudioSessionCategoryOptions } to iOS ,

**Comment by alexmercerind** [comment]
We use OpenSL ES by default at the moment.
