### ISSUE TITLE
How to get screenshot from a video path?

### ISSUE THREAD

**Issue by EMUNES** [media-kit/media-kit#990]
Hello, I try to use this package to get the thumbnail of videos by providing video paths. Using `player.screenshot()` seems not working.

Here is my code:

```
/// Get a video thumbnail from the local video file.
Future<Uint8List?> getVideoThumbnail(String videoPath) async {
  print("--- get video thumbnail from $videoPath ---");

  final player = Player();
  await player.open(Media(videoPath), play: false);
  await player.seek(Duration(milliseconds: 100));
  await player.pause();

  final thumbnail = await player.screenshot(format: "image/png");

  player.dispose();

  print("--- get video thumbnail done: $thumbnail ---");

  if (thumbnail != null) {
    return thumbnail;
  }

  return null;
}
```

I can see the video path, but the `thumbnail` returned from `player.screenshot()` is always `null`. Maybe it's because the code is problematic. If so, is there any correct  example  to take thumbnail of videos? Thanks in advance.

**Comment by alexmercerind** [comment]
Need to attach `VideoController` before taking screenshot.

**Comment by Prince-of-death** [comment]
@alexmercerind what about getting image from a position on the video when the video is playing in the player

**Comment by EMUNES** [comment]
> Need to attach `VideoController` before taking screenshot.

It's working, good to know.

But I find the screenshot process is slow. Say I want to build thumbnails for some videos in the same page. No matter I use a global player to generate screenshot for them separately, or initialize one controller and player for each video to take screenshot, the process could make the UI jam (I'm in debug mode). It's slower than directly read each video into Media and put each of them into a Video widget with separate VideoController, which won't even jam the UI.

**Comment by alexmercerind** [comment]
> It's slower than directly read each video into media and put each of them into a `Video` widget.

2 reasons:
- We use [package:image](https://pub.dev/packages/image) to encode screenshot's pixel buffer... and Dart is slower than C/C++.
- The video playback happens through the GPU... where things are far more optimized. The video output that you see in the `Video` widget is not stored like a "screenshot" in the memory, but using OpenGL etc. specific primitives.

**Comment by alexmercerind** [comment]
I personally use [screenshot-to-file](https://mpv.io/manual/stable/#command-interface-screenshot-to-file) in my project... but it won't really work with our default libs since image encoders have not been enabled. I plan to replace current screenshot implementation with that one in new release... but honestly I'm too tired to figure out CI/CD now, so many attempts.

**Comment by EMUNES** [comment]
Good to know those details. I will try more solutions to deal with video thumbnails.
