### ISSUE TITLE
CMake Error at flutter/ephemeral/.plugin_symlinks/media_kit_libs_windows_video/windows/CMakeLists.txt:43 (message):

### ISSUE THREAD

**Issue by CalmLuo** [media-kit/media-kit#995]
CMake Error at flutter/ephemeral/.plugin_symlinks/media_kit_libs_windows_video/windows/CMakeLists.txt:43 (message):

  E:/Code/Flutter/calm/xxxx/build/windows/x64/mpv-dev-x86_64-20230924-git-652a1dd.7z
  Integrity check failed, please try to re-build project again.
Call Stack (most recent call first):
  flutter/ephemeral/.plugin_symlinks/media_kit_libs_windows_video/windows/CMakeLists.txt:77 (download_and_verify)

Error: Unable to generate build files

**Comment by user1121114685** [comment]
**先通网，再编译**

**Comment by CalmLuo** [comment]
> **先通网，再编译**

跟通网没关系，网是通的，是win 10 SDK 导致的，升到11就好了

**Comment by CalmLuo** [comment]
> **先通网，再编译**

并非网络问题，网一直是通的，更新Win 10 SDK到11即可

**Comment by zynzszyn521** [comment]
我也遇到这个问题，网络也是通的，请问您说的升级Win 11 SDK指的是什么
